/* For Capstone Engine. AUTO-GENERATED FILE, DO NOT EDIT */

#include "arm64_const.h"

void set_arm64_const(lua_State* l)
{
	/* ARM64 shift type */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_SFT_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_SFT_LSL");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_SFT_MSL");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_SFT_LSR");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_SFT_ASR");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM64_SFT_ROR");

	/* ARM64 extender type */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_EXT_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_EXT_UXTB");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_EXT_UXTH");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_EXT_UXTW");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_EXT_UXTX");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM64_EXT_SXTB");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM64_EXT_SXTH");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM64_EXT_SXTW");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM64_EXT_SXTX");

	/* ARM64 condition code */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_CC_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_CC_EQ");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_CC_NE");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_CC_HS");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_CC_LO");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM64_CC_MI");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM64_CC_PL");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM64_CC_VS");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM64_CC_VC");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM64_CC_HI");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM64_CC_LS");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "ARM64_CC_GE");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "ARM64_CC_LT");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "ARM64_CC_GT");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "ARM64_CC_LE");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "ARM64_CC_AL");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM64_CC_NV");

	/* System registers */

	/* System registers for MRS */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_SYSREG_INVALID");
	lua_pushinteger(l, 0x9808);
	lua_setfield(l, -2, "ARM64_SYSREG_MDCCSR_EL0");
	lua_pushinteger(l, 0x9828);
	lua_setfield(l, -2, "ARM64_SYSREG_DBGDTRRX_EL0");
	lua_pushinteger(l, 0x8080);
	lua_setfield(l, -2, "ARM64_SYSREG_MDRAR_EL1");
	lua_pushinteger(l, 0x808c);
	lua_setfield(l, -2, "ARM64_SYSREG_OSLSR_EL1");
	lua_pushinteger(l, 0x83f6);
	lua_setfield(l, -2, "ARM64_SYSREG_DBGAUTHSTATUS_EL1");
	lua_pushinteger(l, 0xdce6);
	lua_setfield(l, -2, "ARM64_SYSREG_PMCEID0_EL0");
	lua_pushinteger(l, 0xdce7);
	lua_setfield(l, -2, "ARM64_SYSREG_PMCEID1_EL0");
	lua_pushinteger(l, 0xc000);
	lua_setfield(l, -2, "ARM64_SYSREG_MIDR_EL1");
	lua_pushinteger(l, 0xc800);
	lua_setfield(l, -2, "ARM64_SYSREG_CCSIDR_EL1");
	lua_pushinteger(l, 0xc801);
	lua_setfield(l, -2, "ARM64_SYSREG_CLIDR_EL1");
	lua_pushinteger(l, 0xd801);
	lua_setfield(l, -2, "ARM64_SYSREG_CTR_EL0");
	lua_pushinteger(l, 0xc005);
	lua_setfield(l, -2, "ARM64_SYSREG_MPIDR_EL1");
	lua_pushinteger(l, 0xc006);
	lua_setfield(l, -2, "ARM64_SYSREG_REVIDR_EL1");
	lua_pushinteger(l, 0xc807);
	lua_setfield(l, -2, "ARM64_SYSREG_AIDR_EL1");
	lua_pushinteger(l, 0xd807);
	lua_setfield(l, -2, "ARM64_SYSREG_DCZID_EL0");
	lua_pushinteger(l, 0xc008);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_PFR0_EL1");
	lua_pushinteger(l, 0xc009);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_PFR1_EL1");
	lua_pushinteger(l, 0xc00a);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_DFR0_EL1");
	lua_pushinteger(l, 0xc00b);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_AFR0_EL1");
	lua_pushinteger(l, 0xc00c);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_MMFR0_EL1");
	lua_pushinteger(l, 0xc00d);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_MMFR1_EL1");
	lua_pushinteger(l, 0xc00e);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_MMFR2_EL1");
	lua_pushinteger(l, 0xc00f);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_MMFR3_EL1");
	lua_pushinteger(l, 0xc010);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_ISAR0_EL1");
	lua_pushinteger(l, 0xc011);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_ISAR1_EL1");
	lua_pushinteger(l, 0xc012);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_ISAR2_EL1");
	lua_pushinteger(l, 0xc013);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_ISAR3_EL1");
	lua_pushinteger(l, 0xc014);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_ISAR4_EL1");
	lua_pushinteger(l, 0xc015);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_ISAR5_EL1");
	lua_pushinteger(l, 0xc020);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64PFR0_EL1");
	lua_pushinteger(l, 0xc021);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64PFR1_EL1");
	lua_pushinteger(l, 0xc028);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64DFR0_EL1");
	lua_pushinteger(l, 0xc029);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64DFR1_EL1");
	lua_pushinteger(l, 0xc02c);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64AFR0_EL1");
	lua_pushinteger(l, 0xc02d);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64AFR1_EL1");
	lua_pushinteger(l, 0xc030);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64ISAR0_EL1");
	lua_pushinteger(l, 0xc031);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64ISAR1_EL1");
	lua_pushinteger(l, 0xc038);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64MMFR0_EL1");
	lua_pushinteger(l, 0xc039);
	lua_setfield(l, -2, "ARM64_SYSREG_ID_A64MMFR1_EL1");
	lua_pushinteger(l, 0xc018);
	lua_setfield(l, -2, "ARM64_SYSREG_MVFR0_EL1");
	lua_pushinteger(l, 0xc019);
	lua_setfield(l, -2, "ARM64_SYSREG_MVFR1_EL1");
	lua_pushinteger(l, 0xc01a);
	lua_setfield(l, -2, "ARM64_SYSREG_MVFR2_EL1");
	lua_pushinteger(l, 0xc601);
	lua_setfield(l, -2, "ARM64_SYSREG_RVBAR_EL1");
	lua_pushinteger(l, 0xe601);
	lua_setfield(l, -2, "ARM64_SYSREG_RVBAR_EL2");
	lua_pushinteger(l, 0xf601);
	lua_setfield(l, -2, "ARM64_SYSREG_RVBAR_EL3");
	lua_pushinteger(l, 0xc608);
	lua_setfield(l, -2, "ARM64_SYSREG_ISR_EL1");
	lua_pushinteger(l, 0xdf01);
	lua_setfield(l, -2, "ARM64_SYSREG_CNTPCT_EL0");
	lua_pushinteger(l, 0xdf02);
	lua_setfield(l, -2, "ARM64_SYSREG_CNTVCT_EL0");
	lua_pushinteger(l, 0x8818);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCSTATR");
	lua_pushinteger(l, 0x8806);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR8");
	lua_pushinteger(l, 0x880e);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR9");
	lua_pushinteger(l, 0x8816);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR10");
	lua_pushinteger(l, 0x881e);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR11");
	lua_pushinteger(l, 0x8826);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR12");
	lua_pushinteger(l, 0x882e);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR13");
	lua_pushinteger(l, 0x8847);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR0");
	lua_pushinteger(l, 0x884f);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR1");
	lua_pushinteger(l, 0x8857);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR2");
	lua_pushinteger(l, 0x885f);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR3");
	lua_pushinteger(l, 0x8867);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR4");
	lua_pushinteger(l, 0x886f);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR5");
	lua_pushinteger(l, 0x8877);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR6");
	lua_pushinteger(l, 0x887f);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCIDR7");
	lua_pushinteger(l, 0x888c);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCOSLSR");
	lua_pushinteger(l, 0x88ac);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCPDSR");
	lua_pushinteger(l, 0x8bd6);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCDEVAFF0");
	lua_pushinteger(l, 0x8bde);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCDEVAFF1");
	lua_pushinteger(l, 0x8bee);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCLSR");
	lua_pushinteger(l, 0x8bf6);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCAUTHSTATUS");
	lua_pushinteger(l, 0x8bfe);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCDEVARCH");
	lua_pushinteger(l, 0x8b97);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCDEVID");
	lua_pushinteger(l, 0x8b9f);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCDEVTYPE");
	lua_pushinteger(l, 0x8ba7);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCPIDR4");
	lua_pushinteger(l, 0x8baf);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCPIDR5");
	lua_pushinteger(l, 0x8bb7);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCPIDR6");
	lua_pushinteger(l, 0x8bbf);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCPIDR7");
	lua_pushinteger(l, 0x8bc7);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCPIDR0");
	lua_pushinteger(l, 0x8bcf);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCPIDR1");
	lua_pushinteger(l, 0x8bd7);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCPIDR2");
	lua_pushinteger(l, 0x8bdf);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCPIDR3");
	lua_pushinteger(l, 0x8be7);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCCIDR0");
	lua_pushinteger(l, 0x8bef);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCCIDR1");
	lua_pushinteger(l, 0x8bf7);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCCIDR2");
	lua_pushinteger(l, 0x8bff);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCCIDR3");
	lua_pushinteger(l, 0xc660);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_IAR1_EL1");
	lua_pushinteger(l, 0xc640);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_IAR0_EL1");
	lua_pushinteger(l, 0xc662);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_HPPIR1_EL1");
	lua_pushinteger(l, 0xc642);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_HPPIR0_EL1");
	lua_pushinteger(l, 0xc65b);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_RPR_EL1");
	lua_pushinteger(l, 0xe659);
	lua_setfield(l, -2, "ARM64_SYSREG_ICH_VTR_EL2");
	lua_pushinteger(l, 0xe65b);
	lua_setfield(l, -2, "ARM64_SYSREG_ICH_EISR_EL2");
	lua_pushinteger(l, 0xe65d);
	lua_setfield(l, -2, "ARM64_SYSREG_ICH_ELSR_EL2");

	/* System registers for MSR */
	lua_pushinteger(l, 0x9828);
	lua_setfield(l, -2, "ARM64_SYSREG_DBGDTRTX_EL0");
	lua_pushinteger(l, 0x8084);
	lua_setfield(l, -2, "ARM64_SYSREG_OSLAR_EL1");
	lua_pushinteger(l, 0xdce4);
	lua_setfield(l, -2, "ARM64_SYSREG_PMSWINC_EL0");
	lua_pushinteger(l, 0x8884);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCOSLAR");
	lua_pushinteger(l, 0x8be6);
	lua_setfield(l, -2, "ARM64_SYSREG_TRCLAR");
	lua_pushinteger(l, 0xc661);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_EOIR1_EL1");
	lua_pushinteger(l, 0xc641);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_EOIR0_EL1");
	lua_pushinteger(l, 0xc659);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_DIR_EL1");
	lua_pushinteger(l, 0xc65d);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_SGI1R_EL1");
	lua_pushinteger(l, 0xc65e);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_ASGI1R_EL1");
	lua_pushinteger(l, 0xc65f);
	lua_setfield(l, -2, "ARM64_SYSREG_ICC_SGI0R_EL1");

	/* System PState Field (MSR instruction) */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_PSTATE_INVALID");
	lua_pushinteger(l, 0x05);
	lua_setfield(l, -2, "ARM64_PSTATE_SPSEL");
	lua_pushinteger(l, 0x1e);
	lua_setfield(l, -2, "ARM64_PSTATE_DAIFSET");
	lua_pushinteger(l, 0x1f);
	lua_setfield(l, -2, "ARM64_PSTATE_DAIFCLR");

	/* Vector arrangement specifier (for FloatingPoint/Advanced SIMD insn) */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_VAS_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_VAS_8B");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_VAS_16B");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_VAS_4H");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_VAS_8H");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM64_VAS_2S");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM64_VAS_4S");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM64_VAS_1D");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM64_VAS_2D");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM64_VAS_1Q");

	/* Vector element size specifier */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_VESS_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_VESS_B");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_VESS_H");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_VESS_S");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_VESS_D");

	/* Memory barrier operands */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_BARRIER_INVALID");
	lua_pushinteger(l, 0x1);
	lua_setfield(l, -2, "ARM64_BARRIER_OSHLD");
	lua_pushinteger(l, 0x2);
	lua_setfield(l, -2, "ARM64_BARRIER_OSHST");
	lua_pushinteger(l, 0x3);
	lua_setfield(l, -2, "ARM64_BARRIER_OSH");
	lua_pushinteger(l, 0x5);
	lua_setfield(l, -2, "ARM64_BARRIER_NSHLD");
	lua_pushinteger(l, 0x6);
	lua_setfield(l, -2, "ARM64_BARRIER_NSHST");
	lua_pushinteger(l, 0x7);
	lua_setfield(l, -2, "ARM64_BARRIER_NSH");
	lua_pushinteger(l, 0x9);
	lua_setfield(l, -2, "ARM64_BARRIER_ISHLD");
	lua_pushinteger(l, 0xa);
	lua_setfield(l, -2, "ARM64_BARRIER_ISHST");
	lua_pushinteger(l, 0xb);
	lua_setfield(l, -2, "ARM64_BARRIER_ISH");
	lua_pushinteger(l, 0xd);
	lua_setfield(l, -2, "ARM64_BARRIER_LD");
	lua_pushinteger(l, 0xe);
	lua_setfield(l, -2, "ARM64_BARRIER_ST");
	lua_pushinteger(l, 0xf);
	lua_setfield(l, -2, "ARM64_BARRIER_SY");

	/* Operand type for instruction's operands */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_OP_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_OP_REG");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_OP_IMM");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_OP_MEM");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_OP_FP");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "ARM64_OP_CIMM");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "ARM64_OP_REG_MRS");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "ARM64_OP_REG_MSR");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "ARM64_OP_PSTATE");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "ARM64_OP_SYS");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "ARM64_OP_PREFETCH");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "ARM64_OP_BARRIER");

	/* TLBI operations */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_TLBI_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_TLBI_VMALLE1IS");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_TLBI_VAE1IS");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_TLBI_ASIDE1IS");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_TLBI_VAAE1IS");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM64_TLBI_VALE1IS");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM64_TLBI_VAALE1IS");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM64_TLBI_ALLE2IS");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM64_TLBI_VAE2IS");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM64_TLBI_ALLE1IS");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM64_TLBI_VALE2IS");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "ARM64_TLBI_VMALLS12E1IS");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "ARM64_TLBI_ALLE3IS");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "ARM64_TLBI_VAE3IS");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "ARM64_TLBI_VALE3IS");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "ARM64_TLBI_IPAS2E1IS");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM64_TLBI_IPAS2LE1IS");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "ARM64_TLBI_IPAS2E1");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "ARM64_TLBI_IPAS2LE1");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "ARM64_TLBI_VMALLE1");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "ARM64_TLBI_VAE1");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "ARM64_TLBI_ASIDE1");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "ARM64_TLBI_VAAE1");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "ARM64_TLBI_VALE1");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "ARM64_TLBI_VAALE1");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "ARM64_TLBI_ALLE2");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "ARM64_TLBI_VAE2");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "ARM64_TLBI_ALLE1");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "ARM64_TLBI_VALE2");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "ARM64_TLBI_VMALLS12E1");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "ARM64_TLBI_ALLE3");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "ARM64_TLBI_VAE3");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "ARM64_TLBI_VALE3");

	/* AT operations */
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "ARM64_AT_S1E1R");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "ARM64_AT_S1E1W");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "ARM64_AT_S1E0R");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "ARM64_AT_S1E0W");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "ARM64_AT_S1E2R");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "ARM64_AT_S1E2W");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "ARM64_AT_S12E1R");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "ARM64_AT_S12E1W");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "ARM64_AT_S12E0R");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "ARM64_AT_S12E0W");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "ARM64_AT_S1E3R");
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "ARM64_AT_S1E3W");

	/* DC operations */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_DC_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_DC_ZVA");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_DC_IVAC");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_DC_ISW");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_DC_CVAC");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM64_DC_CSW");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM64_DC_CVAU");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM64_DC_CIVAC");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM64_DC_CISW");

	/* IC operations */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_IC_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_IC_IALLUIS");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_IC_IALLU");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_IC_IVAU");

	/* Prefetch operations (PRFM) */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_PRFM_INVALID");
	lua_pushinteger(l, 0x00+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLDL1KEEP");
	lua_pushinteger(l, 0x01+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLDL1STRM");
	lua_pushinteger(l, 0x02+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLDL2KEEP");
	lua_pushinteger(l, 0x03+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLDL2STRM");
	lua_pushinteger(l, 0x04+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLDL3KEEP");
	lua_pushinteger(l, 0x05+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLDL3STRM");
	lua_pushinteger(l, 0x08+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLIL1KEEP");
	lua_pushinteger(l, 0x09+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLIL1STRM");
	lua_pushinteger(l, 0x0a+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLIL2KEEP");
	lua_pushinteger(l, 0x0b+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLIL2STRM");
	lua_pushinteger(l, 0x0c+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLIL3KEEP");
	lua_pushinteger(l, 0x0d+1);
	lua_setfield(l, -2, "ARM64_PRFM_PLIL3STRM");
	lua_pushinteger(l, 0x10+1);
	lua_setfield(l, -2, "ARM64_PRFM_PSTL1KEEP");
	lua_pushinteger(l, 0x11+1);
	lua_setfield(l, -2, "ARM64_PRFM_PSTL1STRM");
	lua_pushinteger(l, 0x12+1);
	lua_setfield(l, -2, "ARM64_PRFM_PSTL2KEEP");
	lua_pushinteger(l, 0x13+1);
	lua_setfield(l, -2, "ARM64_PRFM_PSTL2STRM");
	lua_pushinteger(l, 0x14+1);
	lua_setfield(l, -2, "ARM64_PRFM_PSTL3KEEP");
	lua_pushinteger(l, 0x15+1);
	lua_setfield(l, -2, "ARM64_PRFM_PSTL3STRM");

	/* ARM64 registers */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_REG_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_REG_X29");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_REG_X30");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_REG_NZCV");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_REG_SP");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM64_REG_WSP");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM64_REG_WZR");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM64_REG_XZR");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM64_REG_B0");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM64_REG_B1");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM64_REG_B2");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "ARM64_REG_B3");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "ARM64_REG_B4");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "ARM64_REG_B5");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "ARM64_REG_B6");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "ARM64_REG_B7");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM64_REG_B8");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "ARM64_REG_B9");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "ARM64_REG_B10");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "ARM64_REG_B11");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "ARM64_REG_B12");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "ARM64_REG_B13");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "ARM64_REG_B14");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "ARM64_REG_B15");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "ARM64_REG_B16");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "ARM64_REG_B17");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "ARM64_REG_B18");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "ARM64_REG_B19");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "ARM64_REG_B20");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "ARM64_REG_B21");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "ARM64_REG_B22");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "ARM64_REG_B23");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "ARM64_REG_B24");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "ARM64_REG_B25");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "ARM64_REG_B26");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "ARM64_REG_B27");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "ARM64_REG_B28");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "ARM64_REG_B29");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "ARM64_REG_B30");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "ARM64_REG_B31");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "ARM64_REG_D0");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "ARM64_REG_D1");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "ARM64_REG_D2");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "ARM64_REG_D3");
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "ARM64_REG_D4");
	lua_pushinteger(l, 45);
	lua_setfield(l, -2, "ARM64_REG_D5");
	lua_pushinteger(l, 46);
	lua_setfield(l, -2, "ARM64_REG_D6");
	lua_pushinteger(l, 47);
	lua_setfield(l, -2, "ARM64_REG_D7");
	lua_pushinteger(l, 48);
	lua_setfield(l, -2, "ARM64_REG_D8");
	lua_pushinteger(l, 49);
	lua_setfield(l, -2, "ARM64_REG_D9");
	lua_pushinteger(l, 50);
	lua_setfield(l, -2, "ARM64_REG_D10");
	lua_pushinteger(l, 51);
	lua_setfield(l, -2, "ARM64_REG_D11");
	lua_pushinteger(l, 52);
	lua_setfield(l, -2, "ARM64_REG_D12");
	lua_pushinteger(l, 53);
	lua_setfield(l, -2, "ARM64_REG_D13");
	lua_pushinteger(l, 54);
	lua_setfield(l, -2, "ARM64_REG_D14");
	lua_pushinteger(l, 55);
	lua_setfield(l, -2, "ARM64_REG_D15");
	lua_pushinteger(l, 56);
	lua_setfield(l, -2, "ARM64_REG_D16");
	lua_pushinteger(l, 57);
	lua_setfield(l, -2, "ARM64_REG_D17");
	lua_pushinteger(l, 58);
	lua_setfield(l, -2, "ARM64_REG_D18");
	lua_pushinteger(l, 59);
	lua_setfield(l, -2, "ARM64_REG_D19");
	lua_pushinteger(l, 60);
	lua_setfield(l, -2, "ARM64_REG_D20");
	lua_pushinteger(l, 61);
	lua_setfield(l, -2, "ARM64_REG_D21");
	lua_pushinteger(l, 62);
	lua_setfield(l, -2, "ARM64_REG_D22");
	lua_pushinteger(l, 63);
	lua_setfield(l, -2, "ARM64_REG_D23");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "ARM64_REG_D24");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "ARM64_REG_D25");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "ARM64_REG_D26");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "ARM64_REG_D27");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "ARM64_REG_D28");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "ARM64_REG_D29");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "ARM64_REG_D30");
	lua_pushinteger(l, 71);
	lua_setfield(l, -2, "ARM64_REG_D31");
	lua_pushinteger(l, 72);
	lua_setfield(l, -2, "ARM64_REG_H0");
	lua_pushinteger(l, 73);
	lua_setfield(l, -2, "ARM64_REG_H1");
	lua_pushinteger(l, 74);
	lua_setfield(l, -2, "ARM64_REG_H2");
	lua_pushinteger(l, 75);
	lua_setfield(l, -2, "ARM64_REG_H3");
	lua_pushinteger(l, 76);
	lua_setfield(l, -2, "ARM64_REG_H4");
	lua_pushinteger(l, 77);
	lua_setfield(l, -2, "ARM64_REG_H5");
	lua_pushinteger(l, 78);
	lua_setfield(l, -2, "ARM64_REG_H6");
	lua_pushinteger(l, 79);
	lua_setfield(l, -2, "ARM64_REG_H7");
	lua_pushinteger(l, 80);
	lua_setfield(l, -2, "ARM64_REG_H8");
	lua_pushinteger(l, 81);
	lua_setfield(l, -2, "ARM64_REG_H9");
	lua_pushinteger(l, 82);
	lua_setfield(l, -2, "ARM64_REG_H10");
	lua_pushinteger(l, 83);
	lua_setfield(l, -2, "ARM64_REG_H11");
	lua_pushinteger(l, 84);
	lua_setfield(l, -2, "ARM64_REG_H12");
	lua_pushinteger(l, 85);
	lua_setfield(l, -2, "ARM64_REG_H13");
	lua_pushinteger(l, 86);
	lua_setfield(l, -2, "ARM64_REG_H14");
	lua_pushinteger(l, 87);
	lua_setfield(l, -2, "ARM64_REG_H15");
	lua_pushinteger(l, 88);
	lua_setfield(l, -2, "ARM64_REG_H16");
	lua_pushinteger(l, 89);
	lua_setfield(l, -2, "ARM64_REG_H17");
	lua_pushinteger(l, 90);
	lua_setfield(l, -2, "ARM64_REG_H18");
	lua_pushinteger(l, 91);
	lua_setfield(l, -2, "ARM64_REG_H19");
	lua_pushinteger(l, 92);
	lua_setfield(l, -2, "ARM64_REG_H20");
	lua_pushinteger(l, 93);
	lua_setfield(l, -2, "ARM64_REG_H21");
	lua_pushinteger(l, 94);
	lua_setfield(l, -2, "ARM64_REG_H22");
	lua_pushinteger(l, 95);
	lua_setfield(l, -2, "ARM64_REG_H23");
	lua_pushinteger(l, 96);
	lua_setfield(l, -2, "ARM64_REG_H24");
	lua_pushinteger(l, 97);
	lua_setfield(l, -2, "ARM64_REG_H25");
	lua_pushinteger(l, 98);
	lua_setfield(l, -2, "ARM64_REG_H26");
	lua_pushinteger(l, 99);
	lua_setfield(l, -2, "ARM64_REG_H27");
	lua_pushinteger(l, 100);
	lua_setfield(l, -2, "ARM64_REG_H28");
	lua_pushinteger(l, 101);
	lua_setfield(l, -2, "ARM64_REG_H29");
	lua_pushinteger(l, 102);
	lua_setfield(l, -2, "ARM64_REG_H30");
	lua_pushinteger(l, 103);
	lua_setfield(l, -2, "ARM64_REG_H31");
	lua_pushinteger(l, 104);
	lua_setfield(l, -2, "ARM64_REG_Q0");
	lua_pushinteger(l, 105);
	lua_setfield(l, -2, "ARM64_REG_Q1");
	lua_pushinteger(l, 106);
	lua_setfield(l, -2, "ARM64_REG_Q2");
	lua_pushinteger(l, 107);
	lua_setfield(l, -2, "ARM64_REG_Q3");
	lua_pushinteger(l, 108);
	lua_setfield(l, -2, "ARM64_REG_Q4");
	lua_pushinteger(l, 109);
	lua_setfield(l, -2, "ARM64_REG_Q5");
	lua_pushinteger(l, 110);
	lua_setfield(l, -2, "ARM64_REG_Q6");
	lua_pushinteger(l, 111);
	lua_setfield(l, -2, "ARM64_REG_Q7");
	lua_pushinteger(l, 112);
	lua_setfield(l, -2, "ARM64_REG_Q8");
	lua_pushinteger(l, 113);
	lua_setfield(l, -2, "ARM64_REG_Q9");
	lua_pushinteger(l, 114);
	lua_setfield(l, -2, "ARM64_REG_Q10");
	lua_pushinteger(l, 115);
	lua_setfield(l, -2, "ARM64_REG_Q11");
	lua_pushinteger(l, 116);
	lua_setfield(l, -2, "ARM64_REG_Q12");
	lua_pushinteger(l, 117);
	lua_setfield(l, -2, "ARM64_REG_Q13");
	lua_pushinteger(l, 118);
	lua_setfield(l, -2, "ARM64_REG_Q14");
	lua_pushinteger(l, 119);
	lua_setfield(l, -2, "ARM64_REG_Q15");
	lua_pushinteger(l, 120);
	lua_setfield(l, -2, "ARM64_REG_Q16");
	lua_pushinteger(l, 121);
	lua_setfield(l, -2, "ARM64_REG_Q17");
	lua_pushinteger(l, 122);
	lua_setfield(l, -2, "ARM64_REG_Q18");
	lua_pushinteger(l, 123);
	lua_setfield(l, -2, "ARM64_REG_Q19");
	lua_pushinteger(l, 124);
	lua_setfield(l, -2, "ARM64_REG_Q20");
	lua_pushinteger(l, 125);
	lua_setfield(l, -2, "ARM64_REG_Q21");
	lua_pushinteger(l, 126);
	lua_setfield(l, -2, "ARM64_REG_Q22");
	lua_pushinteger(l, 127);
	lua_setfield(l, -2, "ARM64_REG_Q23");
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "ARM64_REG_Q24");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "ARM64_REG_Q25");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "ARM64_REG_Q26");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "ARM64_REG_Q27");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "ARM64_REG_Q28");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "ARM64_REG_Q29");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "ARM64_REG_Q30");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "ARM64_REG_Q31");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "ARM64_REG_S0");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "ARM64_REG_S1");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "ARM64_REG_S2");
	lua_pushinteger(l, 139);
	lua_setfield(l, -2, "ARM64_REG_S3");
	lua_pushinteger(l, 140);
	lua_setfield(l, -2, "ARM64_REG_S4");
	lua_pushinteger(l, 141);
	lua_setfield(l, -2, "ARM64_REG_S5");
	lua_pushinteger(l, 142);
	lua_setfield(l, -2, "ARM64_REG_S6");
	lua_pushinteger(l, 143);
	lua_setfield(l, -2, "ARM64_REG_S7");
	lua_pushinteger(l, 144);
	lua_setfield(l, -2, "ARM64_REG_S8");
	lua_pushinteger(l, 145);
	lua_setfield(l, -2, "ARM64_REG_S9");
	lua_pushinteger(l, 146);
	lua_setfield(l, -2, "ARM64_REG_S10");
	lua_pushinteger(l, 147);
	lua_setfield(l, -2, "ARM64_REG_S11");
	lua_pushinteger(l, 148);
	lua_setfield(l, -2, "ARM64_REG_S12");
	lua_pushinteger(l, 149);
	lua_setfield(l, -2, "ARM64_REG_S13");
	lua_pushinteger(l, 150);
	lua_setfield(l, -2, "ARM64_REG_S14");
	lua_pushinteger(l, 151);
	lua_setfield(l, -2, "ARM64_REG_S15");
	lua_pushinteger(l, 152);
	lua_setfield(l, -2, "ARM64_REG_S16");
	lua_pushinteger(l, 153);
	lua_setfield(l, -2, "ARM64_REG_S17");
	lua_pushinteger(l, 154);
	lua_setfield(l, -2, "ARM64_REG_S18");
	lua_pushinteger(l, 155);
	lua_setfield(l, -2, "ARM64_REG_S19");
	lua_pushinteger(l, 156);
	lua_setfield(l, -2, "ARM64_REG_S20");
	lua_pushinteger(l, 157);
	lua_setfield(l, -2, "ARM64_REG_S21");
	lua_pushinteger(l, 158);
	lua_setfield(l, -2, "ARM64_REG_S22");
	lua_pushinteger(l, 159);
	lua_setfield(l, -2, "ARM64_REG_S23");
	lua_pushinteger(l, 160);
	lua_setfield(l, -2, "ARM64_REG_S24");
	lua_pushinteger(l, 161);
	lua_setfield(l, -2, "ARM64_REG_S25");
	lua_pushinteger(l, 162);
	lua_setfield(l, -2, "ARM64_REG_S26");
	lua_pushinteger(l, 163);
	lua_setfield(l, -2, "ARM64_REG_S27");
	lua_pushinteger(l, 164);
	lua_setfield(l, -2, "ARM64_REG_S28");
	lua_pushinteger(l, 165);
	lua_setfield(l, -2, "ARM64_REG_S29");
	lua_pushinteger(l, 166);
	lua_setfield(l, -2, "ARM64_REG_S30");
	lua_pushinteger(l, 167);
	lua_setfield(l, -2, "ARM64_REG_S31");
	lua_pushinteger(l, 168);
	lua_setfield(l, -2, "ARM64_REG_W0");
	lua_pushinteger(l, 169);
	lua_setfield(l, -2, "ARM64_REG_W1");
	lua_pushinteger(l, 170);
	lua_setfield(l, -2, "ARM64_REG_W2");
	lua_pushinteger(l, 171);
	lua_setfield(l, -2, "ARM64_REG_W3");
	lua_pushinteger(l, 172);
	lua_setfield(l, -2, "ARM64_REG_W4");
	lua_pushinteger(l, 173);
	lua_setfield(l, -2, "ARM64_REG_W5");
	lua_pushinteger(l, 174);
	lua_setfield(l, -2, "ARM64_REG_W6");
	lua_pushinteger(l, 175);
	lua_setfield(l, -2, "ARM64_REG_W7");
	lua_pushinteger(l, 176);
	lua_setfield(l, -2, "ARM64_REG_W8");
	lua_pushinteger(l, 177);
	lua_setfield(l, -2, "ARM64_REG_W9");
	lua_pushinteger(l, 178);
	lua_setfield(l, -2, "ARM64_REG_W10");
	lua_pushinteger(l, 179);
	lua_setfield(l, -2, "ARM64_REG_W11");
	lua_pushinteger(l, 180);
	lua_setfield(l, -2, "ARM64_REG_W12");
	lua_pushinteger(l, 181);
	lua_setfield(l, -2, "ARM64_REG_W13");
	lua_pushinteger(l, 182);
	lua_setfield(l, -2, "ARM64_REG_W14");
	lua_pushinteger(l, 183);
	lua_setfield(l, -2, "ARM64_REG_W15");
	lua_pushinteger(l, 184);
	lua_setfield(l, -2, "ARM64_REG_W16");
	lua_pushinteger(l, 185);
	lua_setfield(l, -2, "ARM64_REG_W17");
	lua_pushinteger(l, 186);
	lua_setfield(l, -2, "ARM64_REG_W18");
	lua_pushinteger(l, 187);
	lua_setfield(l, -2, "ARM64_REG_W19");
	lua_pushinteger(l, 188);
	lua_setfield(l, -2, "ARM64_REG_W20");
	lua_pushinteger(l, 189);
	lua_setfield(l, -2, "ARM64_REG_W21");
	lua_pushinteger(l, 190);
	lua_setfield(l, -2, "ARM64_REG_W22");
	lua_pushinteger(l, 191);
	lua_setfield(l, -2, "ARM64_REG_W23");
	lua_pushinteger(l, 192);
	lua_setfield(l, -2, "ARM64_REG_W24");
	lua_pushinteger(l, 193);
	lua_setfield(l, -2, "ARM64_REG_W25");
	lua_pushinteger(l, 194);
	lua_setfield(l, -2, "ARM64_REG_W26");
	lua_pushinteger(l, 195);
	lua_setfield(l, -2, "ARM64_REG_W27");
	lua_pushinteger(l, 196);
	lua_setfield(l, -2, "ARM64_REG_W28");
	lua_pushinteger(l, 197);
	lua_setfield(l, -2, "ARM64_REG_W29");
	lua_pushinteger(l, 198);
	lua_setfield(l, -2, "ARM64_REG_W30");
	lua_pushinteger(l, 199);
	lua_setfield(l, -2, "ARM64_REG_X0");
	lua_pushinteger(l, 200);
	lua_setfield(l, -2, "ARM64_REG_X1");
	lua_pushinteger(l, 201);
	lua_setfield(l, -2, "ARM64_REG_X2");
	lua_pushinteger(l, 202);
	lua_setfield(l, -2, "ARM64_REG_X3");
	lua_pushinteger(l, 203);
	lua_setfield(l, -2, "ARM64_REG_X4");
	lua_pushinteger(l, 204);
	lua_setfield(l, -2, "ARM64_REG_X5");
	lua_pushinteger(l, 205);
	lua_setfield(l, -2, "ARM64_REG_X6");
	lua_pushinteger(l, 206);
	lua_setfield(l, -2, "ARM64_REG_X7");
	lua_pushinteger(l, 207);
	lua_setfield(l, -2, "ARM64_REG_X8");
	lua_pushinteger(l, 208);
	lua_setfield(l, -2, "ARM64_REG_X9");
	lua_pushinteger(l, 209);
	lua_setfield(l, -2, "ARM64_REG_X10");
	lua_pushinteger(l, 210);
	lua_setfield(l, -2, "ARM64_REG_X11");
	lua_pushinteger(l, 211);
	lua_setfield(l, -2, "ARM64_REG_X12");
	lua_pushinteger(l, 212);
	lua_setfield(l, -2, "ARM64_REG_X13");
	lua_pushinteger(l, 213);
	lua_setfield(l, -2, "ARM64_REG_X14");
	lua_pushinteger(l, 214);
	lua_setfield(l, -2, "ARM64_REG_X15");
	lua_pushinteger(l, 215);
	lua_setfield(l, -2, "ARM64_REG_X16");
	lua_pushinteger(l, 216);
	lua_setfield(l, -2, "ARM64_REG_X17");
	lua_pushinteger(l, 217);
	lua_setfield(l, -2, "ARM64_REG_X18");
	lua_pushinteger(l, 218);
	lua_setfield(l, -2, "ARM64_REG_X19");
	lua_pushinteger(l, 219);
	lua_setfield(l, -2, "ARM64_REG_X20");
	lua_pushinteger(l, 220);
	lua_setfield(l, -2, "ARM64_REG_X21");
	lua_pushinteger(l, 221);
	lua_setfield(l, -2, "ARM64_REG_X22");
	lua_pushinteger(l, 222);
	lua_setfield(l, -2, "ARM64_REG_X23");
	lua_pushinteger(l, 223);
	lua_setfield(l, -2, "ARM64_REG_X24");
	lua_pushinteger(l, 224);
	lua_setfield(l, -2, "ARM64_REG_X25");
	lua_pushinteger(l, 225);
	lua_setfield(l, -2, "ARM64_REG_X26");
	lua_pushinteger(l, 226);
	lua_setfield(l, -2, "ARM64_REG_X27");
	lua_pushinteger(l, 227);
	lua_setfield(l, -2, "ARM64_REG_X28");
	lua_pushinteger(l, 228);
	lua_setfield(l, -2, "ARM64_REG_V0");
	lua_pushinteger(l, 229);
	lua_setfield(l, -2, "ARM64_REG_V1");
	lua_pushinteger(l, 230);
	lua_setfield(l, -2, "ARM64_REG_V2");
	lua_pushinteger(l, 231);
	lua_setfield(l, -2, "ARM64_REG_V3");
	lua_pushinteger(l, 232);
	lua_setfield(l, -2, "ARM64_REG_V4");
	lua_pushinteger(l, 233);
	lua_setfield(l, -2, "ARM64_REG_V5");
	lua_pushinteger(l, 234);
	lua_setfield(l, -2, "ARM64_REG_V6");
	lua_pushinteger(l, 235);
	lua_setfield(l, -2, "ARM64_REG_V7");
	lua_pushinteger(l, 236);
	lua_setfield(l, -2, "ARM64_REG_V8");
	lua_pushinteger(l, 237);
	lua_setfield(l, -2, "ARM64_REG_V9");
	lua_pushinteger(l, 238);
	lua_setfield(l, -2, "ARM64_REG_V10");
	lua_pushinteger(l, 239);
	lua_setfield(l, -2, "ARM64_REG_V11");
	lua_pushinteger(l, 240);
	lua_setfield(l, -2, "ARM64_REG_V12");
	lua_pushinteger(l, 241);
	lua_setfield(l, -2, "ARM64_REG_V13");
	lua_pushinteger(l, 242);
	lua_setfield(l, -2, "ARM64_REG_V14");
	lua_pushinteger(l, 243);
	lua_setfield(l, -2, "ARM64_REG_V15");
	lua_pushinteger(l, 244);
	lua_setfield(l, -2, "ARM64_REG_V16");
	lua_pushinteger(l, 245);
	lua_setfield(l, -2, "ARM64_REG_V17");
	lua_pushinteger(l, 246);
	lua_setfield(l, -2, "ARM64_REG_V18");
	lua_pushinteger(l, 247);
	lua_setfield(l, -2, "ARM64_REG_V19");
	lua_pushinteger(l, 248);
	lua_setfield(l, -2, "ARM64_REG_V20");
	lua_pushinteger(l, 249);
	lua_setfield(l, -2, "ARM64_REG_V21");
	lua_pushinteger(l, 250);
	lua_setfield(l, -2, "ARM64_REG_V22");
	lua_pushinteger(l, 251);
	lua_setfield(l, -2, "ARM64_REG_V23");
	lua_pushinteger(l, 252);
	lua_setfield(l, -2, "ARM64_REG_V24");
	lua_pushinteger(l, 253);
	lua_setfield(l, -2, "ARM64_REG_V25");
	lua_pushinteger(l, 254);
	lua_setfield(l, -2, "ARM64_REG_V26");
	lua_pushinteger(l, 255);
	lua_setfield(l, -2, "ARM64_REG_V27");
	lua_pushinteger(l, 256);
	lua_setfield(l, -2, "ARM64_REG_V28");
	lua_pushinteger(l, 257);
	lua_setfield(l, -2, "ARM64_REG_V29");
	lua_pushinteger(l, 258);
	lua_setfield(l, -2, "ARM64_REG_V30");
	lua_pushinteger(l, 259);
	lua_setfield(l, -2, "ARM64_REG_V31");
	lua_pushinteger(l, 260);
	lua_setfield(l, -2, "ARM64_REG_ENDING");

	/* alias registers */
	lua_pushinteger(l, ARM64_REG_X16);
	lua_setfield(l, -2, "ARM64_REG_IP1");
	lua_pushinteger(l, ARM64_REG_X17);
	lua_setfield(l, -2, "ARM64_REG_IP0");
	lua_pushinteger(l, ARM64_REG_X29);
	lua_setfield(l, -2, "ARM64_REG_FP");
	lua_pushinteger(l, ARM64_REG_X30);
	lua_setfield(l, -2, "ARM64_REG_LR");

	/* ARM64 instruction */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_INS_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_INS_ABS");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM64_INS_ADC");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM64_INS_ADDHN");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM64_INS_ADDHN2");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM64_INS_ADDP");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM64_INS_ADD");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM64_INS_ADDV");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM64_INS_ADR");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM64_INS_ADRP");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM64_INS_AESD");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "ARM64_INS_AESE");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "ARM64_INS_AESIMC");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "ARM64_INS_AESMC");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "ARM64_INS_AND");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "ARM64_INS_ASR");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM64_INS_B");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "ARM64_INS_BFM");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "ARM64_INS_BIC");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "ARM64_INS_BIF");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "ARM64_INS_BIT");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "ARM64_INS_BL");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "ARM64_INS_BLR");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "ARM64_INS_BR");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "ARM64_INS_BRK");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "ARM64_INS_BSL");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "ARM64_INS_CBNZ");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "ARM64_INS_CBZ");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "ARM64_INS_CCMN");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "ARM64_INS_CCMP");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "ARM64_INS_CLREX");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "ARM64_INS_CLS");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "ARM64_INS_CLZ");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "ARM64_INS_CMEQ");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "ARM64_INS_CMGE");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "ARM64_INS_CMGT");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "ARM64_INS_CMHI");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "ARM64_INS_CMHS");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "ARM64_INS_CMLE");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "ARM64_INS_CMLT");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "ARM64_INS_CMTST");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "ARM64_INS_CNT");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "ARM64_INS_MOV");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "ARM64_INS_CRC32B");
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "ARM64_INS_CRC32CB");
	lua_pushinteger(l, 45);
	lua_setfield(l, -2, "ARM64_INS_CRC32CH");
	lua_pushinteger(l, 46);
	lua_setfield(l, -2, "ARM64_INS_CRC32CW");
	lua_pushinteger(l, 47);
	lua_setfield(l, -2, "ARM64_INS_CRC32CX");
	lua_pushinteger(l, 48);
	lua_setfield(l, -2, "ARM64_INS_CRC32H");
	lua_pushinteger(l, 49);
	lua_setfield(l, -2, "ARM64_INS_CRC32W");
	lua_pushinteger(l, 50);
	lua_setfield(l, -2, "ARM64_INS_CRC32X");
	lua_pushinteger(l, 51);
	lua_setfield(l, -2, "ARM64_INS_CSEL");
	lua_pushinteger(l, 52);
	lua_setfield(l, -2, "ARM64_INS_CSINC");
	lua_pushinteger(l, 53);
	lua_setfield(l, -2, "ARM64_INS_CSINV");
	lua_pushinteger(l, 54);
	lua_setfield(l, -2, "ARM64_INS_CSNEG");
	lua_pushinteger(l, 55);
	lua_setfield(l, -2, "ARM64_INS_DCPS1");
	lua_pushinteger(l, 56);
	lua_setfield(l, -2, "ARM64_INS_DCPS2");
	lua_pushinteger(l, 57);
	lua_setfield(l, -2, "ARM64_INS_DCPS3");
	lua_pushinteger(l, 58);
	lua_setfield(l, -2, "ARM64_INS_DMB");
	lua_pushinteger(l, 59);
	lua_setfield(l, -2, "ARM64_INS_DRPS");
	lua_pushinteger(l, 60);
	lua_setfield(l, -2, "ARM64_INS_DSB");
	lua_pushinteger(l, 61);
	lua_setfield(l, -2, "ARM64_INS_DUP");
	lua_pushinteger(l, 62);
	lua_setfield(l, -2, "ARM64_INS_EON");
	lua_pushinteger(l, 63);
	lua_setfield(l, -2, "ARM64_INS_EOR");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "ARM64_INS_ERET");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "ARM64_INS_EXTR");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "ARM64_INS_EXT");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "ARM64_INS_FABD");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "ARM64_INS_FABS");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "ARM64_INS_FACGE");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "ARM64_INS_FACGT");
	lua_pushinteger(l, 71);
	lua_setfield(l, -2, "ARM64_INS_FADD");
	lua_pushinteger(l, 72);
	lua_setfield(l, -2, "ARM64_INS_FADDP");
	lua_pushinteger(l, 73);
	lua_setfield(l, -2, "ARM64_INS_FCCMP");
	lua_pushinteger(l, 74);
	lua_setfield(l, -2, "ARM64_INS_FCCMPE");
	lua_pushinteger(l, 75);
	lua_setfield(l, -2, "ARM64_INS_FCMEQ");
	lua_pushinteger(l, 76);
	lua_setfield(l, -2, "ARM64_INS_FCMGE");
	lua_pushinteger(l, 77);
	lua_setfield(l, -2, "ARM64_INS_FCMGT");
	lua_pushinteger(l, 78);
	lua_setfield(l, -2, "ARM64_INS_FCMLE");
	lua_pushinteger(l, 79);
	lua_setfield(l, -2, "ARM64_INS_FCMLT");
	lua_pushinteger(l, 80);
	lua_setfield(l, -2, "ARM64_INS_FCMP");
	lua_pushinteger(l, 81);
	lua_setfield(l, -2, "ARM64_INS_FCMPE");
	lua_pushinteger(l, 82);
	lua_setfield(l, -2, "ARM64_INS_FCSEL");
	lua_pushinteger(l, 83);
	lua_setfield(l, -2, "ARM64_INS_FCVTAS");
	lua_pushinteger(l, 84);
	lua_setfield(l, -2, "ARM64_INS_FCVTAU");
	lua_pushinteger(l, 85);
	lua_setfield(l, -2, "ARM64_INS_FCVT");
	lua_pushinteger(l, 86);
	lua_setfield(l, -2, "ARM64_INS_FCVTL");
	lua_pushinteger(l, 87);
	lua_setfield(l, -2, "ARM64_INS_FCVTL2");
	lua_pushinteger(l, 88);
	lua_setfield(l, -2, "ARM64_INS_FCVTMS");
	lua_pushinteger(l, 89);
	lua_setfield(l, -2, "ARM64_INS_FCVTMU");
	lua_pushinteger(l, 90);
	lua_setfield(l, -2, "ARM64_INS_FCVTNS");
	lua_pushinteger(l, 91);
	lua_setfield(l, -2, "ARM64_INS_FCVTNU");
	lua_pushinteger(l, 92);
	lua_setfield(l, -2, "ARM64_INS_FCVTN");
	lua_pushinteger(l, 93);
	lua_setfield(l, -2, "ARM64_INS_FCVTN2");
	lua_pushinteger(l, 94);
	lua_setfield(l, -2, "ARM64_INS_FCVTPS");
	lua_pushinteger(l, 95);
	lua_setfield(l, -2, "ARM64_INS_FCVTPU");
	lua_pushinteger(l, 96);
	lua_setfield(l, -2, "ARM64_INS_FCVTXN");
	lua_pushinteger(l, 97);
	lua_setfield(l, -2, "ARM64_INS_FCVTXN2");
	lua_pushinteger(l, 98);
	lua_setfield(l, -2, "ARM64_INS_FCVTZS");
	lua_pushinteger(l, 99);
	lua_setfield(l, -2, "ARM64_INS_FCVTZU");
	lua_pushinteger(l, 100);
	lua_setfield(l, -2, "ARM64_INS_FDIV");
	lua_pushinteger(l, 101);
	lua_setfield(l, -2, "ARM64_INS_FMADD");
	lua_pushinteger(l, 102);
	lua_setfield(l, -2, "ARM64_INS_FMAX");
	lua_pushinteger(l, 103);
	lua_setfield(l, -2, "ARM64_INS_FMAXNM");
	lua_pushinteger(l, 104);
	lua_setfield(l, -2, "ARM64_INS_FMAXNMP");
	lua_pushinteger(l, 105);
	lua_setfield(l, -2, "ARM64_INS_FMAXNMV");
	lua_pushinteger(l, 106);
	lua_setfield(l, -2, "ARM64_INS_FMAXP");
	lua_pushinteger(l, 107);
	lua_setfield(l, -2, "ARM64_INS_FMAXV");
	lua_pushinteger(l, 108);
	lua_setfield(l, -2, "ARM64_INS_FMIN");
	lua_pushinteger(l, 109);
	lua_setfield(l, -2, "ARM64_INS_FMINNM");
	lua_pushinteger(l, 110);
	lua_setfield(l, -2, "ARM64_INS_FMINNMP");
	lua_pushinteger(l, 111);
	lua_setfield(l, -2, "ARM64_INS_FMINNMV");
	lua_pushinteger(l, 112);
	lua_setfield(l, -2, "ARM64_INS_FMINP");
	lua_pushinteger(l, 113);
	lua_setfield(l, -2, "ARM64_INS_FMINV");
	lua_pushinteger(l, 114);
	lua_setfield(l, -2, "ARM64_INS_FMLA");
	lua_pushinteger(l, 115);
	lua_setfield(l, -2, "ARM64_INS_FMLS");
	lua_pushinteger(l, 116);
	lua_setfield(l, -2, "ARM64_INS_FMOV");
	lua_pushinteger(l, 117);
	lua_setfield(l, -2, "ARM64_INS_FMSUB");
	lua_pushinteger(l, 118);
	lua_setfield(l, -2, "ARM64_INS_FMUL");
	lua_pushinteger(l, 119);
	lua_setfield(l, -2, "ARM64_INS_FMULX");
	lua_pushinteger(l, 120);
	lua_setfield(l, -2, "ARM64_INS_FNEG");
	lua_pushinteger(l, 121);
	lua_setfield(l, -2, "ARM64_INS_FNMADD");
	lua_pushinteger(l, 122);
	lua_setfield(l, -2, "ARM64_INS_FNMSUB");
	lua_pushinteger(l, 123);
	lua_setfield(l, -2, "ARM64_INS_FNMUL");
	lua_pushinteger(l, 124);
	lua_setfield(l, -2, "ARM64_INS_FRECPE");
	lua_pushinteger(l, 125);
	lua_setfield(l, -2, "ARM64_INS_FRECPS");
	lua_pushinteger(l, 126);
	lua_setfield(l, -2, "ARM64_INS_FRECPX");
	lua_pushinteger(l, 127);
	lua_setfield(l, -2, "ARM64_INS_FRINTA");
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "ARM64_INS_FRINTI");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "ARM64_INS_FRINTM");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "ARM64_INS_FRINTN");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "ARM64_INS_FRINTP");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "ARM64_INS_FRINTX");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "ARM64_INS_FRINTZ");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "ARM64_INS_FRSQRTE");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "ARM64_INS_FRSQRTS");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "ARM64_INS_FSQRT");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "ARM64_INS_FSUB");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "ARM64_INS_HINT");
	lua_pushinteger(l, 139);
	lua_setfield(l, -2, "ARM64_INS_HLT");
	lua_pushinteger(l, 140);
	lua_setfield(l, -2, "ARM64_INS_HVC");
	lua_pushinteger(l, 141);
	lua_setfield(l, -2, "ARM64_INS_INS");
	lua_pushinteger(l, 142);
	lua_setfield(l, -2, "ARM64_INS_ISB");
	lua_pushinteger(l, 143);
	lua_setfield(l, -2, "ARM64_INS_LD1");
	lua_pushinteger(l, 144);
	lua_setfield(l, -2, "ARM64_INS_LD1R");
	lua_pushinteger(l, 145);
	lua_setfield(l, -2, "ARM64_INS_LD2R");
	lua_pushinteger(l, 146);
	lua_setfield(l, -2, "ARM64_INS_LD2");
	lua_pushinteger(l, 147);
	lua_setfield(l, -2, "ARM64_INS_LD3R");
	lua_pushinteger(l, 148);
	lua_setfield(l, -2, "ARM64_INS_LD3");
	lua_pushinteger(l, 149);
	lua_setfield(l, -2, "ARM64_INS_LD4");
	lua_pushinteger(l, 150);
	lua_setfield(l, -2, "ARM64_INS_LD4R");
	lua_pushinteger(l, 151);
	lua_setfield(l, -2, "ARM64_INS_LDARB");
	lua_pushinteger(l, 152);
	lua_setfield(l, -2, "ARM64_INS_LDARH");
	lua_pushinteger(l, 153);
	lua_setfield(l, -2, "ARM64_INS_LDAR");
	lua_pushinteger(l, 154);
	lua_setfield(l, -2, "ARM64_INS_LDAXP");
	lua_pushinteger(l, 155);
	lua_setfield(l, -2, "ARM64_INS_LDAXRB");
	lua_pushinteger(l, 156);
	lua_setfield(l, -2, "ARM64_INS_LDAXRH");
	lua_pushinteger(l, 157);
	lua_setfield(l, -2, "ARM64_INS_LDAXR");
	lua_pushinteger(l, 158);
	lua_setfield(l, -2, "ARM64_INS_LDNP");
	lua_pushinteger(l, 159);
	lua_setfield(l, -2, "ARM64_INS_LDP");
	lua_pushinteger(l, 160);
	lua_setfield(l, -2, "ARM64_INS_LDPSW");
	lua_pushinteger(l, 161);
	lua_setfield(l, -2, "ARM64_INS_LDRB");
	lua_pushinteger(l, 162);
	lua_setfield(l, -2, "ARM64_INS_LDR");
	lua_pushinteger(l, 163);
	lua_setfield(l, -2, "ARM64_INS_LDRH");
	lua_pushinteger(l, 164);
	lua_setfield(l, -2, "ARM64_INS_LDRSB");
	lua_pushinteger(l, 165);
	lua_setfield(l, -2, "ARM64_INS_LDRSH");
	lua_pushinteger(l, 166);
	lua_setfield(l, -2, "ARM64_INS_LDRSW");
	lua_pushinteger(l, 167);
	lua_setfield(l, -2, "ARM64_INS_LDTRB");
	lua_pushinteger(l, 168);
	lua_setfield(l, -2, "ARM64_INS_LDTRH");
	lua_pushinteger(l, 169);
	lua_setfield(l, -2, "ARM64_INS_LDTRSB");
	lua_pushinteger(l, 170);
	lua_setfield(l, -2, "ARM64_INS_LDTRSH");
	lua_pushinteger(l, 171);
	lua_setfield(l, -2, "ARM64_INS_LDTRSW");
	lua_pushinteger(l, 172);
	lua_setfield(l, -2, "ARM64_INS_LDTR");
	lua_pushinteger(l, 173);
	lua_setfield(l, -2, "ARM64_INS_LDURB");
	lua_pushinteger(l, 174);
	lua_setfield(l, -2, "ARM64_INS_LDUR");
	lua_pushinteger(l, 175);
	lua_setfield(l, -2, "ARM64_INS_LDURH");
	lua_pushinteger(l, 176);
	lua_setfield(l, -2, "ARM64_INS_LDURSB");
	lua_pushinteger(l, 177);
	lua_setfield(l, -2, "ARM64_INS_LDURSH");
	lua_pushinteger(l, 178);
	lua_setfield(l, -2, "ARM64_INS_LDURSW");
	lua_pushinteger(l, 179);
	lua_setfield(l, -2, "ARM64_INS_LDXP");
	lua_pushinteger(l, 180);
	lua_setfield(l, -2, "ARM64_INS_LDXRB");
	lua_pushinteger(l, 181);
	lua_setfield(l, -2, "ARM64_INS_LDXRH");
	lua_pushinteger(l, 182);
	lua_setfield(l, -2, "ARM64_INS_LDXR");
	lua_pushinteger(l, 183);
	lua_setfield(l, -2, "ARM64_INS_LSL");
	lua_pushinteger(l, 184);
	lua_setfield(l, -2, "ARM64_INS_LSR");
	lua_pushinteger(l, 185);
	lua_setfield(l, -2, "ARM64_INS_MADD");
	lua_pushinteger(l, 186);
	lua_setfield(l, -2, "ARM64_INS_MLA");
	lua_pushinteger(l, 187);
	lua_setfield(l, -2, "ARM64_INS_MLS");
	lua_pushinteger(l, 188);
	lua_setfield(l, -2, "ARM64_INS_MOVI");
	lua_pushinteger(l, 189);
	lua_setfield(l, -2, "ARM64_INS_MOVK");
	lua_pushinteger(l, 190);
	lua_setfield(l, -2, "ARM64_INS_MOVN");
	lua_pushinteger(l, 191);
	lua_setfield(l, -2, "ARM64_INS_MOVZ");
	lua_pushinteger(l, 192);
	lua_setfield(l, -2, "ARM64_INS_MRS");
	lua_pushinteger(l, 193);
	lua_setfield(l, -2, "ARM64_INS_MSR");
	lua_pushinteger(l, 194);
	lua_setfield(l, -2, "ARM64_INS_MSUB");
	lua_pushinteger(l, 195);
	lua_setfield(l, -2, "ARM64_INS_MUL");
	lua_pushinteger(l, 196);
	lua_setfield(l, -2, "ARM64_INS_MVNI");
	lua_pushinteger(l, 197);
	lua_setfield(l, -2, "ARM64_INS_NEG");
	lua_pushinteger(l, 198);
	lua_setfield(l, -2, "ARM64_INS_NOT");
	lua_pushinteger(l, 199);
	lua_setfield(l, -2, "ARM64_INS_ORN");
	lua_pushinteger(l, 200);
	lua_setfield(l, -2, "ARM64_INS_ORR");
	lua_pushinteger(l, 201);
	lua_setfield(l, -2, "ARM64_INS_PMULL2");
	lua_pushinteger(l, 202);
	lua_setfield(l, -2, "ARM64_INS_PMULL");
	lua_pushinteger(l, 203);
	lua_setfield(l, -2, "ARM64_INS_PMUL");
	lua_pushinteger(l, 204);
	lua_setfield(l, -2, "ARM64_INS_PRFM");
	lua_pushinteger(l, 205);
	lua_setfield(l, -2, "ARM64_INS_PRFUM");
	lua_pushinteger(l, 206);
	lua_setfield(l, -2, "ARM64_INS_RADDHN");
	lua_pushinteger(l, 207);
	lua_setfield(l, -2, "ARM64_INS_RADDHN2");
	lua_pushinteger(l, 208);
	lua_setfield(l, -2, "ARM64_INS_RBIT");
	lua_pushinteger(l, 209);
	lua_setfield(l, -2, "ARM64_INS_RET");
	lua_pushinteger(l, 210);
	lua_setfield(l, -2, "ARM64_INS_REV16");
	lua_pushinteger(l, 211);
	lua_setfield(l, -2, "ARM64_INS_REV32");
	lua_pushinteger(l, 212);
	lua_setfield(l, -2, "ARM64_INS_REV64");
	lua_pushinteger(l, 213);
	lua_setfield(l, -2, "ARM64_INS_REV");
	lua_pushinteger(l, 214);
	lua_setfield(l, -2, "ARM64_INS_ROR");
	lua_pushinteger(l, 215);
	lua_setfield(l, -2, "ARM64_INS_RSHRN2");
	lua_pushinteger(l, 216);
	lua_setfield(l, -2, "ARM64_INS_RSHRN");
	lua_pushinteger(l, 217);
	lua_setfield(l, -2, "ARM64_INS_RSUBHN");
	lua_pushinteger(l, 218);
	lua_setfield(l, -2, "ARM64_INS_RSUBHN2");
	lua_pushinteger(l, 219);
	lua_setfield(l, -2, "ARM64_INS_SABAL2");
	lua_pushinteger(l, 220);
	lua_setfield(l, -2, "ARM64_INS_SABAL");
	lua_pushinteger(l, 221);
	lua_setfield(l, -2, "ARM64_INS_SABA");
	lua_pushinteger(l, 222);
	lua_setfield(l, -2, "ARM64_INS_SABDL2");
	lua_pushinteger(l, 223);
	lua_setfield(l, -2, "ARM64_INS_SABDL");
	lua_pushinteger(l, 224);
	lua_setfield(l, -2, "ARM64_INS_SABD");
	lua_pushinteger(l, 225);
	lua_setfield(l, -2, "ARM64_INS_SADALP");
	lua_pushinteger(l, 226);
	lua_setfield(l, -2, "ARM64_INS_SADDLP");
	lua_pushinteger(l, 227);
	lua_setfield(l, -2, "ARM64_INS_SADDLV");
	lua_pushinteger(l, 228);
	lua_setfield(l, -2, "ARM64_INS_SADDL2");
	lua_pushinteger(l, 229);
	lua_setfield(l, -2, "ARM64_INS_SADDL");
	lua_pushinteger(l, 230);
	lua_setfield(l, -2, "ARM64_INS_SADDW2");
	lua_pushinteger(l, 231);
	lua_setfield(l, -2, "ARM64_INS_SADDW");
	lua_pushinteger(l, 232);
	lua_setfield(l, -2, "ARM64_INS_SBC");
	lua_pushinteger(l, 233);
	lua_setfield(l, -2, "ARM64_INS_SBFM");
	lua_pushinteger(l, 234);
	lua_setfield(l, -2, "ARM64_INS_SCVTF");
	lua_pushinteger(l, 235);
	lua_setfield(l, -2, "ARM64_INS_SDIV");
	lua_pushinteger(l, 236);
	lua_setfield(l, -2, "ARM64_INS_SHA1C");
	lua_pushinteger(l, 237);
	lua_setfield(l, -2, "ARM64_INS_SHA1H");
	lua_pushinteger(l, 238);
	lua_setfield(l, -2, "ARM64_INS_SHA1M");
	lua_pushinteger(l, 239);
	lua_setfield(l, -2, "ARM64_INS_SHA1P");
	lua_pushinteger(l, 240);
	lua_setfield(l, -2, "ARM64_INS_SHA1SU0");
	lua_pushinteger(l, 241);
	lua_setfield(l, -2, "ARM64_INS_SHA1SU1");
	lua_pushinteger(l, 242);
	lua_setfield(l, -2, "ARM64_INS_SHA256H2");
	lua_pushinteger(l, 243);
	lua_setfield(l, -2, "ARM64_INS_SHA256H");
	lua_pushinteger(l, 244);
	lua_setfield(l, -2, "ARM64_INS_SHA256SU0");
	lua_pushinteger(l, 245);
	lua_setfield(l, -2, "ARM64_INS_SHA256SU1");
	lua_pushinteger(l, 246);
	lua_setfield(l, -2, "ARM64_INS_SHADD");
	lua_pushinteger(l, 247);
	lua_setfield(l, -2, "ARM64_INS_SHLL2");
	lua_pushinteger(l, 248);
	lua_setfield(l, -2, "ARM64_INS_SHLL");
	lua_pushinteger(l, 249);
	lua_setfield(l, -2, "ARM64_INS_SHL");
	lua_pushinteger(l, 250);
	lua_setfield(l, -2, "ARM64_INS_SHRN2");
	lua_pushinteger(l, 251);
	lua_setfield(l, -2, "ARM64_INS_SHRN");
	lua_pushinteger(l, 252);
	lua_setfield(l, -2, "ARM64_INS_SHSUB");
	lua_pushinteger(l, 253);
	lua_setfield(l, -2, "ARM64_INS_SLI");
	lua_pushinteger(l, 254);
	lua_setfield(l, -2, "ARM64_INS_SMADDL");
	lua_pushinteger(l, 255);
	lua_setfield(l, -2, "ARM64_INS_SMAXP");
	lua_pushinteger(l, 256);
	lua_setfield(l, -2, "ARM64_INS_SMAXV");
	lua_pushinteger(l, 257);
	lua_setfield(l, -2, "ARM64_INS_SMAX");
	lua_pushinteger(l, 258);
	lua_setfield(l, -2, "ARM64_INS_SMC");
	lua_pushinteger(l, 259);
	lua_setfield(l, -2, "ARM64_INS_SMINP");
	lua_pushinteger(l, 260);
	lua_setfield(l, -2, "ARM64_INS_SMINV");
	lua_pushinteger(l, 261);
	lua_setfield(l, -2, "ARM64_INS_SMIN");
	lua_pushinteger(l, 262);
	lua_setfield(l, -2, "ARM64_INS_SMLAL2");
	lua_pushinteger(l, 263);
	lua_setfield(l, -2, "ARM64_INS_SMLAL");
	lua_pushinteger(l, 264);
	lua_setfield(l, -2, "ARM64_INS_SMLSL2");
	lua_pushinteger(l, 265);
	lua_setfield(l, -2, "ARM64_INS_SMLSL");
	lua_pushinteger(l, 266);
	lua_setfield(l, -2, "ARM64_INS_SMOV");
	lua_pushinteger(l, 267);
	lua_setfield(l, -2, "ARM64_INS_SMSUBL");
	lua_pushinteger(l, 268);
	lua_setfield(l, -2, "ARM64_INS_SMULH");
	lua_pushinteger(l, 269);
	lua_setfield(l, -2, "ARM64_INS_SMULL2");
	lua_pushinteger(l, 270);
	lua_setfield(l, -2, "ARM64_INS_SMULL");
	lua_pushinteger(l, 271);
	lua_setfield(l, -2, "ARM64_INS_SQABS");
	lua_pushinteger(l, 272);
	lua_setfield(l, -2, "ARM64_INS_SQADD");
	lua_pushinteger(l, 273);
	lua_setfield(l, -2, "ARM64_INS_SQDMLAL");
	lua_pushinteger(l, 274);
	lua_setfield(l, -2, "ARM64_INS_SQDMLAL2");
	lua_pushinteger(l, 275);
	lua_setfield(l, -2, "ARM64_INS_SQDMLSL");
	lua_pushinteger(l, 276);
	lua_setfield(l, -2, "ARM64_INS_SQDMLSL2");
	lua_pushinteger(l, 277);
	lua_setfield(l, -2, "ARM64_INS_SQDMULH");
	lua_pushinteger(l, 278);
	lua_setfield(l, -2, "ARM64_INS_SQDMULL");
	lua_pushinteger(l, 279);
	lua_setfield(l, -2, "ARM64_INS_SQDMULL2");
	lua_pushinteger(l, 280);
	lua_setfield(l, -2, "ARM64_INS_SQNEG");
	lua_pushinteger(l, 281);
	lua_setfield(l, -2, "ARM64_INS_SQRDMULH");
	lua_pushinteger(l, 282);
	lua_setfield(l, -2, "ARM64_INS_SQRSHL");
	lua_pushinteger(l, 283);
	lua_setfield(l, -2, "ARM64_INS_SQRSHRN");
	lua_pushinteger(l, 284);
	lua_setfield(l, -2, "ARM64_INS_SQRSHRN2");
	lua_pushinteger(l, 285);
	lua_setfield(l, -2, "ARM64_INS_SQRSHRUN");
	lua_pushinteger(l, 286);
	lua_setfield(l, -2, "ARM64_INS_SQRSHRUN2");
	lua_pushinteger(l, 287);
	lua_setfield(l, -2, "ARM64_INS_SQSHLU");
	lua_pushinteger(l, 288);
	lua_setfield(l, -2, "ARM64_INS_SQSHL");
	lua_pushinteger(l, 289);
	lua_setfield(l, -2, "ARM64_INS_SQSHRN");
	lua_pushinteger(l, 290);
	lua_setfield(l, -2, "ARM64_INS_SQSHRN2");
	lua_pushinteger(l, 291);
	lua_setfield(l, -2, "ARM64_INS_SQSHRUN");
	lua_pushinteger(l, 292);
	lua_setfield(l, -2, "ARM64_INS_SQSHRUN2");
	lua_pushinteger(l, 293);
	lua_setfield(l, -2, "ARM64_INS_SQSUB");
	lua_pushinteger(l, 294);
	lua_setfield(l, -2, "ARM64_INS_SQXTN2");
	lua_pushinteger(l, 295);
	lua_setfield(l, -2, "ARM64_INS_SQXTN");
	lua_pushinteger(l, 296);
	lua_setfield(l, -2, "ARM64_INS_SQXTUN2");
	lua_pushinteger(l, 297);
	lua_setfield(l, -2, "ARM64_INS_SQXTUN");
	lua_pushinteger(l, 298);
	lua_setfield(l, -2, "ARM64_INS_SRHADD");
	lua_pushinteger(l, 299);
	lua_setfield(l, -2, "ARM64_INS_SRI");
	lua_pushinteger(l, 300);
	lua_setfield(l, -2, "ARM64_INS_SRSHL");
	lua_pushinteger(l, 301);
	lua_setfield(l, -2, "ARM64_INS_SRSHR");
	lua_pushinteger(l, 302);
	lua_setfield(l, -2, "ARM64_INS_SRSRA");
	lua_pushinteger(l, 303);
	lua_setfield(l, -2, "ARM64_INS_SSHLL2");
	lua_pushinteger(l, 304);
	lua_setfield(l, -2, "ARM64_INS_SSHLL");
	lua_pushinteger(l, 305);
	lua_setfield(l, -2, "ARM64_INS_SSHL");
	lua_pushinteger(l, 306);
	lua_setfield(l, -2, "ARM64_INS_SSHR");
	lua_pushinteger(l, 307);
	lua_setfield(l, -2, "ARM64_INS_SSRA");
	lua_pushinteger(l, 308);
	lua_setfield(l, -2, "ARM64_INS_SSUBL2");
	lua_pushinteger(l, 309);
	lua_setfield(l, -2, "ARM64_INS_SSUBL");
	lua_pushinteger(l, 310);
	lua_setfield(l, -2, "ARM64_INS_SSUBW2");
	lua_pushinteger(l, 311);
	lua_setfield(l, -2, "ARM64_INS_SSUBW");
	lua_pushinteger(l, 312);
	lua_setfield(l, -2, "ARM64_INS_ST1");
	lua_pushinteger(l, 313);
	lua_setfield(l, -2, "ARM64_INS_ST2");
	lua_pushinteger(l, 314);
	lua_setfield(l, -2, "ARM64_INS_ST3");
	lua_pushinteger(l, 315);
	lua_setfield(l, -2, "ARM64_INS_ST4");
	lua_pushinteger(l, 316);
	lua_setfield(l, -2, "ARM64_INS_STLRB");
	lua_pushinteger(l, 317);
	lua_setfield(l, -2, "ARM64_INS_STLRH");
	lua_pushinteger(l, 318);
	lua_setfield(l, -2, "ARM64_INS_STLR");
	lua_pushinteger(l, 319);
	lua_setfield(l, -2, "ARM64_INS_STLXP");
	lua_pushinteger(l, 320);
	lua_setfield(l, -2, "ARM64_INS_STLXRB");
	lua_pushinteger(l, 321);
	lua_setfield(l, -2, "ARM64_INS_STLXRH");
	lua_pushinteger(l, 322);
	lua_setfield(l, -2, "ARM64_INS_STLXR");
	lua_pushinteger(l, 323);
	lua_setfield(l, -2, "ARM64_INS_STNP");
	lua_pushinteger(l, 324);
	lua_setfield(l, -2, "ARM64_INS_STP");
	lua_pushinteger(l, 325);
	lua_setfield(l, -2, "ARM64_INS_STRB");
	lua_pushinteger(l, 326);
	lua_setfield(l, -2, "ARM64_INS_STR");
	lua_pushinteger(l, 327);
	lua_setfield(l, -2, "ARM64_INS_STRH");
	lua_pushinteger(l, 328);
	lua_setfield(l, -2, "ARM64_INS_STTRB");
	lua_pushinteger(l, 329);
	lua_setfield(l, -2, "ARM64_INS_STTRH");
	lua_pushinteger(l, 330);
	lua_setfield(l, -2, "ARM64_INS_STTR");
	lua_pushinteger(l, 331);
	lua_setfield(l, -2, "ARM64_INS_STURB");
	lua_pushinteger(l, 332);
	lua_setfield(l, -2, "ARM64_INS_STUR");
	lua_pushinteger(l, 333);
	lua_setfield(l, -2, "ARM64_INS_STURH");
	lua_pushinteger(l, 334);
	lua_setfield(l, -2, "ARM64_INS_STXP");
	lua_pushinteger(l, 335);
	lua_setfield(l, -2, "ARM64_INS_STXRB");
	lua_pushinteger(l, 336);
	lua_setfield(l, -2, "ARM64_INS_STXRH");
	lua_pushinteger(l, 337);
	lua_setfield(l, -2, "ARM64_INS_STXR");
	lua_pushinteger(l, 338);
	lua_setfield(l, -2, "ARM64_INS_SUBHN");
	lua_pushinteger(l, 339);
	lua_setfield(l, -2, "ARM64_INS_SUBHN2");
	lua_pushinteger(l, 340);
	lua_setfield(l, -2, "ARM64_INS_SUB");
	lua_pushinteger(l, 341);
	lua_setfield(l, -2, "ARM64_INS_SUQADD");
	lua_pushinteger(l, 342);
	lua_setfield(l, -2, "ARM64_INS_SVC");
	lua_pushinteger(l, 343);
	lua_setfield(l, -2, "ARM64_INS_SYSL");
	lua_pushinteger(l, 344);
	lua_setfield(l, -2, "ARM64_INS_SYS");
	lua_pushinteger(l, 345);
	lua_setfield(l, -2, "ARM64_INS_TBL");
	lua_pushinteger(l, 346);
	lua_setfield(l, -2, "ARM64_INS_TBNZ");
	lua_pushinteger(l, 347);
	lua_setfield(l, -2, "ARM64_INS_TBX");
	lua_pushinteger(l, 348);
	lua_setfield(l, -2, "ARM64_INS_TBZ");
	lua_pushinteger(l, 349);
	lua_setfield(l, -2, "ARM64_INS_TRN1");
	lua_pushinteger(l, 350);
	lua_setfield(l, -2, "ARM64_INS_TRN2");
	lua_pushinteger(l, 351);
	lua_setfield(l, -2, "ARM64_INS_UABAL2");
	lua_pushinteger(l, 352);
	lua_setfield(l, -2, "ARM64_INS_UABAL");
	lua_pushinteger(l, 353);
	lua_setfield(l, -2, "ARM64_INS_UABA");
	lua_pushinteger(l, 354);
	lua_setfield(l, -2, "ARM64_INS_UABDL2");
	lua_pushinteger(l, 355);
	lua_setfield(l, -2, "ARM64_INS_UABDL");
	lua_pushinteger(l, 356);
	lua_setfield(l, -2, "ARM64_INS_UABD");
	lua_pushinteger(l, 357);
	lua_setfield(l, -2, "ARM64_INS_UADALP");
	lua_pushinteger(l, 358);
	lua_setfield(l, -2, "ARM64_INS_UADDLP");
	lua_pushinteger(l, 359);
	lua_setfield(l, -2, "ARM64_INS_UADDLV");
	lua_pushinteger(l, 360);
	lua_setfield(l, -2, "ARM64_INS_UADDL2");
	lua_pushinteger(l, 361);
	lua_setfield(l, -2, "ARM64_INS_UADDL");
	lua_pushinteger(l, 362);
	lua_setfield(l, -2, "ARM64_INS_UADDW2");
	lua_pushinteger(l, 363);
	lua_setfield(l, -2, "ARM64_INS_UADDW");
	lua_pushinteger(l, 364);
	lua_setfield(l, -2, "ARM64_INS_UBFM");
	lua_pushinteger(l, 365);
	lua_setfield(l, -2, "ARM64_INS_UCVTF");
	lua_pushinteger(l, 366);
	lua_setfield(l, -2, "ARM64_INS_UDIV");
	lua_pushinteger(l, 367);
	lua_setfield(l, -2, "ARM64_INS_UHADD");
	lua_pushinteger(l, 368);
	lua_setfield(l, -2, "ARM64_INS_UHSUB");
	lua_pushinteger(l, 369);
	lua_setfield(l, -2, "ARM64_INS_UMADDL");
	lua_pushinteger(l, 370);
	lua_setfield(l, -2, "ARM64_INS_UMAXP");
	lua_pushinteger(l, 371);
	lua_setfield(l, -2, "ARM64_INS_UMAXV");
	lua_pushinteger(l, 372);
	lua_setfield(l, -2, "ARM64_INS_UMAX");
	lua_pushinteger(l, 373);
	lua_setfield(l, -2, "ARM64_INS_UMINP");
	lua_pushinteger(l, 374);
	lua_setfield(l, -2, "ARM64_INS_UMINV");
	lua_pushinteger(l, 375);
	lua_setfield(l, -2, "ARM64_INS_UMIN");
	lua_pushinteger(l, 376);
	lua_setfield(l, -2, "ARM64_INS_UMLAL2");
	lua_pushinteger(l, 377);
	lua_setfield(l, -2, "ARM64_INS_UMLAL");
	lua_pushinteger(l, 378);
	lua_setfield(l, -2, "ARM64_INS_UMLSL2");
	lua_pushinteger(l, 379);
	lua_setfield(l, -2, "ARM64_INS_UMLSL");
	lua_pushinteger(l, 380);
	lua_setfield(l, -2, "ARM64_INS_UMOV");
	lua_pushinteger(l, 381);
	lua_setfield(l, -2, "ARM64_INS_UMSUBL");
	lua_pushinteger(l, 382);
	lua_setfield(l, -2, "ARM64_INS_UMULH");
	lua_pushinteger(l, 383);
	lua_setfield(l, -2, "ARM64_INS_UMULL2");
	lua_pushinteger(l, 384);
	lua_setfield(l, -2, "ARM64_INS_UMULL");
	lua_pushinteger(l, 385);
	lua_setfield(l, -2, "ARM64_INS_UQADD");
	lua_pushinteger(l, 386);
	lua_setfield(l, -2, "ARM64_INS_UQRSHL");
	lua_pushinteger(l, 387);
	lua_setfield(l, -2, "ARM64_INS_UQRSHRN");
	lua_pushinteger(l, 388);
	lua_setfield(l, -2, "ARM64_INS_UQRSHRN2");
	lua_pushinteger(l, 389);
	lua_setfield(l, -2, "ARM64_INS_UQSHL");
	lua_pushinteger(l, 390);
	lua_setfield(l, -2, "ARM64_INS_UQSHRN");
	lua_pushinteger(l, 391);
	lua_setfield(l, -2, "ARM64_INS_UQSHRN2");
	lua_pushinteger(l, 392);
	lua_setfield(l, -2, "ARM64_INS_UQSUB");
	lua_pushinteger(l, 393);
	lua_setfield(l, -2, "ARM64_INS_UQXTN2");
	lua_pushinteger(l, 394);
	lua_setfield(l, -2, "ARM64_INS_UQXTN");
	lua_pushinteger(l, 395);
	lua_setfield(l, -2, "ARM64_INS_URECPE");
	lua_pushinteger(l, 396);
	lua_setfield(l, -2, "ARM64_INS_URHADD");
	lua_pushinteger(l, 397);
	lua_setfield(l, -2, "ARM64_INS_URSHL");
	lua_pushinteger(l, 398);
	lua_setfield(l, -2, "ARM64_INS_URSHR");
	lua_pushinteger(l, 399);
	lua_setfield(l, -2, "ARM64_INS_URSQRTE");
	lua_pushinteger(l, 400);
	lua_setfield(l, -2, "ARM64_INS_URSRA");
	lua_pushinteger(l, 401);
	lua_setfield(l, -2, "ARM64_INS_USHLL2");
	lua_pushinteger(l, 402);
	lua_setfield(l, -2, "ARM64_INS_USHLL");
	lua_pushinteger(l, 403);
	lua_setfield(l, -2, "ARM64_INS_USHL");
	lua_pushinteger(l, 404);
	lua_setfield(l, -2, "ARM64_INS_USHR");
	lua_pushinteger(l, 405);
	lua_setfield(l, -2, "ARM64_INS_USQADD");
	lua_pushinteger(l, 406);
	lua_setfield(l, -2, "ARM64_INS_USRA");
	lua_pushinteger(l, 407);
	lua_setfield(l, -2, "ARM64_INS_USUBL2");
	lua_pushinteger(l, 408);
	lua_setfield(l, -2, "ARM64_INS_USUBL");
	lua_pushinteger(l, 409);
	lua_setfield(l, -2, "ARM64_INS_USUBW2");
	lua_pushinteger(l, 410);
	lua_setfield(l, -2, "ARM64_INS_USUBW");
	lua_pushinteger(l, 411);
	lua_setfield(l, -2, "ARM64_INS_UZP1");
	lua_pushinteger(l, 412);
	lua_setfield(l, -2, "ARM64_INS_UZP2");
	lua_pushinteger(l, 413);
	lua_setfield(l, -2, "ARM64_INS_XTN2");
	lua_pushinteger(l, 414);
	lua_setfield(l, -2, "ARM64_INS_XTN");
	lua_pushinteger(l, 415);
	lua_setfield(l, -2, "ARM64_INS_ZIP1");
	lua_pushinteger(l, 416);
	lua_setfield(l, -2, "ARM64_INS_ZIP2");
	lua_pushinteger(l, 417);
	lua_setfield(l, -2, "ARM64_INS_MNEG");
	lua_pushinteger(l, 418);
	lua_setfield(l, -2, "ARM64_INS_UMNEGL");
	lua_pushinteger(l, 419);
	lua_setfield(l, -2, "ARM64_INS_SMNEGL");
	lua_pushinteger(l, 420);
	lua_setfield(l, -2, "ARM64_INS_NOP");
	lua_pushinteger(l, 421);
	lua_setfield(l, -2, "ARM64_INS_YIELD");
	lua_pushinteger(l, 422);
	lua_setfield(l, -2, "ARM64_INS_WFE");
	lua_pushinteger(l, 423);
	lua_setfield(l, -2, "ARM64_INS_WFI");
	lua_pushinteger(l, 424);
	lua_setfield(l, -2, "ARM64_INS_SEV");
	lua_pushinteger(l, 425);
	lua_setfield(l, -2, "ARM64_INS_SEVL");
	lua_pushinteger(l, 426);
	lua_setfield(l, -2, "ARM64_INS_NGC");
	lua_pushinteger(l, 427);
	lua_setfield(l, -2, "ARM64_INS_SBFIZ");
	lua_pushinteger(l, 428);
	lua_setfield(l, -2, "ARM64_INS_UBFIZ");
	lua_pushinteger(l, 429);
	lua_setfield(l, -2, "ARM64_INS_SBFX");
	lua_pushinteger(l, 430);
	lua_setfield(l, -2, "ARM64_INS_UBFX");
	lua_pushinteger(l, 431);
	lua_setfield(l, -2, "ARM64_INS_BFI");
	lua_pushinteger(l, 432);
	lua_setfield(l, -2, "ARM64_INS_BFXIL");
	lua_pushinteger(l, 433);
	lua_setfield(l, -2, "ARM64_INS_CMN");
	lua_pushinteger(l, 434);
	lua_setfield(l, -2, "ARM64_INS_MVN");
	lua_pushinteger(l, 435);
	lua_setfield(l, -2, "ARM64_INS_TST");
	lua_pushinteger(l, 436);
	lua_setfield(l, -2, "ARM64_INS_CSET");
	lua_pushinteger(l, 437);
	lua_setfield(l, -2, "ARM64_INS_CINC");
	lua_pushinteger(l, 438);
	lua_setfield(l, -2, "ARM64_INS_CSETM");
	lua_pushinteger(l, 439);
	lua_setfield(l, -2, "ARM64_INS_CINV");
	lua_pushinteger(l, 440);
	lua_setfield(l, -2, "ARM64_INS_CNEG");
	lua_pushinteger(l, 441);
	lua_setfield(l, -2, "ARM64_INS_SXTB");
	lua_pushinteger(l, 442);
	lua_setfield(l, -2, "ARM64_INS_SXTH");
	lua_pushinteger(l, 443);
	lua_setfield(l, -2, "ARM64_INS_SXTW");
	lua_pushinteger(l, 444);
	lua_setfield(l, -2, "ARM64_INS_CMP");
	lua_pushinteger(l, 445);
	lua_setfield(l, -2, "ARM64_INS_UXTB");
	lua_pushinteger(l, 446);
	lua_setfield(l, -2, "ARM64_INS_UXTH");
	lua_pushinteger(l, 447);
	lua_setfield(l, -2, "ARM64_INS_UXTW");
	lua_pushinteger(l, 448);
	lua_setfield(l, -2, "ARM64_INS_IC");
	lua_pushinteger(l, 449);
	lua_setfield(l, -2, "ARM64_INS_DC");
	lua_pushinteger(l, 450);
	lua_setfield(l, -2, "ARM64_INS_AT");
	lua_pushinteger(l, 451);
	lua_setfield(l, -2, "ARM64_INS_TLBI");
	lua_pushinteger(l, 452);
	lua_setfield(l, -2, "ARM64_INS_ENDING");

	/* Group of ARM64 instructions */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM64_GRP_INVALID");

	/* Generic groups */
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM64_GRP_JUMP");

	/* Architecture-specific groups */
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "ARM64_GRP_CRYPTO");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "ARM64_GRP_FPARMV8");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "ARM64_GRP_NEON");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "ARM64_GRP_CRC");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "ARM64_GRP_ENDING");
}