/* For Capstone Engine. AUTO-GENERATED FILE, DO NOT EDIT */

#include "arm_const.h"

void set_arm_const(lua_State* l)
{
	/* ARM shift type */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_SFT_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_SFT_ASR");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_SFT_LSL");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM_SFT_LSR");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM_SFT_ROR");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM_SFT_RRX");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM_SFT_ASR_REG");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM_SFT_LSL_REG");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM_SFT_LSR_REG");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM_SFT_ROR_REG");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM_SFT_RRX_REG");

	/* ARM condition code */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_CC_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_CC_EQ");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_CC_NE");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM_CC_HS");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM_CC_LO");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM_CC_MI");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM_CC_PL");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM_CC_VS");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM_CC_VC");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM_CC_HI");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM_CC_LS");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "ARM_CC_GE");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "ARM_CC_LT");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "ARM_CC_GT");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "ARM_CC_LE");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "ARM_CC_AL");

	/* Special registers for MSR */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_SYSREG_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_SYSREG_SPSR_C");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_SYSREG_SPSR_X");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM_SYSREG_SPSR_S");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM_SYSREG_SPSR_F");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM_SYSREG_CPSR_C");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "ARM_SYSREG_CPSR_X");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "ARM_SYSREG_CPSR_S");
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "ARM_SYSREG_CPSR_F");
	lua_pushinteger(l, 256);
	lua_setfield(l, -2, "ARM_SYSREG_APSR");
	lua_pushinteger(l, 257);
	lua_setfield(l, -2, "ARM_SYSREG_APSR_G");
	lua_pushinteger(l, 258);
	lua_setfield(l, -2, "ARM_SYSREG_APSR_NZCVQ");
	lua_pushinteger(l, 259);
	lua_setfield(l, -2, "ARM_SYSREG_APSR_NZCVQG");
	lua_pushinteger(l, 260);
	lua_setfield(l, -2, "ARM_SYSREG_IAPSR");
	lua_pushinteger(l, 261);
	lua_setfield(l, -2, "ARM_SYSREG_IAPSR_G");
	lua_pushinteger(l, 262);
	lua_setfield(l, -2, "ARM_SYSREG_IAPSR_NZCVQG");
	lua_pushinteger(l, 263);
	lua_setfield(l, -2, "ARM_SYSREG_EAPSR");
	lua_pushinteger(l, 264);
	lua_setfield(l, -2, "ARM_SYSREG_EAPSR_G");
	lua_pushinteger(l, 265);
	lua_setfield(l, -2, "ARM_SYSREG_EAPSR_NZCVQG");
	lua_pushinteger(l, 266);
	lua_setfield(l, -2, "ARM_SYSREG_XPSR");
	lua_pushinteger(l, 267);
	lua_setfield(l, -2, "ARM_SYSREG_XPSR_G");
	lua_pushinteger(l, 268);
	lua_setfield(l, -2, "ARM_SYSREG_XPSR_NZCVQG");
	lua_pushinteger(l, 269);
	lua_setfield(l, -2, "ARM_SYSREG_IPSR");
	lua_pushinteger(l, 270);
	lua_setfield(l, -2, "ARM_SYSREG_EPSR");
	lua_pushinteger(l, 271);
	lua_setfield(l, -2, "ARM_SYSREG_IEPSR");
	lua_pushinteger(l, 272);
	lua_setfield(l, -2, "ARM_SYSREG_MSP");
	lua_pushinteger(l, 273);
	lua_setfield(l, -2, "ARM_SYSREG_PSP");
	lua_pushinteger(l, 274);
	lua_setfield(l, -2, "ARM_SYSREG_PRIMASK");
	lua_pushinteger(l, 275);
	lua_setfield(l, -2, "ARM_SYSREG_BASEPRI");
	lua_pushinteger(l, 276);
	lua_setfield(l, -2, "ARM_SYSREG_BASEPRI_MAX");
	lua_pushinteger(l, 277);
	lua_setfield(l, -2, "ARM_SYSREG_FAULTMASK");
	lua_pushinteger(l, 278);
	lua_setfield(l, -2, "ARM_SYSREG_CONTROL");

	/* The memory barrier constants map directly to the 4-bit encoding of */

	/* the option field for Memory Barrier operations. */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_MB_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_MB_RESERVED_0");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_MB_OSHLD");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM_MB_OSHST");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM_MB_OSH");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM_MB_RESERVED_4");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM_MB_NSHLD");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM_MB_NSHST");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM_MB_NSH");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM_MB_RESERVED_8");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM_MB_ISHLD");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "ARM_MB_ISHST");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "ARM_MB_ISH");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "ARM_MB_RESERVED_12");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "ARM_MB_LD");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "ARM_MB_ST");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM_MB_SY");

	/* Operand type for instruction's operands */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_OP_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_OP_REG");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_OP_IMM");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM_OP_MEM");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM_OP_FP");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "ARM_OP_CIMM");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "ARM_OP_PIMM");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "ARM_OP_SETEND");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "ARM_OP_SYSREG");

	/* Operand type for SETEND instruction */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_SETEND_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_SETEND_BE");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_SETEND_LE");

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_CPSMODE_INVALID");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_CPSMODE_IE");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM_CPSMODE_ID");

	/* Operand type for SETEND instruction */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_CPSFLAG_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_CPSFLAG_F");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_CPSFLAG_I");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM_CPSFLAG_A");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM_CPSFLAG_NONE");

	/* Data type for elements of vector instructions. */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_VECTORDATA_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_VECTORDATA_I8");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_VECTORDATA_I16");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM_VECTORDATA_I32");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM_VECTORDATA_I64");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM_VECTORDATA_S8");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM_VECTORDATA_S16");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM_VECTORDATA_S32");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM_VECTORDATA_S64");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM_VECTORDATA_U8");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM_VECTORDATA_U16");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "ARM_VECTORDATA_U32");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "ARM_VECTORDATA_U64");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "ARM_VECTORDATA_P8");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "ARM_VECTORDATA_F32");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "ARM_VECTORDATA_F64");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM_VECTORDATA_F16F64");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "ARM_VECTORDATA_F64F16");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "ARM_VECTORDATA_F32F16");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "ARM_VECTORDATA_F16F32");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "ARM_VECTORDATA_F64F32");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "ARM_VECTORDATA_F32F64");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "ARM_VECTORDATA_S32F32");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "ARM_VECTORDATA_U32F32");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "ARM_VECTORDATA_F32S32");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "ARM_VECTORDATA_F32U32");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "ARM_VECTORDATA_F64S16");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "ARM_VECTORDATA_F32S16");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "ARM_VECTORDATA_F64S32");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "ARM_VECTORDATA_S16F64");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "ARM_VECTORDATA_S16F32");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "ARM_VECTORDATA_S32F64");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "ARM_VECTORDATA_U16F64");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "ARM_VECTORDATA_U16F32");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "ARM_VECTORDATA_U32F64");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "ARM_VECTORDATA_F64U16");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "ARM_VECTORDATA_F32U16");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "ARM_VECTORDATA_F64U32");

	/* ARM registers */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_REG_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_REG_APSR");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_REG_APSR_NZCV");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM_REG_CPSR");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM_REG_FPEXC");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM_REG_FPINST");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM_REG_FPSCR");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM_REG_FPSCR_NZCV");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM_REG_FPSID");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM_REG_ITSTATE");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM_REG_LR");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "ARM_REG_PC");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "ARM_REG_SP");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "ARM_REG_SPSR");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "ARM_REG_D0");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "ARM_REG_D1");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM_REG_D2");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "ARM_REG_D3");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "ARM_REG_D4");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "ARM_REG_D5");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "ARM_REG_D6");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "ARM_REG_D7");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "ARM_REG_D8");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "ARM_REG_D9");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "ARM_REG_D10");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "ARM_REG_D11");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "ARM_REG_D12");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "ARM_REG_D13");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "ARM_REG_D14");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "ARM_REG_D15");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "ARM_REG_D16");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "ARM_REG_D17");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "ARM_REG_D18");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "ARM_REG_D19");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "ARM_REG_D20");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "ARM_REG_D21");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "ARM_REG_D22");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "ARM_REG_D23");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "ARM_REG_D24");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "ARM_REG_D25");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "ARM_REG_D26");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "ARM_REG_D27");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "ARM_REG_D28");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "ARM_REG_D29");
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "ARM_REG_D30");
	lua_pushinteger(l, 45);
	lua_setfield(l, -2, "ARM_REG_D31");
	lua_pushinteger(l, 46);
	lua_setfield(l, -2, "ARM_REG_FPINST2");
	lua_pushinteger(l, 47);
	lua_setfield(l, -2, "ARM_REG_MVFR0");
	lua_pushinteger(l, 48);
	lua_setfield(l, -2, "ARM_REG_MVFR1");
	lua_pushinteger(l, 49);
	lua_setfield(l, -2, "ARM_REG_MVFR2");
	lua_pushinteger(l, 50);
	lua_setfield(l, -2, "ARM_REG_Q0");
	lua_pushinteger(l, 51);
	lua_setfield(l, -2, "ARM_REG_Q1");
	lua_pushinteger(l, 52);
	lua_setfield(l, -2, "ARM_REG_Q2");
	lua_pushinteger(l, 53);
	lua_setfield(l, -2, "ARM_REG_Q3");
	lua_pushinteger(l, 54);
	lua_setfield(l, -2, "ARM_REG_Q4");
	lua_pushinteger(l, 55);
	lua_setfield(l, -2, "ARM_REG_Q5");
	lua_pushinteger(l, 56);
	lua_setfield(l, -2, "ARM_REG_Q6");
	lua_pushinteger(l, 57);
	lua_setfield(l, -2, "ARM_REG_Q7");
	lua_pushinteger(l, 58);
	lua_setfield(l, -2, "ARM_REG_Q8");
	lua_pushinteger(l, 59);
	lua_setfield(l, -2, "ARM_REG_Q9");
	lua_pushinteger(l, 60);
	lua_setfield(l, -2, "ARM_REG_Q10");
	lua_pushinteger(l, 61);
	lua_setfield(l, -2, "ARM_REG_Q11");
	lua_pushinteger(l, 62);
	lua_setfield(l, -2, "ARM_REG_Q12");
	lua_pushinteger(l, 63);
	lua_setfield(l, -2, "ARM_REG_Q13");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "ARM_REG_Q14");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "ARM_REG_Q15");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "ARM_REG_R0");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "ARM_REG_R1");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "ARM_REG_R2");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "ARM_REG_R3");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "ARM_REG_R4");
	lua_pushinteger(l, 71);
	lua_setfield(l, -2, "ARM_REG_R5");
	lua_pushinteger(l, 72);
	lua_setfield(l, -2, "ARM_REG_R6");
	lua_pushinteger(l, 73);
	lua_setfield(l, -2, "ARM_REG_R7");
	lua_pushinteger(l, 74);
	lua_setfield(l, -2, "ARM_REG_R8");
	lua_pushinteger(l, 75);
	lua_setfield(l, -2, "ARM_REG_R9");
	lua_pushinteger(l, 76);
	lua_setfield(l, -2, "ARM_REG_R10");
	lua_pushinteger(l, 77);
	lua_setfield(l, -2, "ARM_REG_R11");
	lua_pushinteger(l, 78);
	lua_setfield(l, -2, "ARM_REG_R12");
	lua_pushinteger(l, 79);
	lua_setfield(l, -2, "ARM_REG_S0");
	lua_pushinteger(l, 80);
	lua_setfield(l, -2, "ARM_REG_S1");
	lua_pushinteger(l, 81);
	lua_setfield(l, -2, "ARM_REG_S2");
	lua_pushinteger(l, 82);
	lua_setfield(l, -2, "ARM_REG_S3");
	lua_pushinteger(l, 83);
	lua_setfield(l, -2, "ARM_REG_S4");
	lua_pushinteger(l, 84);
	lua_setfield(l, -2, "ARM_REG_S5");
	lua_pushinteger(l, 85);
	lua_setfield(l, -2, "ARM_REG_S6");
	lua_pushinteger(l, 86);
	lua_setfield(l, -2, "ARM_REG_S7");
	lua_pushinteger(l, 87);
	lua_setfield(l, -2, "ARM_REG_S8");
	lua_pushinteger(l, 88);
	lua_setfield(l, -2, "ARM_REG_S9");
	lua_pushinteger(l, 89);
	lua_setfield(l, -2, "ARM_REG_S10");
	lua_pushinteger(l, 90);
	lua_setfield(l, -2, "ARM_REG_S11");
	lua_pushinteger(l, 91);
	lua_setfield(l, -2, "ARM_REG_S12");
	lua_pushinteger(l, 92);
	lua_setfield(l, -2, "ARM_REG_S13");
	lua_pushinteger(l, 93);
	lua_setfield(l, -2, "ARM_REG_S14");
	lua_pushinteger(l, 94);
	lua_setfield(l, -2, "ARM_REG_S15");
	lua_pushinteger(l, 95);
	lua_setfield(l, -2, "ARM_REG_S16");
	lua_pushinteger(l, 96);
	lua_setfield(l, -2, "ARM_REG_S17");
	lua_pushinteger(l, 97);
	lua_setfield(l, -2, "ARM_REG_S18");
	lua_pushinteger(l, 98);
	lua_setfield(l, -2, "ARM_REG_S19");
	lua_pushinteger(l, 99);
	lua_setfield(l, -2, "ARM_REG_S20");
	lua_pushinteger(l, 100);
	lua_setfield(l, -2, "ARM_REG_S21");
	lua_pushinteger(l, 101);
	lua_setfield(l, -2, "ARM_REG_S22");
	lua_pushinteger(l, 102);
	lua_setfield(l, -2, "ARM_REG_S23");
	lua_pushinteger(l, 103);
	lua_setfield(l, -2, "ARM_REG_S24");
    lua_pushinteger(l, 104);
	lua_setfield(l, -2, "ARM_REG_S25");
	lua_pushinteger(l, 105);
	lua_setfield(l, -2, "ARM_REG_S26");
	lua_pushinteger(l, 106);
	lua_setfield(l, -2, "ARM_REG_S27");
	lua_pushinteger(l, 107);
	lua_setfield(l, -2, "ARM_REG_S28");
	lua_pushinteger(l, 108);
	lua_setfield(l, -2, "ARM_REG_S29");
	lua_pushinteger(l, 109);
	lua_setfield(l, -2, "ARM_REG_S30");
	lua_pushinteger(l, 110);
	lua_setfield(l, -2, "ARM_REG_S31");
	lua_pushinteger(l, 111);
	lua_setfield(l, -2, "ARM_REG_ENDING");

	/* alias registers */
	lua_pushinteger(l, ARM_REG_SP);
	lua_setfield(l, -2, "ARM_REG_R13");
	lua_pushinteger(l, ARM_REG_LR);
	lua_setfield(l, -2, "ARM_REG_R14");
	lua_pushinteger(l, ARM_REG_PC);
	lua_setfield(l, -2, "ARM_REG_R15");
	lua_pushinteger(l, ARM_REG_R9);
	lua_setfield(l, -2, "ARM_REG_SB");
	lua_pushinteger(l, ARM_REG_R10);
	lua_setfield(l, -2, "ARM_REG_SL");
	lua_pushinteger(l, ARM_REG_R11);
	lua_setfield(l, -2, "ARM_REG_FP");
	lua_pushinteger(l, ARM_REG_R12);
	lua_setfield(l, -2, "ARM_REG_IP");

	/* ARM instruction */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_INS_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_INS_ADC");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "ARM_INS_ADD");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "ARM_INS_ADR");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "ARM_INS_AESD");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "ARM_INS_AESE");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "ARM_INS_AESIMC");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "ARM_INS_AESMC");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "ARM_INS_AND");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "ARM_INS_BFC");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "ARM_INS_BFI");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "ARM_INS_BIC");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "ARM_INS_BKPT");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "ARM_INS_BL");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "ARM_INS_BLX");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "ARM_INS_BX");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "ARM_INS_BXJ");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "ARM_INS_B");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "ARM_INS_CDP");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "ARM_INS_CDP2");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "ARM_INS_CLREX");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "ARM_INS_CLZ");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "ARM_INS_CMN");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "ARM_INS_CMP");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "ARM_INS_CPS");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "ARM_INS_CRC32B");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "ARM_INS_CRC32CB");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "ARM_INS_CRC32CH");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "ARM_INS_CRC32CW");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "ARM_INS_CRC32H");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "ARM_INS_CRC32W");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "ARM_INS_DBG");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "ARM_INS_DMB");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "ARM_INS_DSB");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "ARM_INS_EOR");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "ARM_INS_VMOV");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "ARM_INS_FLDMDBX");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "ARM_INS_FLDMIAX");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "ARM_INS_VMRS");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "ARM_INS_FSTMDBX");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "ARM_INS_FSTMIAX");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "ARM_INS_HINT");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "ARM_INS_HLT");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "ARM_INS_ISB");
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "ARM_INS_LDA");
	lua_pushinteger(l, 45);
	lua_setfield(l, -2, "ARM_INS_LDAB");
	lua_pushinteger(l, 46);
	lua_setfield(l, -2, "ARM_INS_LDAEX");
	lua_pushinteger(l, 47);
	lua_setfield(l, -2, "ARM_INS_LDAEXB");
	lua_pushinteger(l, 48);
	lua_setfield(l, -2, "ARM_INS_LDAEXD");
	lua_pushinteger(l, 49);
	lua_setfield(l, -2, "ARM_INS_LDAEXH");
	lua_pushinteger(l, 50);
	lua_setfield(l, -2, "ARM_INS_LDAH");
	lua_pushinteger(l, 51);
	lua_setfield(l, -2, "ARM_INS_LDC2L");
	lua_pushinteger(l, 52);
	lua_setfield(l, -2, "ARM_INS_LDC2");
	lua_pushinteger(l, 53);
	lua_setfield(l, -2, "ARM_INS_LDCL");
	lua_pushinteger(l, 54);
	lua_setfield(l, -2, "ARM_INS_LDC");
	lua_pushinteger(l, 55);
	lua_setfield(l, -2, "ARM_INS_LDMDA");
	lua_pushinteger(l, 56);
	lua_setfield(l, -2, "ARM_INS_LDMDB");
	lua_pushinteger(l, 57);
	lua_setfield(l, -2, "ARM_INS_LDM");
	lua_pushinteger(l, 58);
	lua_setfield(l, -2, "ARM_INS_LDMIB");
	lua_pushinteger(l, 59);
	lua_setfield(l, -2, "ARM_INS_LDRBT");
	lua_pushinteger(l, 60);
	lua_setfield(l, -2, "ARM_INS_LDRB");
	lua_pushinteger(l, 61);
	lua_setfield(l, -2, "ARM_INS_LDRD");
	lua_pushinteger(l, 62);
	lua_setfield(l, -2, "ARM_INS_LDREX");
	lua_pushinteger(l, 63);
	lua_setfield(l, -2, "ARM_INS_LDREXB");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "ARM_INS_LDREXD");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "ARM_INS_LDREXH");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "ARM_INS_LDRH");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "ARM_INS_LDRHT");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "ARM_INS_LDRSB");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "ARM_INS_LDRSBT");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "ARM_INS_LDRSH");
	lua_pushinteger(l, 71);
	lua_setfield(l, -2, "ARM_INS_LDRSHT");
	lua_pushinteger(l, 72);
	lua_setfield(l, -2, "ARM_INS_LDRT");
	lua_pushinteger(l, 73);
	lua_setfield(l, -2, "ARM_INS_LDR");
	lua_pushinteger(l, 74);
	lua_setfield(l, -2, "ARM_INS_MCR");
	lua_pushinteger(l, 75);
	lua_setfield(l, -2, "ARM_INS_MCR2");
	lua_pushinteger(l, 76);
	lua_setfield(l, -2, "ARM_INS_MCRR");
	lua_pushinteger(l, 77);
	lua_setfield(l, -2, "ARM_INS_MCRR2");
	lua_pushinteger(l, 78);
	lua_setfield(l, -2, "ARM_INS_MLA");
	lua_pushinteger(l, 79);
	lua_setfield(l, -2, "ARM_INS_MLS");
	lua_pushinteger(l, 80);
	lua_setfield(l, -2, "ARM_INS_MOV");
	lua_pushinteger(l, 81);
	lua_setfield(l, -2, "ARM_INS_MOVT");
	lua_pushinteger(l, 82);
	lua_setfield(l, -2, "ARM_INS_MOVW");
	lua_pushinteger(l, 83);
	lua_setfield(l, -2, "ARM_INS_MRC");
	lua_pushinteger(l, 84);
	lua_setfield(l, -2, "ARM_INS_MRC2");
	lua_pushinteger(l, 85);
	lua_setfield(l, -2, "ARM_INS_MRRC");
	lua_pushinteger(l, 86);
	lua_setfield(l, -2, "ARM_INS_MRRC2");
	lua_pushinteger(l, 87);
	lua_setfield(l, -2, "ARM_INS_MRS");
	lua_pushinteger(l, 88);
	lua_setfield(l, -2, "ARM_INS_MSR");
	lua_pushinteger(l, 89);
	lua_setfield(l, -2, "ARM_INS_MUL");
	lua_pushinteger(l, 90);
	lua_setfield(l, -2, "ARM_INS_MVN");
	lua_pushinteger(l, 91);
	lua_setfield(l, -2, "ARM_INS_ORR");
	lua_pushinteger(l, 92);
	lua_setfield(l, -2, "ARM_INS_PKHBT");
	lua_pushinteger(l, 93);
	lua_setfield(l, -2, "ARM_INS_PKHTB");
	lua_pushinteger(l, 94);
	lua_setfield(l, -2, "ARM_INS_PLDW");
	lua_pushinteger(l, 95);
	lua_setfield(l, -2, "ARM_INS_PLD");
	lua_pushinteger(l, 96);
	lua_setfield(l, -2, "ARM_INS_PLI");
	lua_pushinteger(l, 97);
	lua_setfield(l, -2, "ARM_INS_QADD");
	lua_pushinteger(l, 98);
	lua_setfield(l, -2, "ARM_INS_QADD16");
	lua_pushinteger(l, 99);
	lua_setfield(l, -2, "ARM_INS_QADD8");
	lua_pushinteger(l, 100);
	lua_setfield(l, -2, "ARM_INS_QASX");
	lua_pushinteger(l, 101);
	lua_setfield(l, -2, "ARM_INS_QDADD");
	lua_pushinteger(l, 102);
	lua_setfield(l, -2, "ARM_INS_QDSUB");
	lua_pushinteger(l, 103);
	lua_setfield(l, -2, "ARM_INS_QSAX");
	lua_pushinteger(l, 104);
	lua_setfield(l, -2, "ARM_INS_QSUB");
	lua_pushinteger(l, 105);
	lua_setfield(l, -2, "ARM_INS_QSUB16");
	lua_pushinteger(l, 106);
	lua_setfield(l, -2, "ARM_INS_QSUB8");
	lua_pushinteger(l, 107);
	lua_setfield(l, -2, "ARM_INS_RBIT");
	lua_pushinteger(l, 108);
	lua_setfield(l, -2, "ARM_INS_REV");
	lua_pushinteger(l, 109);
	lua_setfield(l, -2, "ARM_INS_REV16");
	lua_pushinteger(l, 110);
	lua_setfield(l, -2, "ARM_INS_REVSH");
	lua_pushinteger(l, 111);
	lua_setfield(l, -2, "ARM_INS_RFEDA");
	lua_pushinteger(l, 112);
	lua_setfield(l, -2, "ARM_INS_RFEDB");
	lua_pushinteger(l, 113);
	lua_setfield(l, -2, "ARM_INS_RFEIA");
	lua_pushinteger(l, 114);
	lua_setfield(l, -2, "ARM_INS_RFEIB");
	lua_pushinteger(l, 115);
	lua_setfield(l, -2, "ARM_INS_RSB");
	lua_pushinteger(l, 116);
	lua_setfield(l, -2, "ARM_INS_RSC");
	lua_pushinteger(l, 117);
	lua_setfield(l, -2, "ARM_INS_SADD16");
	lua_pushinteger(l, 118);
	lua_setfield(l, -2, "ARM_INS_SADD8");
	lua_pushinteger(l, 119);
	lua_setfield(l, -2, "ARM_INS_SASX");
	lua_pushinteger(l, 120);
	lua_setfield(l, -2, "ARM_INS_SBC");
	lua_pushinteger(l, 121);
	lua_setfield(l, -2, "ARM_INS_SBFX");
	lua_pushinteger(l, 122);
	lua_setfield(l, -2, "ARM_INS_SDIV");
	lua_pushinteger(l, 123);
	lua_setfield(l, -2, "ARM_INS_SEL");
	lua_pushinteger(l, 124);
	lua_setfield(l, -2, "ARM_INS_SETEND");
	lua_pushinteger(l, 125);
	lua_setfield(l, -2, "ARM_INS_SHA1C");
	lua_pushinteger(l, 126);
	lua_setfield(l, -2, "ARM_INS_SHA1H");
	lua_pushinteger(l, 127);
	lua_setfield(l, -2, "ARM_INS_SHA1M");
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "ARM_INS_SHA1P");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "ARM_INS_SHA1SU0");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "ARM_INS_SHA1SU1");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "ARM_INS_SHA256H");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "ARM_INS_SHA256H2");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "ARM_INS_SHA256SU0");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "ARM_INS_SHA256SU1");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "ARM_INS_SHADD16");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "ARM_INS_SHADD8");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "ARM_INS_SHASX");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "ARM_INS_SHSAX");
	lua_pushinteger(l, 139);
	lua_setfield(l, -2, "ARM_INS_SHSUB16");
	lua_pushinteger(l, 140);
	lua_setfield(l, -2, "ARM_INS_SHSUB8");
	lua_pushinteger(l, 141);
	lua_setfield(l, -2, "ARM_INS_SMC");
	lua_pushinteger(l, 142);
	lua_setfield(l, -2, "ARM_INS_SMLABB");
	lua_pushinteger(l, 143);
	lua_setfield(l, -2, "ARM_INS_SMLABT");
	lua_pushinteger(l, 144);
	lua_setfield(l, -2, "ARM_INS_SMLAD");
	lua_pushinteger(l, 145);
	lua_setfield(l, -2, "ARM_INS_SMLADX");
	lua_pushinteger(l, 146);
	lua_setfield(l, -2, "ARM_INS_SMLAL");
	lua_pushinteger(l, 147);
	lua_setfield(l, -2, "ARM_INS_SMLALBB");
	lua_pushinteger(l, 148);
	lua_setfield(l, -2, "ARM_INS_SMLALBT");
	lua_pushinteger(l, 149);
	lua_setfield(l, -2, "ARM_INS_SMLALD");
	lua_pushinteger(l, 150);
	lua_setfield(l, -2, "ARM_INS_SMLALDX");
	lua_pushinteger(l, 151);
	lua_setfield(l, -2, "ARM_INS_SMLALTB");
	lua_pushinteger(l, 152);
	lua_setfield(l, -2, "ARM_INS_SMLALTT");
	lua_pushinteger(l, 153);
	lua_setfield(l, -2, "ARM_INS_SMLATB");
	lua_pushinteger(l, 154);
	lua_setfield(l, -2, "ARM_INS_SMLATT");
	lua_pushinteger(l, 155);
	lua_setfield(l, -2, "ARM_INS_SMLAWB");
	lua_pushinteger(l, 156);
	lua_setfield(l, -2, "ARM_INS_SMLAWT");
	lua_pushinteger(l, 157);
	lua_setfield(l, -2, "ARM_INS_SMLSD");
	lua_pushinteger(l, 158);
	lua_setfield(l, -2, "ARM_INS_SMLSDX");
	lua_pushinteger(l, 159);
	lua_setfield(l, -2, "ARM_INS_SMLSLD");
	lua_pushinteger(l, 160);
	lua_setfield(l, -2, "ARM_INS_SMLSLDX");
	lua_pushinteger(l, 161);
	lua_setfield(l, -2, "ARM_INS_SMMLA");
	lua_pushinteger(l, 162);
	lua_setfield(l, -2, "ARM_INS_SMMLAR");
	lua_pushinteger(l, 163);
	lua_setfield(l, -2, "ARM_INS_SMMLS");
	lua_pushinteger(l, 164);
	lua_setfield(l, -2, "ARM_INS_SMMLSR");
	lua_pushinteger(l, 165);
	lua_setfield(l, -2, "ARM_INS_SMMUL");
	lua_pushinteger(l, 166);
	lua_setfield(l, -2, "ARM_INS_SMMULR");
	lua_pushinteger(l, 167);
	lua_setfield(l, -2, "ARM_INS_SMUAD");
	lua_pushinteger(l, 168);
	lua_setfield(l, -2, "ARM_INS_SMUADX");
	lua_pushinteger(l, 169);
	lua_setfield(l, -2, "ARM_INS_SMULBB");
	lua_pushinteger(l, 170);
	lua_setfield(l, -2, "ARM_INS_SMULBT");
	lua_pushinteger(l, 171);
	lua_setfield(l, -2, "ARM_INS_SMULL");
	lua_pushinteger(l, 172);
	lua_setfield(l, -2, "ARM_INS_SMULTB");
	lua_pushinteger(l, 173);
	lua_setfield(l, -2, "ARM_INS_SMULTT");
	lua_pushinteger(l, 174);
	lua_setfield(l, -2, "ARM_INS_SMULWB");
	lua_pushinteger(l, 175);
	lua_setfield(l, -2, "ARM_INS_SMULWT");
	lua_pushinteger(l, 176);
	lua_setfield(l, -2, "ARM_INS_SMUSD");
	lua_pushinteger(l, 177);
	lua_setfield(l, -2, "ARM_INS_SMUSDX");
	lua_pushinteger(l, 178);
	lua_setfield(l, -2, "ARM_INS_SRSDA");
	lua_pushinteger(l, 179);
	lua_setfield(l, -2, "ARM_INS_SRSDB");
	lua_pushinteger(l, 180);
	lua_setfield(l, -2, "ARM_INS_SRSIA");
	lua_pushinteger(l, 181);
	lua_setfield(l, -2, "ARM_INS_SRSIB");
	lua_pushinteger(l, 182);
	lua_setfield(l, -2, "ARM_INS_SSAT");
	lua_pushinteger(l, 183);
	lua_setfield(l, -2, "ARM_INS_SSAT16");
	lua_pushinteger(l, 184);
	lua_setfield(l, -2, "ARM_INS_SSAX");
	lua_pushinteger(l, 185);
	lua_setfield(l, -2, "ARM_INS_SSUB16");
	lua_pushinteger(l, 186);
	lua_setfield(l, -2, "ARM_INS_SSUB8");
	lua_pushinteger(l, 187);
	lua_setfield(l, -2, "ARM_INS_STC2L");
	lua_pushinteger(l, 188);
	lua_setfield(l, -2, "ARM_INS_STC2");
	lua_pushinteger(l, 189);
	lua_setfield(l, -2, "ARM_INS_STCL");
	lua_pushinteger(l, 190);
	lua_setfield(l, -2, "ARM_INS_STC");
	lua_pushinteger(l, 191);
	lua_setfield(l, -2, "ARM_INS_STL");
	lua_pushinteger(l, 192);
	lua_setfield(l, -2, "ARM_INS_STLB");
	lua_pushinteger(l, 193);
	lua_setfield(l, -2, "ARM_INS_STLEX");
	lua_pushinteger(l, 194);
	lua_setfield(l, -2, "ARM_INS_STLEXB");
	lua_pushinteger(l, 195);
	lua_setfield(l, -2, "ARM_INS_STLEXD");
	lua_pushinteger(l, 196);
	lua_setfield(l, -2, "ARM_INS_STLEXH");
	lua_pushinteger(l, 197);
	lua_setfield(l, -2, "ARM_INS_STLH");
	lua_pushinteger(l, 198);
	lua_setfield(l, -2, "ARM_INS_STMDA");
	lua_pushinteger(l, 199);
	lua_setfield(l, -2, "ARM_INS_STMDB");
	lua_pushinteger(l, 200);
	lua_setfield(l, -2, "ARM_INS_STM");
	lua_pushinteger(l, 201);
	lua_setfield(l, -2, "ARM_INS_STMIB");
	lua_pushinteger(l, 202);
	lua_setfield(l, -2, "ARM_INS_STRBT");
	lua_pushinteger(l, 203);
	lua_setfield(l, -2, "ARM_INS_STRB");
	lua_pushinteger(l, 204);
	lua_setfield(l, -2, "ARM_INS_STRD");
	lua_pushinteger(l, 205);
	lua_setfield(l, -2, "ARM_INS_STREX");
	lua_pushinteger(l, 206);
	lua_setfield(l, -2, "ARM_INS_STREXB");
	lua_pushinteger(l, 207);
	lua_setfield(l, -2, "ARM_INS_STREXD");
	lua_pushinteger(l, 208);
	lua_setfield(l, -2, "ARM_INS_STREXH");
	lua_pushinteger(l, 209);
	lua_setfield(l, -2, "ARM_INS_STRH");
	lua_pushinteger(l, 210);
	lua_setfield(l, -2, "ARM_INS_STRHT");
	lua_pushinteger(l, 211);
	lua_setfield(l, -2, "ARM_INS_STRT");
	lua_pushinteger(l, 212);
	lua_setfield(l, -2, "ARM_INS_STR");
	lua_pushinteger(l, 213);
	lua_setfield(l, -2, "ARM_INS_SUB");
	lua_pushinteger(l, 214);
	lua_setfield(l, -2, "ARM_INS_SVC");
	lua_pushinteger(l, 215);
	lua_setfield(l, -2, "ARM_INS_SWP");
	lua_pushinteger(l, 216);
	lua_setfield(l, -2, "ARM_INS_SWPB");
	lua_pushinteger(l, 217);
	lua_setfield(l, -2, "ARM_INS_SXTAB");
	lua_pushinteger(l, 218);
	lua_setfield(l, -2, "ARM_INS_SXTAB16");
	lua_pushinteger(l, 219);
	lua_setfield(l, -2, "ARM_INS_SXTAH");
	lua_pushinteger(l, 220);
	lua_setfield(l, -2, "ARM_INS_SXTB");
	lua_pushinteger(l, 221);
	lua_setfield(l, -2, "ARM_INS_SXTB16");
	lua_pushinteger(l, 222);
	lua_setfield(l, -2, "ARM_INS_SXTH");
	lua_pushinteger(l, 223);
	lua_setfield(l, -2, "ARM_INS_TEQ");
	lua_pushinteger(l, 224);
	lua_setfield(l, -2, "ARM_INS_TRAP");
	lua_pushinteger(l, 225);
	lua_setfield(l, -2, "ARM_INS_TST");
	lua_pushinteger(l, 226);
	lua_setfield(l, -2, "ARM_INS_UADD16");
	lua_pushinteger(l, 227);
	lua_setfield(l, -2, "ARM_INS_UADD8");
	lua_pushinteger(l, 228);
	lua_setfield(l, -2, "ARM_INS_UASX");
	lua_pushinteger(l, 229);
	lua_setfield(l, -2, "ARM_INS_UBFX");
	lua_pushinteger(l, 230);
	lua_setfield(l, -2, "ARM_INS_UDF");
	lua_pushinteger(l, 231);
	lua_setfield(l, -2, "ARM_INS_UDIV");
	lua_pushinteger(l, 232);
	lua_setfield(l, -2, "ARM_INS_UHADD16");
	lua_pushinteger(l, 233);
	lua_setfield(l, -2, "ARM_INS_UHADD8");
	lua_pushinteger(l, 234);
	lua_setfield(l, -2, "ARM_INS_UHASX");
	lua_pushinteger(l, 235);
	lua_setfield(l, -2, "ARM_INS_UHSAX");
	lua_pushinteger(l, 236);
	lua_setfield(l, -2, "ARM_INS_UHSUB16");
	lua_pushinteger(l, 237);
	lua_setfield(l, -2, "ARM_INS_UHSUB8");
	lua_pushinteger(l, 238);
	lua_setfield(l, -2, "ARM_INS_UMAAL");
	lua_pushinteger(l, 239);
	lua_setfield(l, -2, "ARM_INS_UMLAL");
	lua_pushinteger(l, 240);
	lua_setfield(l, -2, "ARM_INS_UMULL");
	lua_pushinteger(l, 241);
	lua_setfield(l, -2, "ARM_INS_UQADD16");
	lua_pushinteger(l, 242);
	lua_setfield(l, -2, "ARM_INS_UQADD8");
	lua_pushinteger(l, 243);
	lua_setfield(l, -2, "ARM_INS_UQASX");
	lua_pushinteger(l, 244);
	lua_setfield(l, -2, "ARM_INS_UQSAX");
	lua_pushinteger(l, 245);
	lua_setfield(l, -2, "ARM_INS_UQSUB16");
	lua_pushinteger(l, 246);
	lua_setfield(l, -2, "ARM_INS_UQSUB8");
	lua_pushinteger(l, 247);
	lua_setfield(l, -2, "ARM_INS_USAD8");
	lua_pushinteger(l, 248);
	lua_setfield(l, -2, "ARM_INS_USADA8");
	lua_pushinteger(l, 249);
	lua_setfield(l, -2, "ARM_INS_USAT");
	lua_pushinteger(l, 250);
	lua_setfield(l, -2, "ARM_INS_USAT16");
	lua_pushinteger(l, 251);
	lua_setfield(l, -2, "ARM_INS_USAX");
	lua_pushinteger(l, 252);
	lua_setfield(l, -2, "ARM_INS_USUB16");
	lua_pushinteger(l, 253);
	lua_setfield(l, -2, "ARM_INS_USUB8");
	lua_pushinteger(l, 254);
	lua_setfield(l, -2, "ARM_INS_UXTAB");
	lua_pushinteger(l, 255);
	lua_setfield(l, -2, "ARM_INS_UXTAB16");
	lua_pushinteger(l, 256);
	lua_setfield(l, -2, "ARM_INS_UXTAH");
	lua_pushinteger(l, 257);
	lua_setfield(l, -2, "ARM_INS_UXTB");
	lua_pushinteger(l, 258);
	lua_setfield(l, -2, "ARM_INS_UXTB16");
	lua_pushinteger(l, 259);
	lua_setfield(l, -2, "ARM_INS_UXTH");
	lua_pushinteger(l, 260);
	lua_setfield(l, -2, "ARM_INS_VABAL");
	lua_pushinteger(l, 261);
	lua_setfield(l, -2, "ARM_INS_VABA");
	lua_pushinteger(l, 262);
	lua_setfield(l, -2, "ARM_INS_VABDL");
	lua_pushinteger(l, 263);
	lua_setfield(l, -2, "ARM_INS_VABD");
	lua_pushinteger(l, 264);
	lua_setfield(l, -2, "ARM_INS_VABS");
	lua_pushinteger(l, 265);
	lua_setfield(l, -2, "ARM_INS_VACGE");
	lua_pushinteger(l, 266);
	lua_setfield(l, -2, "ARM_INS_VACGT");
	lua_pushinteger(l, 267);
	lua_setfield(l, -2, "ARM_INS_VADD");
	lua_pushinteger(l, 268);
	lua_setfield(l, -2, "ARM_INS_VADDHN");
	lua_pushinteger(l, 269);
	lua_setfield(l, -2, "ARM_INS_VADDL");
	lua_pushinteger(l, 270);
	lua_setfield(l, -2, "ARM_INS_VADDW");
	lua_pushinteger(l, 271);
	lua_setfield(l, -2, "ARM_INS_VAND");
	lua_pushinteger(l, 272);
	lua_setfield(l, -2, "ARM_INS_VBIC");
	lua_pushinteger(l, 273);
	lua_setfield(l, -2, "ARM_INS_VBIF");
	lua_pushinteger(l, 274);
	lua_setfield(l, -2, "ARM_INS_VBIT");
	lua_pushinteger(l, 275);
	lua_setfield(l, -2, "ARM_INS_VBSL");
	lua_pushinteger(l, 276);
	lua_setfield(l, -2, "ARM_INS_VCEQ");
	lua_pushinteger(l, 277);
	lua_setfield(l, -2, "ARM_INS_VCGE");
	lua_pushinteger(l, 278);
	lua_setfield(l, -2, "ARM_INS_VCGT");
	lua_pushinteger(l, 279);
	lua_setfield(l, -2, "ARM_INS_VCLE");
	lua_pushinteger(l, 280);
	lua_setfield(l, -2, "ARM_INS_VCLS");
	lua_pushinteger(l, 281);
	lua_setfield(l, -2, "ARM_INS_VCLT");
	lua_pushinteger(l, 282);
	lua_setfield(l, -2, "ARM_INS_VCLZ");
	lua_pushinteger(l, 283);
	lua_setfield(l, -2, "ARM_INS_VCMP");
	lua_pushinteger(l, 284);
	lua_setfield(l, -2, "ARM_INS_VCMPE");
	lua_pushinteger(l, 285);
	lua_setfield(l, -2, "ARM_INS_VCNT");
	lua_pushinteger(l, 286);
	lua_setfield(l, -2, "ARM_INS_VCVTA");
	lua_pushinteger(l, 287);
	lua_setfield(l, -2, "ARM_INS_VCVTB");
	lua_pushinteger(l, 288);
	lua_setfield(l, -2, "ARM_INS_VCVT");
	lua_pushinteger(l, 289);
	lua_setfield(l, -2, "ARM_INS_VCVTM");
	lua_pushinteger(l, 290);
	lua_setfield(l, -2, "ARM_INS_VCVTN");
	lua_pushinteger(l, 291);
	lua_setfield(l, -2, "ARM_INS_VCVTP");
	lua_pushinteger(l, 292);
	lua_setfield(l, -2, "ARM_INS_VCVTT");
	lua_pushinteger(l, 293);
	lua_setfield(l, -2, "ARM_INS_VDIV");
	lua_pushinteger(l, 294);
	lua_setfield(l, -2, "ARM_INS_VDUP");
	lua_pushinteger(l, 295);
	lua_setfield(l, -2, "ARM_INS_VEOR");
	lua_pushinteger(l, 296);
	lua_setfield(l, -2, "ARM_INS_VEXT");
	lua_pushinteger(l, 297);
	lua_setfield(l, -2, "ARM_INS_VFMA");
	lua_pushinteger(l, 298);
	lua_setfield(l, -2, "ARM_INS_VFMS");
	lua_pushinteger(l, 299);
	lua_setfield(l, -2, "ARM_INS_VFNMA");
	lua_pushinteger(l, 300);
	lua_setfield(l, -2, "ARM_INS_VFNMS");
	lua_pushinteger(l, 301);
	lua_setfield(l, -2, "ARM_INS_VHADD");
	lua_pushinteger(l, 302);
	lua_setfield(l, -2, "ARM_INS_VHSUB");
	lua_pushinteger(l, 303);
	lua_setfield(l, -2, "ARM_INS_VLD1");
	lua_pushinteger(l, 304);
	lua_setfield(l, -2, "ARM_INS_VLD2");
	lua_pushinteger(l, 305);
	lua_setfield(l, -2, "ARM_INS_VLD3");
	lua_pushinteger(l, 306);
	lua_setfield(l, -2, "ARM_INS_VLD4");
	lua_pushinteger(l, 307);
	lua_setfield(l, -2, "ARM_INS_VLDMDB");
	lua_pushinteger(l, 308);
	lua_setfield(l, -2, "ARM_INS_VLDMIA");
	lua_pushinteger(l, 309);
	lua_setfield(l, -2, "ARM_INS_VLDR");
	lua_pushinteger(l, 310);
	lua_setfield(l, -2, "ARM_INS_VMAXNM");
	lua_pushinteger(l, 311);
	lua_setfield(l, -2, "ARM_INS_VMAX");
	lua_pushinteger(l, 312);
	lua_setfield(l, -2, "ARM_INS_VMINNM");
	lua_pushinteger(l, 313);
	lua_setfield(l, -2, "ARM_INS_VMIN");
	lua_pushinteger(l, 314);
	lua_setfield(l, -2, "ARM_INS_VMLA");
	lua_pushinteger(l, 315);
	lua_setfield(l, -2, "ARM_INS_VMLAL");
	lua_pushinteger(l, 316);
	lua_setfield(l, -2, "ARM_INS_VMLS");
	lua_pushinteger(l, 317);
	lua_setfield(l, -2, "ARM_INS_VMLSL");
	lua_pushinteger(l, 318);
	lua_setfield(l, -2, "ARM_INS_VMOVL");
	lua_pushinteger(l, 319);
	lua_setfield(l, -2, "ARM_INS_VMOVN");
	lua_pushinteger(l, 320);
	lua_setfield(l, -2, "ARM_INS_VMSR");
	lua_pushinteger(l, 321);
	lua_setfield(l, -2, "ARM_INS_VMUL");
	lua_pushinteger(l, 322);
	lua_setfield(l, -2, "ARM_INS_VMULL");
	lua_pushinteger(l, 323);
	lua_setfield(l, -2, "ARM_INS_VMVN");
	lua_pushinteger(l, 324);
	lua_setfield(l, -2, "ARM_INS_VNEG");
	lua_pushinteger(l, 325);
	lua_setfield(l, -2, "ARM_INS_VNMLA");
	lua_pushinteger(l, 326);
	lua_setfield(l, -2, "ARM_INS_VNMLS");
	lua_pushinteger(l, 327);
	lua_setfield(l, -2, "ARM_INS_VNMUL");
	lua_pushinteger(l, 328);
	lua_setfield(l, -2, "ARM_INS_VORN");
	lua_pushinteger(l, 329);
	lua_setfield(l, -2, "ARM_INS_VORR");
	lua_pushinteger(l, 330);
	lua_setfield(l, -2, "ARM_INS_VPADAL");
	lua_pushinteger(l, 331);
	lua_setfield(l, -2, "ARM_INS_VPADDL");
	lua_pushinteger(l, 332);
	lua_setfield(l, -2, "ARM_INS_VPADD");
	lua_pushinteger(l, 333);
	lua_setfield(l, -2, "ARM_INS_VPMAX");
	lua_pushinteger(l, 334);
	lua_setfield(l, -2, "ARM_INS_VPMIN");
	lua_pushinteger(l, 335);
	lua_setfield(l, -2, "ARM_INS_VQABS");
	lua_pushinteger(l, 336);
	lua_setfield(l, -2, "ARM_INS_VQADD");
	lua_pushinteger(l, 337);
	lua_setfield(l, -2, "ARM_INS_VQDMLAL");
	lua_pushinteger(l, 338);
	lua_setfield(l, -2, "ARM_INS_VQDMLSL");
	lua_pushinteger(l, 339);
	lua_setfield(l, -2, "ARM_INS_VQDMULH");
	lua_pushinteger(l, 340);
	lua_setfield(l, -2, "ARM_INS_VQDMULL");
	lua_pushinteger(l, 341);
	lua_setfield(l, -2, "ARM_INS_VQMOVUN");
	lua_pushinteger(l, 342);
	lua_setfield(l, -2, "ARM_INS_VQMOVN");
	lua_pushinteger(l, 343);
	lua_setfield(l, -2, "ARM_INS_VQNEG");
	lua_pushinteger(l, 344);
	lua_setfield(l, -2, "ARM_INS_VQRDMULH");
	lua_pushinteger(l, 345);
	lua_setfield(l, -2, "ARM_INS_VQRSHL");
	lua_pushinteger(l, 346);
	lua_setfield(l, -2, "ARM_INS_VQRSHRN");
	lua_pushinteger(l, 347);
	lua_setfield(l, -2, "ARM_INS_VQRSHRUN");
	lua_pushinteger(l, 348);
	lua_setfield(l, -2, "ARM_INS_VQSHL");
	lua_pushinteger(l, 349);
	lua_setfield(l, -2, "ARM_INS_VQSHLU");
	lua_pushinteger(l, 350);
	lua_setfield(l, -2, "ARM_INS_VQSHRN");
	lua_pushinteger(l, 351);
	lua_setfield(l, -2, "ARM_INS_VQSHRUN");
	lua_pushinteger(l, 352);
	lua_setfield(l, -2, "ARM_INS_VQSUB");
	lua_pushinteger(l, 353);
	lua_setfield(l, -2, "ARM_INS_VRADDHN");
	lua_pushinteger(l, 354);
	lua_setfield(l, -2, "ARM_INS_VRECPE");
	lua_pushinteger(l, 355);
	lua_setfield(l, -2, "ARM_INS_VRECPS");
	lua_pushinteger(l, 356);
	lua_setfield(l, -2, "ARM_INS_VREV16");
	lua_pushinteger(l, 357);
	lua_setfield(l, -2, "ARM_INS_VREV32");
	lua_pushinteger(l, 358);
	lua_setfield(l, -2, "ARM_INS_VREV64");
	lua_pushinteger(l, 359);
	lua_setfield(l, -2, "ARM_INS_VRHADD");
	lua_pushinteger(l, 360);
	lua_setfield(l, -2, "ARM_INS_VRINTA");
	lua_pushinteger(l, 361);
	lua_setfield(l, -2, "ARM_INS_VRINTM");
	lua_pushinteger(l, 362);
	lua_setfield(l, -2, "ARM_INS_VRINTN");
	lua_pushinteger(l, 363);
	lua_setfield(l, -2, "ARM_INS_VRINTP");
	lua_pushinteger(l, 364);
	lua_setfield(l, -2, "ARM_INS_VRINTR");
	lua_pushinteger(l, 365);
	lua_setfield(l, -2, "ARM_INS_VRINTX");
	lua_pushinteger(l, 366);
	lua_setfield(l, -2, "ARM_INS_VRINTZ");
	lua_pushinteger(l, 367);
	lua_setfield(l, -2, "ARM_INS_VRSHL");
	lua_pushinteger(l, 368);
	lua_setfield(l, -2, "ARM_INS_VRSHRN");
	lua_pushinteger(l, 369);
	lua_setfield(l, -2, "ARM_INS_VRSHR");
	lua_pushinteger(l, 370);
	lua_setfield(l, -2, "ARM_INS_VRSQRTE");
	lua_pushinteger(l, 371);
	lua_setfield(l, -2, "ARM_INS_VRSQRTS");
	lua_pushinteger(l, 372);
	lua_setfield(l, -2, "ARM_INS_VRSRA");
	lua_pushinteger(l, 373);
	lua_setfield(l, -2, "ARM_INS_VRSUBHN");
	lua_pushinteger(l, 374);
	lua_setfield(l, -2, "ARM_INS_VSELEQ");
	lua_pushinteger(l, 375);
	lua_setfield(l, -2, "ARM_INS_VSELGE");
	lua_pushinteger(l, 376);
	lua_setfield(l, -2, "ARM_INS_VSELGT");
	lua_pushinteger(l, 377);
	lua_setfield(l, -2, "ARM_INS_VSELVS");
	lua_pushinteger(l, 378);
	lua_setfield(l, -2, "ARM_INS_VSHLL");
	lua_pushinteger(l, 379);
	lua_setfield(l, -2, "ARM_INS_VSHL");
	lua_pushinteger(l, 380);
	lua_setfield(l, -2, "ARM_INS_VSHRN");
	lua_pushinteger(l, 381);
	lua_setfield(l, -2, "ARM_INS_VSHR");
	lua_pushinteger(l, 382);
	lua_setfield(l, -2, "ARM_INS_VSLI");
	lua_pushinteger(l, 383);
	lua_setfield(l, -2, "ARM_INS_VSQRT");
	lua_pushinteger(l, 384);
	lua_setfield(l, -2, "ARM_INS_VSRA");
	lua_pushinteger(l, 385);
	lua_setfield(l, -2, "ARM_INS_VSRI");
	lua_pushinteger(l, 386);
	lua_setfield(l, -2, "ARM_INS_VST1");
	lua_pushinteger(l, 387);
	lua_setfield(l, -2, "ARM_INS_VST2");
	lua_pushinteger(l, 388);
	lua_setfield(l, -2, "ARM_INS_VST3");
	lua_pushinteger(l, 389);
	lua_setfield(l, -2, "ARM_INS_VST4");
	lua_pushinteger(l, 390);
	lua_setfield(l, -2, "ARM_INS_VSTMDB");
	lua_pushinteger(l, 391);
	lua_setfield(l, -2, "ARM_INS_VSTMIA");
	lua_pushinteger(l, 392);
	lua_setfield(l, -2, "ARM_INS_VSTR");
	lua_pushinteger(l, 393);
	lua_setfield(l, -2, "ARM_INS_VSUB");
	lua_pushinteger(l, 394);
	lua_setfield(l, -2, "ARM_INS_VSUBHN");
	lua_pushinteger(l, 395);
	lua_setfield(l, -2, "ARM_INS_VSUBL");
	lua_pushinteger(l, 396);
	lua_setfield(l, -2, "ARM_INS_VSUBW");
	lua_pushinteger(l, 397);
	lua_setfield(l, -2, "ARM_INS_VSWP");
	lua_pushinteger(l, 398);
	lua_setfield(l, -2, "ARM_INS_VTBL");
	lua_pushinteger(l, 399);
	lua_setfield(l, -2, "ARM_INS_VTBX");
	lua_pushinteger(l, 400);
	lua_setfield(l, -2, "ARM_INS_VCVTR");
	lua_pushinteger(l, 401);
	lua_setfield(l, -2, "ARM_INS_VTRN");
	lua_pushinteger(l, 402);
	lua_setfield(l, -2, "ARM_INS_VTST");
	lua_pushinteger(l, 403);
	lua_setfield(l, -2, "ARM_INS_VUZP");
	lua_pushinteger(l, 404);
	lua_setfield(l, -2, "ARM_INS_VZIP");
	lua_pushinteger(l, 405);
	lua_setfield(l, -2, "ARM_INS_ADDW");
	lua_pushinteger(l, 406);
	lua_setfield(l, -2, "ARM_INS_ASR");
	lua_pushinteger(l, 407);
	lua_setfield(l, -2, "ARM_INS_DCPS1");
	lua_pushinteger(l, 408);
	lua_setfield(l, -2, "ARM_INS_DCPS2");
	lua_pushinteger(l, 409);
	lua_setfield(l, -2, "ARM_INS_DCPS3");
	lua_pushinteger(l, 410);
	lua_setfield(l, -2, "ARM_INS_IT");
	lua_pushinteger(l, 411);
	lua_setfield(l, -2, "ARM_INS_LSL");
	lua_pushinteger(l, 412);
	lua_setfield(l, -2, "ARM_INS_LSR");
	lua_pushinteger(l, 413);
	lua_setfield(l, -2, "ARM_INS_ASRS");
	lua_pushinteger(l, 414);
	lua_setfield(l, -2, "ARM_INS_LSRS");
	lua_pushinteger(l, 415);
	lua_setfield(l, -2, "ARM_INS_ORN");
	lua_pushinteger(l, 416);
	lua_setfield(l, -2, "ARM_INS_ROR");
	lua_pushinteger(l, 417);
	lua_setfield(l, -2, "ARM_INS_RRX");
	lua_pushinteger(l, 418);
	lua_setfield(l, -2, "ARM_INS_SUBS");
	lua_pushinteger(l, 419);
	lua_setfield(l, -2, "ARM_INS_SUBW");
	lua_pushinteger(l, 420);
	lua_setfield(l, -2, "ARM_INS_TBB");
	lua_pushinteger(l, 421);
	lua_setfield(l, -2, "ARM_INS_TBH");
	lua_pushinteger(l, 422);
	lua_setfield(l, -2, "ARM_INS_CBNZ");
	lua_pushinteger(l, 423);
	lua_setfield(l, -2, "ARM_INS_CBZ");
	lua_pushinteger(l, 424);
	lua_setfield(l, -2, "ARM_INS_MOVS");
	lua_pushinteger(l, 425);
	lua_setfield(l, -2, "ARM_INS_POP");
	lua_pushinteger(l, 426);
	lua_setfield(l, -2, "ARM_INS_PUSH");
	lua_pushinteger(l, 427);
	lua_setfield(l, -2, "ARM_INS_NOP");
	lua_pushinteger(l, 428);
	lua_setfield(l, -2, "ARM_INS_YIELD");
	lua_pushinteger(l, 429);
	lua_setfield(l, -2, "ARM_INS_WFE");
	lua_pushinteger(l, 430);
	lua_setfield(l, -2, "ARM_INS_WFI");
	lua_pushinteger(l, 431);
	lua_setfield(l, -2, "ARM_INS_SEV");
	lua_pushinteger(l, 432);
	lua_setfield(l, -2, "ARM_INS_SEVL");
	lua_pushinteger(l, 433);
	lua_setfield(l, -2, "ARM_INS_VPUSH");
	lua_pushinteger(l, 434);
	lua_setfield(l, -2, "ARM_INS_VPOP");
	lua_pushinteger(l, 435);
	lua_setfield(l, -2, "ARM_INS_ENDING");

	/* Group of ARM instructions */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "ARM_GRP_INVALID");

	/* Generic groups */
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "ARM_GRP_JUMP");

	/* Architecture-specific groups */
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "ARM_GRP_CRYPTO");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "ARM_GRP_DATABARRIER");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "ARM_GRP_DIVIDE");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "ARM_GRP_FPARMV8");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "ARM_GRP_MULTPRO");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "ARM_GRP_NEON");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "ARM_GRP_T2EXTRACTPACK");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "ARM_GRP_THUMB2DSP");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "ARM_GRP_TRUSTZONE");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "ARM_GRP_V4T");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "ARM_GRP_V5T");
	lua_pushinteger(l, 139);
	lua_setfield(l, -2, "ARM_GRP_V5TE");
	lua_pushinteger(l, 140);
	lua_setfield(l, -2, "ARM_GRP_V6");
	lua_pushinteger(l, 141);
	lua_setfield(l, -2, "ARM_GRP_V6T2");
	lua_pushinteger(l, 142);
	lua_setfield(l, -2, "ARM_GRP_V7");
	lua_pushinteger(l, 143);
	lua_setfield(l, -2, "ARM_GRP_V8");
	lua_pushinteger(l, 144);
	lua_setfield(l, -2, "ARM_GRP_VFP2");
	lua_pushinteger(l, 145);
	lua_setfield(l, -2, "ARM_GRP_VFP3");
	lua_pushinteger(l, 146);
	lua_setfield(l, -2, "ARM_GRP_VFP4");
	lua_pushinteger(l, 147);
	lua_setfield(l, -2, "ARM_GRP_ARM");
	lua_pushinteger(l, 148);
	lua_setfield(l, -2, "ARM_GRP_MCLASS");
	lua_pushinteger(l, 149);
	lua_setfield(l, -2, "ARM_GRP_NOTMCLASS");
	lua_pushinteger(l, 150);
	lua_setfield(l, -2, "ARM_GRP_THUMB");
	lua_pushinteger(l, 151);
	lua_setfield(l, -2, "ARM_GRP_THUMB1ONLY");
	lua_pushinteger(l, 152);
	lua_setfield(l, -2, "ARM_GRP_THUMB2");
	lua_pushinteger(l, 153);
	lua_setfield(l, -2, "ARM_GRP_PREV8");
	lua_pushinteger(l, 154);
	lua_setfield(l, -2, "ARM_GRP_FPVMLX");
	lua_pushinteger(l, 155);
	lua_setfield(l, -2, "ARM_GRP_MULOPS");
	lua_pushinteger(l, 156);
	lua_setfield(l, -2, "ARM_GRP_CRC");
	lua_pushinteger(l, 157);
	lua_setfield(l, -2, "ARM_GRP_DPVFP");
	lua_pushinteger(l, 158);
	lua_setfield(l, -2, "ARM_GRP_V6M");
	lua_pushinteger(l, 159);
	lua_setfield(l, -2, "ARM_GRP_ENDING");
}
