/* For Capstone Engine. AUTO-GENERATED FILE, DO NOT EDIT */

#include "mips_const.h"

void set_mips_const(lua_State* l)
{
	/* Operand type for instruction's operands */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "MIPS_OP_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "MIPS_OP_REG");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "MIPS_OP_IMM");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "MIPS_OP_MEM");

	/* MIPS registers */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "MIPS_REG_INVALID");

	/* General purpose registers */
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "MIPS_REG_0");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "MIPS_REG_1");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "MIPS_REG_2");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "MIPS_REG_3");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "MIPS_REG_4");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "MIPS_REG_5");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "MIPS_REG_6");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "MIPS_REG_7");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "MIPS_REG_8");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "MIPS_REG_9");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "MIPS_REG_10");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "MIPS_REG_11");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "MIPS_REG_12");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "MIPS_REG_13");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "MIPS_REG_14");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "MIPS_REG_15");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "MIPS_REG_16");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "MIPS_REG_17");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "MIPS_REG_18");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "MIPS_REG_19");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "MIPS_REG_20");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "MIPS_REG_21");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "MIPS_REG_22");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "MIPS_REG_23");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "MIPS_REG_24");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "MIPS_REG_25");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "MIPS_REG_26");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "MIPS_REG_27");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "MIPS_REG_28");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "MIPS_REG_29");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "MIPS_REG_30");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "MIPS_REG_31");

	/* DSP registers */
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "MIPS_REG_DSPCCOND");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "MIPS_REG_DSPCARRY");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "MIPS_REG_DSPEFI");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "MIPS_REG_DSPOUTFLAG");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "MIPS_REG_DSPOUTFLAG16_19");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "MIPS_REG_DSPOUTFLAG20");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "MIPS_REG_DSPOUTFLAG21");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "MIPS_REG_DSPOUTFLAG22");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "MIPS_REG_DSPOUTFLAG23");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "MIPS_REG_DSPPOS");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "MIPS_REG_DSPSCOUNT");

	/* ACC registers */
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "MIPS_REG_AC0");
	lua_pushinteger(l, 45);
	lua_setfield(l, -2, "MIPS_REG_AC1");
	lua_pushinteger(l, 46);
	lua_setfield(l, -2, "MIPS_REG_AC2");
	lua_pushinteger(l, 47);
	lua_setfield(l, -2, "MIPS_REG_AC3");

	/* COP registers */
	lua_pushinteger(l, 48);
	lua_setfield(l, -2, "MIPS_REG_CC0");
	lua_pushinteger(l, 49);
	lua_setfield(l, -2, "MIPS_REG_CC1");
	lua_pushinteger(l, 50);
	lua_setfield(l, -2, "MIPS_REG_CC2");
	lua_pushinteger(l, 51);
	lua_setfield(l, -2, "MIPS_REG_CC3");
	lua_pushinteger(l, 52);
	lua_setfield(l, -2, "MIPS_REG_CC4");
	lua_pushinteger(l, 53);
	lua_setfield(l, -2, "MIPS_REG_CC5");
	lua_pushinteger(l, 54);
	lua_setfield(l, -2, "MIPS_REG_CC6");
	lua_pushinteger(l, 55);
	lua_setfield(l, -2, "MIPS_REG_CC7");

	/* FPU registers */
	lua_pushinteger(l, 56);
	lua_setfield(l, -2, "MIPS_REG_F0");
	lua_pushinteger(l, 57);
	lua_setfield(l, -2, "MIPS_REG_F1");
	lua_pushinteger(l, 58);
	lua_setfield(l, -2, "MIPS_REG_F2");
	lua_pushinteger(l, 59);
	lua_setfield(l, -2, "MIPS_REG_F3");
	lua_pushinteger(l, 60);
	lua_setfield(l, -2, "MIPS_REG_F4");
	lua_pushinteger(l, 61);
	lua_setfield(l, -2, "MIPS_REG_F5");
	lua_pushinteger(l, 62);
	lua_setfield(l, -2, "MIPS_REG_F6");
	lua_pushinteger(l, 63);
	lua_setfield(l, -2, "MIPS_REG_F7");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "MIPS_REG_F8");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "MIPS_REG_F9");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "MIPS_REG_F10");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "MIPS_REG_F11");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "MIPS_REG_F12");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "MIPS_REG_F13");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "MIPS_REG_F14");
	lua_pushinteger(l, 71);
	lua_setfield(l, -2, "MIPS_REG_F15");
	lua_pushinteger(l, 72);
	lua_setfield(l, -2, "MIPS_REG_F16");
	lua_pushinteger(l, 73);
	lua_setfield(l, -2, "MIPS_REG_F17");
	lua_pushinteger(l, 74);
	lua_setfield(l, -2, "MIPS_REG_F18");
	lua_pushinteger(l, 75);
	lua_setfield(l, -2, "MIPS_REG_F19");
	lua_pushinteger(l, 76);
	lua_setfield(l, -2, "MIPS_REG_F20");
	lua_pushinteger(l, 77);
	lua_setfield(l, -2, "MIPS_REG_F21");
	lua_pushinteger(l, 78);
	lua_setfield(l, -2, "MIPS_REG_F22");
	lua_pushinteger(l, 79);
	lua_setfield(l, -2, "MIPS_REG_F23");
	lua_pushinteger(l, 80);
	lua_setfield(l, -2, "MIPS_REG_F24");
	lua_pushinteger(l, 81);
	lua_setfield(l, -2, "MIPS_REG_F25");
	lua_pushinteger(l, 82);
	lua_setfield(l, -2, "MIPS_REG_F26");
	lua_pushinteger(l, 83);
	lua_setfield(l, -2, "MIPS_REG_F27");
	lua_pushinteger(l, 84);
	lua_setfield(l, -2, "MIPS_REG_F28");
	lua_pushinteger(l, 85);
	lua_setfield(l, -2, "MIPS_REG_F29");
	lua_pushinteger(l, 86);
	lua_setfield(l, -2, "MIPS_REG_F30");
	lua_pushinteger(l, 87);
	lua_setfield(l, -2, "MIPS_REG_F31");
	lua_pushinteger(l, 88);
	lua_setfield(l, -2, "MIPS_REG_FCC0");
	lua_pushinteger(l, 89);
	lua_setfield(l, -2, "MIPS_REG_FCC1");
	lua_pushinteger(l, 90);
	lua_setfield(l, -2, "MIPS_REG_FCC2");
	lua_pushinteger(l, 91);
	lua_setfield(l, -2, "MIPS_REG_FCC3");
	lua_pushinteger(l, 92);
	lua_setfield(l, -2, "MIPS_REG_FCC4");
	lua_pushinteger(l, 93);
	lua_setfield(l, -2, "MIPS_REG_FCC5");
	lua_pushinteger(l, 94);
	lua_setfield(l, -2, "MIPS_REG_FCC6");
	lua_pushinteger(l, 95);
	lua_setfield(l, -2, "MIPS_REG_FCC7");

	/* AFPR128 */
	lua_pushinteger(l, 96);
	lua_setfield(l, -2, "MIPS_REG_W0");
	lua_pushinteger(l, 97);
	lua_setfield(l, -2, "MIPS_REG_W1");
	lua_pushinteger(l, 98);
	lua_setfield(l, -2, "MIPS_REG_W2");
	lua_pushinteger(l, 99);
	lua_setfield(l, -2, "MIPS_REG_W3");
	lua_pushinteger(l, 100);
	lua_setfield(l, -2, "MIPS_REG_W4");
	lua_pushinteger(l, 101);
	lua_setfield(l, -2, "MIPS_REG_W5");
	lua_pushinteger(l, 102);
	lua_setfield(l, -2, "MIPS_REG_W6");
	lua_pushinteger(l, 103);
	lua_setfield(l, -2, "MIPS_REG_W7");
	lua_pushinteger(l, 104);
	lua_setfield(l, -2, "MIPS_REG_W8");
	lua_pushinteger(l, 105);
	lua_setfield(l, -2, "MIPS_REG_W9");
	lua_pushinteger(l, 106);
	lua_setfield(l, -2, "MIPS_REG_W10");
	lua_pushinteger(l, 107);
	lua_setfield(l, -2, "MIPS_REG_W11");
	lua_pushinteger(l, 108);
	lua_setfield(l, -2, "MIPS_REG_W12");
	lua_pushinteger(l, 109);
	lua_setfield(l, -2, "MIPS_REG_W13");
	lua_pushinteger(l, 110);
	lua_setfield(l, -2, "MIPS_REG_W14");
	lua_pushinteger(l, 111);
	lua_setfield(l, -2, "MIPS_REG_W15");
	lua_pushinteger(l, 112);
	lua_setfield(l, -2, "MIPS_REG_W16");
	lua_pushinteger(l, 113);
	lua_setfield(l, -2, "MIPS_REG_W17");
	lua_pushinteger(l, 114);
	lua_setfield(l, -2, "MIPS_REG_W18");
	lua_pushinteger(l, 115);
	lua_setfield(l, -2, "MIPS_REG_W19");
	lua_pushinteger(l, 116);
	lua_setfield(l, -2, "MIPS_REG_W20");
	lua_pushinteger(l, 117);
	lua_setfield(l, -2, "MIPS_REG_W21");
	lua_pushinteger(l, 118);
	lua_setfield(l, -2, "MIPS_REG_W22");
	lua_pushinteger(l, 119);
	lua_setfield(l, -2, "MIPS_REG_W23");
	lua_pushinteger(l, 120);
	lua_setfield(l, -2, "MIPS_REG_W24");
	lua_pushinteger(l, 121);
	lua_setfield(l, -2, "MIPS_REG_W25");
	lua_pushinteger(l, 122);
	lua_setfield(l, -2, "MIPS_REG_W26");
	lua_pushinteger(l, 123);
	lua_setfield(l, -2, "MIPS_REG_W27");
	lua_pushinteger(l, 124);
	lua_setfield(l, -2, "MIPS_REG_W28");
	lua_pushinteger(l, 125);
	lua_setfield(l, -2, "MIPS_REG_W29");
	lua_pushinteger(l, 126);
	lua_setfield(l, -2, "MIPS_REG_W30");
	lua_pushinteger(l, 127);
	lua_setfield(l, -2, "MIPS_REG_W31");
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "MIPS_REG_HI");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "MIPS_REG_LO");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "MIPS_REG_P0");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "MIPS_REG_P1");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "MIPS_REG_P2");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "MIPS_REG_MPL0");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "MIPS_REG_MPL1");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "MIPS_REG_MPL2");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "MIPS_REG_ENDING");
	lua_pushinteger(l, MIPS_REG_0);
	lua_setfield(l, -2, "MIPS_REG_ZERO");
	lua_pushinteger(l, MIPS_REG_1);
	lua_setfield(l, -2, "MIPS_REG_AT");
	lua_pushinteger(l, MIPS_REG_2);
	lua_setfield(l, -2, "MIPS_REG_V0");
	lua_pushinteger(l, MIPS_REG_3);
	lua_setfield(l, -2, "MIPS_REG_V1");
	lua_pushinteger(l, MIPS_REG_4);
	lua_setfield(l, -2, "MIPS_REG_A0");
	lua_pushinteger(l, MIPS_REG_5);
	lua_setfield(l, -2, "MIPS_REG_A1");
	lua_pushinteger(l, MIPS_REG_6);
	lua_setfield(l, -2, "MIPS_REG_A2");
	lua_pushinteger(l, MIPS_REG_7);
	lua_setfield(l, -2, "MIPS_REG_A3");
	lua_pushinteger(l, MIPS_REG_8);
	lua_setfield(l, -2, "MIPS_REG_T0");
	lua_pushinteger(l, MIPS_REG_9);
	lua_setfield(l, -2, "MIPS_REG_T1");
	lua_pushinteger(l, MIPS_REG_10);
	lua_setfield(l, -2, "MIPS_REG_T2");
	lua_pushinteger(l, MIPS_REG_11);
	lua_setfield(l, -2, "MIPS_REG_T3");
	lua_pushinteger(l, MIPS_REG_12);
	lua_setfield(l, -2, "MIPS_REG_T4");
	lua_pushinteger(l, MIPS_REG_13);
	lua_setfield(l, -2, "MIPS_REG_T5");
	lua_pushinteger(l, MIPS_REG_14);
	lua_setfield(l, -2, "MIPS_REG_T6");
	lua_pushinteger(l, MIPS_REG_15);
	lua_setfield(l, -2, "MIPS_REG_T7");
	lua_pushinteger(l, MIPS_REG_16);
	lua_setfield(l, -2, "MIPS_REG_S0");
	lua_pushinteger(l, MIPS_REG_17);
	lua_setfield(l, -2, "MIPS_REG_S1");
	lua_pushinteger(l, MIPS_REG_18);
	lua_setfield(l, -2, "MIPS_REG_S2");
	lua_pushinteger(l, MIPS_REG_19);
	lua_setfield(l, -2, "MIPS_REG_S3");
	lua_pushinteger(l, MIPS_REG_20);
	lua_setfield(l, -2, "MIPS_REG_S4");
	lua_pushinteger(l, MIPS_REG_21);
	lua_setfield(l, -2, "MIPS_REG_S5");
	lua_pushinteger(l, MIPS_REG_22);
	lua_setfield(l, -2, "MIPS_REG_S6");
	lua_pushinteger(l, MIPS_REG_23);
	lua_setfield(l, -2, "MIPS_REG_S7");
	lua_pushinteger(l, MIPS_REG_24);
	lua_setfield(l, -2, "MIPS_REG_T8");
	lua_pushinteger(l, MIPS_REG_25);
	lua_setfield(l, -2, "MIPS_REG_T9");
	lua_pushinteger(l, MIPS_REG_26);
	lua_setfield(l, -2, "MIPS_REG_K0");
	lua_pushinteger(l, MIPS_REG_27);
	lua_setfield(l, -2, "MIPS_REG_K1");
	lua_pushinteger(l, MIPS_REG_28);
	lua_setfield(l, -2, "MIPS_REG_GP");
	lua_pushinteger(l, MIPS_REG_29);
	lua_setfield(l, -2, "MIPS_REG_SP");
	lua_pushinteger(l, MIPS_REG_30);
	lua_setfield(l, -2, "MIPS_REG_FP");
	lua_pushinteger(l, MIPS_REG_30);
	lua_setfield(l, -2, "MIPS_REG_S8");
	lua_pushinteger(l, MIPS_REG_31);
	lua_setfield(l, -2, "MIPS_REG_RA");
	lua_pushinteger(l, MIPS_REG_AC0);
	lua_setfield(l, -2, "MIPS_REG_HI0");
	lua_pushinteger(l, MIPS_REG_AC1);
	lua_setfield(l, -2, "MIPS_REG_HI1");
	lua_pushinteger(l, MIPS_REG_AC2);
	lua_setfield(l, -2, "MIPS_REG_HI2");
	lua_pushinteger(l, MIPS_REG_AC3);
	lua_setfield(l, -2, "MIPS_REG_HI3");
	lua_pushinteger(l, MIPS_REG_HI0);
	lua_setfield(l, -2, "MIPS_REG_LO0");
	lua_pushinteger(l, MIPS_REG_HI1);
	lua_setfield(l, -2, "MIPS_REG_LO1");
	lua_pushinteger(l, MIPS_REG_HI2);
	lua_setfield(l, -2, "MIPS_REG_LO2");
	lua_pushinteger(l, MIPS_REG_HI3);
	lua_setfield(l, -2, "MIPS_REG_LO3");

	/* MIPS instruction */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "MIPS_INS_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "MIPS_INS_ABSQ_S");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "MIPS_INS_ADD");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "MIPS_INS_ADDIUPC");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "MIPS_INS_ADDQH");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "MIPS_INS_ADDQH_R");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "MIPS_INS_ADDQ");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "MIPS_INS_ADDQ_S");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "MIPS_INS_ADDSC");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "MIPS_INS_ADDS_A");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "MIPS_INS_ADDS_S");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "MIPS_INS_ADDS_U");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "MIPS_INS_ADDUH");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "MIPS_INS_ADDUH_R");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "MIPS_INS_ADDU");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "MIPS_INS_ADDU_S");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "MIPS_INS_ADDVI");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "MIPS_INS_ADDV");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "MIPS_INS_ADDWC");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "MIPS_INS_ADD_A");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "MIPS_INS_ADDI");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "MIPS_INS_ADDIU");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "MIPS_INS_ALIGN");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "MIPS_INS_ALUIPC");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "MIPS_INS_AND");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "MIPS_INS_ANDI");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "MIPS_INS_APPEND");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "MIPS_INS_ASUB_S");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "MIPS_INS_ASUB_U");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "MIPS_INS_AUI");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "MIPS_INS_AUIPC");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "MIPS_INS_AVER_S");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "MIPS_INS_AVER_U");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "MIPS_INS_AVE_S");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "MIPS_INS_AVE_U");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "MIPS_INS_BADDU");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "MIPS_INS_BAL");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "MIPS_INS_BALC");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "MIPS_INS_BALIGN");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "MIPS_INS_BC");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "MIPS_INS_BC0F");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "MIPS_INS_BC0FL");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "MIPS_INS_BC0T");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "MIPS_INS_BC0TL");
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "MIPS_INS_BC1EQZ");
	lua_pushinteger(l, 45);
	lua_setfield(l, -2, "MIPS_INS_BC1F");
	lua_pushinteger(l, 46);
	lua_setfield(l, -2, "MIPS_INS_BC1FL");
	lua_pushinteger(l, 47);
	lua_setfield(l, -2, "MIPS_INS_BC1NEZ");
	lua_pushinteger(l, 48);
	lua_setfield(l, -2, "MIPS_INS_BC1T");
	lua_pushinteger(l, 49);
	lua_setfield(l, -2, "MIPS_INS_BC1TL");
	lua_pushinteger(l, 50);
	lua_setfield(l, -2, "MIPS_INS_BC2EQZ");
	lua_pushinteger(l, 51);
	lua_setfield(l, -2, "MIPS_INS_BC2F");
	lua_pushinteger(l, 52);
	lua_setfield(l, -2, "MIPS_INS_BC2FL");
	lua_pushinteger(l, 53);
	lua_setfield(l, -2, "MIPS_INS_BC2NEZ");
	lua_pushinteger(l, 54);
	lua_setfield(l, -2, "MIPS_INS_BC2T");
	lua_pushinteger(l, 55);
	lua_setfield(l, -2, "MIPS_INS_BC2TL");
	lua_pushinteger(l, 56);
	lua_setfield(l, -2, "MIPS_INS_BC3F");
	lua_pushinteger(l, 57);
	lua_setfield(l, -2, "MIPS_INS_BC3FL");
	lua_pushinteger(l, 58);
	lua_setfield(l, -2, "MIPS_INS_BC3T");
	lua_pushinteger(l, 59);
	lua_setfield(l, -2, "MIPS_INS_BC3TL");
	lua_pushinteger(l, 60);
	lua_setfield(l, -2, "MIPS_INS_BCLRI");
	lua_pushinteger(l, 61);
	lua_setfield(l, -2, "MIPS_INS_BCLR");
	lua_pushinteger(l, 62);
	lua_setfield(l, -2, "MIPS_INS_BEQ");
	lua_pushinteger(l, 63);
	lua_setfield(l, -2, "MIPS_INS_BEQC");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "MIPS_INS_BEQL");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "MIPS_INS_BEQZALC");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "MIPS_INS_BEQZC");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "MIPS_INS_BGEC");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "MIPS_INS_BGEUC");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "MIPS_INS_BGEZ");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "MIPS_INS_BGEZAL");
	lua_pushinteger(l, 71);
	lua_setfield(l, -2, "MIPS_INS_BGEZALC");
	lua_pushinteger(l, 72);
	lua_setfield(l, -2, "MIPS_INS_BGEZALL");
	lua_pushinteger(l, 73);
	lua_setfield(l, -2, "MIPS_INS_BGEZALS");
	lua_pushinteger(l, 74);
	lua_setfield(l, -2, "MIPS_INS_BGEZC");
	lua_pushinteger(l, 75);
	lua_setfield(l, -2, "MIPS_INS_BGEZL");
	lua_pushinteger(l, 76);
	lua_setfield(l, -2, "MIPS_INS_BGTZ");
	lua_pushinteger(l, 77);
	lua_setfield(l, -2, "MIPS_INS_BGTZALC");
	lua_pushinteger(l, 78);
	lua_setfield(l, -2, "MIPS_INS_BGTZC");
	lua_pushinteger(l, 79);
	lua_setfield(l, -2, "MIPS_INS_BGTZL");
	lua_pushinteger(l, 80);
	lua_setfield(l, -2, "MIPS_INS_BINSLI");
	lua_pushinteger(l, 81);
	lua_setfield(l, -2, "MIPS_INS_BINSL");
	lua_pushinteger(l, 82);
	lua_setfield(l, -2, "MIPS_INS_BINSRI");
	lua_pushinteger(l, 83);
	lua_setfield(l, -2, "MIPS_INS_BINSR");
	lua_pushinteger(l, 84);
	lua_setfield(l, -2, "MIPS_INS_BITREV");
	lua_pushinteger(l, 85);
	lua_setfield(l, -2, "MIPS_INS_BITSWAP");
	lua_pushinteger(l, 86);
	lua_setfield(l, -2, "MIPS_INS_BLEZ");
	lua_pushinteger(l, 87);
	lua_setfield(l, -2, "MIPS_INS_BLEZALC");
	lua_pushinteger(l, 88);
	lua_setfield(l, -2, "MIPS_INS_BLEZC");
	lua_pushinteger(l, 89);
	lua_setfield(l, -2, "MIPS_INS_BLEZL");
	lua_pushinteger(l, 90);
	lua_setfield(l, -2, "MIPS_INS_BLTC");
	lua_pushinteger(l, 91);
	lua_setfield(l, -2, "MIPS_INS_BLTUC");
	lua_pushinteger(l, 92);
	lua_setfield(l, -2, "MIPS_INS_BLTZ");
	lua_pushinteger(l, 93);
	lua_setfield(l, -2, "MIPS_INS_BLTZAL");
	lua_pushinteger(l, 94);
	lua_setfield(l, -2, "MIPS_INS_BLTZALC");
	lua_pushinteger(l, 95);
	lua_setfield(l, -2, "MIPS_INS_BLTZALL");
	lua_pushinteger(l, 96);
	lua_setfield(l, -2, "MIPS_INS_BLTZALS");
	lua_pushinteger(l, 97);
	lua_setfield(l, -2, "MIPS_INS_BLTZC");
	lua_pushinteger(l, 98);
	lua_setfield(l, -2, "MIPS_INS_BLTZL");
	lua_pushinteger(l, 99);
	lua_setfield(l, -2, "MIPS_INS_BMNZI");
	lua_pushinteger(l, 100);
	lua_setfield(l, -2, "MIPS_INS_BMNZ");
	lua_pushinteger(l, 101);
	lua_setfield(l, -2, "MIPS_INS_BMZI");
	lua_pushinteger(l, 102);
	lua_setfield(l, -2, "MIPS_INS_BMZ");
	lua_pushinteger(l, 103);
	lua_setfield(l, -2, "MIPS_INS_BNE");
	lua_pushinteger(l, 104);
	lua_setfield(l, -2, "MIPS_INS_BNEC");
	lua_pushinteger(l, 105);
	lua_setfield(l, -2, "MIPS_INS_BNEGI");
	lua_pushinteger(l, 106);
	lua_setfield(l, -2, "MIPS_INS_BNEG");
	lua_pushinteger(l, 107);
	lua_setfield(l, -2, "MIPS_INS_BNEL");
	lua_pushinteger(l, 108);
	lua_setfield(l, -2, "MIPS_INS_BNEZALC");
	lua_pushinteger(l, 109);
	lua_setfield(l, -2, "MIPS_INS_BNEZC");
	lua_pushinteger(l, 110);
	lua_setfield(l, -2, "MIPS_INS_BNVC");
	lua_pushinteger(l, 111);
	lua_setfield(l, -2, "MIPS_INS_BNZ");
	lua_pushinteger(l, 112);
	lua_setfield(l, -2, "MIPS_INS_BOVC");
	lua_pushinteger(l, 113);
	lua_setfield(l, -2, "MIPS_INS_BPOSGE32");
	lua_pushinteger(l, 114);
	lua_setfield(l, -2, "MIPS_INS_BREAK");
	lua_pushinteger(l, 115);
	lua_setfield(l, -2, "MIPS_INS_BSELI");
	lua_pushinteger(l, 116);
	lua_setfield(l, -2, "MIPS_INS_BSEL");
	lua_pushinteger(l, 117);
	lua_setfield(l, -2, "MIPS_INS_BSETI");
	lua_pushinteger(l, 118);
	lua_setfield(l, -2, "MIPS_INS_BSET");
	lua_pushinteger(l, 119);
	lua_setfield(l, -2, "MIPS_INS_BZ");
	lua_pushinteger(l, 120);
	lua_setfield(l, -2, "MIPS_INS_BEQZ");
	lua_pushinteger(l, 121);
	lua_setfield(l, -2, "MIPS_INS_B");
	lua_pushinteger(l, 122);
	lua_setfield(l, -2, "MIPS_INS_BNEZ");
	lua_pushinteger(l, 123);
	lua_setfield(l, -2, "MIPS_INS_BTEQZ");
	lua_pushinteger(l, 124);
	lua_setfield(l, -2, "MIPS_INS_BTNEZ");
	lua_pushinteger(l, 125);
	lua_setfield(l, -2, "MIPS_INS_CACHE");
	lua_pushinteger(l, 126);
	lua_setfield(l, -2, "MIPS_INS_CEIL");
	lua_pushinteger(l, 127);
	lua_setfield(l, -2, "MIPS_INS_CEQI");
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "MIPS_INS_CEQ");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "MIPS_INS_CFC1");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "MIPS_INS_CFCMSA");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "MIPS_INS_CINS");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "MIPS_INS_CINS32");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "MIPS_INS_CLASS");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "MIPS_INS_CLEI_S");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "MIPS_INS_CLEI_U");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "MIPS_INS_CLE_S");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "MIPS_INS_CLE_U");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "MIPS_INS_CLO");
	lua_pushinteger(l, 139);
	lua_setfield(l, -2, "MIPS_INS_CLTI_S");
	lua_pushinteger(l, 140);
	lua_setfield(l, -2, "MIPS_INS_CLTI_U");
	lua_pushinteger(l, 141);
	lua_setfield(l, -2, "MIPS_INS_CLT_S");
	lua_pushinteger(l, 142);
	lua_setfield(l, -2, "MIPS_INS_CLT_U");
	lua_pushinteger(l, 143);
	lua_setfield(l, -2, "MIPS_INS_CLZ");
	lua_pushinteger(l, 144);
	lua_setfield(l, -2, "MIPS_INS_CMPGDU");
	lua_pushinteger(l, 145);
	lua_setfield(l, -2, "MIPS_INS_CMPGU");
	lua_pushinteger(l, 146);
	lua_setfield(l, -2, "MIPS_INS_CMPU");
	lua_pushinteger(l, 147);
	lua_setfield(l, -2, "MIPS_INS_CMP");
	lua_pushinteger(l, 148);
	lua_setfield(l, -2, "MIPS_INS_COPY_S");
	lua_pushinteger(l, 149);
	lua_setfield(l, -2, "MIPS_INS_COPY_U");
	lua_pushinteger(l, 150);
	lua_setfield(l, -2, "MIPS_INS_CTC1");
	lua_pushinteger(l, 151);
	lua_setfield(l, -2, "MIPS_INS_CTCMSA");
	lua_pushinteger(l, 152);
	lua_setfield(l, -2, "MIPS_INS_CVT");
	lua_pushinteger(l, 153);
	lua_setfield(l, -2, "MIPS_INS_C");
	lua_pushinteger(l, 154);
	lua_setfield(l, -2, "MIPS_INS_CMPI");
	lua_pushinteger(l, 155);
	lua_setfield(l, -2, "MIPS_INS_DADD");
	lua_pushinteger(l, 156);
	lua_setfield(l, -2, "MIPS_INS_DADDI");
	lua_pushinteger(l, 157);
	lua_setfield(l, -2, "MIPS_INS_DADDIU");
	lua_pushinteger(l, 158);
	lua_setfield(l, -2, "MIPS_INS_DADDU");
	lua_pushinteger(l, 159);
	lua_setfield(l, -2, "MIPS_INS_DAHI");
	lua_pushinteger(l, 160);
	lua_setfield(l, -2, "MIPS_INS_DALIGN");
	lua_pushinteger(l, 161);
	lua_setfield(l, -2, "MIPS_INS_DATI");
	lua_pushinteger(l, 162);
	lua_setfield(l, -2, "MIPS_INS_DAUI");
	lua_pushinteger(l, 163);
	lua_setfield(l, -2, "MIPS_INS_DBITSWAP");
	lua_pushinteger(l, 164);
	lua_setfield(l, -2, "MIPS_INS_DCLO");
	lua_pushinteger(l, 165);
	lua_setfield(l, -2, "MIPS_INS_DCLZ");
	lua_pushinteger(l, 166);
	lua_setfield(l, -2, "MIPS_INS_DDIV");
	lua_pushinteger(l, 167);
	lua_setfield(l, -2, "MIPS_INS_DDIVU");
	lua_pushinteger(l, 168);
	lua_setfield(l, -2, "MIPS_INS_DERET");
	lua_pushinteger(l, 169);
	lua_setfield(l, -2, "MIPS_INS_DEXT");
	lua_pushinteger(l, 170);
	lua_setfield(l, -2, "MIPS_INS_DEXTM");
	lua_pushinteger(l, 171);
	lua_setfield(l, -2, "MIPS_INS_DEXTU");
	lua_pushinteger(l, 172);
	lua_setfield(l, -2, "MIPS_INS_DI");
	lua_pushinteger(l, 173);
	lua_setfield(l, -2, "MIPS_INS_DINS");
	lua_pushinteger(l, 174);
	lua_setfield(l, -2, "MIPS_INS_DINSM");
	lua_pushinteger(l, 175);
	lua_setfield(l, -2, "MIPS_INS_DINSU");
	lua_pushinteger(l, 176);
	lua_setfield(l, -2, "MIPS_INS_DIV");
	lua_pushinteger(l, 177);
	lua_setfield(l, -2, "MIPS_INS_DIVU");
	lua_pushinteger(l, 178);
	lua_setfield(l, -2, "MIPS_INS_DIV_S");
	lua_pushinteger(l, 179);
	lua_setfield(l, -2, "MIPS_INS_DIV_U");
	lua_pushinteger(l, 180);
	lua_setfield(l, -2, "MIPS_INS_DLSA");
	lua_pushinteger(l, 181);
	lua_setfield(l, -2, "MIPS_INS_DMFC0");
	lua_pushinteger(l, 182);
	lua_setfield(l, -2, "MIPS_INS_DMFC1");
	lua_pushinteger(l, 183);
	lua_setfield(l, -2, "MIPS_INS_DMFC2");
	lua_pushinteger(l, 184);
	lua_setfield(l, -2, "MIPS_INS_DMOD");
	lua_pushinteger(l, 185);
	lua_setfield(l, -2, "MIPS_INS_DMODU");
	lua_pushinteger(l, 186);
	lua_setfield(l, -2, "MIPS_INS_DMTC0");
	lua_pushinteger(l, 187);
	lua_setfield(l, -2, "MIPS_INS_DMTC1");
	lua_pushinteger(l, 188);
	lua_setfield(l, -2, "MIPS_INS_DMTC2");
	lua_pushinteger(l, 189);
	lua_setfield(l, -2, "MIPS_INS_DMUH");
	lua_pushinteger(l, 190);
	lua_setfield(l, -2, "MIPS_INS_DMUHU");
	lua_pushinteger(l, 191);
	lua_setfield(l, -2, "MIPS_INS_DMUL");
	lua_pushinteger(l, 192);
	lua_setfield(l, -2, "MIPS_INS_DMULT");
	lua_pushinteger(l, 193);
	lua_setfield(l, -2, "MIPS_INS_DMULTU");
	lua_pushinteger(l, 194);
	lua_setfield(l, -2, "MIPS_INS_DMULU");
	lua_pushinteger(l, 195);
	lua_setfield(l, -2, "MIPS_INS_DOTP_S");
	lua_pushinteger(l, 196);
	lua_setfield(l, -2, "MIPS_INS_DOTP_U");
	lua_pushinteger(l, 197);
	lua_setfield(l, -2, "MIPS_INS_DPADD_S");
	lua_pushinteger(l, 198);
	lua_setfield(l, -2, "MIPS_INS_DPADD_U");
	lua_pushinteger(l, 199);
	lua_setfield(l, -2, "MIPS_INS_DPAQX_SA");
	lua_pushinteger(l, 200);
	lua_setfield(l, -2, "MIPS_INS_DPAQX_S");
	lua_pushinteger(l, 201);
	lua_setfield(l, -2, "MIPS_INS_DPAQ_SA");
	lua_pushinteger(l, 202);
	lua_setfield(l, -2, "MIPS_INS_DPAQ_S");
	lua_pushinteger(l, 203);
	lua_setfield(l, -2, "MIPS_INS_DPAU");
	lua_pushinteger(l, 204);
	lua_setfield(l, -2, "MIPS_INS_DPAX");
	lua_pushinteger(l, 205);
	lua_setfield(l, -2, "MIPS_INS_DPA");
	lua_pushinteger(l, 206);
	lua_setfield(l, -2, "MIPS_INS_DPOP");
	lua_pushinteger(l, 207);
	lua_setfield(l, -2, "MIPS_INS_DPSQX_SA");
	lua_pushinteger(l, 208);
	lua_setfield(l, -2, "MIPS_INS_DPSQX_S");
	lua_pushinteger(l, 209);
	lua_setfield(l, -2, "MIPS_INS_DPSQ_SA");
	lua_pushinteger(l, 210);
	lua_setfield(l, -2, "MIPS_INS_DPSQ_S");
	lua_pushinteger(l, 211);
	lua_setfield(l, -2, "MIPS_INS_DPSUB_S");
	lua_pushinteger(l, 212);
	lua_setfield(l, -2, "MIPS_INS_DPSUB_U");
	lua_pushinteger(l, 213);
	lua_setfield(l, -2, "MIPS_INS_DPSU");
	lua_pushinteger(l, 214);
	lua_setfield(l, -2, "MIPS_INS_DPSX");
	lua_pushinteger(l, 215);
	lua_setfield(l, -2, "MIPS_INS_DPS");
	lua_pushinteger(l, 216);
	lua_setfield(l, -2, "MIPS_INS_DROTR");
	lua_pushinteger(l, 217);
	lua_setfield(l, -2, "MIPS_INS_DROTR32");
	lua_pushinteger(l, 218);
	lua_setfield(l, -2, "MIPS_INS_DROTRV");
	lua_pushinteger(l, 219);
	lua_setfield(l, -2, "MIPS_INS_DSBH");
	lua_pushinteger(l, 220);
	lua_setfield(l, -2, "MIPS_INS_DSHD");
	lua_pushinteger(l, 221);
	lua_setfield(l, -2, "MIPS_INS_DSLL");
	lua_pushinteger(l, 222);
	lua_setfield(l, -2, "MIPS_INS_DSLL32");
	lua_pushinteger(l, 223);
	lua_setfield(l, -2, "MIPS_INS_DSLLV");
	lua_pushinteger(l, 224);
	lua_setfield(l, -2, "MIPS_INS_DSRA");
	lua_pushinteger(l, 225);
	lua_setfield(l, -2, "MIPS_INS_DSRA32");
	lua_pushinteger(l, 226);
	lua_setfield(l, -2, "MIPS_INS_DSRAV");
	lua_pushinteger(l, 227);
	lua_setfield(l, -2, "MIPS_INS_DSRL");
	lua_pushinteger(l, 228);
	lua_setfield(l, -2, "MIPS_INS_DSRL32");
	lua_pushinteger(l, 229);
	lua_setfield(l, -2, "MIPS_INS_DSRLV");
	lua_pushinteger(l, 230);
	lua_setfield(l, -2, "MIPS_INS_DSUB");
	lua_pushinteger(l, 231);
	lua_setfield(l, -2, "MIPS_INS_DSUBU");
	lua_pushinteger(l, 232);
	lua_setfield(l, -2, "MIPS_INS_EHB");
	lua_pushinteger(l, 233);
	lua_setfield(l, -2, "MIPS_INS_EI");
	lua_pushinteger(l, 234);
	lua_setfield(l, -2, "MIPS_INS_ERET");
	lua_pushinteger(l, 235);
	lua_setfield(l, -2, "MIPS_INS_EXT");
	lua_pushinteger(l, 236);
	lua_setfield(l, -2, "MIPS_INS_EXTP");
	lua_pushinteger(l, 237);
	lua_setfield(l, -2, "MIPS_INS_EXTPDP");
	lua_pushinteger(l, 238);
	lua_setfield(l, -2, "MIPS_INS_EXTPDPV");
	lua_pushinteger(l, 239);
	lua_setfield(l, -2, "MIPS_INS_EXTPV");
	lua_pushinteger(l, 240);
	lua_setfield(l, -2, "MIPS_INS_EXTRV_RS");
	lua_pushinteger(l, 241);
	lua_setfield(l, -2, "MIPS_INS_EXTRV_R");
	lua_pushinteger(l, 242);
	lua_setfield(l, -2, "MIPS_INS_EXTRV_S");
	lua_pushinteger(l, 243);
	lua_setfield(l, -2, "MIPS_INS_EXTRV");
	lua_pushinteger(l, 244);
	lua_setfield(l, -2, "MIPS_INS_EXTR_RS");
	lua_pushinteger(l, 245);
	lua_setfield(l, -2, "MIPS_INS_EXTR_R");
	lua_pushinteger(l, 246);
	lua_setfield(l, -2, "MIPS_INS_EXTR_S");
	lua_pushinteger(l, 247);
	lua_setfield(l, -2, "MIPS_INS_EXTR");
	lua_pushinteger(l, 248);
	lua_setfield(l, -2, "MIPS_INS_EXTS");
	lua_pushinteger(l, 249);
	lua_setfield(l, -2, "MIPS_INS_EXTS32");
	lua_pushinteger(l, 250);
	lua_setfield(l, -2, "MIPS_INS_ABS");
	lua_pushinteger(l, 251);
	lua_setfield(l, -2, "MIPS_INS_FADD");
	lua_pushinteger(l, 252);
	lua_setfield(l, -2, "MIPS_INS_FCAF");
	lua_pushinteger(l, 253);
	lua_setfield(l, -2, "MIPS_INS_FCEQ");
	lua_pushinteger(l, 254);
	lua_setfield(l, -2, "MIPS_INS_FCLASS");
	lua_pushinteger(l, 255);
	lua_setfield(l, -2, "MIPS_INS_FCLE");
	lua_pushinteger(l, 256);
	lua_setfield(l, -2, "MIPS_INS_FCLT");
	lua_pushinteger(l, 257);
	lua_setfield(l, -2, "MIPS_INS_FCNE");
	lua_pushinteger(l, 258);
	lua_setfield(l, -2, "MIPS_INS_FCOR");
	lua_pushinteger(l, 259);
	lua_setfield(l, -2, "MIPS_INS_FCUEQ");
	lua_pushinteger(l, 260);
	lua_setfield(l, -2, "MIPS_INS_FCULE");
	lua_pushinteger(l, 261);
	lua_setfield(l, -2, "MIPS_INS_FCULT");
	lua_pushinteger(l, 262);
	lua_setfield(l, -2, "MIPS_INS_FCUNE");
	lua_pushinteger(l, 263);
	lua_setfield(l, -2, "MIPS_INS_FCUN");
	lua_pushinteger(l, 264);
	lua_setfield(l, -2, "MIPS_INS_FDIV");
	lua_pushinteger(l, 265);
	lua_setfield(l, -2, "MIPS_INS_FEXDO");
	lua_pushinteger(l, 266);
	lua_setfield(l, -2, "MIPS_INS_FEXP2");
	lua_pushinteger(l, 267);
	lua_setfield(l, -2, "MIPS_INS_FEXUPL");
	lua_pushinteger(l, 268);
	lua_setfield(l, -2, "MIPS_INS_FEXUPR");
	lua_pushinteger(l, 269);
	lua_setfield(l, -2, "MIPS_INS_FFINT_S");
	lua_pushinteger(l, 270);
	lua_setfield(l, -2, "MIPS_INS_FFINT_U");
	lua_pushinteger(l, 271);
	lua_setfield(l, -2, "MIPS_INS_FFQL");
	lua_pushinteger(l, 272);
	lua_setfield(l, -2, "MIPS_INS_FFQR");
	lua_pushinteger(l, 273);
	lua_setfield(l, -2, "MIPS_INS_FILL");
	lua_pushinteger(l, 274);
	lua_setfield(l, -2, "MIPS_INS_FLOG2");
	lua_pushinteger(l, 275);
	lua_setfield(l, -2, "MIPS_INS_FLOOR");
	lua_pushinteger(l, 276);
	lua_setfield(l, -2, "MIPS_INS_FMADD");
	lua_pushinteger(l, 277);
	lua_setfield(l, -2, "MIPS_INS_FMAX_A");
	lua_pushinteger(l, 278);
	lua_setfield(l, -2, "MIPS_INS_FMAX");
	lua_pushinteger(l, 279);
	lua_setfield(l, -2, "MIPS_INS_FMIN_A");
	lua_pushinteger(l, 280);
	lua_setfield(l, -2, "MIPS_INS_FMIN");
	lua_pushinteger(l, 281);
	lua_setfield(l, -2, "MIPS_INS_MOV");
	lua_pushinteger(l, 282);
	lua_setfield(l, -2, "MIPS_INS_FMSUB");
	lua_pushinteger(l, 283);
	lua_setfield(l, -2, "MIPS_INS_FMUL");
	lua_pushinteger(l, 284);
	lua_setfield(l, -2, "MIPS_INS_MUL");
	lua_pushinteger(l, 285);
	lua_setfield(l, -2, "MIPS_INS_NEG");
	lua_pushinteger(l, 286);
	lua_setfield(l, -2, "MIPS_INS_FRCP");
	lua_pushinteger(l, 287);
	lua_setfield(l, -2, "MIPS_INS_FRINT");
	lua_pushinteger(l, 288);
	lua_setfield(l, -2, "MIPS_INS_FRSQRT");
	lua_pushinteger(l, 289);
	lua_setfield(l, -2, "MIPS_INS_FSAF");
	lua_pushinteger(l, 290);
	lua_setfield(l, -2, "MIPS_INS_FSEQ");
	lua_pushinteger(l, 291);
	lua_setfield(l, -2, "MIPS_INS_FSLE");
	lua_pushinteger(l, 292);
	lua_setfield(l, -2, "MIPS_INS_FSLT");
	lua_pushinteger(l, 293);
	lua_setfield(l, -2, "MIPS_INS_FSNE");
	lua_pushinteger(l, 294);
	lua_setfield(l, -2, "MIPS_INS_FSOR");
	lua_pushinteger(l, 295);
	lua_setfield(l, -2, "MIPS_INS_FSQRT");
	lua_pushinteger(l, 296);
	lua_setfield(l, -2, "MIPS_INS_SQRT");
	lua_pushinteger(l, 297);
	lua_setfield(l, -2, "MIPS_INS_FSUB");
	lua_pushinteger(l, 298);
	lua_setfield(l, -2, "MIPS_INS_SUB");
	lua_pushinteger(l, 299);
	lua_setfield(l, -2, "MIPS_INS_FSUEQ");
	lua_pushinteger(l, 300);
	lua_setfield(l, -2, "MIPS_INS_FSULE");
	lua_pushinteger(l, 301);
	lua_setfield(l, -2, "MIPS_INS_FSULT");
	lua_pushinteger(l, 302);
	lua_setfield(l, -2, "MIPS_INS_FSUNE");
	lua_pushinteger(l, 303);
	lua_setfield(l, -2, "MIPS_INS_FSUN");
	lua_pushinteger(l, 304);
	lua_setfield(l, -2, "MIPS_INS_FTINT_S");
	lua_pushinteger(l, 305);
	lua_setfield(l, -2, "MIPS_INS_FTINT_U");
	lua_pushinteger(l, 306);
	lua_setfield(l, -2, "MIPS_INS_FTQ");
	lua_pushinteger(l, 307);
	lua_setfield(l, -2, "MIPS_INS_FTRUNC_S");
	lua_pushinteger(l, 308);
	lua_setfield(l, -2, "MIPS_INS_FTRUNC_U");
	lua_pushinteger(l, 309);
	lua_setfield(l, -2, "MIPS_INS_HADD_S");
	lua_pushinteger(l, 310);
	lua_setfield(l, -2, "MIPS_INS_HADD_U");
	lua_pushinteger(l, 311);
	lua_setfield(l, -2, "MIPS_INS_HSUB_S");
	lua_pushinteger(l, 312);
	lua_setfield(l, -2, "MIPS_INS_HSUB_U");
	lua_pushinteger(l, 313);
	lua_setfield(l, -2, "MIPS_INS_ILVEV");
	lua_pushinteger(l, 314);
	lua_setfield(l, -2, "MIPS_INS_ILVL");
	lua_pushinteger(l, 315);
	lua_setfield(l, -2, "MIPS_INS_ILVOD");
	lua_pushinteger(l, 316);
	lua_setfield(l, -2, "MIPS_INS_ILVR");
	lua_pushinteger(l, 317);
	lua_setfield(l, -2, "MIPS_INS_INS");
	lua_pushinteger(l, 318);
	lua_setfield(l, -2, "MIPS_INS_INSERT");
	lua_pushinteger(l, 319);
	lua_setfield(l, -2, "MIPS_INS_INSV");
	lua_pushinteger(l, 320);
	lua_setfield(l, -2, "MIPS_INS_INSVE");
	lua_pushinteger(l, 321);
	lua_setfield(l, -2, "MIPS_INS_J");
	lua_pushinteger(l, 322);
	lua_setfield(l, -2, "MIPS_INS_JAL");
	lua_pushinteger(l, 323);
	lua_setfield(l, -2, "MIPS_INS_JALR");
	lua_pushinteger(l, 324);
	lua_setfield(l, -2, "MIPS_INS_JALRS");
	lua_pushinteger(l, 325);
	lua_setfield(l, -2, "MIPS_INS_JALS");
	lua_pushinteger(l, 326);
	lua_setfield(l, -2, "MIPS_INS_JALX");
	lua_pushinteger(l, 327);
	lua_setfield(l, -2, "MIPS_INS_JIALC");
	lua_pushinteger(l, 328);
	lua_setfield(l, -2, "MIPS_INS_JIC");
	lua_pushinteger(l, 329);
	lua_setfield(l, -2, "MIPS_INS_JR");
	lua_pushinteger(l, 330);
	lua_setfield(l, -2, "MIPS_INS_JRADDIUSP");
	lua_pushinteger(l, 331);
	lua_setfield(l, -2, "MIPS_INS_JRC");
	lua_pushinteger(l, 332);
	lua_setfield(l, -2, "MIPS_INS_JALRC");
	lua_pushinteger(l, 333);
	lua_setfield(l, -2, "MIPS_INS_LB");
	lua_pushinteger(l, 334);
	lua_setfield(l, -2, "MIPS_INS_LBUX");
	lua_pushinteger(l, 335);
	lua_setfield(l, -2, "MIPS_INS_LBU");
	lua_pushinteger(l, 336);
	lua_setfield(l, -2, "MIPS_INS_LD");
	lua_pushinteger(l, 337);
	lua_setfield(l, -2, "MIPS_INS_LDC1");
	lua_pushinteger(l, 338);
	lua_setfield(l, -2, "MIPS_INS_LDC2");
	lua_pushinteger(l, 339);
	lua_setfield(l, -2, "MIPS_INS_LDC3");
	lua_pushinteger(l, 340);
	lua_setfield(l, -2, "MIPS_INS_LDI");
	lua_pushinteger(l, 341);
	lua_setfield(l, -2, "MIPS_INS_LDL");
	lua_pushinteger(l, 342);
	lua_setfield(l, -2, "MIPS_INS_LDPC");
	lua_pushinteger(l, 343);
	lua_setfield(l, -2, "MIPS_INS_LDR");
	lua_pushinteger(l, 344);
	lua_setfield(l, -2, "MIPS_INS_LDXC1");
	lua_pushinteger(l, 345);
	lua_setfield(l, -2, "MIPS_INS_LH");
	lua_pushinteger(l, 346);
	lua_setfield(l, -2, "MIPS_INS_LHX");
	lua_pushinteger(l, 347);
	lua_setfield(l, -2, "MIPS_INS_LHU");
	lua_pushinteger(l, 348);
	lua_setfield(l, -2, "MIPS_INS_LL");
	lua_pushinteger(l, 349);
	lua_setfield(l, -2, "MIPS_INS_LLD");
	lua_pushinteger(l, 350);
	lua_setfield(l, -2, "MIPS_INS_LSA");
	lua_pushinteger(l, 351);
	lua_setfield(l, -2, "MIPS_INS_LUXC1");
	lua_pushinteger(l, 352);
	lua_setfield(l, -2, "MIPS_INS_LUI");
	lua_pushinteger(l, 353);
	lua_setfield(l, -2, "MIPS_INS_LW");
	lua_pushinteger(l, 354);
	lua_setfield(l, -2, "MIPS_INS_LWC1");
	lua_pushinteger(l, 355);
	lua_setfield(l, -2, "MIPS_INS_LWC2");
	lua_pushinteger(l, 356);
	lua_setfield(l, -2, "MIPS_INS_LWC3");
	lua_pushinteger(l, 357);
	lua_setfield(l, -2, "MIPS_INS_LWL");
	lua_pushinteger(l, 358);
	lua_setfield(l, -2, "MIPS_INS_LWPC");
	lua_pushinteger(l, 359);
	lua_setfield(l, -2, "MIPS_INS_LWR");
	lua_pushinteger(l, 360);
	lua_setfield(l, -2, "MIPS_INS_LWUPC");
	lua_pushinteger(l, 361);
	lua_setfield(l, -2, "MIPS_INS_LWU");
	lua_pushinteger(l, 362);
	lua_setfield(l, -2, "MIPS_INS_LWX");
	lua_pushinteger(l, 363);
	lua_setfield(l, -2, "MIPS_INS_LWXC1");
	lua_pushinteger(l, 364);
	lua_setfield(l, -2, "MIPS_INS_LI");
	lua_pushinteger(l, 365);
	lua_setfield(l, -2, "MIPS_INS_MADD");
	lua_pushinteger(l, 366);
	lua_setfield(l, -2, "MIPS_INS_MADDF");
	lua_pushinteger(l, 367);
	lua_setfield(l, -2, "MIPS_INS_MADDR_Q");
	lua_pushinteger(l, 368);
	lua_setfield(l, -2, "MIPS_INS_MADDU");
	lua_pushinteger(l, 369);
	lua_setfield(l, -2, "MIPS_INS_MADDV");
	lua_pushinteger(l, 370);
	lua_setfield(l, -2, "MIPS_INS_MADD_Q");
	lua_pushinteger(l, 371);
	lua_setfield(l, -2, "MIPS_INS_MAQ_SA");
	lua_pushinteger(l, 372);
	lua_setfield(l, -2, "MIPS_INS_MAQ_S");
	lua_pushinteger(l, 373);
	lua_setfield(l, -2, "MIPS_INS_MAXA");
	lua_pushinteger(l, 374);
	lua_setfield(l, -2, "MIPS_INS_MAXI_S");
	lua_pushinteger(l, 375);
	lua_setfield(l, -2, "MIPS_INS_MAXI_U");
	lua_pushinteger(l, 376);
	lua_setfield(l, -2, "MIPS_INS_MAX_A");
	lua_pushinteger(l, 377);
	lua_setfield(l, -2, "MIPS_INS_MAX");
	lua_pushinteger(l, 378);
	lua_setfield(l, -2, "MIPS_INS_MAX_S");
	lua_pushinteger(l, 379);
	lua_setfield(l, -2, "MIPS_INS_MAX_U");
	lua_pushinteger(l, 380);
	lua_setfield(l, -2, "MIPS_INS_MFC0");
	lua_pushinteger(l, 381);
	lua_setfield(l, -2, "MIPS_INS_MFC1");
	lua_pushinteger(l, 382);
	lua_setfield(l, -2, "MIPS_INS_MFC2");
	lua_pushinteger(l, 383);
	lua_setfield(l, -2, "MIPS_INS_MFHC1");
	lua_pushinteger(l, 384);
	lua_setfield(l, -2, "MIPS_INS_MFHI");
	lua_pushinteger(l, 385);
	lua_setfield(l, -2, "MIPS_INS_MFLO");
	lua_pushinteger(l, 386);
	lua_setfield(l, -2, "MIPS_INS_MINA");
	lua_pushinteger(l, 387);
	lua_setfield(l, -2, "MIPS_INS_MINI_S");
	lua_pushinteger(l, 388);
	lua_setfield(l, -2, "MIPS_INS_MINI_U");
	lua_pushinteger(l, 389);
	lua_setfield(l, -2, "MIPS_INS_MIN_A");
	lua_pushinteger(l, 390);
	lua_setfield(l, -2, "MIPS_INS_MIN");
	lua_pushinteger(l, 391);
	lua_setfield(l, -2, "MIPS_INS_MIN_S");
	lua_pushinteger(l, 392);
	lua_setfield(l, -2, "MIPS_INS_MIN_U");
	lua_pushinteger(l, 393);
	lua_setfield(l, -2, "MIPS_INS_MOD");
	lua_pushinteger(l, 394);
	lua_setfield(l, -2, "MIPS_INS_MODSUB");
	lua_pushinteger(l, 395);
	lua_setfield(l, -2, "MIPS_INS_MODU");
	lua_pushinteger(l, 396);
	lua_setfield(l, -2, "MIPS_INS_MOD_S");
	lua_pushinteger(l, 397);
	lua_setfield(l, -2, "MIPS_INS_MOD_U");
	lua_pushinteger(l, 398);
	lua_setfield(l, -2, "MIPS_INS_MOVE");
	lua_pushinteger(l, 399);
	lua_setfield(l, -2, "MIPS_INS_MOVF");
	lua_pushinteger(l, 400);
	lua_setfield(l, -2, "MIPS_INS_MOVN");
	lua_pushinteger(l, 401);
	lua_setfield(l, -2, "MIPS_INS_MOVT");
	lua_pushinteger(l, 402);
	lua_setfield(l, -2, "MIPS_INS_MOVZ");
	lua_pushinteger(l, 403);
	lua_setfield(l, -2, "MIPS_INS_MSUB");
	lua_pushinteger(l, 404);
	lua_setfield(l, -2, "MIPS_INS_MSUBF");
	lua_pushinteger(l, 405);
	lua_setfield(l, -2, "MIPS_INS_MSUBR_Q");
	lua_pushinteger(l, 406);
	lua_setfield(l, -2, "MIPS_INS_MSUBU");
	lua_pushinteger(l, 407);
	lua_setfield(l, -2, "MIPS_INS_MSUBV");
	lua_pushinteger(l, 408);
	lua_setfield(l, -2, "MIPS_INS_MSUB_Q");
	lua_pushinteger(l, 409);
	lua_setfield(l, -2, "MIPS_INS_MTC0");
	lua_pushinteger(l, 410);
	lua_setfield(l, -2, "MIPS_INS_MTC1");
	lua_pushinteger(l, 411);
	lua_setfield(l, -2, "MIPS_INS_MTC2");
	lua_pushinteger(l, 412);
	lua_setfield(l, -2, "MIPS_INS_MTHC1");
	lua_pushinteger(l, 413);
	lua_setfield(l, -2, "MIPS_INS_MTHI");
	lua_pushinteger(l, 414);
	lua_setfield(l, -2, "MIPS_INS_MTHLIP");
	lua_pushinteger(l, 415);
	lua_setfield(l, -2, "MIPS_INS_MTLO");
	lua_pushinteger(l, 416);
	lua_setfield(l, -2, "MIPS_INS_MTM0");
	lua_pushinteger(l, 417);
	lua_setfield(l, -2, "MIPS_INS_MTM1");
	lua_pushinteger(l, 418);
	lua_setfield(l, -2, "MIPS_INS_MTM2");
	lua_pushinteger(l, 419);
	lua_setfield(l, -2, "MIPS_INS_MTP0");
	lua_pushinteger(l, 420);
	lua_setfield(l, -2, "MIPS_INS_MTP1");
	lua_pushinteger(l, 421);
	lua_setfield(l, -2, "MIPS_INS_MTP2");
	lua_pushinteger(l, 422);
	lua_setfield(l, -2, "MIPS_INS_MUH");
	lua_pushinteger(l, 423);
	lua_setfield(l, -2, "MIPS_INS_MUHU");
	lua_pushinteger(l, 424);
	lua_setfield(l, -2, "MIPS_INS_MULEQ_S");
	lua_pushinteger(l, 425);
	lua_setfield(l, -2, "MIPS_INS_MULEU_S");
	lua_pushinteger(l, 426);
	lua_setfield(l, -2, "MIPS_INS_MULQ_RS");
	lua_pushinteger(l, 427);
	lua_setfield(l, -2, "MIPS_INS_MULQ_S");
	lua_pushinteger(l, 428);
	lua_setfield(l, -2, "MIPS_INS_MULR_Q");
	lua_pushinteger(l, 429);
	lua_setfield(l, -2, "MIPS_INS_MULSAQ_S");
	lua_pushinteger(l, 430);
	lua_setfield(l, -2, "MIPS_INS_MULSA");
	lua_pushinteger(l, 431);
	lua_setfield(l, -2, "MIPS_INS_MULT");
	lua_pushinteger(l, 432);
	lua_setfield(l, -2, "MIPS_INS_MULTU");
	lua_pushinteger(l, 433);
	lua_setfield(l, -2, "MIPS_INS_MULU");
	lua_pushinteger(l, 434);
	lua_setfield(l, -2, "MIPS_INS_MULV");
	lua_pushinteger(l, 435);
	lua_setfield(l, -2, "MIPS_INS_MUL_Q");
	lua_pushinteger(l, 436);
	lua_setfield(l, -2, "MIPS_INS_MUL_S");
	lua_pushinteger(l, 437);
	lua_setfield(l, -2, "MIPS_INS_NLOC");
	lua_pushinteger(l, 438);
	lua_setfield(l, -2, "MIPS_INS_NLZC");
	lua_pushinteger(l, 439);
	lua_setfield(l, -2, "MIPS_INS_NMADD");
	lua_pushinteger(l, 440);
	lua_setfield(l, -2, "MIPS_INS_NMSUB");
	lua_pushinteger(l, 441);
	lua_setfield(l, -2, "MIPS_INS_NOR");
	lua_pushinteger(l, 442);
	lua_setfield(l, -2, "MIPS_INS_NORI");
	lua_pushinteger(l, 443);
	lua_setfield(l, -2, "MIPS_INS_NOT");
	lua_pushinteger(l, 444);
	lua_setfield(l, -2, "MIPS_INS_OR");
	lua_pushinteger(l, 445);
	lua_setfield(l, -2, "MIPS_INS_ORI");
	lua_pushinteger(l, 446);
	lua_setfield(l, -2, "MIPS_INS_PACKRL");
	lua_pushinteger(l, 447);
	lua_setfield(l, -2, "MIPS_INS_PAUSE");
	lua_pushinteger(l, 448);
	lua_setfield(l, -2, "MIPS_INS_PCKEV");
	lua_pushinteger(l, 449);
	lua_setfield(l, -2, "MIPS_INS_PCKOD");
	lua_pushinteger(l, 450);
	lua_setfield(l, -2, "MIPS_INS_PCNT");
	lua_pushinteger(l, 451);
	lua_setfield(l, -2, "MIPS_INS_PICK");
	lua_pushinteger(l, 452);
	lua_setfield(l, -2, "MIPS_INS_POP");
	lua_pushinteger(l, 453);
	lua_setfield(l, -2, "MIPS_INS_PRECEQU");
	lua_pushinteger(l, 454);
	lua_setfield(l, -2, "MIPS_INS_PRECEQ");
	lua_pushinteger(l, 455);
	lua_setfield(l, -2, "MIPS_INS_PRECEU");
	lua_pushinteger(l, 456);
	lua_setfield(l, -2, "MIPS_INS_PRECRQU_S");
	lua_pushinteger(l, 457);
	lua_setfield(l, -2, "MIPS_INS_PRECRQ");
	lua_pushinteger(l, 458);
	lua_setfield(l, -2, "MIPS_INS_PRECRQ_RS");
	lua_pushinteger(l, 459);
	lua_setfield(l, -2, "MIPS_INS_PRECR");
	lua_pushinteger(l, 460);
	lua_setfield(l, -2, "MIPS_INS_PRECR_SRA");
	lua_pushinteger(l, 461);
	lua_setfield(l, -2, "MIPS_INS_PRECR_SRA_R");
	lua_pushinteger(l, 462);
	lua_setfield(l, -2, "MIPS_INS_PREF");
	lua_pushinteger(l, 463);
	lua_setfield(l, -2, "MIPS_INS_PREPEND");
	lua_pushinteger(l, 464);
	lua_setfield(l, -2, "MIPS_INS_RADDU");
	lua_pushinteger(l, 465);
	lua_setfield(l, -2, "MIPS_INS_RDDSP");
	lua_pushinteger(l, 466);
	lua_setfield(l, -2, "MIPS_INS_RDHWR");
	lua_pushinteger(l, 467);
	lua_setfield(l, -2, "MIPS_INS_REPLV");
	lua_pushinteger(l, 468);
	lua_setfield(l, -2, "MIPS_INS_REPL");
	lua_pushinteger(l, 469);
	lua_setfield(l, -2, "MIPS_INS_RINT");
	lua_pushinteger(l, 470);
	lua_setfield(l, -2, "MIPS_INS_ROTR");
	lua_pushinteger(l, 471);
	lua_setfield(l, -2, "MIPS_INS_ROTRV");
	lua_pushinteger(l, 472);
	lua_setfield(l, -2, "MIPS_INS_ROUND");
	lua_pushinteger(l, 473);
	lua_setfield(l, -2, "MIPS_INS_SAT_S");
	lua_pushinteger(l, 474);
	lua_setfield(l, -2, "MIPS_INS_SAT_U");
	lua_pushinteger(l, 475);
	lua_setfield(l, -2, "MIPS_INS_SB");
	lua_pushinteger(l, 476);
	lua_setfield(l, -2, "MIPS_INS_SC");
	lua_pushinteger(l, 477);
	lua_setfield(l, -2, "MIPS_INS_SCD");
	lua_pushinteger(l, 478);
	lua_setfield(l, -2, "MIPS_INS_SD");
	lua_pushinteger(l, 479);
	lua_setfield(l, -2, "MIPS_INS_SDBBP");
	lua_pushinteger(l, 480);
	lua_setfield(l, -2, "MIPS_INS_SDC1");
	lua_pushinteger(l, 481);
	lua_setfield(l, -2, "MIPS_INS_SDC2");
	lua_pushinteger(l, 482);
	lua_setfield(l, -2, "MIPS_INS_SDC3");
	lua_pushinteger(l, 483);
	lua_setfield(l, -2, "MIPS_INS_SDL");
	lua_pushinteger(l, 484);
	lua_setfield(l, -2, "MIPS_INS_SDR");
	lua_pushinteger(l, 485);
	lua_setfield(l, -2, "MIPS_INS_SDXC1");
	lua_pushinteger(l, 486);
	lua_setfield(l, -2, "MIPS_INS_SEB");
	lua_pushinteger(l, 487);
	lua_setfield(l, -2, "MIPS_INS_SEH");
	lua_pushinteger(l, 488);
	lua_setfield(l, -2, "MIPS_INS_SELEQZ");
	lua_pushinteger(l, 489);
	lua_setfield(l, -2, "MIPS_INS_SELNEZ");
	lua_pushinteger(l, 490);
	lua_setfield(l, -2, "MIPS_INS_SEL");
	lua_pushinteger(l, 491);
	lua_setfield(l, -2, "MIPS_INS_SEQ");
	lua_pushinteger(l, 492);
	lua_setfield(l, -2, "MIPS_INS_SEQI");
	lua_pushinteger(l, 493);
	lua_setfield(l, -2, "MIPS_INS_SH");
	lua_pushinteger(l, 494);
	lua_setfield(l, -2, "MIPS_INS_SHF");
	lua_pushinteger(l, 495);
	lua_setfield(l, -2, "MIPS_INS_SHILO");
	lua_pushinteger(l, 496);
	lua_setfield(l, -2, "MIPS_INS_SHILOV");
	lua_pushinteger(l, 497);
	lua_setfield(l, -2, "MIPS_INS_SHLLV");
	lua_pushinteger(l, 498);
	lua_setfield(l, -2, "MIPS_INS_SHLLV_S");
	lua_pushinteger(l, 499);
	lua_setfield(l, -2, "MIPS_INS_SHLL");
	lua_pushinteger(l, 500);
	lua_setfield(l, -2, "MIPS_INS_SHLL_S");
	lua_pushinteger(l, 501);
	lua_setfield(l, -2, "MIPS_INS_SHRAV");
	lua_pushinteger(l, 502);
	lua_setfield(l, -2, "MIPS_INS_SHRAV_R");
	lua_pushinteger(l, 503);
	lua_setfield(l, -2, "MIPS_INS_SHRA");
	lua_pushinteger(l, 504);
	lua_setfield(l, -2, "MIPS_INS_SHRA_R");
	lua_pushinteger(l, 505);
	lua_setfield(l, -2, "MIPS_INS_SHRLV");
	lua_pushinteger(l, 506);
	lua_setfield(l, -2, "MIPS_INS_SHRL");
	lua_pushinteger(l, 507);
	lua_setfield(l, -2, "MIPS_INS_SLDI");
	lua_pushinteger(l, 508);
	lua_setfield(l, -2, "MIPS_INS_SLD");
	lua_pushinteger(l, 509);
	lua_setfield(l, -2, "MIPS_INS_SLL");
	lua_pushinteger(l, 510);
	lua_setfield(l, -2, "MIPS_INS_SLLI");
	lua_pushinteger(l, 511);
	lua_setfield(l, -2, "MIPS_INS_SLLV");
	lua_pushinteger(l, 512);
	lua_setfield(l, -2, "MIPS_INS_SLT");
	lua_pushinteger(l, 513);
	lua_setfield(l, -2, "MIPS_INS_SLTI");
	lua_pushinteger(l, 514);
	lua_setfield(l, -2, "MIPS_INS_SLTIU");
	lua_pushinteger(l, 515);
	lua_setfield(l, -2, "MIPS_INS_SLTU");
	lua_pushinteger(l, 516);
	lua_setfield(l, -2, "MIPS_INS_SNE");
	lua_pushinteger(l, 517);
	lua_setfield(l, -2, "MIPS_INS_SNEI");
	lua_pushinteger(l, 518);
	lua_setfield(l, -2, "MIPS_INS_SPLATI");
	lua_pushinteger(l, 519);
	lua_setfield(l, -2, "MIPS_INS_SPLAT");
	lua_pushinteger(l, 520);
	lua_setfield(l, -2, "MIPS_INS_SRA");
	lua_pushinteger(l, 521);
	lua_setfield(l, -2, "MIPS_INS_SRAI");
	lua_pushinteger(l, 522);
	lua_setfield(l, -2, "MIPS_INS_SRARI");
	lua_pushinteger(l, 523);
	lua_setfield(l, -2, "MIPS_INS_SRAR");
	lua_pushinteger(l, 524);
	lua_setfield(l, -2, "MIPS_INS_SRAV");
	lua_pushinteger(l, 525);
	lua_setfield(l, -2, "MIPS_INS_SRL");
	lua_pushinteger(l, 526);
	lua_setfield(l, -2, "MIPS_INS_SRLI");
	lua_pushinteger(l, 527);
	lua_setfield(l, -2, "MIPS_INS_SRLRI");
	lua_pushinteger(l, 528);
	lua_setfield(l, -2, "MIPS_INS_SRLR");
	lua_pushinteger(l, 529);
	lua_setfield(l, -2, "MIPS_INS_SRLV");
	lua_pushinteger(l, 530);
	lua_setfield(l, -2, "MIPS_INS_SSNOP");
	lua_pushinteger(l, 531);
	lua_setfield(l, -2, "MIPS_INS_ST");
	lua_pushinteger(l, 532);
	lua_setfield(l, -2, "MIPS_INS_SUBQH");
	lua_pushinteger(l, 533);
	lua_setfield(l, -2, "MIPS_INS_SUBQH_R");
	lua_pushinteger(l, 534);
	lua_setfield(l, -2, "MIPS_INS_SUBQ");
	lua_pushinteger(l, 535);
	lua_setfield(l, -2, "MIPS_INS_SUBQ_S");
	lua_pushinteger(l, 536);
	lua_setfield(l, -2, "MIPS_INS_SUBSUS_U");
	lua_pushinteger(l, 537);
	lua_setfield(l, -2, "MIPS_INS_SUBSUU_S");
	lua_pushinteger(l, 538);
	lua_setfield(l, -2, "MIPS_INS_SUBS_S");
	lua_pushinteger(l, 539);
	lua_setfield(l, -2, "MIPS_INS_SUBS_U");
	lua_pushinteger(l, 540);
	lua_setfield(l, -2, "MIPS_INS_SUBUH");
	lua_pushinteger(l, 541);
	lua_setfield(l, -2, "MIPS_INS_SUBUH_R");
	lua_pushinteger(l, 542);
	lua_setfield(l, -2, "MIPS_INS_SUBU");
	lua_pushinteger(l, 543);
	lua_setfield(l, -2, "MIPS_INS_SUBU_S");
	lua_pushinteger(l, 544);
	lua_setfield(l, -2, "MIPS_INS_SUBVI");
	lua_pushinteger(l, 545);
	lua_setfield(l, -2, "MIPS_INS_SUBV");
	lua_pushinteger(l, 546);
	lua_setfield(l, -2, "MIPS_INS_SUXC1");
	lua_pushinteger(l, 547);
	lua_setfield(l, -2, "MIPS_INS_SW");
	lua_pushinteger(l, 548);
	lua_setfield(l, -2, "MIPS_INS_SWC1");
	lua_pushinteger(l, 549);
	lua_setfield(l, -2, "MIPS_INS_SWC2");
	lua_pushinteger(l, 550);
	lua_setfield(l, -2, "MIPS_INS_SWC3");
	lua_pushinteger(l, 551);
	lua_setfield(l, -2, "MIPS_INS_SWL");
	lua_pushinteger(l, 552);
	lua_setfield(l, -2, "MIPS_INS_SWR");
	lua_pushinteger(l, 553);
	lua_setfield(l, -2, "MIPS_INS_SWXC1");
	lua_pushinteger(l, 554);
	lua_setfield(l, -2, "MIPS_INS_SYNC");
	lua_pushinteger(l, 555);
	lua_setfield(l, -2, "MIPS_INS_SYSCALL");
	lua_pushinteger(l, 556);
	lua_setfield(l, -2, "MIPS_INS_TEQ");
	lua_pushinteger(l, 557);
	lua_setfield(l, -2, "MIPS_INS_TEQI");
	lua_pushinteger(l, 558);
	lua_setfield(l, -2, "MIPS_INS_TGE");
	lua_pushinteger(l, 559);
	lua_setfield(l, -2, "MIPS_INS_TGEI");
	lua_pushinteger(l, 560);
	lua_setfield(l, -2, "MIPS_INS_TGEIU");
	lua_pushinteger(l, 561);
	lua_setfield(l, -2, "MIPS_INS_TGEU");
	lua_pushinteger(l, 562);
	lua_setfield(l, -2, "MIPS_INS_TLBP");
	lua_pushinteger(l, 563);
	lua_setfield(l, -2, "MIPS_INS_TLBR");
	lua_pushinteger(l, 564);
	lua_setfield(l, -2, "MIPS_INS_TLBWI");
	lua_pushinteger(l, 565);
	lua_setfield(l, -2, "MIPS_INS_TLBWR");
	lua_pushinteger(l, 566);
	lua_setfield(l, -2, "MIPS_INS_TLT");
	lua_pushinteger(l, 567);
	lua_setfield(l, -2, "MIPS_INS_TLTI");
	lua_pushinteger(l, 568);
	lua_setfield(l, -2, "MIPS_INS_TLTIU");
	lua_pushinteger(l, 569);
	lua_setfield(l, -2, "MIPS_INS_TLTU");
	lua_pushinteger(l, 570);
	lua_setfield(l, -2, "MIPS_INS_TNE");
	lua_pushinteger(l, 571);
	lua_setfield(l, -2, "MIPS_INS_TNEI");
	lua_pushinteger(l, 572);
	lua_setfield(l, -2, "MIPS_INS_TRUNC");
	lua_pushinteger(l, 573);
	lua_setfield(l, -2, "MIPS_INS_V3MULU");
	lua_pushinteger(l, 574);
	lua_setfield(l, -2, "MIPS_INS_VMM0");
	lua_pushinteger(l, 575);
	lua_setfield(l, -2, "MIPS_INS_VMULU");
	lua_pushinteger(l, 576);
	lua_setfield(l, -2, "MIPS_INS_VSHF");
	lua_pushinteger(l, 577);
	lua_setfield(l, -2, "MIPS_INS_WAIT");
	lua_pushinteger(l, 578);
	lua_setfield(l, -2, "MIPS_INS_WRDSP");
	lua_pushinteger(l, 579);
	lua_setfield(l, -2, "MIPS_INS_WSBH");
	lua_pushinteger(l, 580);
	lua_setfield(l, -2, "MIPS_INS_XOR");
	lua_pushinteger(l, 581);
	lua_setfield(l, -2, "MIPS_INS_XORI");

	/* some alias instructions */
	lua_pushinteger(l, 582);
	lua_setfield(l, -2, "MIPS_INS_NOP");
	lua_pushinteger(l, 583);
	lua_setfield(l, -2, "MIPS_INS_NEGU");

	/* special instructions */
	lua_pushinteger(l, 584);
	lua_setfield(l, -2, "MIPS_INS_JALR_HB");
	lua_pushinteger(l, 585);
	lua_setfield(l, -2, "MIPS_INS_JR_HB");
	lua_pushinteger(l, 586);
	lua_setfield(l, -2, "MIPS_INS_ENDING");

	/* Group of MIPS instructions */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "MIPS_GRP_INVALID");

	/* Generic groups */
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "MIPS_GRP_JUMP");

	/* Architecture-specific groups */
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "MIPS_GRP_BITCOUNT");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "MIPS_GRP_DSP");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "MIPS_GRP_DSPR2");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "MIPS_GRP_FPIDX");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "MIPS_GRP_MSA");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "MIPS_GRP_MIPS32R2");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "MIPS_GRP_MIPS64");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "MIPS_GRP_MIPS64R2");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "MIPS_GRP_SEINREG");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "MIPS_GRP_STDENC");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "MIPS_GRP_SWAP");
	lua_pushinteger(l, 139);
	lua_setfield(l, -2, "MIPS_GRP_MICROMIPS");
	lua_pushinteger(l, 140);
	lua_setfield(l, -2, "MIPS_GRP_MIPS16MODE");
	lua_pushinteger(l, 141);
	lua_setfield(l, -2, "MIPS_GRP_FP64BIT");
	lua_pushinteger(l, 142);
	lua_setfield(l, -2, "MIPS_GRP_NONANSFPMATH");
	lua_pushinteger(l, 143);
	lua_setfield(l, -2, "MIPS_GRP_NOTFP64BIT");
	lua_pushinteger(l, 144);
	lua_setfield(l, -2, "MIPS_GRP_NOTINMICROMIPS");
	lua_pushinteger(l, 145);
	lua_setfield(l, -2, "MIPS_GRP_NOTNACL");
	lua_pushinteger(l, 146);
	lua_setfield(l, -2, "MIPS_GRP_NOTMIPS32R6");
	lua_pushinteger(l, 147);
	lua_setfield(l, -2, "MIPS_GRP_NOTMIPS64R6");
	lua_pushinteger(l, 148);
	lua_setfield(l, -2, "MIPS_GRP_CNMIPS");
	lua_pushinteger(l, 149);
	lua_setfield(l, -2, "MIPS_GRP_MIPS32");
	lua_pushinteger(l, 150);
	lua_setfield(l, -2, "MIPS_GRP_MIPS32R6");
	lua_pushinteger(l, 151);
	lua_setfield(l, -2, "MIPS_GRP_MIPS64R6");
	lua_pushinteger(l, 152);
	lua_setfield(l, -2, "MIPS_GRP_MIPS2");
	lua_pushinteger(l, 153);
	lua_setfield(l, -2, "MIPS_GRP_MIPS3");
	lua_pushinteger(l, 154);
	lua_setfield(l, -2, "MIPS_GRP_MIPS3_32");
	lua_pushinteger(l, 155);
	lua_setfield(l, -2, "MIPS_GRP_MIPS3_32R2");
	lua_pushinteger(l, 156);
	lua_setfield(l, -2, "MIPS_GRP_MIPS4_32");
	lua_pushinteger(l, 157);
	lua_setfield(l, -2, "MIPS_GRP_MIPS4_32R2");
	lua_pushinteger(l, 158);
	lua_setfield(l, -2, "MIPS_GRP_MIPS5_32R2");
	lua_pushinteger(l, 159);
	lua_setfield(l, -2, "MIPS_GRP_GP32BIT");
	lua_pushinteger(l, 160);
	lua_setfield(l, -2, "MIPS_GRP_GP64BIT");
	lua_pushinteger(l, 161);
	lua_setfield(l, -2, "MIPS_GRP_ENDING");
}