/* For Capstone Engine. AUTO-GENERATED FILE, DO NOT EDIT */

#include "ppc_const.h"

void set_ppc_const(lua_State* l)
{
	/* PPC branch codes for some branch instructions */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "PPC_BC_INVALID");
	lua_pushinteger(l, (0<<5)|12);
	lua_setfield(l, -2, "PPC_BC_LT");
	lua_pushinteger(l, (1<<5)|4);
	lua_setfield(l, -2, "PPC_BC_LE");
	lua_pushinteger(l, (2<<5)|12);
	lua_setfield(l, -2, "PPC_BC_EQ");
	lua_pushinteger(l, (0<<5)|4);
	lua_setfield(l, -2, "PPC_BC_GE");
	lua_pushinteger(l, (1<<5)|12);
	lua_setfield(l, -2, "PPC_BC_GT");
	lua_pushinteger(l, (2<<5)|4);
	lua_setfield(l, -2, "PPC_BC_NE");
	lua_pushinteger(l, (3<<5)|12);
	lua_setfield(l, -2, "PPC_BC_UN");
	lua_pushinteger(l, (3<<5)|4);
	lua_setfield(l, -2, "PPC_BC_NU");
	lua_pushinteger(l, (4<<5)|12);
	lua_setfield(l, -2, "PPC_BC_SO");
	lua_pushinteger(l, (4<<5)|4);
	lua_setfield(l, -2, "PPC_BC_NS");

	/* PPC branch hint for some branch instructions */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "PPC_BH_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "PPC_BH_PLUS");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "PPC_BH_MINUS");

	/* Operand type for instruction's operands */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "PPC_OP_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "PPC_OP_REG");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "PPC_OP_IMM");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "PPC_OP_MEM");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "PPC_OP_CRX");

	/* PPC registers */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "PPC_REG_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "PPC_REG_CARRY");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "PPC_REG_CC");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "PPC_REG_CR0");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "PPC_REG_CR1");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "PPC_REG_CR2");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "PPC_REG_CR3");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "PPC_REG_CR4");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "PPC_REG_CR5");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "PPC_REG_CR6");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "PPC_REG_CR7");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "PPC_REG_CTR");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "PPC_REG_F0");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "PPC_REG_F1");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "PPC_REG_F2");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "PPC_REG_F3");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "PPC_REG_F4");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "PPC_REG_F5");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "PPC_REG_F6");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "PPC_REG_F7");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "PPC_REG_F8");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "PPC_REG_F9");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "PPC_REG_F10");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "PPC_REG_F11");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "PPC_REG_F12");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "PPC_REG_F13");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "PPC_REG_F14");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "PPC_REG_F15");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "PPC_REG_F16");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "PPC_REG_F17");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "PPC_REG_F18");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "PPC_REG_F19");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "PPC_REG_F20");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "PPC_REG_F21");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "PPC_REG_F22");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "PPC_REG_F23");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "PPC_REG_F24");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "PPC_REG_F25");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "PPC_REG_F26");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "PPC_REG_F27");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "PPC_REG_F28");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "PPC_REG_F29");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "PPC_REG_F30");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "PPC_REG_F31");
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "PPC_REG_LR");
	lua_pushinteger(l, 45);
	lua_setfield(l, -2, "PPC_REG_R0");
	lua_pushinteger(l, 46);
	lua_setfield(l, -2, "PPC_REG_R1");
	lua_pushinteger(l, 47);
	lua_setfield(l, -2, "PPC_REG_R2");
	lua_pushinteger(l, 48);
	lua_setfield(l, -2, "PPC_REG_R3");
	lua_pushinteger(l, 49);
	lua_setfield(l, -2, "PPC_REG_R4");
	lua_pushinteger(l, 50);
	lua_setfield(l, -2, "PPC_REG_R5");
	lua_pushinteger(l, 51);
	lua_setfield(l, -2, "PPC_REG_R6");
	lua_pushinteger(l, 52);
	lua_setfield(l, -2, "PPC_REG_R7");
	lua_pushinteger(l, 53);
	lua_setfield(l, -2, "PPC_REG_R8");
	lua_pushinteger(l, 54);
	lua_setfield(l, -2, "PPC_REG_R9");
	lua_pushinteger(l, 55);
	lua_setfield(l, -2, "PPC_REG_R10");
	lua_pushinteger(l, 56);
	lua_setfield(l, -2, "PPC_REG_R11");
	lua_pushinteger(l, 57);
	lua_setfield(l, -2, "PPC_REG_R12");
	lua_pushinteger(l, 58);
	lua_setfield(l, -2, "PPC_REG_R13");
	lua_pushinteger(l, 59);
	lua_setfield(l, -2, "PPC_REG_R14");
	lua_pushinteger(l, 60);
	lua_setfield(l, -2, "PPC_REG_R15");
	lua_pushinteger(l, 61);
	lua_setfield(l, -2, "PPC_REG_R16");
	lua_pushinteger(l, 62);
	lua_setfield(l, -2, "PPC_REG_R17");
	lua_pushinteger(l, 63);
	lua_setfield(l, -2, "PPC_REG_R18");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "PPC_REG_R19");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "PPC_REG_R20");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "PPC_REG_R21");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "PPC_REG_R22");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "PPC_REG_R23");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "PPC_REG_R24");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "PPC_REG_R25");
	lua_pushinteger(l, 71);
	lua_setfield(l, -2, "PPC_REG_R26");
	lua_pushinteger(l, 72);
	lua_setfield(l, -2, "PPC_REG_R27");
	lua_pushinteger(l, 73);
	lua_setfield(l, -2, "PPC_REG_R28");
	lua_pushinteger(l, 74);
	lua_setfield(l, -2, "PPC_REG_R29");
	lua_pushinteger(l, 75);
	lua_setfield(l, -2, "PPC_REG_R30");
	lua_pushinteger(l, 76);
	lua_setfield(l, -2, "PPC_REG_R31");
	lua_pushinteger(l, 77);
	lua_setfield(l, -2, "PPC_REG_V0");
	lua_pushinteger(l, 78);
	lua_setfield(l, -2, "PPC_REG_V1");
	lua_pushinteger(l, 79);
	lua_setfield(l, -2, "PPC_REG_V2");
	lua_pushinteger(l, 80);
	lua_setfield(l, -2, "PPC_REG_V3");
	lua_pushinteger(l, 81);
	lua_setfield(l, -2, "PPC_REG_V4");
	lua_pushinteger(l, 82);
	lua_setfield(l, -2, "PPC_REG_V5");
	lua_pushinteger(l, 83);
	lua_setfield(l, -2, "PPC_REG_V6");
	lua_pushinteger(l, 84);
	lua_setfield(l, -2, "PPC_REG_V7");
	lua_pushinteger(l, 85);
	lua_setfield(l, -2, "PPC_REG_V8");
	lua_pushinteger(l, 86);
	lua_setfield(l, -2, "PPC_REG_V9");
	lua_pushinteger(l, 87);
	lua_setfield(l, -2, "PPC_REG_V10");
	lua_pushinteger(l, 88);
	lua_setfield(l, -2, "PPC_REG_V11");
	lua_pushinteger(l, 89);
	lua_setfield(l, -2, "PPC_REG_V12");
	lua_pushinteger(l, 90);
	lua_setfield(l, -2, "PPC_REG_V13");
	lua_pushinteger(l, 91);
	lua_setfield(l, -2, "PPC_REG_V14");
	lua_pushinteger(l, 92);
	lua_setfield(l, -2, "PPC_REG_V15");
	lua_pushinteger(l, 93);
	lua_setfield(l, -2, "PPC_REG_V16");
	lua_pushinteger(l, 94);
	lua_setfield(l, -2, "PPC_REG_V17");
	lua_pushinteger(l, 95);
	lua_setfield(l, -2, "PPC_REG_V18");
	lua_pushinteger(l, 96);
	lua_setfield(l, -2, "PPC_REG_V19");
	lua_pushinteger(l, 97);
	lua_setfield(l, -2, "PPC_REG_V20");
	lua_pushinteger(l, 98);
	lua_setfield(l, -2, "PPC_REG_V21");
	lua_pushinteger(l, 99);
	lua_setfield(l, -2, "PPC_REG_V22");
	lua_pushinteger(l, 100);
	lua_setfield(l, -2, "PPC_REG_V23");
	lua_pushinteger(l, 101);
	lua_setfield(l, -2, "PPC_REG_V24");
	lua_pushinteger(l, 102);
	lua_setfield(l, -2, "PPC_REG_V25");
	lua_pushinteger(l, 103);
	lua_setfield(l, -2, "PPC_REG_V26");
	lua_pushinteger(l, 104);
	lua_setfield(l, -2, "PPC_REG_V27");
	lua_pushinteger(l, 105);
	lua_setfield(l, -2, "PPC_REG_V28");
	lua_pushinteger(l, 106);
	lua_setfield(l, -2, "PPC_REG_V29");
	lua_pushinteger(l, 107);
	lua_setfield(l, -2, "PPC_REG_V30");
	lua_pushinteger(l, 108);
	lua_setfield(l, -2, "PPC_REG_V31");
	lua_pushinteger(l, 109);
	lua_setfield(l, -2, "PPC_REG_VRSAVE");
	lua_pushinteger(l, 110);
	lua_setfield(l, -2, "PPC_REG_VS0");
	lua_pushinteger(l, 111);
	lua_setfield(l, -2, "PPC_REG_VS1");
	lua_pushinteger(l, 112);
	lua_setfield(l, -2, "PPC_REG_VS2");
	lua_pushinteger(l, 113);
	lua_setfield(l, -2, "PPC_REG_VS3");
	lua_pushinteger(l, 114);
	lua_setfield(l, -2, "PPC_REG_VS4");
	lua_pushinteger(l, 115);
	lua_setfield(l, -2, "PPC_REG_VS5");
	lua_pushinteger(l, 116);
	lua_setfield(l, -2, "PPC_REG_VS6");
	lua_pushinteger(l, 117);
	lua_setfield(l, -2, "PPC_REG_VS7");
	lua_pushinteger(l, 118);
	lua_setfield(l, -2, "PPC_REG_VS8");
	lua_pushinteger(l, 119);
	lua_setfield(l, -2, "PPC_REG_VS9");
	lua_pushinteger(l, 120);
	lua_setfield(l, -2, "PPC_REG_VS10");
	lua_pushinteger(l, 121);
	lua_setfield(l, -2, "PPC_REG_VS11");
	lua_pushinteger(l, 122);
	lua_setfield(l, -2, "PPC_REG_VS12");
	lua_pushinteger(l, 123);
	lua_setfield(l, -2, "PPC_REG_VS13");
	lua_pushinteger(l, 124);
	lua_setfield(l, -2, "PPC_REG_VS14");
	lua_pushinteger(l, 125);
	lua_setfield(l, -2, "PPC_REG_VS15");
	lua_pushinteger(l, 126);
	lua_setfield(l, -2, "PPC_REG_VS16");
	lua_pushinteger(l, 127);
	lua_setfield(l, -2, "PPC_REG_VS17");
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "PPC_REG_VS18");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "PPC_REG_VS19");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "PPC_REG_VS20");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "PPC_REG_VS21");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "PPC_REG_VS22");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "PPC_REG_VS23");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "PPC_REG_VS24");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "PPC_REG_VS25");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "PPC_REG_VS26");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "PPC_REG_VS27");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "PPC_REG_VS28");
	lua_pushinteger(l, 139);
	lua_setfield(l, -2, "PPC_REG_VS29");
	lua_pushinteger(l, 140);
	lua_setfield(l, -2, "PPC_REG_VS30");
	lua_pushinteger(l, 141);
	lua_setfield(l, -2, "PPC_REG_VS31");
	lua_pushinteger(l, 142);
	lua_setfield(l, -2, "PPC_REG_VS32");
	lua_pushinteger(l, 143);
	lua_setfield(l, -2, "PPC_REG_VS33");
	lua_pushinteger(l, 144);
	lua_setfield(l, -2, "PPC_REG_VS34");
	lua_pushinteger(l, 145);
	lua_setfield(l, -2, "PPC_REG_VS35");
	lua_pushinteger(l, 146);
	lua_setfield(l, -2, "PPC_REG_VS36");
	lua_pushinteger(l, 147);
	lua_setfield(l, -2, "PPC_REG_VS37");
	lua_pushinteger(l, 148);
	lua_setfield(l, -2, "PPC_REG_VS38");
	lua_pushinteger(l, 149);
	lua_setfield(l, -2, "PPC_REG_VS39");
	lua_pushinteger(l, 150);
	lua_setfield(l, -2, "PPC_REG_VS40");
	lua_pushinteger(l, 151);
	lua_setfield(l, -2, "PPC_REG_VS41");
	lua_pushinteger(l, 152);
	lua_setfield(l, -2, "PPC_REG_VS42");
	lua_pushinteger(l, 153);
	lua_setfield(l, -2, "PPC_REG_VS43");
	lua_pushinteger(l, 154);
	lua_setfield(l, -2, "PPC_REG_VS44");
	lua_pushinteger(l, 155);
	lua_setfield(l, -2, "PPC_REG_VS45");
	lua_pushinteger(l, 156);
	lua_setfield(l, -2, "PPC_REG_VS46");
	lua_pushinteger(l, 157);
	lua_setfield(l, -2, "PPC_REG_VS47");
	lua_pushinteger(l, 158);
	lua_setfield(l, -2, "PPC_REG_VS48");
	lua_pushinteger(l, 159);
	lua_setfield(l, -2, "PPC_REG_VS49");
	lua_pushinteger(l, 160);
	lua_setfield(l, -2, "PPC_REG_VS50");
	lua_pushinteger(l, 161);
	lua_setfield(l, -2, "PPC_REG_VS51");
	lua_pushinteger(l, 162);
	lua_setfield(l, -2, "PPC_REG_VS52");
	lua_pushinteger(l, 163);
	lua_setfield(l, -2, "PPC_REG_VS53");
	lua_pushinteger(l, 164);
	lua_setfield(l, -2, "PPC_REG_VS54");
	lua_pushinteger(l, 165);
	lua_setfield(l, -2, "PPC_REG_VS55");
	lua_pushinteger(l, 166);
	lua_setfield(l, -2, "PPC_REG_VS56");
	lua_pushinteger(l, 167);
	lua_setfield(l, -2, "PPC_REG_VS57");
	lua_pushinteger(l, 168);
	lua_setfield(l, -2, "PPC_REG_VS58");
	lua_pushinteger(l, 169);
	lua_setfield(l, -2, "PPC_REG_VS59");
	lua_pushinteger(l, 170);
	lua_setfield(l, -2, "PPC_REG_VS60");
	lua_pushinteger(l, 171);
	lua_setfield(l, -2, "PPC_REG_VS61");
	lua_pushinteger(l, 172);
	lua_setfield(l, -2, "PPC_REG_VS62");
	lua_pushinteger(l, 173);
	lua_setfield(l, -2, "PPC_REG_VS63");
	lua_pushinteger(l, 174);
	lua_setfield(l, -2, "PPC_REG_RM");
	lua_pushinteger(l, 175);
	lua_setfield(l, -2, "PPC_REG_CTR8");
	lua_pushinteger(l, 176);
	lua_setfield(l, -2, "PPC_REG_LR8");
	lua_pushinteger(l, 177);
	lua_setfield(l, -2, "PPC_REG_CR1EQ");
	lua_pushinteger(l, 178);
	lua_setfield(l, -2, "PPC_REG_ENDING");

	/* PPC instruction */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "PPC_INS_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "PPC_INS_ADD");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "PPC_INS_ADDC");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "PPC_INS_ADDE");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "PPC_INS_ADDI");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "PPC_INS_ADDIC");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "PPC_INS_ADDIS");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "PPC_INS_ADDME");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "PPC_INS_ADDZE");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "PPC_INS_AND");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "PPC_INS_ANDC");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "PPC_INS_ANDIS");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "PPC_INS_ANDI");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "PPC_INS_B");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "PPC_INS_BA");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "PPC_INS_BC");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "PPC_INS_BCCTR");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "PPC_INS_BCCTRL");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "PPC_INS_BCL");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "PPC_INS_BCLR");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "PPC_INS_BCLRL");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "PPC_INS_BCTR");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "PPC_INS_BCTRL");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "PPC_INS_BDNZ");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "PPC_INS_BDNZA");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "PPC_INS_BDNZL");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "PPC_INS_BDNZLA");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "PPC_INS_BDNZLR");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "PPC_INS_BDNZLRL");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "PPC_INS_BDZ");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "PPC_INS_BDZA");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "PPC_INS_BDZL");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "PPC_INS_BDZLA");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "PPC_INS_BDZLR");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "PPC_INS_BDZLRL");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "PPC_INS_BL");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "PPC_INS_BLA");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "PPC_INS_BLR");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "PPC_INS_BLRL");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "PPC_INS_BRINC");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "PPC_INS_CMPD");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "PPC_INS_CMPDI");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "PPC_INS_CMPLD");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "PPC_INS_CMPLDI");
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "PPC_INS_CMPLW");
	lua_pushinteger(l, 45);
	lua_setfield(l, -2, "PPC_INS_CMPLWI");
	lua_pushinteger(l, 46);
	lua_setfield(l, -2, "PPC_INS_CMPW");
	lua_pushinteger(l, 47);
	lua_setfield(l, -2, "PPC_INS_CMPWI");
	lua_pushinteger(l, 48);
	lua_setfield(l, -2, "PPC_INS_CNTLZD");
	lua_pushinteger(l, 49);
	lua_setfield(l, -2, "PPC_INS_CNTLZW");
	lua_pushinteger(l, 50);
	lua_setfield(l, -2, "PPC_INS_CREQV");
	lua_pushinteger(l, 51);
	lua_setfield(l, -2, "PPC_INS_CRXOR");
	lua_pushinteger(l, 52);
	lua_setfield(l, -2, "PPC_INS_CRAND");
	lua_pushinteger(l, 53);
	lua_setfield(l, -2, "PPC_INS_CRANDC");
	lua_pushinteger(l, 54);
	lua_setfield(l, -2, "PPC_INS_CRNAND");
	lua_pushinteger(l, 55);
	lua_setfield(l, -2, "PPC_INS_CRNOR");
	lua_pushinteger(l, 56);
	lua_setfield(l, -2, "PPC_INS_CROR");
	lua_pushinteger(l, 57);
	lua_setfield(l, -2, "PPC_INS_CRORC");
	lua_pushinteger(l, 58);
	lua_setfield(l, -2, "PPC_INS_DCBA");
	lua_pushinteger(l, 59);
	lua_setfield(l, -2, "PPC_INS_DCBF");
	lua_pushinteger(l, 60);
	lua_setfield(l, -2, "PPC_INS_DCBI");
	lua_pushinteger(l, 61);
	lua_setfield(l, -2, "PPC_INS_DCBST");
	lua_pushinteger(l, 62);
	lua_setfield(l, -2, "PPC_INS_DCBT");
	lua_pushinteger(l, 63);
	lua_setfield(l, -2, "PPC_INS_DCBTST");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "PPC_INS_DCBZ");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "PPC_INS_DCBZL");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "PPC_INS_DCCCI");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "PPC_INS_DIVD");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "PPC_INS_DIVDU");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "PPC_INS_DIVW");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "PPC_INS_DIVWU");
	lua_pushinteger(l, 71);
	lua_setfield(l, -2, "PPC_INS_DSS");
	lua_pushinteger(l, 72);
	lua_setfield(l, -2, "PPC_INS_DSSALL");
	lua_pushinteger(l, 73);
	lua_setfield(l, -2, "PPC_INS_DST");
	lua_pushinteger(l, 74);
	lua_setfield(l, -2, "PPC_INS_DSTST");
	lua_pushinteger(l, 75);
	lua_setfield(l, -2, "PPC_INS_DSTSTT");
	lua_pushinteger(l, 76);
	lua_setfield(l, -2, "PPC_INS_DSTT");
	lua_pushinteger(l, 77);
	lua_setfield(l, -2, "PPC_INS_EIEIO");
	lua_pushinteger(l, 78);
	lua_setfield(l, -2, "PPC_INS_EQV");
	lua_pushinteger(l, 79);
	lua_setfield(l, -2, "PPC_INS_EVABS");
	lua_pushinteger(l, 80);
	lua_setfield(l, -2, "PPC_INS_EVADDIW");
	lua_pushinteger(l, 81);
	lua_setfield(l, -2, "PPC_INS_EVADDSMIAAW");
	lua_pushinteger(l, 82);
	lua_setfield(l, -2, "PPC_INS_EVADDSSIAAW");
	lua_pushinteger(l, 83);
	lua_setfield(l, -2, "PPC_INS_EVADDUMIAAW");
	lua_pushinteger(l, 84);
	lua_setfield(l, -2, "PPC_INS_EVADDUSIAAW");
	lua_pushinteger(l, 85);
	lua_setfield(l, -2, "PPC_INS_EVADDW");
	lua_pushinteger(l, 86);
	lua_setfield(l, -2, "PPC_INS_EVAND");
	lua_pushinteger(l, 87);
	lua_setfield(l, -2, "PPC_INS_EVANDC");
	lua_pushinteger(l, 88);
	lua_setfield(l, -2, "PPC_INS_EVCMPEQ");
	lua_pushinteger(l, 89);
	lua_setfield(l, -2, "PPC_INS_EVCMPGTS");
	lua_pushinteger(l, 90);
	lua_setfield(l, -2, "PPC_INS_EVCMPGTU");
	lua_pushinteger(l, 91);
	lua_setfield(l, -2, "PPC_INS_EVCMPLTS");
	lua_pushinteger(l, 92);
	lua_setfield(l, -2, "PPC_INS_EVCMPLTU");
	lua_pushinteger(l, 93);
	lua_setfield(l, -2, "PPC_INS_EVCNTLSW");
	lua_pushinteger(l, 94);
	lua_setfield(l, -2, "PPC_INS_EVCNTLZW");
	lua_pushinteger(l, 95);
	lua_setfield(l, -2, "PPC_INS_EVDIVWS");
	lua_pushinteger(l, 96);
	lua_setfield(l, -2, "PPC_INS_EVDIVWU");
	lua_pushinteger(l, 97);
	lua_setfield(l, -2, "PPC_INS_EVEQV");
	lua_pushinteger(l, 98);
	lua_setfield(l, -2, "PPC_INS_EVEXTSB");
	lua_pushinteger(l, 99);
	lua_setfield(l, -2, "PPC_INS_EVEXTSH");
	lua_pushinteger(l, 100);
	lua_setfield(l, -2, "PPC_INS_EVLDD");
	lua_pushinteger(l, 101);
	lua_setfield(l, -2, "PPC_INS_EVLDDX");
	lua_pushinteger(l, 102);
	lua_setfield(l, -2, "PPC_INS_EVLDH");
	lua_pushinteger(l, 103);
	lua_setfield(l, -2, "PPC_INS_EVLDHX");
	lua_pushinteger(l, 104);
	lua_setfield(l, -2, "PPC_INS_EVLDW");
	lua_pushinteger(l, 105);
	lua_setfield(l, -2, "PPC_INS_EVLDWX");
	lua_pushinteger(l, 106);
	lua_setfield(l, -2, "PPC_INS_EVLHHESPLAT");
	lua_pushinteger(l, 107);
	lua_setfield(l, -2, "PPC_INS_EVLHHESPLATX");
	lua_pushinteger(l, 108);
	lua_setfield(l, -2, "PPC_INS_EVLHHOSSPLAT");
	lua_pushinteger(l, 109);
	lua_setfield(l, -2, "PPC_INS_EVLHHOSSPLATX");
	lua_pushinteger(l, 110);
	lua_setfield(l, -2, "PPC_INS_EVLHHOUSPLAT");
	lua_pushinteger(l, 111);
	lua_setfield(l, -2, "PPC_INS_EVLHHOUSPLATX");
	lua_pushinteger(l, 112);
	lua_setfield(l, -2, "PPC_INS_EVLWHE");
	lua_pushinteger(l, 113);
	lua_setfield(l, -2, "PPC_INS_EVLWHEX");
	lua_pushinteger(l, 114);
	lua_setfield(l, -2, "PPC_INS_EVLWHOS");
	lua_pushinteger(l, 115);
	lua_setfield(l, -2, "PPC_INS_EVLWHOSX");
	lua_pushinteger(l, 116);
	lua_setfield(l, -2, "PPC_INS_EVLWHOU");
	lua_pushinteger(l, 117);
	lua_setfield(l, -2, "PPC_INS_EVLWHOUX");
	lua_pushinteger(l, 118);
	lua_setfield(l, -2, "PPC_INS_EVLWHSPLAT");
	lua_pushinteger(l, 119);
	lua_setfield(l, -2, "PPC_INS_EVLWHSPLATX");
	lua_pushinteger(l, 120);
	lua_setfield(l, -2, "PPC_INS_EVLWWSPLAT");
	lua_pushinteger(l, 121);
	lua_setfield(l, -2, "PPC_INS_EVLWWSPLATX");
	lua_pushinteger(l, 122);
	lua_setfield(l, -2, "PPC_INS_EVMERGEHI");
	lua_pushinteger(l, 123);
	lua_setfield(l, -2, "PPC_INS_EVMERGEHILO");
	lua_pushinteger(l, 124);
	lua_setfield(l, -2, "PPC_INS_EVMERGELO");
	lua_pushinteger(l, 125);
	lua_setfield(l, -2, "PPC_INS_EVMERGELOHI");
	lua_pushinteger(l, 126);
	lua_setfield(l, -2, "PPC_INS_EVMHEGSMFAA");
	lua_pushinteger(l, 127);
	lua_setfield(l, -2, "PPC_INS_EVMHEGSMFAN");
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "PPC_INS_EVMHEGSMIAA");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "PPC_INS_EVMHEGSMIAN");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "PPC_INS_EVMHEGUMIAA");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "PPC_INS_EVMHEGUMIAN");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "PPC_INS_EVMHESMF");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "PPC_INS_EVMHESMFA");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "PPC_INS_EVMHESMFAAW");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "PPC_INS_EVMHESMFANW");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "PPC_INS_EVMHESMI");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "PPC_INS_EVMHESMIA");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "PPC_INS_EVMHESMIAAW");
	lua_pushinteger(l, 139);
	lua_setfield(l, -2, "PPC_INS_EVMHESMIANW");
	lua_pushinteger(l, 140);
	lua_setfield(l, -2, "PPC_INS_EVMHESSF");
	lua_pushinteger(l, 141);
	lua_setfield(l, -2, "PPC_INS_EVMHESSFA");
	lua_pushinteger(l, 142);
	lua_setfield(l, -2, "PPC_INS_EVMHESSFAAW");
	lua_pushinteger(l, 143);
	lua_setfield(l, -2, "PPC_INS_EVMHESSFANW");
	lua_pushinteger(l, 144);
	lua_setfield(l, -2, "PPC_INS_EVMHESSIAAW");
	lua_pushinteger(l, 145);
	lua_setfield(l, -2, "PPC_INS_EVMHESSIANW");
	lua_pushinteger(l, 146);
	lua_setfield(l, -2, "PPC_INS_EVMHEUMI");
	lua_pushinteger(l, 147);
	lua_setfield(l, -2, "PPC_INS_EVMHEUMIA");
	lua_pushinteger(l, 148);
	lua_setfield(l, -2, "PPC_INS_EVMHEUMIAAW");
	lua_pushinteger(l, 149);
	lua_setfield(l, -2, "PPC_INS_EVMHEUMIANW");
	lua_pushinteger(l, 150);
	lua_setfield(l, -2, "PPC_INS_EVMHEUSIAAW");
	lua_pushinteger(l, 151);
	lua_setfield(l, -2, "PPC_INS_EVMHEUSIANW");
	lua_pushinteger(l, 152);
	lua_setfield(l, -2, "PPC_INS_EVMHOGSMFAA");
	lua_pushinteger(l, 153);
	lua_setfield(l, -2, "PPC_INS_EVMHOGSMFAN");
	lua_pushinteger(l, 154);
	lua_setfield(l, -2, "PPC_INS_EVMHOGSMIAA");
	lua_pushinteger(l, 155);
	lua_setfield(l, -2, "PPC_INS_EVMHOGSMIAN");
	lua_pushinteger(l, 156);
	lua_setfield(l, -2, "PPC_INS_EVMHOGUMIAA");
	lua_pushinteger(l, 157);
	lua_setfield(l, -2, "PPC_INS_EVMHOGUMIAN");
	lua_pushinteger(l, 158);
	lua_setfield(l, -2, "PPC_INS_EVMHOSMF");
	lua_pushinteger(l, 159);
	lua_setfield(l, -2, "PPC_INS_EVMHOSMFA");
	lua_pushinteger(l, 160);
	lua_setfield(l, -2, "PPC_INS_EVMHOSMFAAW");
	lua_pushinteger(l, 161);
	lua_setfield(l, -2, "PPC_INS_EVMHOSMFANW");
	lua_pushinteger(l, 162);
	lua_setfield(l, -2, "PPC_INS_EVMHOSMI");
	lua_pushinteger(l, 163);
	lua_setfield(l, -2, "PPC_INS_EVMHOSMIA");
	lua_pushinteger(l, 164);
	lua_setfield(l, -2, "PPC_INS_EVMHOSMIAAW");
	lua_pushinteger(l, 165);
	lua_setfield(l, -2, "PPC_INS_EVMHOSMIANW");
	lua_pushinteger(l, 166);
	lua_setfield(l, -2, "PPC_INS_EVMHOSSF");
	lua_pushinteger(l, 167);
	lua_setfield(l, -2, "PPC_INS_EVMHOSSFA");
	lua_pushinteger(l, 168);
	lua_setfield(l, -2, "PPC_INS_EVMHOSSFAAW");
	lua_pushinteger(l, 169);
	lua_setfield(l, -2, "PPC_INS_EVMHOSSFANW");
	lua_pushinteger(l, 170);
	lua_setfield(l, -2, "PPC_INS_EVMHOSSIAAW");
	lua_pushinteger(l, 171);
	lua_setfield(l, -2, "PPC_INS_EVMHOSSIANW");
	lua_pushinteger(l, 172);
	lua_setfield(l, -2, "PPC_INS_EVMHOUMI");
	lua_pushinteger(l, 173);
	lua_setfield(l, -2, "PPC_INS_EVMHOUMIA");
	lua_pushinteger(l, 174);
	lua_setfield(l, -2, "PPC_INS_EVMHOUMIAAW");
	lua_pushinteger(l, 175);
	lua_setfield(l, -2, "PPC_INS_EVMHOUMIANW");
	lua_pushinteger(l, 176);
	lua_setfield(l, -2, "PPC_INS_EVMHOUSIAAW");
	lua_pushinteger(l, 177);
	lua_setfield(l, -2, "PPC_INS_EVMHOUSIANW");
	lua_pushinteger(l, 178);
	lua_setfield(l, -2, "PPC_INS_EVMRA");
	lua_pushinteger(l, 179);
	lua_setfield(l, -2, "PPC_INS_EVMWHSMF");
	lua_pushinteger(l, 180);
	lua_setfield(l, -2, "PPC_INS_EVMWHSMFA");
	lua_pushinteger(l, 181);
	lua_setfield(l, -2, "PPC_INS_EVMWHSMI");
	lua_pushinteger(l, 182);
	lua_setfield(l, -2, "PPC_INS_EVMWHSMIA");
	lua_pushinteger(l, 183);
	lua_setfield(l, -2, "PPC_INS_EVMWHSSF");
	lua_pushinteger(l, 184);
	lua_setfield(l, -2, "PPC_INS_EVMWHSSFA");
	lua_pushinteger(l, 185);
	lua_setfield(l, -2, "PPC_INS_EVMWHUMI");
	lua_pushinteger(l, 186);
	lua_setfield(l, -2, "PPC_INS_EVMWHUMIA");
	lua_pushinteger(l, 187);
	lua_setfield(l, -2, "PPC_INS_EVMWLSMIAAW");
	lua_pushinteger(l, 188);
	lua_setfield(l, -2, "PPC_INS_EVMWLSMIANW");
	lua_pushinteger(l, 189);
	lua_setfield(l, -2, "PPC_INS_EVMWLSSIAAW");
	lua_pushinteger(l, 190);
	lua_setfield(l, -2, "PPC_INS_EVMWLSSIANW");
	lua_pushinteger(l, 191);
	lua_setfield(l, -2, "PPC_INS_EVMWLUMI");
	lua_pushinteger(l, 192);
	lua_setfield(l, -2, "PPC_INS_EVMWLUMIA");
	lua_pushinteger(l, 193);
	lua_setfield(l, -2, "PPC_INS_EVMWLUMIAAW");
	lua_pushinteger(l, 194);
	lua_setfield(l, -2, "PPC_INS_EVMWLUMIANW");
	lua_pushinteger(l, 195);
	lua_setfield(l, -2, "PPC_INS_EVMWLUSIAAW");
	lua_pushinteger(l, 196);
	lua_setfield(l, -2, "PPC_INS_EVMWLUSIANW");
	lua_pushinteger(l, 197);
	lua_setfield(l, -2, "PPC_INS_EVMWSMF");
	lua_pushinteger(l, 198);
	lua_setfield(l, -2, "PPC_INS_EVMWSMFA");
	lua_pushinteger(l, 199);
	lua_setfield(l, -2, "PPC_INS_EVMWSMFAA");
	lua_pushinteger(l, 200);
	lua_setfield(l, -2, "PPC_INS_EVMWSMFAN");
	lua_pushinteger(l, 201);
	lua_setfield(l, -2, "PPC_INS_EVMWSMI");
	lua_pushinteger(l, 202);
	lua_setfield(l, -2, "PPC_INS_EVMWSMIA");
	lua_pushinteger(l, 203);
	lua_setfield(l, -2, "PPC_INS_EVMWSMIAA");
	lua_pushinteger(l, 204);
	lua_setfield(l, -2, "PPC_INS_EVMWSMIAN");
	lua_pushinteger(l, 205);
	lua_setfield(l, -2, "PPC_INS_EVMWSSF");
	lua_pushinteger(l, 206);
	lua_setfield(l, -2, "PPC_INS_EVMWSSFA");
	lua_pushinteger(l, 207);
	lua_setfield(l, -2, "PPC_INS_EVMWSSFAA");
	lua_pushinteger(l, 208);
	lua_setfield(l, -2, "PPC_INS_EVMWSSFAN");
	lua_pushinteger(l, 209);
	lua_setfield(l, -2, "PPC_INS_EVMWUMI");
	lua_pushinteger(l, 210);
	lua_setfield(l, -2, "PPC_INS_EVMWUMIA");
	lua_pushinteger(l, 211);
	lua_setfield(l, -2, "PPC_INS_EVMWUMIAA");
	lua_pushinteger(l, 212);
	lua_setfield(l, -2, "PPC_INS_EVMWUMIAN");
	lua_pushinteger(l, 213);
	lua_setfield(l, -2, "PPC_INS_EVNAND");
	lua_pushinteger(l, 214);
	lua_setfield(l, -2, "PPC_INS_EVNEG");
	lua_pushinteger(l, 215);
	lua_setfield(l, -2, "PPC_INS_EVNOR");
	lua_pushinteger(l, 216);
	lua_setfield(l, -2, "PPC_INS_EVOR");
	lua_pushinteger(l, 217);
	lua_setfield(l, -2, "PPC_INS_EVORC");
	lua_pushinteger(l, 218);
	lua_setfield(l, -2, "PPC_INS_EVRLW");
	lua_pushinteger(l, 219);
	lua_setfield(l, -2, "PPC_INS_EVRLWI");
	lua_pushinteger(l, 220);
	lua_setfield(l, -2, "PPC_INS_EVRNDW");
	lua_pushinteger(l, 221);
	lua_setfield(l, -2, "PPC_INS_EVSLW");
	lua_pushinteger(l, 222);
	lua_setfield(l, -2, "PPC_INS_EVSLWI");
	lua_pushinteger(l, 223);
	lua_setfield(l, -2, "PPC_INS_EVSPLATFI");
	lua_pushinteger(l, 224);
	lua_setfield(l, -2, "PPC_INS_EVSPLATI");
	lua_pushinteger(l, 225);
	lua_setfield(l, -2, "PPC_INS_EVSRWIS");
	lua_pushinteger(l, 226);
	lua_setfield(l, -2, "PPC_INS_EVSRWIU");
	lua_pushinteger(l, 227);
	lua_setfield(l, -2, "PPC_INS_EVSRWS");
	lua_pushinteger(l, 228);
	lua_setfield(l, -2, "PPC_INS_EVSRWU");
	lua_pushinteger(l, 229);
	lua_setfield(l, -2, "PPC_INS_EVSTDD");
	lua_pushinteger(l, 230);
	lua_setfield(l, -2, "PPC_INS_EVSTDDX");
	lua_pushinteger(l, 231);
	lua_setfield(l, -2, "PPC_INS_EVSTDH");
	lua_pushinteger(l, 232);
	lua_setfield(l, -2, "PPC_INS_EVSTDHX");
	lua_pushinteger(l, 233);
	lua_setfield(l, -2, "PPC_INS_EVSTDW");
	lua_pushinteger(l, 234);
	lua_setfield(l, -2, "PPC_INS_EVSTDWX");
	lua_pushinteger(l, 235);
	lua_setfield(l, -2, "PPC_INS_EVSTWHE");
	lua_pushinteger(l, 236);
	lua_setfield(l, -2, "PPC_INS_EVSTWHEX");
	lua_pushinteger(l, 237);
	lua_setfield(l, -2, "PPC_INS_EVSTWHO");
	lua_pushinteger(l, 238);
	lua_setfield(l, -2, "PPC_INS_EVSTWHOX");
	lua_pushinteger(l, 239);
	lua_setfield(l, -2, "PPC_INS_EVSTWWE");
	lua_pushinteger(l, 240);
	lua_setfield(l, -2, "PPC_INS_EVSTWWEX");
	lua_pushinteger(l, 241);
	lua_setfield(l, -2, "PPC_INS_EVSTWWO");
	lua_pushinteger(l, 242);
	lua_setfield(l, -2, "PPC_INS_EVSTWWOX");
	lua_pushinteger(l, 243);
	lua_setfield(l, -2, "PPC_INS_EVSUBFSMIAAW");
	lua_pushinteger(l, 244);
	lua_setfield(l, -2, "PPC_INS_EVSUBFSSIAAW");
	lua_pushinteger(l, 245);
	lua_setfield(l, -2, "PPC_INS_EVSUBFUMIAAW");
	lua_pushinteger(l, 246);
	lua_setfield(l, -2, "PPC_INS_EVSUBFUSIAAW");
	lua_pushinteger(l, 247);
	lua_setfield(l, -2, "PPC_INS_EVSUBFW");
	lua_pushinteger(l, 248);
	lua_setfield(l, -2, "PPC_INS_EVSUBIFW");
	lua_pushinteger(l, 249);
	lua_setfield(l, -2, "PPC_INS_EVXOR");
	lua_pushinteger(l, 250);
	lua_setfield(l, -2, "PPC_INS_EXTSB");
	lua_pushinteger(l, 251);
	lua_setfield(l, -2, "PPC_INS_EXTSH");
	lua_pushinteger(l, 252);
	lua_setfield(l, -2, "PPC_INS_EXTSW");
	lua_pushinteger(l, 253);
	lua_setfield(l, -2, "PPC_INS_FABS");
	lua_pushinteger(l, 254);
	lua_setfield(l, -2, "PPC_INS_FADD");
	lua_pushinteger(l, 255);
	lua_setfield(l, -2, "PPC_INS_FADDS");
	lua_pushinteger(l, 256);
	lua_setfield(l, -2, "PPC_INS_FCFID");
	lua_pushinteger(l, 257);
	lua_setfield(l, -2, "PPC_INS_FCFIDS");
	lua_pushinteger(l, 258);
	lua_setfield(l, -2, "PPC_INS_FCFIDU");
	lua_pushinteger(l, 259);
	lua_setfield(l, -2, "PPC_INS_FCFIDUS");
	lua_pushinteger(l, 260);
	lua_setfield(l, -2, "PPC_INS_FCMPU");
	lua_pushinteger(l, 261);
	lua_setfield(l, -2, "PPC_INS_FCPSGN");
	lua_pushinteger(l, 262);
	lua_setfield(l, -2, "PPC_INS_FCTID");
	lua_pushinteger(l, 263);
	lua_setfield(l, -2, "PPC_INS_FCTIDUZ");
	lua_pushinteger(l, 264);
	lua_setfield(l, -2, "PPC_INS_FCTIDZ");
	lua_pushinteger(l, 265);
	lua_setfield(l, -2, "PPC_INS_FCTIW");
	lua_pushinteger(l, 266);
	lua_setfield(l, -2, "PPC_INS_FCTIWUZ");
	lua_pushinteger(l, 267);
	lua_setfield(l, -2, "PPC_INS_FCTIWZ");
	lua_pushinteger(l, 268);
	lua_setfield(l, -2, "PPC_INS_FDIV");
	lua_pushinteger(l, 269);
	lua_setfield(l, -2, "PPC_INS_FDIVS");
	lua_pushinteger(l, 270);
	lua_setfield(l, -2, "PPC_INS_FMADD");
	lua_pushinteger(l, 271);
	lua_setfield(l, -2, "PPC_INS_FMADDS");
	lua_pushinteger(l, 272);
	lua_setfield(l, -2, "PPC_INS_FMR");
	lua_pushinteger(l, 273);
	lua_setfield(l, -2, "PPC_INS_FMSUB");
	lua_pushinteger(l, 274);
	lua_setfield(l, -2, "PPC_INS_FMSUBS");
	lua_pushinteger(l, 275);
	lua_setfield(l, -2, "PPC_INS_FMUL");
	lua_pushinteger(l, 276);
	lua_setfield(l, -2, "PPC_INS_FMULS");
	lua_pushinteger(l, 277);
	lua_setfield(l, -2, "PPC_INS_FNABS");
	lua_pushinteger(l, 278);
	lua_setfield(l, -2, "PPC_INS_FNEG");
	lua_pushinteger(l, 279);
	lua_setfield(l, -2, "PPC_INS_FNMADD");
	lua_pushinteger(l, 280);
	lua_setfield(l, -2, "PPC_INS_FNMADDS");
	lua_pushinteger(l, 281);
	lua_setfield(l, -2, "PPC_INS_FNMSUB");
	lua_pushinteger(l, 282);
	lua_setfield(l, -2, "PPC_INS_FNMSUBS");
	lua_pushinteger(l, 283);
	lua_setfield(l, -2, "PPC_INS_FRE");
	lua_pushinteger(l, 284);
	lua_setfield(l, -2, "PPC_INS_FRES");
	lua_pushinteger(l, 285);
	lua_setfield(l, -2, "PPC_INS_FRIM");
	lua_pushinteger(l, 286);
	lua_setfield(l, -2, "PPC_INS_FRIN");
	lua_pushinteger(l, 287);
	lua_setfield(l, -2, "PPC_INS_FRIP");
	lua_pushinteger(l, 288);
	lua_setfield(l, -2, "PPC_INS_FRIZ");
	lua_pushinteger(l, 289);
	lua_setfield(l, -2, "PPC_INS_FRSP");
	lua_pushinteger(l, 290);
	lua_setfield(l, -2, "PPC_INS_FRSQRTE");
	lua_pushinteger(l, 291);
	lua_setfield(l, -2, "PPC_INS_FRSQRTES");
	lua_pushinteger(l, 292);
	lua_setfield(l, -2, "PPC_INS_FSEL");
	lua_pushinteger(l, 293);
	lua_setfield(l, -2, "PPC_INS_FSQRT");
	lua_pushinteger(l, 294);
	lua_setfield(l, -2, "PPC_INS_FSQRTS");
	lua_pushinteger(l, 295);
	lua_setfield(l, -2, "PPC_INS_FSUB");
	lua_pushinteger(l, 296);
	lua_setfield(l, -2, "PPC_INS_FSUBS");
	lua_pushinteger(l, 297);
	lua_setfield(l, -2, "PPC_INS_ICBI");
	lua_pushinteger(l, 298);
	lua_setfield(l, -2, "PPC_INS_ICCCI");
	lua_pushinteger(l, 299);
	lua_setfield(l, -2, "PPC_INS_ISEL");
	lua_pushinteger(l, 300);
	lua_setfield(l, -2, "PPC_INS_ISYNC");
	lua_pushinteger(l, 301);
	lua_setfield(l, -2, "PPC_INS_LA");
	lua_pushinteger(l, 302);
	lua_setfield(l, -2, "PPC_INS_LBZ");
	lua_pushinteger(l, 303);
	lua_setfield(l, -2, "PPC_INS_LBZU");
	lua_pushinteger(l, 304);
	lua_setfield(l, -2, "PPC_INS_LBZUX");
	lua_pushinteger(l, 305);
	lua_setfield(l, -2, "PPC_INS_LBZX");
	lua_pushinteger(l, 306);
	lua_setfield(l, -2, "PPC_INS_LD");
	lua_pushinteger(l, 307);
	lua_setfield(l, -2, "PPC_INS_LDARX");
	lua_pushinteger(l, 308);
	lua_setfield(l, -2, "PPC_INS_LDBRX");
	lua_pushinteger(l, 309);
	lua_setfield(l, -2, "PPC_INS_LDU");
	lua_pushinteger(l, 310);
	lua_setfield(l, -2, "PPC_INS_LDUX");
	lua_pushinteger(l, 311);
	lua_setfield(l, -2, "PPC_INS_LDX");
	lua_pushinteger(l, 312);
	lua_setfield(l, -2, "PPC_INS_LFD");
	lua_pushinteger(l, 313);
	lua_setfield(l, -2, "PPC_INS_LFDU");
	lua_pushinteger(l, 314);
	lua_setfield(l, -2, "PPC_INS_LFDUX");
	lua_pushinteger(l, 315);
	lua_setfield(l, -2, "PPC_INS_LFDX");
	lua_pushinteger(l, 316);
	lua_setfield(l, -2, "PPC_INS_LFIWAX");
	lua_pushinteger(l, 317);
	lua_setfield(l, -2, "PPC_INS_LFIWZX");
	lua_pushinteger(l, 318);
	lua_setfield(l, -2, "PPC_INS_LFS");
	lua_pushinteger(l, 319);
	lua_setfield(l, -2, "PPC_INS_LFSU");
	lua_pushinteger(l, 320);
	lua_setfield(l, -2, "PPC_INS_LFSUX");
	lua_pushinteger(l, 321);
	lua_setfield(l, -2, "PPC_INS_LFSX");
	lua_pushinteger(l, 322);
	lua_setfield(l, -2, "PPC_INS_LHA");
	lua_pushinteger(l, 323);
	lua_setfield(l, -2, "PPC_INS_LHAU");
	lua_pushinteger(l, 324);
	lua_setfield(l, -2, "PPC_INS_LHAUX");
	lua_pushinteger(l, 325);
	lua_setfield(l, -2, "PPC_INS_LHAX");
	lua_pushinteger(l, 326);
	lua_setfield(l, -2, "PPC_INS_LHBRX");
	lua_pushinteger(l, 327);
	lua_setfield(l, -2, "PPC_INS_LHZ");
	lua_pushinteger(l, 328);
	lua_setfield(l, -2, "PPC_INS_LHZU");
	lua_pushinteger(l, 329);
	lua_setfield(l, -2, "PPC_INS_LHZUX");
	lua_pushinteger(l, 330);
	lua_setfield(l, -2, "PPC_INS_LHZX");
	lua_pushinteger(l, 331);
	lua_setfield(l, -2, "PPC_INS_LI");
	lua_pushinteger(l, 332);
	lua_setfield(l, -2, "PPC_INS_LIS");
	lua_pushinteger(l, 333);
	lua_setfield(l, -2, "PPC_INS_LMW");
	lua_pushinteger(l, 334);
	lua_setfield(l, -2, "PPC_INS_LSWI");
	lua_pushinteger(l, 335);
	lua_setfield(l, -2, "PPC_INS_LVEBX");
	lua_pushinteger(l, 336);
	lua_setfield(l, -2, "PPC_INS_LVEHX");
	lua_pushinteger(l, 337);
	lua_setfield(l, -2, "PPC_INS_LVEWX");
	lua_pushinteger(l, 338);
	lua_setfield(l, -2, "PPC_INS_LVSL");
	lua_pushinteger(l, 339);
	lua_setfield(l, -2, "PPC_INS_LVSR");
	lua_pushinteger(l, 340);
	lua_setfield(l, -2, "PPC_INS_LVX");
	lua_pushinteger(l, 341);
	lua_setfield(l, -2, "PPC_INS_LVXL");
	lua_pushinteger(l, 342);
	lua_setfield(l, -2, "PPC_INS_LWA");
	lua_pushinteger(l, 343);
	lua_setfield(l, -2, "PPC_INS_LWARX");
	lua_pushinteger(l, 344);
	lua_setfield(l, -2, "PPC_INS_LWAUX");
	lua_pushinteger(l, 345);
	lua_setfield(l, -2, "PPC_INS_LWAX");
	lua_pushinteger(l, 346);
	lua_setfield(l, -2, "PPC_INS_LWBRX");
	lua_pushinteger(l, 347);
	lua_setfield(l, -2, "PPC_INS_LWZ");
	lua_pushinteger(l, 348);
	lua_setfield(l, -2, "PPC_INS_LWZU");
	lua_pushinteger(l, 349);
	lua_setfield(l, -2, "PPC_INS_LWZUX");
	lua_pushinteger(l, 350);
	lua_setfield(l, -2, "PPC_INS_LWZX");
	lua_pushinteger(l, 351);
	lua_setfield(l, -2, "PPC_INS_LXSDX");
	lua_pushinteger(l, 352);
	lua_setfield(l, -2, "PPC_INS_LXVD2X");
	lua_pushinteger(l, 353);
	lua_setfield(l, -2, "PPC_INS_LXVDSX");
	lua_pushinteger(l, 354);
	lua_setfield(l, -2, "PPC_INS_LXVW4X");
	lua_pushinteger(l, 355);
	lua_setfield(l, -2, "PPC_INS_MBAR");
	lua_pushinteger(l, 356);
	lua_setfield(l, -2, "PPC_INS_MCRF");
	lua_pushinteger(l, 357);
	lua_setfield(l, -2, "PPC_INS_MFCR");
	lua_pushinteger(l, 358);
	lua_setfield(l, -2, "PPC_INS_MFCTR");
	lua_pushinteger(l, 359);
	lua_setfield(l, -2, "PPC_INS_MFDCR");
	lua_pushinteger(l, 360);
	lua_setfield(l, -2, "PPC_INS_MFFS");
	lua_pushinteger(l, 361);
	lua_setfield(l, -2, "PPC_INS_MFLR");
	lua_pushinteger(l, 362);
	lua_setfield(l, -2, "PPC_INS_MFMSR");
	lua_pushinteger(l, 363);
	lua_setfield(l, -2, "PPC_INS_MFOCRF");
	lua_pushinteger(l, 364);
	lua_setfield(l, -2, "PPC_INS_MFSPR");
	lua_pushinteger(l, 365);
	lua_setfield(l, -2, "PPC_INS_MFSR");
	lua_pushinteger(l, 366);
	lua_setfield(l, -2, "PPC_INS_MFSRIN");
	lua_pushinteger(l, 367);
	lua_setfield(l, -2, "PPC_INS_MFTB");
	lua_pushinteger(l, 368);
	lua_setfield(l, -2, "PPC_INS_MFVSCR");
	lua_pushinteger(l, 369);
	lua_setfield(l, -2, "PPC_INS_MSYNC");
	lua_pushinteger(l, 370);
	lua_setfield(l, -2, "PPC_INS_MTCRF");
	lua_pushinteger(l, 371);
	lua_setfield(l, -2, "PPC_INS_MTCTR");
	lua_pushinteger(l, 372);
	lua_setfield(l, -2, "PPC_INS_MTDCR");
	lua_pushinteger(l, 373);
	lua_setfield(l, -2, "PPC_INS_MTFSB0");
	lua_pushinteger(l, 374);
	lua_setfield(l, -2, "PPC_INS_MTFSB1");
	lua_pushinteger(l, 375);
	lua_setfield(l, -2, "PPC_INS_MTFSF");
	lua_pushinteger(l, 376);
	lua_setfield(l, -2, "PPC_INS_MTLR");
	lua_pushinteger(l, 377);
	lua_setfield(l, -2, "PPC_INS_MTMSR");
	lua_pushinteger(l, 378);
	lua_setfield(l, -2, "PPC_INS_MTMSRD");
	lua_pushinteger(l, 379);
	lua_setfield(l, -2, "PPC_INS_MTOCRF");
	lua_pushinteger(l, 380);
	lua_setfield(l, -2, "PPC_INS_MTSPR");
	lua_pushinteger(l, 381);
	lua_setfield(l, -2, "PPC_INS_MTSR");
	lua_pushinteger(l, 382);
	lua_setfield(l, -2, "PPC_INS_MTSRIN");
	lua_pushinteger(l, 383);
	lua_setfield(l, -2, "PPC_INS_MTVSCR");
	lua_pushinteger(l, 384);
	lua_setfield(l, -2, "PPC_INS_MULHD");
	lua_pushinteger(l, 385);
	lua_setfield(l, -2, "PPC_INS_MULHDU");
	lua_pushinteger(l, 386);
	lua_setfield(l, -2, "PPC_INS_MULHW");
	lua_pushinteger(l, 387);
	lua_setfield(l, -2, "PPC_INS_MULHWU");
	lua_pushinteger(l, 388);
	lua_setfield(l, -2, "PPC_INS_MULLD");
	lua_pushinteger(l, 389);
	lua_setfield(l, -2, "PPC_INS_MULLI");
	lua_pushinteger(l, 390);
	lua_setfield(l, -2, "PPC_INS_MULLW");
	lua_pushinteger(l, 391);
	lua_setfield(l, -2, "PPC_INS_NAND");
	lua_pushinteger(l, 392);
	lua_setfield(l, -2, "PPC_INS_NEG");
	lua_pushinteger(l, 393);
	lua_setfield(l, -2, "PPC_INS_NOP");
	lua_pushinteger(l, 394);
	lua_setfield(l, -2, "PPC_INS_ORI");
	lua_pushinteger(l, 395);
	lua_setfield(l, -2, "PPC_INS_NOR");
	lua_pushinteger(l, 396);
	lua_setfield(l, -2, "PPC_INS_OR");
	lua_pushinteger(l, 397);
	lua_setfield(l, -2, "PPC_INS_ORC");
	lua_pushinteger(l, 398);
	lua_setfield(l, -2, "PPC_INS_ORIS");
	lua_pushinteger(l, 399);
	lua_setfield(l, -2, "PPC_INS_POPCNTD");
	lua_pushinteger(l, 400);
	lua_setfield(l, -2, "PPC_INS_POPCNTW");
	lua_pushinteger(l, 401);
	lua_setfield(l, -2, "PPC_INS_RFCI");
	lua_pushinteger(l, 402);
	lua_setfield(l, -2, "PPC_INS_RFDI");
	lua_pushinteger(l, 403);
	lua_setfield(l, -2, "PPC_INS_RFI");
	lua_pushinteger(l, 404);
	lua_setfield(l, -2, "PPC_INS_RFID");
	lua_pushinteger(l, 405);
	lua_setfield(l, -2, "PPC_INS_RFMCI");
	lua_pushinteger(l, 406);
	lua_setfield(l, -2, "PPC_INS_RLDCL");
	lua_pushinteger(l, 407);
	lua_setfield(l, -2, "PPC_INS_RLDCR");
	lua_pushinteger(l, 408);
	lua_setfield(l, -2, "PPC_INS_RLDIC");
	lua_pushinteger(l, 409);
	lua_setfield(l, -2, "PPC_INS_RLDICL");
	lua_pushinteger(l, 410);
	lua_setfield(l, -2, "PPC_INS_RLDICR");
	lua_pushinteger(l, 411);
	lua_setfield(l, -2, "PPC_INS_RLDIMI");
	lua_pushinteger(l, 412);
	lua_setfield(l, -2, "PPC_INS_RLWIMI");
	lua_pushinteger(l, 413);
	lua_setfield(l, -2, "PPC_INS_RLWINM");
	lua_pushinteger(l, 414);
	lua_setfield(l, -2, "PPC_INS_RLWNM");
	lua_pushinteger(l, 415);
	lua_setfield(l, -2, "PPC_INS_SC");
	lua_pushinteger(l, 416);
	lua_setfield(l, -2, "PPC_INS_SLBIA");
	lua_pushinteger(l, 417);
	lua_setfield(l, -2, "PPC_INS_SLBIE");
	lua_pushinteger(l, 418);
	lua_setfield(l, -2, "PPC_INS_SLBMFEE");
	lua_pushinteger(l, 419);
	lua_setfield(l, -2, "PPC_INS_SLBMTE");
	lua_pushinteger(l, 420);
	lua_setfield(l, -2, "PPC_INS_SLD");
	lua_pushinteger(l, 421);
	lua_setfield(l, -2, "PPC_INS_SLW");
	lua_pushinteger(l, 422);
	lua_setfield(l, -2, "PPC_INS_SRAD");
	lua_pushinteger(l, 423);
	lua_setfield(l, -2, "PPC_INS_SRADI");
	lua_pushinteger(l, 424);
	lua_setfield(l, -2, "PPC_INS_SRAW");
	lua_pushinteger(l, 425);
	lua_setfield(l, -2, "PPC_INS_SRAWI");
	lua_pushinteger(l, 426);
	lua_setfield(l, -2, "PPC_INS_SRD");
	lua_pushinteger(l, 427);
	lua_setfield(l, -2, "PPC_INS_SRW");
	lua_pushinteger(l, 428);
	lua_setfield(l, -2, "PPC_INS_STB");
	lua_pushinteger(l, 429);
	lua_setfield(l, -2, "PPC_INS_STBU");
	lua_pushinteger(l, 430);
	lua_setfield(l, -2, "PPC_INS_STBUX");
	lua_pushinteger(l, 431);
	lua_setfield(l, -2, "PPC_INS_STBX");
	lua_pushinteger(l, 432);
	lua_setfield(l, -2, "PPC_INS_STD");
	lua_pushinteger(l, 433);
	lua_setfield(l, -2, "PPC_INS_STDBRX");
	lua_pushinteger(l, 434);
	lua_setfield(l, -2, "PPC_INS_STDCX");
	lua_pushinteger(l, 435);
	lua_setfield(l, -2, "PPC_INS_STDU");
	lua_pushinteger(l, 436);
	lua_setfield(l, -2, "PPC_INS_STDUX");
	lua_pushinteger(l, 437);
	lua_setfield(l, -2, "PPC_INS_STDX");
	lua_pushinteger(l, 438);
	lua_setfield(l, -2, "PPC_INS_STFD");
	lua_pushinteger(l, 439);
	lua_setfield(l, -2, "PPC_INS_STFDU");
	lua_pushinteger(l, 440);
	lua_setfield(l, -2, "PPC_INS_STFDUX");
	lua_pushinteger(l, 441);
	lua_setfield(l, -2, "PPC_INS_STFDX");
	lua_pushinteger(l, 442);
	lua_setfield(l, -2, "PPC_INS_STFIWX");
	lua_pushinteger(l, 443);
	lua_setfield(l, -2, "PPC_INS_STFS");
	lua_pushinteger(l, 444);
	lua_setfield(l, -2, "PPC_INS_STFSU");
	lua_pushinteger(l, 445);
	lua_setfield(l, -2, "PPC_INS_STFSUX");
	lua_pushinteger(l, 446);
	lua_setfield(l, -2, "PPC_INS_STFSX");
	lua_pushinteger(l, 447);
	lua_setfield(l, -2, "PPC_INS_STH");
	lua_pushinteger(l, 448);
	lua_setfield(l, -2, "PPC_INS_STHBRX");
	lua_pushinteger(l, 449);
	lua_setfield(l, -2, "PPC_INS_STHU");
	lua_pushinteger(l, 450);
	lua_setfield(l, -2, "PPC_INS_STHUX");
	lua_pushinteger(l, 451);
	lua_setfield(l, -2, "PPC_INS_STHX");
	lua_pushinteger(l, 452);
	lua_setfield(l, -2, "PPC_INS_STMW");
	lua_pushinteger(l, 453);
	lua_setfield(l, -2, "PPC_INS_STSWI");
	lua_pushinteger(l, 454);
	lua_setfield(l, -2, "PPC_INS_STVEBX");
	lua_pushinteger(l, 455);
	lua_setfield(l, -2, "PPC_INS_STVEHX");
	lua_pushinteger(l, 456);
	lua_setfield(l, -2, "PPC_INS_STVEWX");
	lua_pushinteger(l, 457);
	lua_setfield(l, -2, "PPC_INS_STVX");
	lua_pushinteger(l, 458);
	lua_setfield(l, -2, "PPC_INS_STVXL");
	lua_pushinteger(l, 459);
	lua_setfield(l, -2, "PPC_INS_STW");
	lua_pushinteger(l, 460);
	lua_setfield(l, -2, "PPC_INS_STWBRX");
	lua_pushinteger(l, 461);
	lua_setfield(l, -2, "PPC_INS_STWCX");
	lua_pushinteger(l, 462);
	lua_setfield(l, -2, "PPC_INS_STWU");
	lua_pushinteger(l, 463);
	lua_setfield(l, -2, "PPC_INS_STWUX");
	lua_pushinteger(l, 464);
	lua_setfield(l, -2, "PPC_INS_STWX");
	lua_pushinteger(l, 465);
	lua_setfield(l, -2, "PPC_INS_STXSDX");
	lua_pushinteger(l, 466);
	lua_setfield(l, -2, "PPC_INS_STXVD2X");
	lua_pushinteger(l, 467);
	lua_setfield(l, -2, "PPC_INS_STXVW4X");
	lua_pushinteger(l, 468);
	lua_setfield(l, -2, "PPC_INS_SUBF");
	lua_pushinteger(l, 469);
	lua_setfield(l, -2, "PPC_INS_SUBFC");
	lua_pushinteger(l, 470);
	lua_setfield(l, -2, "PPC_INS_SUBFE");
	lua_pushinteger(l, 471);
	lua_setfield(l, -2, "PPC_INS_SUBFIC");
	lua_pushinteger(l, 472);
	lua_setfield(l, -2, "PPC_INS_SUBFME");
	lua_pushinteger(l, 473);
	lua_setfield(l, -2, "PPC_INS_SUBFZE");
	lua_pushinteger(l, 474);
	lua_setfield(l, -2, "PPC_INS_SYNC");
	lua_pushinteger(l, 475);
	lua_setfield(l, -2, "PPC_INS_TD");
	lua_pushinteger(l, 476);
	lua_setfield(l, -2, "PPC_INS_TDI");
	lua_pushinteger(l, 477);
	lua_setfield(l, -2, "PPC_INS_TLBIA");
	lua_pushinteger(l, 478);
	lua_setfield(l, -2, "PPC_INS_TLBIE");
	lua_pushinteger(l, 479);
	lua_setfield(l, -2, "PPC_INS_TLBIEL");
	lua_pushinteger(l, 480);
	lua_setfield(l, -2, "PPC_INS_TLBIVAX");
	lua_pushinteger(l, 481);
	lua_setfield(l, -2, "PPC_INS_TLBLD");
	lua_pushinteger(l, 482);
	lua_setfield(l, -2, "PPC_INS_TLBLI");
	lua_pushinteger(l, 483);
	lua_setfield(l, -2, "PPC_INS_TLBRE");
	lua_pushinteger(l, 484);
	lua_setfield(l, -2, "PPC_INS_TLBSX");
	lua_pushinteger(l, 485);
	lua_setfield(l, -2, "PPC_INS_TLBSYNC");
	lua_pushinteger(l, 486);
	lua_setfield(l, -2, "PPC_INS_TLBWE");
	lua_pushinteger(l, 487);
	lua_setfield(l, -2, "PPC_INS_TRAP");
	lua_pushinteger(l, 488);
	lua_setfield(l, -2, "PPC_INS_TW");
	lua_pushinteger(l, 489);
	lua_setfield(l, -2, "PPC_INS_TWI");
	lua_pushinteger(l, 490);
	lua_setfield(l, -2, "PPC_INS_VADDCUW");
	lua_pushinteger(l, 491);
	lua_setfield(l, -2, "PPC_INS_VADDFP");
	lua_pushinteger(l, 492);
	lua_setfield(l, -2, "PPC_INS_VADDSBS");
	lua_pushinteger(l, 493);
	lua_setfield(l, -2, "PPC_INS_VADDSHS");
	lua_pushinteger(l, 494);
	lua_setfield(l, -2, "PPC_INS_VADDSWS");
	lua_pushinteger(l, 495);
	lua_setfield(l, -2, "PPC_INS_VADDUBM");
	lua_pushinteger(l, 496);
	lua_setfield(l, -2, "PPC_INS_VADDUBS");
	lua_pushinteger(l, 497);
	lua_setfield(l, -2, "PPC_INS_VADDUHM");
	lua_pushinteger(l, 498);
	lua_setfield(l, -2, "PPC_INS_VADDUHS");
	lua_pushinteger(l, 499);
	lua_setfield(l, -2, "PPC_INS_VADDUWM");
	lua_pushinteger(l, 500);
	lua_setfield(l, -2, "PPC_INS_VADDUWS");
	lua_pushinteger(l, 501);
	lua_setfield(l, -2, "PPC_INS_VAND");
	lua_pushinteger(l, 502);
	lua_setfield(l, -2, "PPC_INS_VANDC");
	lua_pushinteger(l, 503);
	lua_setfield(l, -2, "PPC_INS_VAVGSB");
	lua_pushinteger(l, 504);
	lua_setfield(l, -2, "PPC_INS_VAVGSH");
	lua_pushinteger(l, 505);
	lua_setfield(l, -2, "PPC_INS_VAVGSW");
	lua_pushinteger(l, 506);
	lua_setfield(l, -2, "PPC_INS_VAVGUB");
	lua_pushinteger(l, 507);
	lua_setfield(l, -2, "PPC_INS_VAVGUH");
	lua_pushinteger(l, 508);
	lua_setfield(l, -2, "PPC_INS_VAVGUW");
	lua_pushinteger(l, 509);
	lua_setfield(l, -2, "PPC_INS_VCFSX");
	lua_pushinteger(l, 510);
	lua_setfield(l, -2, "PPC_INS_VCFUX");
	lua_pushinteger(l, 511);
	lua_setfield(l, -2, "PPC_INS_VCMPBFP");
	lua_pushinteger(l, 512);
	lua_setfield(l, -2, "PPC_INS_VCMPEQFP");
	lua_pushinteger(l, 513);
	lua_setfield(l, -2, "PPC_INS_VCMPEQUB");
	lua_pushinteger(l, 514);
	lua_setfield(l, -2, "PPC_INS_VCMPEQUH");
	lua_pushinteger(l, 515);
	lua_setfield(l, -2, "PPC_INS_VCMPEQUW");
	lua_pushinteger(l, 516);
	lua_setfield(l, -2, "PPC_INS_VCMPGEFP");
	lua_pushinteger(l, 517);
	lua_setfield(l, -2, "PPC_INS_VCMPGTFP");
	lua_pushinteger(l, 518);
	lua_setfield(l, -2, "PPC_INS_VCMPGTSB");
	lua_pushinteger(l, 519);
	lua_setfield(l, -2, "PPC_INS_VCMPGTSH");
	lua_pushinteger(l, 520);
	lua_setfield(l, -2, "PPC_INS_VCMPGTSW");
	lua_pushinteger(l, 521);
	lua_setfield(l, -2, "PPC_INS_VCMPGTUB");
	lua_pushinteger(l, 522);
	lua_setfield(l, -2, "PPC_INS_VCMPGTUH");
	lua_pushinteger(l, 523);
	lua_setfield(l, -2, "PPC_INS_VCMPGTUW");
	lua_pushinteger(l, 524);
	lua_setfield(l, -2, "PPC_INS_VCTSXS");
	lua_pushinteger(l, 525);
	lua_setfield(l, -2, "PPC_INS_VCTUXS");
	lua_pushinteger(l, 526);
	lua_setfield(l, -2, "PPC_INS_VEXPTEFP");
	lua_pushinteger(l, 527);
	lua_setfield(l, -2, "PPC_INS_VLOGEFP");
	lua_pushinteger(l, 528);
	lua_setfield(l, -2, "PPC_INS_VMADDFP");
	lua_pushinteger(l, 529);
	lua_setfield(l, -2, "PPC_INS_VMAXFP");
	lua_pushinteger(l, 530);
	lua_setfield(l, -2, "PPC_INS_VMAXSB");
	lua_pushinteger(l, 531);
	lua_setfield(l, -2, "PPC_INS_VMAXSH");
	lua_pushinteger(l, 532);
	lua_setfield(l, -2, "PPC_INS_VMAXSW");
	lua_pushinteger(l, 533);
	lua_setfield(l, -2, "PPC_INS_VMAXUB");
	lua_pushinteger(l, 534);
	lua_setfield(l, -2, "PPC_INS_VMAXUH");
	lua_pushinteger(l, 535);
	lua_setfield(l, -2, "PPC_INS_VMAXUW");
	lua_pushinteger(l, 536);
	lua_setfield(l, -2, "PPC_INS_VMHADDSHS");
	lua_pushinteger(l, 537);
	lua_setfield(l, -2, "PPC_INS_VMHRADDSHS");
	lua_pushinteger(l, 538);
	lua_setfield(l, -2, "PPC_INS_VMINFP");
	lua_pushinteger(l, 539);
	lua_setfield(l, -2, "PPC_INS_VMINSB");
	lua_pushinteger(l, 540);
	lua_setfield(l, -2, "PPC_INS_VMINSH");
	lua_pushinteger(l, 541);
	lua_setfield(l, -2, "PPC_INS_VMINSW");
	lua_pushinteger(l, 542);
	lua_setfield(l, -2, "PPC_INS_VMINUB");
	lua_pushinteger(l, 543);
	lua_setfield(l, -2, "PPC_INS_VMINUH");
	lua_pushinteger(l, 544);
	lua_setfield(l, -2, "PPC_INS_VMINUW");
	lua_pushinteger(l, 545);
	lua_setfield(l, -2, "PPC_INS_VMLADDUHM");
	lua_pushinteger(l, 546);
	lua_setfield(l, -2, "PPC_INS_VMRGHB");
	lua_pushinteger(l, 547);
	lua_setfield(l, -2, "PPC_INS_VMRGHH");
	lua_pushinteger(l, 548);
	lua_setfield(l, -2, "PPC_INS_VMRGHW");
	lua_pushinteger(l, 549);
	lua_setfield(l, -2, "PPC_INS_VMRGLB");
	lua_pushinteger(l, 550);
	lua_setfield(l, -2, "PPC_INS_VMRGLH");
	lua_pushinteger(l, 551);
	lua_setfield(l, -2, "PPC_INS_VMRGLW");
	lua_pushinteger(l, 552);
	lua_setfield(l, -2, "PPC_INS_VMSUMMBM");
	lua_pushinteger(l, 553);
	lua_setfield(l, -2, "PPC_INS_VMSUMSHM");
	lua_pushinteger(l, 554);
	lua_setfield(l, -2, "PPC_INS_VMSUMSHS");
	lua_pushinteger(l, 555);
	lua_setfield(l, -2, "PPC_INS_VMSUMUBM");
	lua_pushinteger(l, 556);
	lua_setfield(l, -2, "PPC_INS_VMSUMUHM");
	lua_pushinteger(l, 557);
	lua_setfield(l, -2, "PPC_INS_VMSUMUHS");
	lua_pushinteger(l, 558);
	lua_setfield(l, -2, "PPC_INS_VMULESB");
	lua_pushinteger(l, 559);
	lua_setfield(l, -2, "PPC_INS_VMULESH");
	lua_pushinteger(l, 560);
	lua_setfield(l, -2, "PPC_INS_VMULEUB");
	lua_pushinteger(l, 561);
	lua_setfield(l, -2, "PPC_INS_VMULEUH");
	lua_pushinteger(l, 562);
	lua_setfield(l, -2, "PPC_INS_VMULOSB");
	lua_pushinteger(l, 563);
	lua_setfield(l, -2, "PPC_INS_VMULOSH");
	lua_pushinteger(l, 564);
	lua_setfield(l, -2, "PPC_INS_VMULOUB");
	lua_pushinteger(l, 565);
	lua_setfield(l, -2, "PPC_INS_VMULOUH");
	lua_pushinteger(l, 566);
	lua_setfield(l, -2, "PPC_INS_VNMSUBFP");
	lua_pushinteger(l, 567);
	lua_setfield(l, -2, "PPC_INS_VNOR");
	lua_pushinteger(l, 568);
	lua_setfield(l, -2, "PPC_INS_VOR");
	lua_pushinteger(l, 569);
	lua_setfield(l, -2, "PPC_INS_VPERM");
	lua_pushinteger(l, 570);
	lua_setfield(l, -2, "PPC_INS_VPKPX");
	lua_pushinteger(l, 571);
	lua_setfield(l, -2, "PPC_INS_VPKSHSS");
	lua_pushinteger(l, 572);
	lua_setfield(l, -2, "PPC_INS_VPKSHUS");
	lua_pushinteger(l, 573);
	lua_setfield(l, -2, "PPC_INS_VPKSWSS");
	lua_pushinteger(l, 574);
	lua_setfield(l, -2, "PPC_INS_VPKSWUS");
	lua_pushinteger(l, 575);
	lua_setfield(l, -2, "PPC_INS_VPKUHUM");
	lua_pushinteger(l, 576);
	lua_setfield(l, -2, "PPC_INS_VPKUHUS");
	lua_pushinteger(l, 577);
	lua_setfield(l, -2, "PPC_INS_VPKUWUM");
	lua_pushinteger(l, 578);
	lua_setfield(l, -2, "PPC_INS_VPKUWUS");
	lua_pushinteger(l, 579);
	lua_setfield(l, -2, "PPC_INS_VREFP");
	lua_pushinteger(l, 580);
	lua_setfield(l, -2, "PPC_INS_VRFIM");
	lua_pushinteger(l, 581);
	lua_setfield(l, -2, "PPC_INS_VRFIN");
	lua_pushinteger(l, 582);
	lua_setfield(l, -2, "PPC_INS_VRFIP");
	lua_pushinteger(l, 583);
	lua_setfield(l, -2, "PPC_INS_VRFIZ");
	lua_pushinteger(l, 584);
	lua_setfield(l, -2, "PPC_INS_VRLB");
	lua_pushinteger(l, 585);
	lua_setfield(l, -2, "PPC_INS_VRLH");
	lua_pushinteger(l, 586);
	lua_setfield(l, -2, "PPC_INS_VRLW");
	lua_pushinteger(l, 587);
	lua_setfield(l, -2, "PPC_INS_VRSQRTEFP");
	lua_pushinteger(l, 588);
	lua_setfield(l, -2, "PPC_INS_VSEL");
	lua_pushinteger(l, 589);
	lua_setfield(l, -2, "PPC_INS_VSL");
	lua_pushinteger(l, 590);
	lua_setfield(l, -2, "PPC_INS_VSLB");
	lua_pushinteger(l, 591);
	lua_setfield(l, -2, "PPC_INS_VSLDOI");
	lua_pushinteger(l, 592);
	lua_setfield(l, -2, "PPC_INS_VSLH");
	lua_pushinteger(l, 593);
	lua_setfield(l, -2, "PPC_INS_VSLO");
	lua_pushinteger(l, 594);
	lua_setfield(l, -2, "PPC_INS_VSLW");
	lua_pushinteger(l, 595);
	lua_setfield(l, -2, "PPC_INS_VSPLTB");
	lua_pushinteger(l, 596);
	lua_setfield(l, -2, "PPC_INS_VSPLTH");
	lua_pushinteger(l, 597);
	lua_setfield(l, -2, "PPC_INS_VSPLTISB");
	lua_pushinteger(l, 598);
	lua_setfield(l, -2, "PPC_INS_VSPLTISH");
	lua_pushinteger(l, 599);
	lua_setfield(l, -2, "PPC_INS_VSPLTISW");
	lua_pushinteger(l, 600);
	lua_setfield(l, -2, "PPC_INS_VSPLTW");
	lua_pushinteger(l, 601);
	lua_setfield(l, -2, "PPC_INS_VSR");
	lua_pushinteger(l, 602);
	lua_setfield(l, -2, "PPC_INS_VSRAB");
	lua_pushinteger(l, 603);
	lua_setfield(l, -2, "PPC_INS_VSRAH");
	lua_pushinteger(l, 604);
	lua_setfield(l, -2, "PPC_INS_VSRAW");
	lua_pushinteger(l, 605);
	lua_setfield(l, -2, "PPC_INS_VSRB");
	lua_pushinteger(l, 606);
	lua_setfield(l, -2, "PPC_INS_VSRH");
	lua_pushinteger(l, 607);
	lua_setfield(l, -2, "PPC_INS_VSRO");
	lua_pushinteger(l, 608);
	lua_setfield(l, -2, "PPC_INS_VSRW");
	lua_pushinteger(l, 609);
	lua_setfield(l, -2, "PPC_INS_VSUBCUW");
	lua_pushinteger(l, 610);
	lua_setfield(l, -2, "PPC_INS_VSUBFP");
	lua_pushinteger(l, 611);
	lua_setfield(l, -2, "PPC_INS_VSUBSBS");
	lua_pushinteger(l, 612);
	lua_setfield(l, -2, "PPC_INS_VSUBSHS");
	lua_pushinteger(l, 613);
	lua_setfield(l, -2, "PPC_INS_VSUBSWS");
	lua_pushinteger(l, 614);
	lua_setfield(l, -2, "PPC_INS_VSUBUBM");
	lua_pushinteger(l, 615);
	lua_setfield(l, -2, "PPC_INS_VSUBUBS");
	lua_pushinteger(l, 616);
	lua_setfield(l, -2, "PPC_INS_VSUBUHM");
	lua_pushinteger(l, 617);
	lua_setfield(l, -2, "PPC_INS_VSUBUHS");
	lua_pushinteger(l, 618);
	lua_setfield(l, -2, "PPC_INS_VSUBUWM");
	lua_pushinteger(l, 619);
	lua_setfield(l, -2, "PPC_INS_VSUBUWS");
	lua_pushinteger(l, 620);
	lua_setfield(l, -2, "PPC_INS_VSUM2SWS");
	lua_pushinteger(l, 621);
	lua_setfield(l, -2, "PPC_INS_VSUM4SBS");
	lua_pushinteger(l, 622);
	lua_setfield(l, -2, "PPC_INS_VSUM4SHS");
	lua_pushinteger(l, 623);
	lua_setfield(l, -2, "PPC_INS_VSUM4UBS");
	lua_pushinteger(l, 624);
	lua_setfield(l, -2, "PPC_INS_VSUMSWS");
	lua_pushinteger(l, 625);
	lua_setfield(l, -2, "PPC_INS_VUPKHPX");
	lua_pushinteger(l, 626);
	lua_setfield(l, -2, "PPC_INS_VUPKHSB");
	lua_pushinteger(l, 627);
	lua_setfield(l, -2, "PPC_INS_VUPKHSH");
	lua_pushinteger(l, 628);
	lua_setfield(l, -2, "PPC_INS_VUPKLPX");
	lua_pushinteger(l, 629);
	lua_setfield(l, -2, "PPC_INS_VUPKLSB");
	lua_pushinteger(l, 630);
	lua_setfield(l, -2, "PPC_INS_VUPKLSH");
	lua_pushinteger(l, 631);
	lua_setfield(l, -2, "PPC_INS_VXOR");
	lua_pushinteger(l, 632);
	lua_setfield(l, -2, "PPC_INS_WAIT");
	lua_pushinteger(l, 633);
	lua_setfield(l, -2, "PPC_INS_WRTEE");
	lua_pushinteger(l, 634);
	lua_setfield(l, -2, "PPC_INS_WRTEEI");
	lua_pushinteger(l, 635);
	lua_setfield(l, -2, "PPC_INS_XOR");
	lua_pushinteger(l, 636);
	lua_setfield(l, -2, "PPC_INS_XORI");
	lua_pushinteger(l, 637);
	lua_setfield(l, -2, "PPC_INS_XORIS");
	lua_pushinteger(l, 638);
	lua_setfield(l, -2, "PPC_INS_XSABSDP");
	lua_pushinteger(l, 639);
	lua_setfield(l, -2, "PPC_INS_XSADDDP");
	lua_pushinteger(l, 640);
	lua_setfield(l, -2, "PPC_INS_XSCMPODP");
	lua_pushinteger(l, 641);
	lua_setfield(l, -2, "PPC_INS_XSCMPUDP");
	lua_pushinteger(l, 642);
	lua_setfield(l, -2, "PPC_INS_XSCPSGNDP");
	lua_pushinteger(l, 643);
	lua_setfield(l, -2, "PPC_INS_XSCVDPSP");
	lua_pushinteger(l, 644);
	lua_setfield(l, -2, "PPC_INS_XSCVDPSXDS");
	lua_pushinteger(l, 645);
	lua_setfield(l, -2, "PPC_INS_XSCVDPSXWS");
	lua_pushinteger(l, 646);
	lua_setfield(l, -2, "PPC_INS_XSCVDPUXDS");
	lua_pushinteger(l, 647);
	lua_setfield(l, -2, "PPC_INS_XSCVDPUXWS");
	lua_pushinteger(l, 648);
	lua_setfield(l, -2, "PPC_INS_XSCVSPDP");
	lua_pushinteger(l, 649);
	lua_setfield(l, -2, "PPC_INS_XSCVSXDDP");
	lua_pushinteger(l, 650);
	lua_setfield(l, -2, "PPC_INS_XSCVUXDDP");
	lua_pushinteger(l, 651);
	lua_setfield(l, -2, "PPC_INS_XSDIVDP");
	lua_pushinteger(l, 652);
	lua_setfield(l, -2, "PPC_INS_XSMADDADP");
	lua_pushinteger(l, 653);
	lua_setfield(l, -2, "PPC_INS_XSMADDMDP");
	lua_pushinteger(l, 654);
	lua_setfield(l, -2, "PPC_INS_XSMAXDP");
	lua_pushinteger(l, 655);
	lua_setfield(l, -2, "PPC_INS_XSMINDP");
	lua_pushinteger(l, 656);
	lua_setfield(l, -2, "PPC_INS_XSMSUBADP");
	lua_pushinteger(l, 657);
	lua_setfield(l, -2, "PPC_INS_XSMSUBMDP");
	lua_pushinteger(l, 658);
	lua_setfield(l, -2, "PPC_INS_XSMULDP");
	lua_pushinteger(l, 659);
	lua_setfield(l, -2, "PPC_INS_XSNABSDP");
	lua_pushinteger(l, 660);
	lua_setfield(l, -2, "PPC_INS_XSNEGDP");
	lua_pushinteger(l, 661);
	lua_setfield(l, -2, "PPC_INS_XSNMADDADP");
	lua_pushinteger(l, 662);
	lua_setfield(l, -2, "PPC_INS_XSNMADDMDP");
	lua_pushinteger(l, 663);
	lua_setfield(l, -2, "PPC_INS_XSNMSUBADP");
	lua_pushinteger(l, 664);
	lua_setfield(l, -2, "PPC_INS_XSNMSUBMDP");
	lua_pushinteger(l, 665);
	lua_setfield(l, -2, "PPC_INS_XSRDPI");
	lua_pushinteger(l, 666);
	lua_setfield(l, -2, "PPC_INS_XSRDPIC");
	lua_pushinteger(l, 667);
	lua_setfield(l, -2, "PPC_INS_XSRDPIM");
	lua_pushinteger(l, 668);
	lua_setfield(l, -2, "PPC_INS_XSRDPIP");
	lua_pushinteger(l, 669);
	lua_setfield(l, -2, "PPC_INS_XSRDPIZ");
	lua_pushinteger(l, 670);
	lua_setfield(l, -2, "PPC_INS_XSREDP");
	lua_pushinteger(l, 671);
	lua_setfield(l, -2, "PPC_INS_XSRSQRTEDP");
	lua_pushinteger(l, 672);
	lua_setfield(l, -2, "PPC_INS_XSSQRTDP");
	lua_pushinteger(l, 673);
	lua_setfield(l, -2, "PPC_INS_XSSUBDP");
	lua_pushinteger(l, 674);
	lua_setfield(l, -2, "PPC_INS_XSTDIVDP");
	lua_pushinteger(l, 675);
	lua_setfield(l, -2, "PPC_INS_XSTSQRTDP");
	lua_pushinteger(l, 676);
	lua_setfield(l, -2, "PPC_INS_XVABSDP");
	lua_pushinteger(l, 677);
	lua_setfield(l, -2, "PPC_INS_XVABSSP");
	lua_pushinteger(l, 678);
	lua_setfield(l, -2, "PPC_INS_XVADDDP");
	lua_pushinteger(l, 679);
	lua_setfield(l, -2, "PPC_INS_XVADDSP");
	lua_pushinteger(l, 680);
	lua_setfield(l, -2, "PPC_INS_XVCMPEQDP");
	lua_pushinteger(l, 681);
	lua_setfield(l, -2, "PPC_INS_XVCMPEQSP");
	lua_pushinteger(l, 682);
	lua_setfield(l, -2, "PPC_INS_XVCMPGEDP");
	lua_pushinteger(l, 683);
	lua_setfield(l, -2, "PPC_INS_XVCMPGESP");
	lua_pushinteger(l, 684);
	lua_setfield(l, -2, "PPC_INS_XVCMPGTDP");
	lua_pushinteger(l, 685);
	lua_setfield(l, -2, "PPC_INS_XVCMPGTSP");
	lua_pushinteger(l, 686);
	lua_setfield(l, -2, "PPC_INS_XVCPSGNDP");
	lua_pushinteger(l, 687);
	lua_setfield(l, -2, "PPC_INS_XVCPSGNSP");
	lua_pushinteger(l, 688);
	lua_setfield(l, -2, "PPC_INS_XVCVDPSP");
	lua_pushinteger(l, 689);
	lua_setfield(l, -2, "PPC_INS_XVCVDPSXDS");
	lua_pushinteger(l, 690);
	lua_setfield(l, -2, "PPC_INS_XVCVDPSXWS");
	lua_pushinteger(l, 691);
	lua_setfield(l, -2, "PPC_INS_XVCVDPUXDS");
	lua_pushinteger(l, 692);
	lua_setfield(l, -2, "PPC_INS_XVCVDPUXWS");
	lua_pushinteger(l, 693);
	lua_setfield(l, -2, "PPC_INS_XVCVSPDP");
	lua_pushinteger(l, 694);
	lua_setfield(l, -2, "PPC_INS_XVCVSPSXDS");
	lua_pushinteger(l, 695);
	lua_setfield(l, -2, "PPC_INS_XVCVSPSXWS");
	lua_pushinteger(l, 696);
	lua_setfield(l, -2, "PPC_INS_XVCVSPUXDS");
	lua_pushinteger(l, 697);
	lua_setfield(l, -2, "PPC_INS_XVCVSPUXWS");
	lua_pushinteger(l, 698);
	lua_setfield(l, -2, "PPC_INS_XVCVSXDDP");
	lua_pushinteger(l, 699);
	lua_setfield(l, -2, "PPC_INS_XVCVSXDSP");
	lua_pushinteger(l, 700);
	lua_setfield(l, -2, "PPC_INS_XVCVSXWDP");
	lua_pushinteger(l, 701);
	lua_setfield(l, -2, "PPC_INS_XVCVSXWSP");
	lua_pushinteger(l, 702);
	lua_setfield(l, -2, "PPC_INS_XVCVUXDDP");
	lua_pushinteger(l, 703);
	lua_setfield(l, -2, "PPC_INS_XVCVUXDSP");
	lua_pushinteger(l, 704);
	lua_setfield(l, -2, "PPC_INS_XVCVUXWDP");
	lua_pushinteger(l, 705);
	lua_setfield(l, -2, "PPC_INS_XVCVUXWSP");
	lua_pushinteger(l, 706);
	lua_setfield(l, -2, "PPC_INS_XVDIVDP");
	lua_pushinteger(l, 707);
	lua_setfield(l, -2, "PPC_INS_XVDIVSP");
	lua_pushinteger(l, 708);
	lua_setfield(l, -2, "PPC_INS_XVMADDADP");
	lua_pushinteger(l, 709);
	lua_setfield(l, -2, "PPC_INS_XVMADDASP");
	lua_pushinteger(l, 710);
	lua_setfield(l, -2, "PPC_INS_XVMADDMDP");
	lua_pushinteger(l, 711);
	lua_setfield(l, -2, "PPC_INS_XVMADDMSP");
	lua_pushinteger(l, 712);
	lua_setfield(l, -2, "PPC_INS_XVMAXDP");
	lua_pushinteger(l, 713);
	lua_setfield(l, -2, "PPC_INS_XVMAXSP");
	lua_pushinteger(l, 714);
	lua_setfield(l, -2, "PPC_INS_XVMINDP");
	lua_pushinteger(l, 715);
	lua_setfield(l, -2, "PPC_INS_XVMINSP");
	lua_pushinteger(l, 716);
	lua_setfield(l, -2, "PPC_INS_XVMSUBADP");
	lua_pushinteger(l, 717);
	lua_setfield(l, -2, "PPC_INS_XVMSUBASP");
	lua_pushinteger(l, 718);
	lua_setfield(l, -2, "PPC_INS_XVMSUBMDP");
	lua_pushinteger(l, 719);
	lua_setfield(l, -2, "PPC_INS_XVMSUBMSP");
	lua_pushinteger(l, 720);
	lua_setfield(l, -2, "PPC_INS_XVMULDP");
	lua_pushinteger(l, 721);
	lua_setfield(l, -2, "PPC_INS_XVMULSP");
	lua_pushinteger(l, 722);
	lua_setfield(l, -2, "PPC_INS_XVNABSDP");
	lua_pushinteger(l, 723);
	lua_setfield(l, -2, "PPC_INS_XVNABSSP");
	lua_pushinteger(l, 724);
	lua_setfield(l, -2, "PPC_INS_XVNEGDP");
	lua_pushinteger(l, 725);
	lua_setfield(l, -2, "PPC_INS_XVNEGSP");
	lua_pushinteger(l, 726);
	lua_setfield(l, -2, "PPC_INS_XVNMADDADP");
	lua_pushinteger(l, 727);
	lua_setfield(l, -2, "PPC_INS_XVNMADDASP");
	lua_pushinteger(l, 728);
	lua_setfield(l, -2, "PPC_INS_XVNMADDMDP");
	lua_pushinteger(l, 729);
	lua_setfield(l, -2, "PPC_INS_XVNMADDMSP");
	lua_pushinteger(l, 730);
	lua_setfield(l, -2, "PPC_INS_XVNMSUBADP");
	lua_pushinteger(l, 731);
	lua_setfield(l, -2, "PPC_INS_XVNMSUBASP");
	lua_pushinteger(l, 732);
	lua_setfield(l, -2, "PPC_INS_XVNMSUBMDP");
	lua_pushinteger(l, 733);
	lua_setfield(l, -2, "PPC_INS_XVNMSUBMSP");
	lua_pushinteger(l, 734);
	lua_setfield(l, -2, "PPC_INS_XVRDPI");
	lua_pushinteger(l, 735);
	lua_setfield(l, -2, "PPC_INS_XVRDPIC");
	lua_pushinteger(l, 736);
	lua_setfield(l, -2, "PPC_INS_XVRDPIM");
	lua_pushinteger(l, 737);
	lua_setfield(l, -2, "PPC_INS_XVRDPIP");
	lua_pushinteger(l, 738);
	lua_setfield(l, -2, "PPC_INS_XVRDPIZ");
	lua_pushinteger(l, 739);
	lua_setfield(l, -2, "PPC_INS_XVREDP");
	lua_pushinteger(l, 740);
	lua_setfield(l, -2, "PPC_INS_XVRESP");
	lua_pushinteger(l, 741);
	lua_setfield(l, -2, "PPC_INS_XVRSPI");
	lua_pushinteger(l, 742);
	lua_setfield(l, -2, "PPC_INS_XVRSPIC");
	lua_pushinteger(l, 743);
	lua_setfield(l, -2, "PPC_INS_XVRSPIM");
	lua_pushinteger(l, 744);
	lua_setfield(l, -2, "PPC_INS_XVRSPIP");
	lua_pushinteger(l, 745);
	lua_setfield(l, -2, "PPC_INS_XVRSPIZ");
	lua_pushinteger(l, 746);
	lua_setfield(l, -2, "PPC_INS_XVRSQRTEDP");
	lua_pushinteger(l, 747);
	lua_setfield(l, -2, "PPC_INS_XVRSQRTESP");
	lua_pushinteger(l, 748);
	lua_setfield(l, -2, "PPC_INS_XVSQRTDP");
	lua_pushinteger(l, 749);
	lua_setfield(l, -2, "PPC_INS_XVSQRTSP");
	lua_pushinteger(l, 750);
	lua_setfield(l, -2, "PPC_INS_XVSUBDP");
	lua_pushinteger(l, 751);
	lua_setfield(l, -2, "PPC_INS_XVSUBSP");
	lua_pushinteger(l, 752);
	lua_setfield(l, -2, "PPC_INS_XVTDIVDP");
	lua_pushinteger(l, 753);
	lua_setfield(l, -2, "PPC_INS_XVTDIVSP");
	lua_pushinteger(l, 754);
	lua_setfield(l, -2, "PPC_INS_XVTSQRTDP");
	lua_pushinteger(l, 755);
	lua_setfield(l, -2, "PPC_INS_XVTSQRTSP");
	lua_pushinteger(l, 756);
	lua_setfield(l, -2, "PPC_INS_XXLAND");
	lua_pushinteger(l, 757);
	lua_setfield(l, -2, "PPC_INS_XXLANDC");
	lua_pushinteger(l, 758);
	lua_setfield(l, -2, "PPC_INS_XXLNOR");
	lua_pushinteger(l, 759);
	lua_setfield(l, -2, "PPC_INS_XXLOR");
	lua_pushinteger(l, 760);
	lua_setfield(l, -2, "PPC_INS_XXLXOR");
	lua_pushinteger(l, 761);
	lua_setfield(l, -2, "PPC_INS_XXMRGHW");
	lua_pushinteger(l, 762);
	lua_setfield(l, -2, "PPC_INS_XXMRGLW");
	lua_pushinteger(l, 763);
	lua_setfield(l, -2, "PPC_INS_XXPERMDI");
	lua_pushinteger(l, 764);
	lua_setfield(l, -2, "PPC_INS_XXSEL");
	lua_pushinteger(l, 765);
	lua_setfield(l, -2, "PPC_INS_XXSLDWI");
	lua_pushinteger(l, 766);
	lua_setfield(l, -2, "PPC_INS_XXSPLTW");
	lua_pushinteger(l, 767);
	lua_setfield(l, -2, "PPC_INS_BCA");
	lua_pushinteger(l, 768);
	lua_setfield(l, -2, "PPC_INS_BCLA");
	lua_pushinteger(l, 769);
	lua_setfield(l, -2, "PPC_INS_SLWI");
	lua_pushinteger(l, 770);
	lua_setfield(l, -2, "PPC_INS_SRWI");
	lua_pushinteger(l, 771);
	lua_setfield(l, -2, "PPC_INS_SLDI");
	lua_pushinteger(l, 772);
	lua_setfield(l, -2, "PPC_INS_BTA");
	lua_pushinteger(l, 773);
	lua_setfield(l, -2, "PPC_INS_CRSET");
	lua_pushinteger(l, 774);
	lua_setfield(l, -2, "PPC_INS_CRNOT");
	lua_pushinteger(l, 775);
	lua_setfield(l, -2, "PPC_INS_CRMOVE");
	lua_pushinteger(l, 776);
	lua_setfield(l, -2, "PPC_INS_CRCLR");
	lua_pushinteger(l, 777);
	lua_setfield(l, -2, "PPC_INS_MFBR0");
	lua_pushinteger(l, 778);
	lua_setfield(l, -2, "PPC_INS_MFBR1");
	lua_pushinteger(l, 779);
	lua_setfield(l, -2, "PPC_INS_MFBR2");
	lua_pushinteger(l, 780);
	lua_setfield(l, -2, "PPC_INS_MFBR3");
	lua_pushinteger(l, 781);
	lua_setfield(l, -2, "PPC_INS_MFBR4");
	lua_pushinteger(l, 782);
	lua_setfield(l, -2, "PPC_INS_MFBR5");
	lua_pushinteger(l, 783);
	lua_setfield(l, -2, "PPC_INS_MFBR6");
	lua_pushinteger(l, 784);
	lua_setfield(l, -2, "PPC_INS_MFBR7");
	lua_pushinteger(l, 785);
	lua_setfield(l, -2, "PPC_INS_MFXER");
	lua_pushinteger(l, 786);
	lua_setfield(l, -2, "PPC_INS_MFRTCU");
	lua_pushinteger(l, 787);
	lua_setfield(l, -2, "PPC_INS_MFRTCL");
	lua_pushinteger(l, 788);
	lua_setfield(l, -2, "PPC_INS_MFDSCR");
	lua_pushinteger(l, 789);
	lua_setfield(l, -2, "PPC_INS_MFDSISR");
	lua_pushinteger(l, 790);
	lua_setfield(l, -2, "PPC_INS_MFDAR");
	lua_pushinteger(l, 791);
	lua_setfield(l, -2, "PPC_INS_MFSRR2");
	lua_pushinteger(l, 792);
	lua_setfield(l, -2, "PPC_INS_MFSRR3");
	lua_pushinteger(l, 793);
	lua_setfield(l, -2, "PPC_INS_MFCFAR");
	lua_pushinteger(l, 794);
	lua_setfield(l, -2, "PPC_INS_MFAMR");
	lua_pushinteger(l, 795);
	lua_setfield(l, -2, "PPC_INS_MFPID");
	lua_pushinteger(l, 796);
	lua_setfield(l, -2, "PPC_INS_MFTBLO");
	lua_pushinteger(l, 797);
	lua_setfield(l, -2, "PPC_INS_MFTBHI");
	lua_pushinteger(l, 798);
	lua_setfield(l, -2, "PPC_INS_MFDBATU");
	lua_pushinteger(l, 799);
	lua_setfield(l, -2, "PPC_INS_MFDBATL");
	lua_pushinteger(l, 800);
	lua_setfield(l, -2, "PPC_INS_MFIBATU");
	lua_pushinteger(l, 801);
	lua_setfield(l, -2, "PPC_INS_MFIBATL");
	lua_pushinteger(l, 802);
	lua_setfield(l, -2, "PPC_INS_MFDCCR");
	lua_pushinteger(l, 803);
	lua_setfield(l, -2, "PPC_INS_MFICCR");
	lua_pushinteger(l, 804);
	lua_setfield(l, -2, "PPC_INS_MFDEAR");
	lua_pushinteger(l, 805);
	lua_setfield(l, -2, "PPC_INS_MFESR");
	lua_pushinteger(l, 806);
	lua_setfield(l, -2, "PPC_INS_MFSPEFSCR");
	lua_pushinteger(l, 807);
	lua_setfield(l, -2, "PPC_INS_MFTCR");
	lua_pushinteger(l, 808);
	lua_setfield(l, -2, "PPC_INS_MFASR");
	lua_pushinteger(l, 809);
	lua_setfield(l, -2, "PPC_INS_MFPVR");
	lua_pushinteger(l, 810);
	lua_setfield(l, -2, "PPC_INS_MFTBU");
	lua_pushinteger(l, 811);
	lua_setfield(l, -2, "PPC_INS_MTCR");
	lua_pushinteger(l, 812);
	lua_setfield(l, -2, "PPC_INS_MTBR0");
	lua_pushinteger(l, 813);
	lua_setfield(l, -2, "PPC_INS_MTBR1");
	lua_pushinteger(l, 814);
	lua_setfield(l, -2, "PPC_INS_MTBR2");
	lua_pushinteger(l, 815);
	lua_setfield(l, -2, "PPC_INS_MTBR3");
	lua_pushinteger(l, 816);
	lua_setfield(l, -2, "PPC_INS_MTBR4");
	lua_pushinteger(l, 817);
	lua_setfield(l, -2, "PPC_INS_MTBR5");
	lua_pushinteger(l, 818);
	lua_setfield(l, -2, "PPC_INS_MTBR6");
	lua_pushinteger(l, 819);
	lua_setfield(l, -2, "PPC_INS_MTBR7");
	lua_pushinteger(l, 820);
	lua_setfield(l, -2, "PPC_INS_MTXER");
	lua_pushinteger(l, 821);
	lua_setfield(l, -2, "PPC_INS_MTDSCR");
	lua_pushinteger(l, 822);
	lua_setfield(l, -2, "PPC_INS_MTDSISR");
	lua_pushinteger(l, 823);
	lua_setfield(l, -2, "PPC_INS_MTDAR");
	lua_pushinteger(l, 824);
	lua_setfield(l, -2, "PPC_INS_MTSRR2");
	lua_pushinteger(l, 825);
	lua_setfield(l, -2, "PPC_INS_MTSRR3");
	lua_pushinteger(l, 826);
	lua_setfield(l, -2, "PPC_INS_MTCFAR");
	lua_pushinteger(l, 827);
	lua_setfield(l, -2, "PPC_INS_MTAMR");
	lua_pushinteger(l, 828);
	lua_setfield(l, -2, "PPC_INS_MTPID");
	lua_pushinteger(l, 829);
	lua_setfield(l, -2, "PPC_INS_MTTBL");
	lua_pushinteger(l, 830);
	lua_setfield(l, -2, "PPC_INS_MTTBU");
	lua_pushinteger(l, 831);
	lua_setfield(l, -2, "PPC_INS_MTTBLO");
	lua_pushinteger(l, 832);
	lua_setfield(l, -2, "PPC_INS_MTTBHI");
	lua_pushinteger(l, 833);
	lua_setfield(l, -2, "PPC_INS_MTDBATU");
	lua_pushinteger(l, 834);
	lua_setfield(l, -2, "PPC_INS_MTDBATL");
	lua_pushinteger(l, 835);
	lua_setfield(l, -2, "PPC_INS_MTIBATU");
	lua_pushinteger(l, 836);
	lua_setfield(l, -2, "PPC_INS_MTIBATL");
	lua_pushinteger(l, 837);
	lua_setfield(l, -2, "PPC_INS_MTDCCR");
	lua_pushinteger(l, 838);
	lua_setfield(l, -2, "PPC_INS_MTICCR");
	lua_pushinteger(l, 839);
	lua_setfield(l, -2, "PPC_INS_MTDEAR");
	lua_pushinteger(l, 840);
	lua_setfield(l, -2, "PPC_INS_MTESR");
	lua_pushinteger(l, 841);
	lua_setfield(l, -2, "PPC_INS_MTSPEFSCR");
	lua_pushinteger(l, 842);
	lua_setfield(l, -2, "PPC_INS_MTTCR");
	lua_pushinteger(l, 843);
	lua_setfield(l, -2, "PPC_INS_NOT");
	lua_pushinteger(l, 844);
	lua_setfield(l, -2, "PPC_INS_MR");
	lua_pushinteger(l, 845);
	lua_setfield(l, -2, "PPC_INS_ROTLD");
	lua_pushinteger(l, 846);
	lua_setfield(l, -2, "PPC_INS_ROTLDI");
	lua_pushinteger(l, 847);
	lua_setfield(l, -2, "PPC_INS_CLRLDI");
	lua_pushinteger(l, 848);
	lua_setfield(l, -2, "PPC_INS_ROTLWI");
	lua_pushinteger(l, 849);
	lua_setfield(l, -2, "PPC_INS_CLRLWI");
	lua_pushinteger(l, 850);
	lua_setfield(l, -2, "PPC_INS_ROTLW");
	lua_pushinteger(l, 851);
	lua_setfield(l, -2, "PPC_INS_SUB");
	lua_pushinteger(l, 852);
	lua_setfield(l, -2, "PPC_INS_SUBC");
	lua_pushinteger(l, 853);
	lua_setfield(l, -2, "PPC_INS_LWSYNC");
	lua_pushinteger(l, 854);
	lua_setfield(l, -2, "PPC_INS_PTESYNC");
	lua_pushinteger(l, 855);
	lua_setfield(l, -2, "PPC_INS_TDLT");
	lua_pushinteger(l, 856);
	lua_setfield(l, -2, "PPC_INS_TDEQ");
	lua_pushinteger(l, 857);
	lua_setfield(l, -2, "PPC_INS_TDGT");
	lua_pushinteger(l, 858);
	lua_setfield(l, -2, "PPC_INS_TDNE");
	lua_pushinteger(l, 859);
	lua_setfield(l, -2, "PPC_INS_TDLLT");
	lua_pushinteger(l, 860);
	lua_setfield(l, -2, "PPC_INS_TDLGT");
	lua_pushinteger(l, 861);
	lua_setfield(l, -2, "PPC_INS_TDU");
	lua_pushinteger(l, 862);
	lua_setfield(l, -2, "PPC_INS_TDLTI");
	lua_pushinteger(l, 863);
	lua_setfield(l, -2, "PPC_INS_TDEQI");
	lua_pushinteger(l, 864);
	lua_setfield(l, -2, "PPC_INS_TDGTI");
	lua_pushinteger(l, 865);
	lua_setfield(l, -2, "PPC_INS_TDNEI");
	lua_pushinteger(l, 866);
	lua_setfield(l, -2, "PPC_INS_TDLLTI");
	lua_pushinteger(l, 867);
	lua_setfield(l, -2, "PPC_INS_TDLGTI");
	lua_pushinteger(l, 868);
	lua_setfield(l, -2, "PPC_INS_TDUI");
	lua_pushinteger(l, 869);
	lua_setfield(l, -2, "PPC_INS_TLBREHI");
	lua_pushinteger(l, 870);
	lua_setfield(l, -2, "PPC_INS_TLBRELO");
	lua_pushinteger(l, 871);
	lua_setfield(l, -2, "PPC_INS_TLBWEHI");
	lua_pushinteger(l, 872);
	lua_setfield(l, -2, "PPC_INS_TLBWELO");
	lua_pushinteger(l, 873);
	lua_setfield(l, -2, "PPC_INS_TWLT");
	lua_pushinteger(l, 874);
	lua_setfield(l, -2, "PPC_INS_TWEQ");
	lua_pushinteger(l, 875);
	lua_setfield(l, -2, "PPC_INS_TWGT");
	lua_pushinteger(l, 876);
	lua_setfield(l, -2, "PPC_INS_TWNE");
	lua_pushinteger(l, 877);
	lua_setfield(l, -2, "PPC_INS_TWLLT");
	lua_pushinteger(l, 878);
	lua_setfield(l, -2, "PPC_INS_TWLGT");
	lua_pushinteger(l, 879);
	lua_setfield(l, -2, "PPC_INS_TWU");
	lua_pushinteger(l, 880);
	lua_setfield(l, -2, "PPC_INS_TWLTI");
	lua_pushinteger(l, 881);
	lua_setfield(l, -2, "PPC_INS_TWEQI");
	lua_pushinteger(l, 882);
	lua_setfield(l, -2, "PPC_INS_TWGTI");
	lua_pushinteger(l, 883);
	lua_setfield(l, -2, "PPC_INS_TWNEI");
	lua_pushinteger(l, 884);
	lua_setfield(l, -2, "PPC_INS_TWLLTI");
	lua_pushinteger(l, 885);
	lua_setfield(l, -2, "PPC_INS_TWLGTI");
	lua_pushinteger(l, 886);
	lua_setfield(l, -2, "PPC_INS_TWUI");
	lua_pushinteger(l, 887);
	lua_setfield(l, -2, "PPC_INS_WAITRSV");
	lua_pushinteger(l, 888);
	lua_setfield(l, -2, "PPC_INS_WAITIMPL");
	lua_pushinteger(l, 889);
	lua_setfield(l, -2, "PPC_INS_XNOP");
	lua_pushinteger(l, 890);
	lua_setfield(l, -2, "PPC_INS_XVMOVDP");
	lua_pushinteger(l, 891);
	lua_setfield(l, -2, "PPC_INS_XVMOVSP");
	lua_pushinteger(l, 892);
	lua_setfield(l, -2, "PPC_INS_XXSPLTD");
	lua_pushinteger(l, 893);
	lua_setfield(l, -2, "PPC_INS_XXMRGHD");
	lua_pushinteger(l, 894);
	lua_setfield(l, -2, "PPC_INS_XXMRGLD");
	lua_pushinteger(l, 895);
	lua_setfield(l, -2, "PPC_INS_XXSWAPD");
	lua_pushinteger(l, 896);
	lua_setfield(l, -2, "PPC_INS_BT");
	lua_pushinteger(l, 897);
	lua_setfield(l, -2, "PPC_INS_BF");
	lua_pushinteger(l, 898);
	lua_setfield(l, -2, "PPC_INS_BDNZT");
	lua_pushinteger(l, 899);
	lua_setfield(l, -2, "PPC_INS_BDNZF");
	lua_pushinteger(l, 900);
	lua_setfield(l, -2, "PPC_INS_BDZF");
	lua_pushinteger(l, 901);
	lua_setfield(l, -2, "PPC_INS_BDZT");
	lua_pushinteger(l, 902);
	lua_setfield(l, -2, "PPC_INS_BFA");
	lua_pushinteger(l, 903);
	lua_setfield(l, -2, "PPC_INS_BDNZTA");
	lua_pushinteger(l, 904);
	lua_setfield(l, -2, "PPC_INS_BDNZFA");
	lua_pushinteger(l, 905);
	lua_setfield(l, -2, "PPC_INS_BDZTA");
	lua_pushinteger(l, 906);
	lua_setfield(l, -2, "PPC_INS_BDZFA");
	lua_pushinteger(l, 907);
	lua_setfield(l, -2, "PPC_INS_BTCTR");
	lua_pushinteger(l, 908);
	lua_setfield(l, -2, "PPC_INS_BFCTR");
	lua_pushinteger(l, 909);
	lua_setfield(l, -2, "PPC_INS_BTCTRL");
	lua_pushinteger(l, 910);
	lua_setfield(l, -2, "PPC_INS_BFCTRL");
	lua_pushinteger(l, 911);
	lua_setfield(l, -2, "PPC_INS_BTL");
	lua_pushinteger(l, 912);
	lua_setfield(l, -2, "PPC_INS_BFL");
	lua_pushinteger(l, 913);
	lua_setfield(l, -2, "PPC_INS_BDNZTL");
	lua_pushinteger(l, 914);
	lua_setfield(l, -2, "PPC_INS_BDNZFL");
	lua_pushinteger(l, 915);
	lua_setfield(l, -2, "PPC_INS_BDZTL");
	lua_pushinteger(l, 916);
	lua_setfield(l, -2, "PPC_INS_BDZFL");
	lua_pushinteger(l, 917);
	lua_setfield(l, -2, "PPC_INS_BTLA");
	lua_pushinteger(l, 918);
	lua_setfield(l, -2, "PPC_INS_BFLA");
	lua_pushinteger(l, 919);
	lua_setfield(l, -2, "PPC_INS_BDNZTLA");
	lua_pushinteger(l, 920);
	lua_setfield(l, -2, "PPC_INS_BDNZFLA");
	lua_pushinteger(l, 921);
	lua_setfield(l, -2, "PPC_INS_BDZTLA");
	lua_pushinteger(l, 922);
	lua_setfield(l, -2, "PPC_INS_BDZFLA");
	lua_pushinteger(l, 923);
	lua_setfield(l, -2, "PPC_INS_BTLR");
	lua_pushinteger(l, 924);
	lua_setfield(l, -2, "PPC_INS_BFLR");
	lua_pushinteger(l, 925);
	lua_setfield(l, -2, "PPC_INS_BDNZTLR");
	lua_pushinteger(l, 926);
	lua_setfield(l, -2, "PPC_INS_BDZTLR");
	lua_pushinteger(l, 927);
	lua_setfield(l, -2, "PPC_INS_BDZFLR");
	lua_pushinteger(l, 928);
	lua_setfield(l, -2, "PPC_INS_BTLRL");
	lua_pushinteger(l, 929);
	lua_setfield(l, -2, "PPC_INS_BFLRL");
	lua_pushinteger(l, 930);
	lua_setfield(l, -2, "PPC_INS_BDNZTLRL");
	lua_pushinteger(l, 931);
	lua_setfield(l, -2, "PPC_INS_BDNZFLRL");
	lua_pushinteger(l, 932);
	lua_setfield(l, -2, "PPC_INS_BDZTLRL");
	lua_pushinteger(l, 933);
	lua_setfield(l, -2, "PPC_INS_BDZFLRL");
	lua_pushinteger(l, 934);
	lua_setfield(l, -2, "PPC_INS_ENDING");

	/* Group of PPC instructions */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "PPC_GRP_INVALID");

	/* Generic groups */
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "PPC_GRP_JUMP");

	/* Architecture-specific groups */
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "PPC_GRP_ALTIVEC");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "PPC_GRP_MODE32");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "PPC_GRP_MODE64");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "PPC_GRP_BOOKE");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "PPC_GRP_NOTBOOKE");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "PPC_GRP_SPE");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "PPC_GRP_VSX");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "PPC_GRP_E500");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "PPC_GRP_PPC4XX");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "PPC_GRP_PPC6XX");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "PPC_GRP_ENDING");
}