/* For Capstone Engine. AUTO-GENERATED FILE, DO NOT EDIT */

#include "sysz_const.h"

void set_sysz_const(lua_State* l)
{
	/* Enums corresponding to SystemZ condition codes */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "SYSZ_CC_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "SYSZ_CC_O");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "SYSZ_CC_H");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "SYSZ_CC_NLE");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "SYSZ_CC_L");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "SYSZ_CC_NHE");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "SYSZ_CC_LH");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "SYSZ_CC_NE");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "SYSZ_CC_E");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "SYSZ_CC_NLH");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "SYSZ_CC_HE");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "SYSZ_CC_NL");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "SYSZ_CC_LE");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "SYSZ_CC_NH");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "SYSZ_CC_NO");

	/* Operand type for instruction's operands */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "SYSZ_OP_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "SYSZ_OP_REG");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "SYSZ_OP_IMM");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "SYSZ_OP_MEM");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "SYSZ_OP_ACREG");

	/* SystemZ registers */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "SYSZ_REG_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "SYSZ_REG_0");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "SYSZ_REG_1");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "SYSZ_REG_2");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "SYSZ_REG_3");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "SYSZ_REG_4");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "SYSZ_REG_5");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "SYSZ_REG_6");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "SYSZ_REG_7");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "SYSZ_REG_8");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "SYSZ_REG_9");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "SYSZ_REG_10");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "SYSZ_REG_11");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "SYSZ_REG_12");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "SYSZ_REG_13");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "SYSZ_REG_14");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "SYSZ_REG_15");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "SYSZ_REG_CC");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "SYSZ_REG_F0");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "SYSZ_REG_F1");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "SYSZ_REG_F2");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "SYSZ_REG_F3");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "SYSZ_REG_F4");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "SYSZ_REG_F5");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "SYSZ_REG_F6");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "SYSZ_REG_F7");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "SYSZ_REG_F8");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "SYSZ_REG_F9");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "SYSZ_REG_F10");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "SYSZ_REG_F11");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "SYSZ_REG_F12");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "SYSZ_REG_F13");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "SYSZ_REG_F14");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "SYSZ_REG_F15");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "SYSZ_REG_R0L");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "SYSZ_REG_ENDING");

	/* SystemZ instruction */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "SYSZ_INS_INVALID");
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "SYSZ_INS_A");
	lua_pushinteger(l, 2);
	lua_setfield(l, -2, "SYSZ_INS_ADB");
	lua_pushinteger(l, 3);
	lua_setfield(l, -2, "SYSZ_INS_ADBR");
	lua_pushinteger(l, 4);
	lua_setfield(l, -2, "SYSZ_INS_AEB");
	lua_pushinteger(l, 5);
	lua_setfield(l, -2, "SYSZ_INS_AEBR");
	lua_pushinteger(l, 6);
	lua_setfield(l, -2, "SYSZ_INS_AFI");
	lua_pushinteger(l, 7);
	lua_setfield(l, -2, "SYSZ_INS_AG");
	lua_pushinteger(l, 8);
	lua_setfield(l, -2, "SYSZ_INS_AGF");
	lua_pushinteger(l, 9);
	lua_setfield(l, -2, "SYSZ_INS_AGFI");
	lua_pushinteger(l, 10);
	lua_setfield(l, -2, "SYSZ_INS_AGFR");
	lua_pushinteger(l, 11);
	lua_setfield(l, -2, "SYSZ_INS_AGHI");
	lua_pushinteger(l, 12);
	lua_setfield(l, -2, "SYSZ_INS_AGHIK");
	lua_pushinteger(l, 13);
	lua_setfield(l, -2, "SYSZ_INS_AGR");
	lua_pushinteger(l, 14);
	lua_setfield(l, -2, "SYSZ_INS_AGRK");
	lua_pushinteger(l, 15);
	lua_setfield(l, -2, "SYSZ_INS_AGSI");
	lua_pushinteger(l, 16);
	lua_setfield(l, -2, "SYSZ_INS_AH");
	lua_pushinteger(l, 17);
	lua_setfield(l, -2, "SYSZ_INS_AHI");
	lua_pushinteger(l, 18);
	lua_setfield(l, -2, "SYSZ_INS_AHIK");
	lua_pushinteger(l, 19);
	lua_setfield(l, -2, "SYSZ_INS_AHY");
	lua_pushinteger(l, 20);
	lua_setfield(l, -2, "SYSZ_INS_AIH");
	lua_pushinteger(l, 21);
	lua_setfield(l, -2, "SYSZ_INS_AL");
	lua_pushinteger(l, 22);
	lua_setfield(l, -2, "SYSZ_INS_ALC");
	lua_pushinteger(l, 23);
	lua_setfield(l, -2, "SYSZ_INS_ALCG");
	lua_pushinteger(l, 24);
	lua_setfield(l, -2, "SYSZ_INS_ALCGR");
	lua_pushinteger(l, 25);
	lua_setfield(l, -2, "SYSZ_INS_ALCR");
	lua_pushinteger(l, 26);
	lua_setfield(l, -2, "SYSZ_INS_ALFI");
	lua_pushinteger(l, 27);
	lua_setfield(l, -2, "SYSZ_INS_ALG");
	lua_pushinteger(l, 28);
	lua_setfield(l, -2, "SYSZ_INS_ALGF");
	lua_pushinteger(l, 29);
	lua_setfield(l, -2, "SYSZ_INS_ALGFI");
	lua_pushinteger(l, 30);
	lua_setfield(l, -2, "SYSZ_INS_ALGFR");
	lua_pushinteger(l, 31);
	lua_setfield(l, -2, "SYSZ_INS_ALGHSIK");
	lua_pushinteger(l, 32);
	lua_setfield(l, -2, "SYSZ_INS_ALGR");
	lua_pushinteger(l, 33);
	lua_setfield(l, -2, "SYSZ_INS_ALGRK");
	lua_pushinteger(l, 34);
	lua_setfield(l, -2, "SYSZ_INS_ALHSIK");
	lua_pushinteger(l, 35);
	lua_setfield(l, -2, "SYSZ_INS_ALR");
	lua_pushinteger(l, 36);
	lua_setfield(l, -2, "SYSZ_INS_ALRK");
	lua_pushinteger(l, 37);
	lua_setfield(l, -2, "SYSZ_INS_ALY");
	lua_pushinteger(l, 38);
	lua_setfield(l, -2, "SYSZ_INS_AR");
	lua_pushinteger(l, 39);
	lua_setfield(l, -2, "SYSZ_INS_ARK");
	lua_pushinteger(l, 40);
	lua_setfield(l, -2, "SYSZ_INS_ASI");
	lua_pushinteger(l, 41);
	lua_setfield(l, -2, "SYSZ_INS_AXBR");
	lua_pushinteger(l, 42);
	lua_setfield(l, -2, "SYSZ_INS_AY");
	lua_pushinteger(l, 43);
	lua_setfield(l, -2, "SYSZ_INS_BCR");
	lua_pushinteger(l, 44);
	lua_setfield(l, -2, "SYSZ_INS_BRC");
	lua_pushinteger(l, 45);
	lua_setfield(l, -2, "SYSZ_INS_BRCL");
	lua_pushinteger(l, 46);
	lua_setfield(l, -2, "SYSZ_INS_CGIJ");
	lua_pushinteger(l, 47);
	lua_setfield(l, -2, "SYSZ_INS_CGRJ");
	lua_pushinteger(l, 48);
	lua_setfield(l, -2, "SYSZ_INS_CIJ");
	lua_pushinteger(l, 49);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJ");
	lua_pushinteger(l, 50);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJ");
	lua_pushinteger(l, 51);
	lua_setfield(l, -2, "SYSZ_INS_CLIJ");
	lua_pushinteger(l, 52);
	lua_setfield(l, -2, "SYSZ_INS_CLRJ");
	lua_pushinteger(l, 53);
	lua_setfield(l, -2, "SYSZ_INS_CRJ");
	lua_pushinteger(l, 54);
	lua_setfield(l, -2, "SYSZ_INS_BER");
	lua_pushinteger(l, 55);
	lua_setfield(l, -2, "SYSZ_INS_JE");
	lua_pushinteger(l, 56);
	lua_setfield(l, -2, "SYSZ_INS_JGE");
	lua_pushinteger(l, 57);
	lua_setfield(l, -2, "SYSZ_INS_LOCE");
	lua_pushinteger(l, 58);
	lua_setfield(l, -2, "SYSZ_INS_LOCGE");
	lua_pushinteger(l, 59);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRE");
	lua_pushinteger(l, 60);
	lua_setfield(l, -2, "SYSZ_INS_LOCRE");
	lua_pushinteger(l, 61);
	lua_setfield(l, -2, "SYSZ_INS_STOCE");
	lua_pushinteger(l, 62);
	lua_setfield(l, -2, "SYSZ_INS_STOCGE");
	lua_pushinteger(l, 63);
	lua_setfield(l, -2, "SYSZ_INS_BHR");
	lua_pushinteger(l, 64);
	lua_setfield(l, -2, "SYSZ_INS_BHER");
	lua_pushinteger(l, 65);
	lua_setfield(l, -2, "SYSZ_INS_JHE");
	lua_pushinteger(l, 66);
	lua_setfield(l, -2, "SYSZ_INS_JGHE");
	lua_pushinteger(l, 67);
	lua_setfield(l, -2, "SYSZ_INS_LOCHE");
	lua_pushinteger(l, 68);
	lua_setfield(l, -2, "SYSZ_INS_LOCGHE");
	lua_pushinteger(l, 69);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRHE");
	lua_pushinteger(l, 70);
	lua_setfield(l, -2, "SYSZ_INS_LOCRHE");
	lua_pushinteger(l, 71);
	lua_setfield(l, -2, "SYSZ_INS_STOCHE");
	lua_pushinteger(l, 72);
	lua_setfield(l, -2, "SYSZ_INS_STOCGHE");
	lua_pushinteger(l, 73);
	lua_setfield(l, -2, "SYSZ_INS_JH");
	lua_pushinteger(l, 74);
	lua_setfield(l, -2, "SYSZ_INS_JGH");
	lua_pushinteger(l, 75);
	lua_setfield(l, -2, "SYSZ_INS_LOCH");
	lua_pushinteger(l, 76);
	lua_setfield(l, -2, "SYSZ_INS_LOCGH");
	lua_pushinteger(l, 77);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRH");
	lua_pushinteger(l, 78);
	lua_setfield(l, -2, "SYSZ_INS_LOCRH");
	lua_pushinteger(l, 79);
	lua_setfield(l, -2, "SYSZ_INS_STOCH");
	lua_pushinteger(l, 80);
	lua_setfield(l, -2, "SYSZ_INS_STOCGH");
	lua_pushinteger(l, 81);
	lua_setfield(l, -2, "SYSZ_INS_CGIJNLH");
	lua_pushinteger(l, 82);
	lua_setfield(l, -2, "SYSZ_INS_CGRJNLH");
	lua_pushinteger(l, 83);
	lua_setfield(l, -2, "SYSZ_INS_CIJNLH");
	lua_pushinteger(l, 84);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJNLH");
	lua_pushinteger(l, 85);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJNLH");
	lua_pushinteger(l, 86);
	lua_setfield(l, -2, "SYSZ_INS_CLIJNLH");
	lua_pushinteger(l, 87);
	lua_setfield(l, -2, "SYSZ_INS_CLRJNLH");
	lua_pushinteger(l, 88);
	lua_setfield(l, -2, "SYSZ_INS_CRJNLH");
	lua_pushinteger(l, 89);
	lua_setfield(l, -2, "SYSZ_INS_CGIJE");
	lua_pushinteger(l, 90);
	lua_setfield(l, -2, "SYSZ_INS_CGRJE");
	lua_pushinteger(l, 91);
	lua_setfield(l, -2, "SYSZ_INS_CIJE");
	lua_pushinteger(l, 92);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJE");
	lua_pushinteger(l, 93);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJE");
	lua_pushinteger(l, 94);
	lua_setfield(l, -2, "SYSZ_INS_CLIJE");
	lua_pushinteger(l, 95);
	lua_setfield(l, -2, "SYSZ_INS_CLRJE");
	lua_pushinteger(l, 96);
	lua_setfield(l, -2, "SYSZ_INS_CRJE");
	lua_pushinteger(l, 97);
	lua_setfield(l, -2, "SYSZ_INS_CGIJNLE");
	lua_pushinteger(l, 98);
	lua_setfield(l, -2, "SYSZ_INS_CGRJNLE");
	lua_pushinteger(l, 99);
	lua_setfield(l, -2, "SYSZ_INS_CIJNLE");
	lua_pushinteger(l, 100);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJNLE");
	lua_pushinteger(l, 101);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJNLE");
	lua_pushinteger(l, 102);
	lua_setfield(l, -2, "SYSZ_INS_CLIJNLE");
	lua_pushinteger(l, 103);
	lua_setfield(l, -2, "SYSZ_INS_CLRJNLE");
	lua_pushinteger(l, 104);
	lua_setfield(l, -2, "SYSZ_INS_CRJNLE");
	lua_pushinteger(l, 105);
	lua_setfield(l, -2, "SYSZ_INS_CGIJH");
	lua_pushinteger(l, 106);
	lua_setfield(l, -2, "SYSZ_INS_CGRJH");
	lua_pushinteger(l, 107);
	lua_setfield(l, -2, "SYSZ_INS_CIJH");
	lua_pushinteger(l, 108);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJH");
	lua_pushinteger(l, 109);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJH");
	lua_pushinteger(l, 110);
	lua_setfield(l, -2, "SYSZ_INS_CLIJH");
	lua_pushinteger(l, 111);
	lua_setfield(l, -2, "SYSZ_INS_CLRJH");
	lua_pushinteger(l, 112);
	lua_setfield(l, -2, "SYSZ_INS_CRJH");
	lua_pushinteger(l, 113);
	lua_setfield(l, -2, "SYSZ_INS_CGIJNL");
	lua_pushinteger(l, 114);
	lua_setfield(l, -2, "SYSZ_INS_CGRJNL");
	lua_pushinteger(l, 115);
	lua_setfield(l, -2, "SYSZ_INS_CIJNL");
	lua_pushinteger(l, 116);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJNL");
	lua_pushinteger(l, 117);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJNL");
	lua_pushinteger(l, 118);
	lua_setfield(l, -2, "SYSZ_INS_CLIJNL");
	lua_pushinteger(l, 119);
	lua_setfield(l, -2, "SYSZ_INS_CLRJNL");
	lua_pushinteger(l, 120);
	lua_setfield(l, -2, "SYSZ_INS_CRJNL");
	lua_pushinteger(l, 121);
	lua_setfield(l, -2, "SYSZ_INS_CGIJHE");
	lua_pushinteger(l, 122);
	lua_setfield(l, -2, "SYSZ_INS_CGRJHE");
	lua_pushinteger(l, 123);
	lua_setfield(l, -2, "SYSZ_INS_CIJHE");
	lua_pushinteger(l, 124);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJHE");
	lua_pushinteger(l, 125);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJHE");
	lua_pushinteger(l, 126);
	lua_setfield(l, -2, "SYSZ_INS_CLIJHE");
	lua_pushinteger(l, 127);
	lua_setfield(l, -2, "SYSZ_INS_CLRJHE");
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "SYSZ_INS_CRJHE");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "SYSZ_INS_CGIJNHE");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "SYSZ_INS_CGRJNHE");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "SYSZ_INS_CIJNHE");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJNHE");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJNHE");
	lua_pushinteger(l, 134);
	lua_setfield(l, -2, "SYSZ_INS_CLIJNHE");
	lua_pushinteger(l, 135);
	lua_setfield(l, -2, "SYSZ_INS_CLRJNHE");
	lua_pushinteger(l, 136);
	lua_setfield(l, -2, "SYSZ_INS_CRJNHE");
	lua_pushinteger(l, 137);
	lua_setfield(l, -2, "SYSZ_INS_CGIJL");
	lua_pushinteger(l, 138);
	lua_setfield(l, -2, "SYSZ_INS_CGRJL");
	lua_pushinteger(l, 139);
	lua_setfield(l, -2, "SYSZ_INS_CIJL");
	lua_pushinteger(l, 140);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJL");
	lua_pushinteger(l, 141);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJL");
	lua_pushinteger(l, 142);
	lua_setfield(l, -2, "SYSZ_INS_CLIJL");
	lua_pushinteger(l, 143);
	lua_setfield(l, -2, "SYSZ_INS_CLRJL");
	lua_pushinteger(l, 144);
	lua_setfield(l, -2, "SYSZ_INS_CRJL");
	lua_pushinteger(l, 145);
	lua_setfield(l, -2, "SYSZ_INS_CGIJNH");
	lua_pushinteger(l, 146);
	lua_setfield(l, -2, "SYSZ_INS_CGRJNH");
	lua_pushinteger(l, 147);
	lua_setfield(l, -2, "SYSZ_INS_CIJNH");
	lua_pushinteger(l, 148);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJNH");
	lua_pushinteger(l, 149);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJNH");
	lua_pushinteger(l, 150);
	lua_setfield(l, -2, "SYSZ_INS_CLIJNH");
	lua_pushinteger(l, 151);
	lua_setfield(l, -2, "SYSZ_INS_CLRJNH");
	lua_pushinteger(l, 152);
	lua_setfield(l, -2, "SYSZ_INS_CRJNH");
	lua_pushinteger(l, 153);
	lua_setfield(l, -2, "SYSZ_INS_CGIJLE");
	lua_pushinteger(l, 154);
	lua_setfield(l, -2, "SYSZ_INS_CGRJLE");
	lua_pushinteger(l, 155);
	lua_setfield(l, -2, "SYSZ_INS_CIJLE");
	lua_pushinteger(l, 156);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJLE");
	lua_pushinteger(l, 157);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJLE");
	lua_pushinteger(l, 158);
	lua_setfield(l, -2, "SYSZ_INS_CLIJLE");
	lua_pushinteger(l, 159);
	lua_setfield(l, -2, "SYSZ_INS_CLRJLE");
	lua_pushinteger(l, 160);
	lua_setfield(l, -2, "SYSZ_INS_CRJLE");
	lua_pushinteger(l, 161);
	lua_setfield(l, -2, "SYSZ_INS_CGIJNE");
	lua_pushinteger(l, 162);
	lua_setfield(l, -2, "SYSZ_INS_CGRJNE");
	lua_pushinteger(l, 163);
	lua_setfield(l, -2, "SYSZ_INS_CIJNE");
	lua_pushinteger(l, 164);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJNE");
	lua_pushinteger(l, 165);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJNE");
	lua_pushinteger(l, 166);
	lua_setfield(l, -2, "SYSZ_INS_CLIJNE");
	lua_pushinteger(l, 167);
	lua_setfield(l, -2, "SYSZ_INS_CLRJNE");
	lua_pushinteger(l, 168);
	lua_setfield(l, -2, "SYSZ_INS_CRJNE");
	lua_pushinteger(l, 169);
	lua_setfield(l, -2, "SYSZ_INS_CGIJLH");
	lua_pushinteger(l, 170);
	lua_setfield(l, -2, "SYSZ_INS_CGRJLH");
	lua_pushinteger(l, 171);
	lua_setfield(l, -2, "SYSZ_INS_CIJLH");
	lua_pushinteger(l, 172);
	lua_setfield(l, -2, "SYSZ_INS_CLGIJLH");
	lua_pushinteger(l, 173);
	lua_setfield(l, -2, "SYSZ_INS_CLGRJLH");
	lua_pushinteger(l, 174);
	lua_setfield(l, -2, "SYSZ_INS_CLIJLH");
	lua_pushinteger(l, 175);
	lua_setfield(l, -2, "SYSZ_INS_CLRJLH");
	lua_pushinteger(l, 176);
	lua_setfield(l, -2, "SYSZ_INS_CRJLH");
	lua_pushinteger(l, 177);
	lua_setfield(l, -2, "SYSZ_INS_BLR");
	lua_pushinteger(l, 178);
	lua_setfield(l, -2, "SYSZ_INS_BLER");
	lua_pushinteger(l, 179);
	lua_setfield(l, -2, "SYSZ_INS_JLE");
	lua_pushinteger(l, 180);
	lua_setfield(l, -2, "SYSZ_INS_JGLE");
	lua_pushinteger(l, 181);
	lua_setfield(l, -2, "SYSZ_INS_LOCLE");
	lua_pushinteger(l, 182);
	lua_setfield(l, -2, "SYSZ_INS_LOCGLE");
	lua_pushinteger(l, 183);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRLE");
	lua_pushinteger(l, 184);
	lua_setfield(l, -2, "SYSZ_INS_LOCRLE");
	lua_pushinteger(l, 185);
	lua_setfield(l, -2, "SYSZ_INS_STOCLE");
	lua_pushinteger(l, 186);
	lua_setfield(l, -2, "SYSZ_INS_STOCGLE");
	lua_pushinteger(l, 187);
	lua_setfield(l, -2, "SYSZ_INS_BLHR");
	lua_pushinteger(l, 188);
	lua_setfield(l, -2, "SYSZ_INS_JLH");
	lua_pushinteger(l, 189);
	lua_setfield(l, -2, "SYSZ_INS_JGLH");
	lua_pushinteger(l, 190);
	lua_setfield(l, -2, "SYSZ_INS_LOCLH");
	lua_pushinteger(l, 191);
	lua_setfield(l, -2, "SYSZ_INS_LOCGLH");
	lua_pushinteger(l, 192);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRLH");
	lua_pushinteger(l, 193);
	lua_setfield(l, -2, "SYSZ_INS_LOCRLH");
	lua_pushinteger(l, 194);
	lua_setfield(l, -2, "SYSZ_INS_STOCLH");
	lua_pushinteger(l, 195);
	lua_setfield(l, -2, "SYSZ_INS_STOCGLH");
	lua_pushinteger(l, 196);
	lua_setfield(l, -2, "SYSZ_INS_JL");
	lua_pushinteger(l, 197);
	lua_setfield(l, -2, "SYSZ_INS_JGL");
	lua_pushinteger(l, 198);
	lua_setfield(l, -2, "SYSZ_INS_LOCL");
	lua_pushinteger(l, 199);
	lua_setfield(l, -2, "SYSZ_INS_LOCGL");
	lua_pushinteger(l, 200);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRL");
	lua_pushinteger(l, 201);
	lua_setfield(l, -2, "SYSZ_INS_LOCRL");
	lua_pushinteger(l, 202);
	lua_setfield(l, -2, "SYSZ_INS_LOC");
	lua_pushinteger(l, 203);
	lua_setfield(l, -2, "SYSZ_INS_LOCG");
	lua_pushinteger(l, 204);
	lua_setfield(l, -2, "SYSZ_INS_LOCGR");
	lua_pushinteger(l, 205);
	lua_setfield(l, -2, "SYSZ_INS_LOCR");
	lua_pushinteger(l, 206);
	lua_setfield(l, -2, "SYSZ_INS_STOCL");
	lua_pushinteger(l, 207);
	lua_setfield(l, -2, "SYSZ_INS_STOCGL");
	lua_pushinteger(l, 208);
	lua_setfield(l, -2, "SYSZ_INS_BNER");
	lua_pushinteger(l, 209);
	lua_setfield(l, -2, "SYSZ_INS_JNE");
	lua_pushinteger(l, 210);
	lua_setfield(l, -2, "SYSZ_INS_JGNE");
	lua_pushinteger(l, 211);
	lua_setfield(l, -2, "SYSZ_INS_LOCNE");
	lua_pushinteger(l, 212);
	lua_setfield(l, -2, "SYSZ_INS_LOCGNE");
	lua_pushinteger(l, 213);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRNE");
	lua_pushinteger(l, 214);
	lua_setfield(l, -2, "SYSZ_INS_LOCRNE");
	lua_pushinteger(l, 215);
	lua_setfield(l, -2, "SYSZ_INS_STOCNE");
	lua_pushinteger(l, 216);
	lua_setfield(l, -2, "SYSZ_INS_STOCGNE");
	lua_pushinteger(l, 217);
	lua_setfield(l, -2, "SYSZ_INS_BNHR");
	lua_pushinteger(l, 218);
	lua_setfield(l, -2, "SYSZ_INS_BNHER");
	lua_pushinteger(l, 219);
	lua_setfield(l, -2, "SYSZ_INS_JNHE");
	lua_pushinteger(l, 220);
	lua_setfield(l, -2, "SYSZ_INS_JGNHE");
	lua_pushinteger(l, 221);
	lua_setfield(l, -2, "SYSZ_INS_LOCNHE");
	lua_pushinteger(l, 222);
	lua_setfield(l, -2, "SYSZ_INS_LOCGNHE");
	lua_pushinteger(l, 223);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRNHE");
	lua_pushinteger(l, 224);
	lua_setfield(l, -2, "SYSZ_INS_LOCRNHE");
	lua_pushinteger(l, 225);
	lua_setfield(l, -2, "SYSZ_INS_STOCNHE");
	lua_pushinteger(l, 226);
	lua_setfield(l, -2, "SYSZ_INS_STOCGNHE");
	lua_pushinteger(l, 227);
	lua_setfield(l, -2, "SYSZ_INS_JNH");
	lua_pushinteger(l, 228);
	lua_setfield(l, -2, "SYSZ_INS_JGNH");
	lua_pushinteger(l, 229);
	lua_setfield(l, -2, "SYSZ_INS_LOCNH");
	lua_pushinteger(l, 230);
	lua_setfield(l, -2, "SYSZ_INS_LOCGNH");
	lua_pushinteger(l, 231);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRNH");
	lua_pushinteger(l, 232);
	lua_setfield(l, -2, "SYSZ_INS_LOCRNH");
	lua_pushinteger(l, 233);
	lua_setfield(l, -2, "SYSZ_INS_STOCNH");
	lua_pushinteger(l, 234);
	lua_setfield(l, -2, "SYSZ_INS_STOCGNH");
	lua_pushinteger(l, 235);
	lua_setfield(l, -2, "SYSZ_INS_BNLR");
	lua_pushinteger(l, 236);
	lua_setfield(l, -2, "SYSZ_INS_BNLER");
	lua_pushinteger(l, 237);
	lua_setfield(l, -2, "SYSZ_INS_JNLE");
	lua_pushinteger(l, 238);
	lua_setfield(l, -2, "SYSZ_INS_JGNLE");
	lua_pushinteger(l, 239);
	lua_setfield(l, -2, "SYSZ_INS_LOCNLE");
	lua_pushinteger(l, 240);
	lua_setfield(l, -2, "SYSZ_INS_LOCGNLE");
	lua_pushinteger(l, 241);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRNLE");
	lua_pushinteger(l, 242);
	lua_setfield(l, -2, "SYSZ_INS_LOCRNLE");
	lua_pushinteger(l, 243);
	lua_setfield(l, -2, "SYSZ_INS_STOCNLE");
	lua_pushinteger(l, 244);
	lua_setfield(l, -2, "SYSZ_INS_STOCGNLE");
	lua_pushinteger(l, 245);
	lua_setfield(l, -2, "SYSZ_INS_BNLHR");
	lua_pushinteger(l, 246);
	lua_setfield(l, -2, "SYSZ_INS_JNLH");
	lua_pushinteger(l, 247);
	lua_setfield(l, -2, "SYSZ_INS_JGNLH");
	lua_pushinteger(l, 248);
	lua_setfield(l, -2, "SYSZ_INS_LOCNLH");
	lua_pushinteger(l, 249);
	lua_setfield(l, -2, "SYSZ_INS_LOCGNLH");
	lua_pushinteger(l, 250);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRNLH");
	lua_pushinteger(l, 251);
	lua_setfield(l, -2, "SYSZ_INS_LOCRNLH");
	lua_pushinteger(l, 252);
	lua_setfield(l, -2, "SYSZ_INS_STOCNLH");
	lua_pushinteger(l, 253);
	lua_setfield(l, -2, "SYSZ_INS_STOCGNLH");
	lua_pushinteger(l, 254);
	lua_setfield(l, -2, "SYSZ_INS_JNL");
	lua_pushinteger(l, 255);
	lua_setfield(l, -2, "SYSZ_INS_JGNL");
	lua_pushinteger(l, 256);
	lua_setfield(l, -2, "SYSZ_INS_LOCNL");
	lua_pushinteger(l, 257);
	lua_setfield(l, -2, "SYSZ_INS_LOCGNL");
	lua_pushinteger(l, 258);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRNL");
	lua_pushinteger(l, 259);
	lua_setfield(l, -2, "SYSZ_INS_LOCRNL");
	lua_pushinteger(l, 260);
	lua_setfield(l, -2, "SYSZ_INS_STOCNL");
	lua_pushinteger(l, 261);
	lua_setfield(l, -2, "SYSZ_INS_STOCGNL");
	lua_pushinteger(l, 262);
	lua_setfield(l, -2, "SYSZ_INS_BNOR");
	lua_pushinteger(l, 263);
	lua_setfield(l, -2, "SYSZ_INS_JNO");
	lua_pushinteger(l, 264);
	lua_setfield(l, -2, "SYSZ_INS_JGNO");
	lua_pushinteger(l, 265);
	lua_setfield(l, -2, "SYSZ_INS_LOCNO");
	lua_pushinteger(l, 266);
	lua_setfield(l, -2, "SYSZ_INS_LOCGNO");
	lua_pushinteger(l, 267);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRNO");
	lua_pushinteger(l, 268);
	lua_setfield(l, -2, "SYSZ_INS_LOCRNO");
	lua_pushinteger(l, 269);
	lua_setfield(l, -2, "SYSZ_INS_STOCNO");
	lua_pushinteger(l, 270);
	lua_setfield(l, -2, "SYSZ_INS_STOCGNO");
	lua_pushinteger(l, 271);
	lua_setfield(l, -2, "SYSZ_INS_BOR");
	lua_pushinteger(l, 272);
	lua_setfield(l, -2, "SYSZ_INS_JO");
	lua_pushinteger(l, 273);
	lua_setfield(l, -2, "SYSZ_INS_JGO");
	lua_pushinteger(l, 274);
	lua_setfield(l, -2, "SYSZ_INS_LOCO");
	lua_pushinteger(l, 275);
	lua_setfield(l, -2, "SYSZ_INS_LOCGO");
	lua_pushinteger(l, 276);
	lua_setfield(l, -2, "SYSZ_INS_LOCGRO");
	lua_pushinteger(l, 277);
	lua_setfield(l, -2, "SYSZ_INS_LOCRO");
	lua_pushinteger(l, 278);
	lua_setfield(l, -2, "SYSZ_INS_STOCO");
	lua_pushinteger(l, 279);
	lua_setfield(l, -2, "SYSZ_INS_STOCGO");
	lua_pushinteger(l, 280);
	lua_setfield(l, -2, "SYSZ_INS_STOC");
	lua_pushinteger(l, 281);
	lua_setfield(l, -2, "SYSZ_INS_STOCG");
	lua_pushinteger(l, 282);
	lua_setfield(l, -2, "SYSZ_INS_BASR");
	lua_pushinteger(l, 283);
	lua_setfield(l, -2, "SYSZ_INS_BR");
	lua_pushinteger(l, 284);
	lua_setfield(l, -2, "SYSZ_INS_BRAS");
	lua_pushinteger(l, 285);
	lua_setfield(l, -2, "SYSZ_INS_BRASL");
	lua_pushinteger(l, 286);
	lua_setfield(l, -2, "SYSZ_INS_J");
	lua_pushinteger(l, 287);
	lua_setfield(l, -2, "SYSZ_INS_JG");
	lua_pushinteger(l, 288);
	lua_setfield(l, -2, "SYSZ_INS_BRCT");
	lua_pushinteger(l, 289);
	lua_setfield(l, -2, "SYSZ_INS_BRCTG");
	lua_pushinteger(l, 290);
	lua_setfield(l, -2, "SYSZ_INS_C");
	lua_pushinteger(l, 291);
	lua_setfield(l, -2, "SYSZ_INS_CDB");
	lua_pushinteger(l, 292);
	lua_setfield(l, -2, "SYSZ_INS_CDBR");
	lua_pushinteger(l, 293);
	lua_setfield(l, -2, "SYSZ_INS_CDFBR");
	lua_pushinteger(l, 294);
	lua_setfield(l, -2, "SYSZ_INS_CDGBR");
	lua_pushinteger(l, 295);
	lua_setfield(l, -2, "SYSZ_INS_CDLFBR");
	lua_pushinteger(l, 296);
	lua_setfield(l, -2, "SYSZ_INS_CDLGBR");
	lua_pushinteger(l, 297);
	lua_setfield(l, -2, "SYSZ_INS_CEB");
	lua_pushinteger(l, 298);
	lua_setfield(l, -2, "SYSZ_INS_CEBR");
	lua_pushinteger(l, 299);
	lua_setfield(l, -2, "SYSZ_INS_CEFBR");
	lua_pushinteger(l, 300);
	lua_setfield(l, -2, "SYSZ_INS_CEGBR");
	lua_pushinteger(l, 301);
	lua_setfield(l, -2, "SYSZ_INS_CELFBR");
	lua_pushinteger(l, 302);
	lua_setfield(l, -2, "SYSZ_INS_CELGBR");
	lua_pushinteger(l, 303);
	lua_setfield(l, -2, "SYSZ_INS_CFDBR");
	lua_pushinteger(l, 304);
	lua_setfield(l, -2, "SYSZ_INS_CFEBR");
	lua_pushinteger(l, 305);
	lua_setfield(l, -2, "SYSZ_INS_CFI");
	lua_pushinteger(l, 306);
	lua_setfield(l, -2, "SYSZ_INS_CFXBR");
	lua_pushinteger(l, 307);
	lua_setfield(l, -2, "SYSZ_INS_CG");
	lua_pushinteger(l, 308);
	lua_setfield(l, -2, "SYSZ_INS_CGDBR");
	lua_pushinteger(l, 309);
	lua_setfield(l, -2, "SYSZ_INS_CGEBR");
	lua_pushinteger(l, 310);
	lua_setfield(l, -2, "SYSZ_INS_CGF");
	lua_pushinteger(l, 311);
	lua_setfield(l, -2, "SYSZ_INS_CGFI");
	lua_pushinteger(l, 312);
	lua_setfield(l, -2, "SYSZ_INS_CGFR");
	lua_pushinteger(l, 313);
	lua_setfield(l, -2, "SYSZ_INS_CGFRL");
	lua_pushinteger(l, 314);
	lua_setfield(l, -2, "SYSZ_INS_CGH");
	lua_pushinteger(l, 315);
	lua_setfield(l, -2, "SYSZ_INS_CGHI");
	lua_pushinteger(l, 316);
	lua_setfield(l, -2, "SYSZ_INS_CGHRL");
	lua_pushinteger(l, 317);
	lua_setfield(l, -2, "SYSZ_INS_CGHSI");
	lua_pushinteger(l, 318);
	lua_setfield(l, -2, "SYSZ_INS_CGR");
	lua_pushinteger(l, 319);
	lua_setfield(l, -2, "SYSZ_INS_CGRL");
	lua_pushinteger(l, 320);
	lua_setfield(l, -2, "SYSZ_INS_CGXBR");
	lua_pushinteger(l, 321);
	lua_setfield(l, -2, "SYSZ_INS_CH");
	lua_pushinteger(l, 322);
	lua_setfield(l, -2, "SYSZ_INS_CHF");
	lua_pushinteger(l, 323);
	lua_setfield(l, -2, "SYSZ_INS_CHHSI");
	lua_pushinteger(l, 324);
	lua_setfield(l, -2, "SYSZ_INS_CHI");
	lua_pushinteger(l, 325);
	lua_setfield(l, -2, "SYSZ_INS_CHRL");
	lua_pushinteger(l, 326);
	lua_setfield(l, -2, "SYSZ_INS_CHSI");
	lua_pushinteger(l, 327);
	lua_setfield(l, -2, "SYSZ_INS_CHY");
	lua_pushinteger(l, 328);
	lua_setfield(l, -2, "SYSZ_INS_CIH");
	lua_pushinteger(l, 329);
	lua_setfield(l, -2, "SYSZ_INS_CL");
	lua_pushinteger(l, 330);
	lua_setfield(l, -2, "SYSZ_INS_CLC");
	lua_pushinteger(l, 331);
	lua_setfield(l, -2, "SYSZ_INS_CLFDBR");
	lua_pushinteger(l, 332);
	lua_setfield(l, -2, "SYSZ_INS_CLFEBR");
	lua_pushinteger(l, 333);
	lua_setfield(l, -2, "SYSZ_INS_CLFHSI");
	lua_pushinteger(l, 334);
	lua_setfield(l, -2, "SYSZ_INS_CLFI");
	lua_pushinteger(l, 335);
	lua_setfield(l, -2, "SYSZ_INS_CLFXBR");
	lua_pushinteger(l, 336);
	lua_setfield(l, -2, "SYSZ_INS_CLG");
	lua_pushinteger(l, 337);
	lua_setfield(l, -2, "SYSZ_INS_CLGDBR");
	lua_pushinteger(l, 338);
	lua_setfield(l, -2, "SYSZ_INS_CLGEBR");
	lua_pushinteger(l, 339);
	lua_setfield(l, -2, "SYSZ_INS_CLGF");
	lua_pushinteger(l, 340);
	lua_setfield(l, -2, "SYSZ_INS_CLGFI");
	lua_pushinteger(l, 341);
	lua_setfield(l, -2, "SYSZ_INS_CLGFR");
	lua_pushinteger(l, 342);
	lua_setfield(l, -2, "SYSZ_INS_CLGFRL");
	lua_pushinteger(l, 343);
	lua_setfield(l, -2, "SYSZ_INS_CLGHRL");
	lua_pushinteger(l, 344);
	lua_setfield(l, -2, "SYSZ_INS_CLGHSI");
	lua_pushinteger(l, 345);
	lua_setfield(l, -2, "SYSZ_INS_CLGR");
	lua_pushinteger(l, 346);
	lua_setfield(l, -2, "SYSZ_INS_CLGRL");
	lua_pushinteger(l, 347);
	lua_setfield(l, -2, "SYSZ_INS_CLGXBR");
	lua_pushinteger(l, 348);
	lua_setfield(l, -2, "SYSZ_INS_CLHF");
	lua_pushinteger(l, 349);
	lua_setfield(l, -2, "SYSZ_INS_CLHHSI");
	lua_pushinteger(l, 350);
	lua_setfield(l, -2, "SYSZ_INS_CLHRL");
	lua_pushinteger(l, 351);
	lua_setfield(l, -2, "SYSZ_INS_CLI");
	lua_pushinteger(l, 352);
	lua_setfield(l, -2, "SYSZ_INS_CLIH");
	lua_pushinteger(l, 353);
	lua_setfield(l, -2, "SYSZ_INS_CLIY");
	lua_pushinteger(l, 354);
	lua_setfield(l, -2, "SYSZ_INS_CLR");
	lua_pushinteger(l, 355);
	lua_setfield(l, -2, "SYSZ_INS_CLRL");
	lua_pushinteger(l, 356);
	lua_setfield(l, -2, "SYSZ_INS_CLST");
	lua_pushinteger(l, 357);
	lua_setfield(l, -2, "SYSZ_INS_CLY");
	lua_pushinteger(l, 358);
	lua_setfield(l, -2, "SYSZ_INS_CPSDR");
	lua_pushinteger(l, 359);
	lua_setfield(l, -2, "SYSZ_INS_CR");
	lua_pushinteger(l, 360);
	lua_setfield(l, -2, "SYSZ_INS_CRL");
	lua_pushinteger(l, 361);
	lua_setfield(l, -2, "SYSZ_INS_CS");
	lua_pushinteger(l, 362);
	lua_setfield(l, -2, "SYSZ_INS_CSG");
	lua_pushinteger(l, 363);
	lua_setfield(l, -2, "SYSZ_INS_CSY");
	lua_pushinteger(l, 364);
	lua_setfield(l, -2, "SYSZ_INS_CXBR");
	lua_pushinteger(l, 365);
	lua_setfield(l, -2, "SYSZ_INS_CXFBR");
	lua_pushinteger(l, 366);
	lua_setfield(l, -2, "SYSZ_INS_CXGBR");
	lua_pushinteger(l, 367);
	lua_setfield(l, -2, "SYSZ_INS_CXLFBR");
	lua_pushinteger(l, 368);
	lua_setfield(l, -2, "SYSZ_INS_CXLGBR");
	lua_pushinteger(l, 369);
	lua_setfield(l, -2, "SYSZ_INS_CY");
	lua_pushinteger(l, 370);
	lua_setfield(l, -2, "SYSZ_INS_DDB");
	lua_pushinteger(l, 371);
	lua_setfield(l, -2, "SYSZ_INS_DDBR");
	lua_pushinteger(l, 372);
	lua_setfield(l, -2, "SYSZ_INS_DEB");
	lua_pushinteger(l, 373);
	lua_setfield(l, -2, "SYSZ_INS_DEBR");
	lua_pushinteger(l, 374);
	lua_setfield(l, -2, "SYSZ_INS_DL");
	lua_pushinteger(l, 375);
	lua_setfield(l, -2, "SYSZ_INS_DLG");
	lua_pushinteger(l, 376);
	lua_setfield(l, -2, "SYSZ_INS_DLGR");
	lua_pushinteger(l, 377);
	lua_setfield(l, -2, "SYSZ_INS_DLR");
	lua_pushinteger(l, 378);
	lua_setfield(l, -2, "SYSZ_INS_DSG");
	lua_pushinteger(l, 379);
	lua_setfield(l, -2, "SYSZ_INS_DSGF");
	lua_pushinteger(l, 380);
	lua_setfield(l, -2, "SYSZ_INS_DSGFR");
	lua_pushinteger(l, 381);
	lua_setfield(l, -2, "SYSZ_INS_DSGR");
	lua_pushinteger(l, 382);
	lua_setfield(l, -2, "SYSZ_INS_DXBR");
	lua_pushinteger(l, 383);
	lua_setfield(l, -2, "SYSZ_INS_EAR");
	lua_pushinteger(l, 384);
	lua_setfield(l, -2, "SYSZ_INS_FIDBR");
	lua_pushinteger(l, 385);
	lua_setfield(l, -2, "SYSZ_INS_FIDBRA");
	lua_pushinteger(l, 386);
	lua_setfield(l, -2, "SYSZ_INS_FIEBR");
	lua_pushinteger(l, 387);
	lua_setfield(l, -2, "SYSZ_INS_FIEBRA");
	lua_pushinteger(l, 388);
	lua_setfield(l, -2, "SYSZ_INS_FIXBR");
	lua_pushinteger(l, 389);
	lua_setfield(l, -2, "SYSZ_INS_FIXBRA");
	lua_pushinteger(l, 390);
	lua_setfield(l, -2, "SYSZ_INS_FLOGR");
	lua_pushinteger(l, 391);
	lua_setfield(l, -2, "SYSZ_INS_IC");
	lua_pushinteger(l, 392);
	lua_setfield(l, -2, "SYSZ_INS_ICY");
	lua_pushinteger(l, 393);
	lua_setfield(l, -2, "SYSZ_INS_IIHF");
	lua_pushinteger(l, 394);
	lua_setfield(l, -2, "SYSZ_INS_IIHH");
	lua_pushinteger(l, 395);
	lua_setfield(l, -2, "SYSZ_INS_IIHL");
	lua_pushinteger(l, 396);
	lua_setfield(l, -2, "SYSZ_INS_IILF");
	lua_pushinteger(l, 397);
	lua_setfield(l, -2, "SYSZ_INS_IILH");
	lua_pushinteger(l, 398);
	lua_setfield(l, -2, "SYSZ_INS_IILL");
	lua_pushinteger(l, 399);
	lua_setfield(l, -2, "SYSZ_INS_IPM");
	lua_pushinteger(l, 400);
	lua_setfield(l, -2, "SYSZ_INS_L");
	lua_pushinteger(l, 401);
	lua_setfield(l, -2, "SYSZ_INS_LA");
	lua_pushinteger(l, 402);
	lua_setfield(l, -2, "SYSZ_INS_LAA");
	lua_pushinteger(l, 403);
	lua_setfield(l, -2, "SYSZ_INS_LAAG");
	lua_pushinteger(l, 404);
	lua_setfield(l, -2, "SYSZ_INS_LAAL");
	lua_pushinteger(l, 405);
	lua_setfield(l, -2, "SYSZ_INS_LAALG");
	lua_pushinteger(l, 406);
	lua_setfield(l, -2, "SYSZ_INS_LAN");
	lua_pushinteger(l, 407);
	lua_setfield(l, -2, "SYSZ_INS_LANG");
	lua_pushinteger(l, 408);
	lua_setfield(l, -2, "SYSZ_INS_LAO");
	lua_pushinteger(l, 409);
	lua_setfield(l, -2, "SYSZ_INS_LAOG");
	lua_pushinteger(l, 410);
	lua_setfield(l, -2, "SYSZ_INS_LARL");
	lua_pushinteger(l, 411);
	lua_setfield(l, -2, "SYSZ_INS_LAX");
	lua_pushinteger(l, 412);
	lua_setfield(l, -2, "SYSZ_INS_LAXG");
	lua_pushinteger(l, 413);
	lua_setfield(l, -2, "SYSZ_INS_LAY");
	lua_pushinteger(l, 414);
	lua_setfield(l, -2, "SYSZ_INS_LB");
	lua_pushinteger(l, 415);
	lua_setfield(l, -2, "SYSZ_INS_LBH");
	lua_pushinteger(l, 416);
	lua_setfield(l, -2, "SYSZ_INS_LBR");
	lua_pushinteger(l, 417);
	lua_setfield(l, -2, "SYSZ_INS_LCDBR");
	lua_pushinteger(l, 418);
	lua_setfield(l, -2, "SYSZ_INS_LCEBR");
	lua_pushinteger(l, 419);
	lua_setfield(l, -2, "SYSZ_INS_LCGFR");
	lua_pushinteger(l, 420);
	lua_setfield(l, -2, "SYSZ_INS_LCGR");
	lua_pushinteger(l, 421);
	lua_setfield(l, -2, "SYSZ_INS_LCR");
	lua_pushinteger(l, 422);
	lua_setfield(l, -2, "SYSZ_INS_LCXBR");
	lua_pushinteger(l, 423);
	lua_setfield(l, -2, "SYSZ_INS_LD");
	lua_pushinteger(l, 424);
	lua_setfield(l, -2, "SYSZ_INS_LDEB");
	lua_pushinteger(l, 425);
	lua_setfield(l, -2, "SYSZ_INS_LDEBR");
	lua_pushinteger(l, 426);
	lua_setfield(l, -2, "SYSZ_INS_LDGR");
	lua_pushinteger(l, 427);
	lua_setfield(l, -2, "SYSZ_INS_LDR");
	lua_pushinteger(l, 428);
	lua_setfield(l, -2, "SYSZ_INS_LDXBR");
	lua_pushinteger(l, 429);
	lua_setfield(l, -2, "SYSZ_INS_LDXBRA");
	lua_pushinteger(l, 430);
	lua_setfield(l, -2, "SYSZ_INS_LDY");
	lua_pushinteger(l, 431);
	lua_setfield(l, -2, "SYSZ_INS_LE");
	lua_pushinteger(l, 432);
	lua_setfield(l, -2, "SYSZ_INS_LEDBR");
	lua_pushinteger(l, 433);
	lua_setfield(l, -2, "SYSZ_INS_LEDBRA");
	lua_pushinteger(l, 434);
	lua_setfield(l, -2, "SYSZ_INS_LER");
	lua_pushinteger(l, 435);
	lua_setfield(l, -2, "SYSZ_INS_LEXBR");
	lua_pushinteger(l, 436);
	lua_setfield(l, -2, "SYSZ_INS_LEXBRA");
	lua_pushinteger(l, 437);
	lua_setfield(l, -2, "SYSZ_INS_LEY");
	lua_pushinteger(l, 438);
	lua_setfield(l, -2, "SYSZ_INS_LFH");
	lua_pushinteger(l, 439);
	lua_setfield(l, -2, "SYSZ_INS_LG");
	lua_pushinteger(l, 440);
	lua_setfield(l, -2, "SYSZ_INS_LGB");
	lua_pushinteger(l, 441);
	lua_setfield(l, -2, "SYSZ_INS_LGBR");
	lua_pushinteger(l, 442);
	lua_setfield(l, -2, "SYSZ_INS_LGDR");
	lua_pushinteger(l, 443);
	lua_setfield(l, -2, "SYSZ_INS_LGF");
	lua_pushinteger(l, 444);
	lua_setfield(l, -2, "SYSZ_INS_LGFI");
	lua_pushinteger(l, 445);
	lua_setfield(l, -2, "SYSZ_INS_LGFR");
	lua_pushinteger(l, 446);
	lua_setfield(l, -2, "SYSZ_INS_LGFRL");
	lua_pushinteger(l, 447);
	lua_setfield(l, -2, "SYSZ_INS_LGH");
	lua_pushinteger(l, 448);
	lua_setfield(l, -2, "SYSZ_INS_LGHI");
	lua_pushinteger(l, 449);
	lua_setfield(l, -2, "SYSZ_INS_LGHR");
	lua_pushinteger(l, 450);
	lua_setfield(l, -2, "SYSZ_INS_LGHRL");
	lua_pushinteger(l, 451);
	lua_setfield(l, -2, "SYSZ_INS_LGR");
	lua_pushinteger(l, 452);
	lua_setfield(l, -2, "SYSZ_INS_LGRL");
	lua_pushinteger(l, 453);
	lua_setfield(l, -2, "SYSZ_INS_LH");
	lua_pushinteger(l, 454);
	lua_setfield(l, -2, "SYSZ_INS_LHH");
	lua_pushinteger(l, 455);
	lua_setfield(l, -2, "SYSZ_INS_LHI");
	lua_pushinteger(l, 456);
	lua_setfield(l, -2, "SYSZ_INS_LHR");
	lua_pushinteger(l, 457);
	lua_setfield(l, -2, "SYSZ_INS_LHRL");
	lua_pushinteger(l, 458);
	lua_setfield(l, -2, "SYSZ_INS_LHY");
	lua_pushinteger(l, 459);
	lua_setfield(l, -2, "SYSZ_INS_LLC");
	lua_pushinteger(l, 460);
	lua_setfield(l, -2, "SYSZ_INS_LLCH");
	lua_pushinteger(l, 461);
	lua_setfield(l, -2, "SYSZ_INS_LLCR");
	lua_pushinteger(l, 462);
	lua_setfield(l, -2, "SYSZ_INS_LLGC");
	lua_pushinteger(l, 463);
	lua_setfield(l, -2, "SYSZ_INS_LLGCR");
	lua_pushinteger(l, 464);
	lua_setfield(l, -2, "SYSZ_INS_LLGF");
	lua_pushinteger(l, 465);
	lua_setfield(l, -2, "SYSZ_INS_LLGFR");
	lua_pushinteger(l, 466);
	lua_setfield(l, -2, "SYSZ_INS_LLGFRL");
	lua_pushinteger(l, 467);
	lua_setfield(l, -2, "SYSZ_INS_LLGH");
	lua_pushinteger(l, 468);
	lua_setfield(l, -2, "SYSZ_INS_LLGHR");
	lua_pushinteger(l, 469);
	lua_setfield(l, -2, "SYSZ_INS_LLGHRL");
	lua_pushinteger(l, 470);
	lua_setfield(l, -2, "SYSZ_INS_LLH");
	lua_pushinteger(l, 471);
	lua_setfield(l, -2, "SYSZ_INS_LLHH");
	lua_pushinteger(l, 472);
	lua_setfield(l, -2, "SYSZ_INS_LLHR");
	lua_pushinteger(l, 473);
	lua_setfield(l, -2, "SYSZ_INS_LLHRL");
	lua_pushinteger(l, 474);
	lua_setfield(l, -2, "SYSZ_INS_LLIHF");
	lua_pushinteger(l, 475);
	lua_setfield(l, -2, "SYSZ_INS_LLIHH");
	lua_pushinteger(l, 476);
	lua_setfield(l, -2, "SYSZ_INS_LLIHL");
	lua_pushinteger(l, 477);
	lua_setfield(l, -2, "SYSZ_INS_LLILF");
	lua_pushinteger(l, 478);
	lua_setfield(l, -2, "SYSZ_INS_LLILH");
	lua_pushinteger(l, 479);
	lua_setfield(l, -2, "SYSZ_INS_LLILL");
	lua_pushinteger(l, 480);
	lua_setfield(l, -2, "SYSZ_INS_LMG");
	lua_pushinteger(l, 481);
	lua_setfield(l, -2, "SYSZ_INS_LNDBR");
	lua_pushinteger(l, 482);
	lua_setfield(l, -2, "SYSZ_INS_LNEBR");
	lua_pushinteger(l, 483);
	lua_setfield(l, -2, "SYSZ_INS_LNGFR");
	lua_pushinteger(l, 484);
	lua_setfield(l, -2, "SYSZ_INS_LNGR");
	lua_pushinteger(l, 485);
	lua_setfield(l, -2, "SYSZ_INS_LNR");
	lua_pushinteger(l, 486);
	lua_setfield(l, -2, "SYSZ_INS_LNXBR");
	lua_pushinteger(l, 487);
	lua_setfield(l, -2, "SYSZ_INS_LPDBR");
	lua_pushinteger(l, 488);
	lua_setfield(l, -2, "SYSZ_INS_LPEBR");
	lua_pushinteger(l, 489);
	lua_setfield(l, -2, "SYSZ_INS_LPGFR");
	lua_pushinteger(l, 490);
	lua_setfield(l, -2, "SYSZ_INS_LPGR");
	lua_pushinteger(l, 491);
	lua_setfield(l, -2, "SYSZ_INS_LPR");
	lua_pushinteger(l, 492);
	lua_setfield(l, -2, "SYSZ_INS_LPXBR");
	lua_pushinteger(l, 493);
	lua_setfield(l, -2, "SYSZ_INS_LR");
	lua_pushinteger(l, 494);
	lua_setfield(l, -2, "SYSZ_INS_LRL");
	lua_pushinteger(l, 495);
	lua_setfield(l, -2, "SYSZ_INS_LRV");
	lua_pushinteger(l, 496);
	lua_setfield(l, -2, "SYSZ_INS_LRVG");
	lua_pushinteger(l, 497);
	lua_setfield(l, -2, "SYSZ_INS_LRVGR");
	lua_pushinteger(l, 498);
	lua_setfield(l, -2, "SYSZ_INS_LRVR");
	lua_pushinteger(l, 499);
	lua_setfield(l, -2, "SYSZ_INS_LT");
	lua_pushinteger(l, 500);
	lua_setfield(l, -2, "SYSZ_INS_LTDBR");
	lua_pushinteger(l, 501);
	lua_setfield(l, -2, "SYSZ_INS_LTEBR");
	lua_pushinteger(l, 502);
	lua_setfield(l, -2, "SYSZ_INS_LTG");
	lua_pushinteger(l, 503);
	lua_setfield(l, -2, "SYSZ_INS_LTGF");
	lua_pushinteger(l, 504);
	lua_setfield(l, -2, "SYSZ_INS_LTGFR");
	lua_pushinteger(l, 505);
	lua_setfield(l, -2, "SYSZ_INS_LTGR");
	lua_pushinteger(l, 506);
	lua_setfield(l, -2, "SYSZ_INS_LTR");
	lua_pushinteger(l, 507);
	lua_setfield(l, -2, "SYSZ_INS_LTXBR");
	lua_pushinteger(l, 508);
	lua_setfield(l, -2, "SYSZ_INS_LXDB");
	lua_pushinteger(l, 509);
	lua_setfield(l, -2, "SYSZ_INS_LXDBR");
	lua_pushinteger(l, 510);
	lua_setfield(l, -2, "SYSZ_INS_LXEB");
	lua_pushinteger(l, 511);
	lua_setfield(l, -2, "SYSZ_INS_LXEBR");
	lua_pushinteger(l, 512);
	lua_setfield(l, -2, "SYSZ_INS_LXR");
	lua_pushinteger(l, 513);
	lua_setfield(l, -2, "SYSZ_INS_LY");
	lua_pushinteger(l, 514);
	lua_setfield(l, -2, "SYSZ_INS_LZDR");
	lua_pushinteger(l, 515);
	lua_setfield(l, -2, "SYSZ_INS_LZER");
	lua_pushinteger(l, 516);
	lua_setfield(l, -2, "SYSZ_INS_LZXR");
	lua_pushinteger(l, 517);
	lua_setfield(l, -2, "SYSZ_INS_MADB");
	lua_pushinteger(l, 518);
	lua_setfield(l, -2, "SYSZ_INS_MADBR");
	lua_pushinteger(l, 519);
	lua_setfield(l, -2, "SYSZ_INS_MAEB");
	lua_pushinteger(l, 520);
	lua_setfield(l, -2, "SYSZ_INS_MAEBR");
	lua_pushinteger(l, 521);
	lua_setfield(l, -2, "SYSZ_INS_MDB");
	lua_pushinteger(l, 522);
	lua_setfield(l, -2, "SYSZ_INS_MDBR");
	lua_pushinteger(l, 523);
	lua_setfield(l, -2, "SYSZ_INS_MDEB");
	lua_pushinteger(l, 524);
	lua_setfield(l, -2, "SYSZ_INS_MDEBR");
	lua_pushinteger(l, 525);
	lua_setfield(l, -2, "SYSZ_INS_MEEB");
	lua_pushinteger(l, 526);
	lua_setfield(l, -2, "SYSZ_INS_MEEBR");
	lua_pushinteger(l, 527);
	lua_setfield(l, -2, "SYSZ_INS_MGHI");
	lua_pushinteger(l, 528);
	lua_setfield(l, -2, "SYSZ_INS_MH");
	lua_pushinteger(l, 529);
	lua_setfield(l, -2, "SYSZ_INS_MHI");
	lua_pushinteger(l, 530);
	lua_setfield(l, -2, "SYSZ_INS_MHY");
	lua_pushinteger(l, 531);
	lua_setfield(l, -2, "SYSZ_INS_MLG");
	lua_pushinteger(l, 532);
	lua_setfield(l, -2, "SYSZ_INS_MLGR");
	lua_pushinteger(l, 533);
	lua_setfield(l, -2, "SYSZ_INS_MS");
	lua_pushinteger(l, 534);
	lua_setfield(l, -2, "SYSZ_INS_MSDB");
	lua_pushinteger(l, 535);
	lua_setfield(l, -2, "SYSZ_INS_MSDBR");
	lua_pushinteger(l, 536);
	lua_setfield(l, -2, "SYSZ_INS_MSEB");
	lua_pushinteger(l, 537);
	lua_setfield(l, -2, "SYSZ_INS_MSEBR");
	lua_pushinteger(l, 538);
	lua_setfield(l, -2, "SYSZ_INS_MSFI");
	lua_pushinteger(l, 539);
	lua_setfield(l, -2, "SYSZ_INS_MSG");
	lua_pushinteger(l, 540);
	lua_setfield(l, -2, "SYSZ_INS_MSGF");
	lua_pushinteger(l, 541);
	lua_setfield(l, -2, "SYSZ_INS_MSGFI");
	lua_pushinteger(l, 542);
	lua_setfield(l, -2, "SYSZ_INS_MSGFR");
	lua_pushinteger(l, 543);
	lua_setfield(l, -2, "SYSZ_INS_MSGR");
	lua_pushinteger(l, 544);
	lua_setfield(l, -2, "SYSZ_INS_MSR");
	lua_pushinteger(l, 545);
	lua_setfield(l, -2, "SYSZ_INS_MSY");
	lua_pushinteger(l, 546);
	lua_setfield(l, -2, "SYSZ_INS_MVC");
	lua_pushinteger(l, 547);
	lua_setfield(l, -2, "SYSZ_INS_MVGHI");
	lua_pushinteger(l, 548);
	lua_setfield(l, -2, "SYSZ_INS_MVHHI");
	lua_pushinteger(l, 549);
	lua_setfield(l, -2, "SYSZ_INS_MVHI");
	lua_pushinteger(l, 550);
	lua_setfield(l, -2, "SYSZ_INS_MVI");
	lua_pushinteger(l, 551);
	lua_setfield(l, -2, "SYSZ_INS_MVIY");
	lua_pushinteger(l, 552);
	lua_setfield(l, -2, "SYSZ_INS_MVST");
	lua_pushinteger(l, 553);
	lua_setfield(l, -2, "SYSZ_INS_MXBR");
	lua_pushinteger(l, 554);
	lua_setfield(l, -2, "SYSZ_INS_MXDB");
	lua_pushinteger(l, 555);
	lua_setfield(l, -2, "SYSZ_INS_MXDBR");
	lua_pushinteger(l, 556);
	lua_setfield(l, -2, "SYSZ_INS_N");
	lua_pushinteger(l, 557);
	lua_setfield(l, -2, "SYSZ_INS_NC");
	lua_pushinteger(l, 558);
	lua_setfield(l, -2, "SYSZ_INS_NG");
	lua_pushinteger(l, 559);
	lua_setfield(l, -2, "SYSZ_INS_NGR");
	lua_pushinteger(l, 560);
	lua_setfield(l, -2, "SYSZ_INS_NGRK");
	lua_pushinteger(l, 561);
	lua_setfield(l, -2, "SYSZ_INS_NI");
	lua_pushinteger(l, 562);
	lua_setfield(l, -2, "SYSZ_INS_NIHF");
	lua_pushinteger(l, 563);
	lua_setfield(l, -2, "SYSZ_INS_NIHH");
	lua_pushinteger(l, 564);
	lua_setfield(l, -2, "SYSZ_INS_NIHL");
	lua_pushinteger(l, 565);
	lua_setfield(l, -2, "SYSZ_INS_NILF");
	lua_pushinteger(l, 566);
	lua_setfield(l, -2, "SYSZ_INS_NILH");
	lua_pushinteger(l, 567);
	lua_setfield(l, -2, "SYSZ_INS_NILL");
	lua_pushinteger(l, 568);
	lua_setfield(l, -2, "SYSZ_INS_NIY");
	lua_pushinteger(l, 569);
	lua_setfield(l, -2, "SYSZ_INS_NR");
	lua_pushinteger(l, 570);
	lua_setfield(l, -2, "SYSZ_INS_NRK");
	lua_pushinteger(l, 571);
	lua_setfield(l, -2, "SYSZ_INS_NY");
	lua_pushinteger(l, 572);
	lua_setfield(l, -2, "SYSZ_INS_O");
	lua_pushinteger(l, 573);
	lua_setfield(l, -2, "SYSZ_INS_OC");
	lua_pushinteger(l, 574);
	lua_setfield(l, -2, "SYSZ_INS_OG");
	lua_pushinteger(l, 575);
	lua_setfield(l, -2, "SYSZ_INS_OGR");
	lua_pushinteger(l, 576);
	lua_setfield(l, -2, "SYSZ_INS_OGRK");
	lua_pushinteger(l, 577);
	lua_setfield(l, -2, "SYSZ_INS_OI");
	lua_pushinteger(l, 578);
	lua_setfield(l, -2, "SYSZ_INS_OIHF");
	lua_pushinteger(l, 579);
	lua_setfield(l, -2, "SYSZ_INS_OIHH");
	lua_pushinteger(l, 580);
	lua_setfield(l, -2, "SYSZ_INS_OIHL");
	lua_pushinteger(l, 581);
	lua_setfield(l, -2, "SYSZ_INS_OILF");
	lua_pushinteger(l, 582);
	lua_setfield(l, -2, "SYSZ_INS_OILH");
	lua_pushinteger(l, 583);
	lua_setfield(l, -2, "SYSZ_INS_OILL");
	lua_pushinteger(l, 584);
	lua_setfield(l, -2, "SYSZ_INS_OIY");
	lua_pushinteger(l, 585);
	lua_setfield(l, -2, "SYSZ_INS_OR");
	lua_pushinteger(l, 586);
	lua_setfield(l, -2, "SYSZ_INS_ORK");
	lua_pushinteger(l, 587);
	lua_setfield(l, -2, "SYSZ_INS_OY");
	lua_pushinteger(l, 588);
	lua_setfield(l, -2, "SYSZ_INS_PFD");
	lua_pushinteger(l, 589);
	lua_setfield(l, -2, "SYSZ_INS_PFDRL");
	lua_pushinteger(l, 590);
	lua_setfield(l, -2, "SYSZ_INS_RISBG");
	lua_pushinteger(l, 591);
	lua_setfield(l, -2, "SYSZ_INS_RISBHG");
	lua_pushinteger(l, 592);
	lua_setfield(l, -2, "SYSZ_INS_RISBLG");
	lua_pushinteger(l, 593);
	lua_setfield(l, -2, "SYSZ_INS_RLL");
	lua_pushinteger(l, 594);
	lua_setfield(l, -2, "SYSZ_INS_RLLG");
	lua_pushinteger(l, 595);
	lua_setfield(l, -2, "SYSZ_INS_RNSBG");
	lua_pushinteger(l, 596);
	lua_setfield(l, -2, "SYSZ_INS_ROSBG");
	lua_pushinteger(l, 597);
	lua_setfield(l, -2, "SYSZ_INS_RXSBG");
	lua_pushinteger(l, 598);
	lua_setfield(l, -2, "SYSZ_INS_S");
	lua_pushinteger(l, 599);
	lua_setfield(l, -2, "SYSZ_INS_SDB");
	lua_pushinteger(l, 600);
	lua_setfield(l, -2, "SYSZ_INS_SDBR");
	lua_pushinteger(l, 601);
	lua_setfield(l, -2, "SYSZ_INS_SEB");
	lua_pushinteger(l, 602);
	lua_setfield(l, -2, "SYSZ_INS_SEBR");
	lua_pushinteger(l, 603);
	lua_setfield(l, -2, "SYSZ_INS_SG");
	lua_pushinteger(l, 604);
	lua_setfield(l, -2, "SYSZ_INS_SGF");
	lua_pushinteger(l, 605);
	lua_setfield(l, -2, "SYSZ_INS_SGFR");
	lua_pushinteger(l, 606);
	lua_setfield(l, -2, "SYSZ_INS_SGR");
	lua_pushinteger(l, 607);
	lua_setfield(l, -2, "SYSZ_INS_SGRK");
	lua_pushinteger(l, 608);
	lua_setfield(l, -2, "SYSZ_INS_SH");
	lua_pushinteger(l, 609);
	lua_setfield(l, -2, "SYSZ_INS_SHY");
	lua_pushinteger(l, 610);
	lua_setfield(l, -2, "SYSZ_INS_SL");
	lua_pushinteger(l, 611);
	lua_setfield(l, -2, "SYSZ_INS_SLB");
	lua_pushinteger(l, 612);
	lua_setfield(l, -2, "SYSZ_INS_SLBG");
	lua_pushinteger(l, 613);
	lua_setfield(l, -2, "SYSZ_INS_SLBR");
	lua_pushinteger(l, 614);
	lua_setfield(l, -2, "SYSZ_INS_SLFI");
	lua_pushinteger(l, 615);
	lua_setfield(l, -2, "SYSZ_INS_SLG");
	lua_pushinteger(l, 616);
	lua_setfield(l, -2, "SYSZ_INS_SLBGR");
	lua_pushinteger(l, 617);
	lua_setfield(l, -2, "SYSZ_INS_SLGF");
	lua_pushinteger(l, 618);
	lua_setfield(l, -2, "SYSZ_INS_SLGFI");
	lua_pushinteger(l, 619);
	lua_setfield(l, -2, "SYSZ_INS_SLGFR");
	lua_pushinteger(l, 620);
	lua_setfield(l, -2, "SYSZ_INS_SLGR");
	lua_pushinteger(l, 621);
	lua_setfield(l, -2, "SYSZ_INS_SLGRK");
	lua_pushinteger(l, 622);
	lua_setfield(l, -2, "SYSZ_INS_SLL");
	lua_pushinteger(l, 623);
	lua_setfield(l, -2, "SYSZ_INS_SLLG");
	lua_pushinteger(l, 624);
	lua_setfield(l, -2, "SYSZ_INS_SLLK");
	lua_pushinteger(l, 625);
	lua_setfield(l, -2, "SYSZ_INS_SLR");
	lua_pushinteger(l, 626);
	lua_setfield(l, -2, "SYSZ_INS_SLRK");
	lua_pushinteger(l, 627);
	lua_setfield(l, -2, "SYSZ_INS_SLY");
	lua_pushinteger(l, 628);
	lua_setfield(l, -2, "SYSZ_INS_SQDB");
	lua_pushinteger(l, 629);
	lua_setfield(l, -2, "SYSZ_INS_SQDBR");
	lua_pushinteger(l, 630);
	lua_setfield(l, -2, "SYSZ_INS_SQEB");
	lua_pushinteger(l, 631);
	lua_setfield(l, -2, "SYSZ_INS_SQEBR");
	lua_pushinteger(l, 632);
	lua_setfield(l, -2, "SYSZ_INS_SQXBR");
	lua_pushinteger(l, 633);
	lua_setfield(l, -2, "SYSZ_INS_SR");
	lua_pushinteger(l, 634);
	lua_setfield(l, -2, "SYSZ_INS_SRA");
	lua_pushinteger(l, 635);
	lua_setfield(l, -2, "SYSZ_INS_SRAG");
	lua_pushinteger(l, 636);
	lua_setfield(l, -2, "SYSZ_INS_SRAK");
	lua_pushinteger(l, 637);
	lua_setfield(l, -2, "SYSZ_INS_SRK");
	lua_pushinteger(l, 638);
	lua_setfield(l, -2, "SYSZ_INS_SRL");
	lua_pushinteger(l, 639);
	lua_setfield(l, -2, "SYSZ_INS_SRLG");
	lua_pushinteger(l, 640);
	lua_setfield(l, -2, "SYSZ_INS_SRLK");
	lua_pushinteger(l, 641);
	lua_setfield(l, -2, "SYSZ_INS_SRST");
	lua_pushinteger(l, 642);
	lua_setfield(l, -2, "SYSZ_INS_ST");
	lua_pushinteger(l, 643);
	lua_setfield(l, -2, "SYSZ_INS_STC");
	lua_pushinteger(l, 644);
	lua_setfield(l, -2, "SYSZ_INS_STCH");
	lua_pushinteger(l, 645);
	lua_setfield(l, -2, "SYSZ_INS_STCY");
	lua_pushinteger(l, 646);
	lua_setfield(l, -2, "SYSZ_INS_STD");
	lua_pushinteger(l, 647);
	lua_setfield(l, -2, "SYSZ_INS_STDY");
	lua_pushinteger(l, 648);
	lua_setfield(l, -2, "SYSZ_INS_STE");
	lua_pushinteger(l, 649);
	lua_setfield(l, -2, "SYSZ_INS_STEY");
	lua_pushinteger(l, 650);
	lua_setfield(l, -2, "SYSZ_INS_STFH");
	lua_pushinteger(l, 651);
	lua_setfield(l, -2, "SYSZ_INS_STG");
	lua_pushinteger(l, 652);
	lua_setfield(l, -2, "SYSZ_INS_STGRL");
	lua_pushinteger(l, 653);
	lua_setfield(l, -2, "SYSZ_INS_STH");
	lua_pushinteger(l, 654);
	lua_setfield(l, -2, "SYSZ_INS_STHH");
	lua_pushinteger(l, 655);
	lua_setfield(l, -2, "SYSZ_INS_STHRL");
	lua_pushinteger(l, 656);
	lua_setfield(l, -2, "SYSZ_INS_STHY");
	lua_pushinteger(l, 657);
	lua_setfield(l, -2, "SYSZ_INS_STMG");
	lua_pushinteger(l, 658);
	lua_setfield(l, -2, "SYSZ_INS_STRL");
	lua_pushinteger(l, 659);
	lua_setfield(l, -2, "SYSZ_INS_STRV");
	lua_pushinteger(l, 660);
	lua_setfield(l, -2, "SYSZ_INS_STRVG");
	lua_pushinteger(l, 661);
	lua_setfield(l, -2, "SYSZ_INS_STY");
	lua_pushinteger(l, 662);
	lua_setfield(l, -2, "SYSZ_INS_SXBR");
	lua_pushinteger(l, 663);
	lua_setfield(l, -2, "SYSZ_INS_SY");
	lua_pushinteger(l, 664);
	lua_setfield(l, -2, "SYSZ_INS_TM");
	lua_pushinteger(l, 665);
	lua_setfield(l, -2, "SYSZ_INS_TMHH");
	lua_pushinteger(l, 666);
	lua_setfield(l, -2, "SYSZ_INS_TMHL");
	lua_pushinteger(l, 667);
	lua_setfield(l, -2, "SYSZ_INS_TMLH");
	lua_pushinteger(l, 668);
	lua_setfield(l, -2, "SYSZ_INS_TMLL");
	lua_pushinteger(l, 669);
	lua_setfield(l, -2, "SYSZ_INS_TMY");
	lua_pushinteger(l, 670);
	lua_setfield(l, -2, "SYSZ_INS_X");
	lua_pushinteger(l, 671);
	lua_setfield(l, -2, "SYSZ_INS_XC");
	lua_pushinteger(l, 672);
	lua_setfield(l, -2, "SYSZ_INS_XG");
	lua_pushinteger(l, 673);
	lua_setfield(l, -2, "SYSZ_INS_XGR");
	lua_pushinteger(l, 674);
	lua_setfield(l, -2, "SYSZ_INS_XGRK");
	lua_pushinteger(l, 675);
	lua_setfield(l, -2, "SYSZ_INS_XI");
	lua_pushinteger(l, 676);
	lua_setfield(l, -2, "SYSZ_INS_XIHF");
	lua_pushinteger(l, 677);
	lua_setfield(l, -2, "SYSZ_INS_XILF");
	lua_pushinteger(l, 678);
	lua_setfield(l, -2, "SYSZ_INS_XIY");
	lua_pushinteger(l, 679);
	lua_setfield(l, -2, "SYSZ_INS_XR");
	lua_pushinteger(l, 680);
	lua_setfield(l, -2, "SYSZ_INS_XRK");
	lua_pushinteger(l, 681);
	lua_setfield(l, -2, "SYSZ_INS_XY");
	lua_pushinteger(l, 682);
	lua_setfield(l, -2, "SYSZ_INS_ENDING");

	/* Group of SystemZ instructions */

	lua_pushinteger(l, 0);
	lua_setfield(l, -2, "SYSZ_GRP_INVALID");

	/* Generic groups */
	lua_pushinteger(l, 1);
	lua_setfield(l, -2, "SYSZ_GRP_JUMP");

	/* Architecture-specific groups */
	lua_pushinteger(l, 128);
	lua_setfield(l, -2, "SYSZ_GRP_DISTINCTOPS");
	lua_pushinteger(l, 129);
	lua_setfield(l, -2, "SYSZ_GRP_FPEXTENSION");
	lua_pushinteger(l, 130);
	lua_setfield(l, -2, "SYSZ_GRP_HIGHWORD");
	lua_pushinteger(l, 131);
	lua_setfield(l, -2, "SYSZ_GRP_INTERLOCKEDACCESS1");
	lua_pushinteger(l, 132);
	lua_setfield(l, -2, "SYSZ_GRP_LOADSTOREONCOND");
	lua_pushinteger(l, 133);
	lua_setfield(l, -2, "SYSZ_GRP_ENDING");
}